### ISSUE TITLE
/lib/rex/post/meterpreter/channels/pool.rb:84:in `read' EOFError EOFError

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#10008]
```
[-] Post failed: EOFError EOFError
[-] Call stack:
[-]   /Users/xxx/safe/top20/metasploit-framework/lib/rex/post/meterpreter/channels/pool.rb:84:in `read'
[-]   /Users/xxx/safe/top20/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/io.rb:25:in `sysread'
[-]   /Users/xxx/safe/top20/metasploit-framework/lib/msf/core/post/file.rb:431:in `_read_file_meterpreter'
[-]   /Users/xxx/safe/top20/metasploit-framework/lib/msf/core/post/file.rb:281:in `read_file'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:79:in `block in download_files'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:77:in `each'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:77:in `download_files'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:89:in `block in downloadOneDrive'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:87:in `each'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:87:in `downloadOneDrive'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:115:in `block in run'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:113:in `each'
[-]   /Users/xxx/.msf4/modules/post/windows/gather/enum_files.rb:113:in `run'
```

**Comment by busterb** [comment]
I think the intent is for the module writer to read until EOFError naturally.
