### ISSUE TITLE
Module auxiliary/scanner/get_user_spns fails with 'Unknown', possibly due to unhandled connection error

### ISSUE THREAD

**Issue by tfriesen** [rapid7/metasploit-framework#10294]
## Steps to reproduce
    msf > use auxiliary/gather/get_user_spns 
    msf auxiliary(gather/get_user_spns) > set RHOSTS <some hosts>
    RHOSTS => <some hosts>
    msf auxiliary(gather/get_user_spns) > set domain <domain>
    domain => <domain>
    msf auxiliary(gather/get_user_spns) > set pass <password>
    pass => <password>
    msf auxiliary(gather/get_user_spns) > set user <user>
    user => <user>
    msf auxiliary(gather/get_user_spns) > run

    [*] Running for <a host>
    #<Thread:0x00007ff9e12f6498@/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:93    run> terminated with exception (report_on_exception is true):
    Traceback (most recent call last):
	4: from /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
	3: from /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
	2: from /usr/share/metasploit-framework/modules/auxiliary/gather/get_user_spns.py:43:in `run_host'
	1: from /usr/share/metasploit-framework/lib/msf/core/module/external.rb:27:in `execute_module'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary.rb:163:in `fail_with': unknown: Module exited abnormally (Msf::Auxiliary::Failed)
    [-] Auxiliary aborted due to failure: unknown: Module exited abnormally
    [*] Auxiliary module execution completed

## Expected behavior

Module succeeds, or at least returns a useful error message.

## Current behavior

Module fails with unhelpful error message. See above. 

From framework.log:

    [07/12/2018 14:37:26] [e(0)] core: Unexpected output running /usr/share/metasploit-framework/modules/auxiliary/gather/get_user_spns.py:
    module.run(metadata, run)
      File "/usr/share/metasploit-framework/lib/msf/core/modules/external/python/metasploit/module.py", line 100, in run
    ret = callback(args)
      File "/usr/share/metasploit-framework/modules/auxiliary/gather/get_user_spns.py", line 317, in run
    executer.run()
      File "/usr/share/metasploit-framework/modules/auxiliary/gather/get_user_spns.py", line 210, in run
    ldapConnection = ldap.LDAPConnection('ldap://%s'%self.__target, self.baseDN, self.__kdcHost)
      File "/usr/local/lib/python2.7/dist-packages/impacket/ldap/ldap.py", line 106, in __init__
    self._socket.connect(sa)
      File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
    socket.error: [Errno 111] Connection refused

    [07/12/2018 14:37:26] [e(0)] core: thread exception: ScannerHost(gather/get_user_spns)-***REDACTED HOST*** critical=false  error: Msf::Auxiliary::Failed unknown: Module exited abnormally
      source:
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:129:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:140:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:82:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:92:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:105:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:546:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:508:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:502:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:502:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:49:in `<main>'
    [07/12/2018 14:37:26] [e(0)] core: Call Stack
    /usr/share/metasploit-framework/lib/msf/core/auxiliary.rb:163:in `fail_with'
    /usr/share/metasploit-framework/lib/msf/core/module/external.rb:27:in `execute_module'
    /usr/share/metasploit-framework/modules/auxiliary/gather/get_user_spns.py:43:in `run_host'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
    /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'

The log seems to suggest that the error occurs because an uncaught connection attempt to LDAP failed. However, if I specify a host that has a known LDAP service running, I get the same error.

### Metasploit version

msf auxiliary(gather/get_user_spns) > version 
Framework: 4.16.65-dev
Console  : 4.16.65-dev

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali Linux rolling, up-to-date, running inside VirtualBox with a bridged adapter

**Comment by tfriesen** [comment]
Ok, so I've figured out the problem.

If my domain is 'MYOFFICE', specifying:

    set domain MYOFFICE

does not work. However, if instead I use:

    set domain MYOFFICE.local

I get the expected result.

Feel free to close this issue if you like, but I would suggest improving the error handling and error message.
