### ISSUE TITLE
ArgumentError comparison of Fixnum with nil failed

### ISSUE THREAD

**Issue by realtebo** [rapid7/metasploit-framework#10316]
## Steps to reproduce

1. I am using pentestbox on windows 10
2. Launch msfconsole
3. use auxiliary/gather/enum_dns
4. using following settings

```
  Name         Current Setting                                                     
  ----         ---------------                                                     
  DOMAIN       google.it                                                           
  ENUM_A       true                                                                
  ENUM_AXFR    true                                                                
  ENUM_BRT     true                                                                
  ENUM_CNAME   true                                                                
  ENUM_MX      true                                                                
  ENUM_NS      true                                                                
  ENUM_RVL     true                                                                
  ENUM_SOA     true                                                                
  ENUM_SRV     true                                                                
  ENUM_TLD     false                                                               
  ENUM_TXT     true                                                                
  IPRANGE                                                                          
  NS                                                                               
  STOP_WLDCRD  false                                                               
  THREADS      1                                                                   
  WORDLIST     C:/PentestBox/bin/metasploit-framework/data/wordlists/namelist.txt  

```
5. run

## Expected behavior

No errors, only usefull infos

## Current behavior
```

msf5 auxiliary(gather/enum_dns) > run

[*] querying DNS NS records for google.it
[+] google.it NS: ns1.google.com.
[+] google.it NS: ns2.google.com.
[+] google.it NS: ns3.google.com.
[+] google.it NS: ns4.google.com.
[*] Attempting DNS AXFR for google.it from ns1.google.com.
[+] ns1.google.com. A: 216.239.32.10
W, [2018-07-15T17:17:27.751869 #7252]  WARN -- : AXFR query, switching to TCP
[*] Attempting DNS AXFR for google.it from ns2.google.com.
[+] ns2.google.com. A: 216.239.34.10
W, [2018-07-15T17:17:27.874698 #7252]  WARN -- : AXFR query, switching to TCP
[*] Attempting DNS AXFR for google.it from ns3.google.com.
[+] ns3.google.com. A: 216.239.36.10
W, [2018-07-15T17:17:28.031805 #7252]  WARN -- : AXFR query, switching to TCP
[*] Attempting DNS AXFR for google.it from ns4.google.com.
[+] ns4.google.com. A: 216.239.38.10
W, [2018-07-15T17:17:28.177594 #7252]  WARN -- : AXFR query, switching to TCP
[+] google.it A: 216.58.205.195
[*] querying DNS CNAME records for google.it
[*] querying DNS NS records for google.it
[+] google.it NS: ns1.google.com.
[+] google.it NS: ns2.google.com.
[+] google.it NS: ns3.google.com.
[+] google.it NS: ns4.google.com.
[*] querying DNS MX records for google.it
[+] google.it MX: aspmx.l.google.com.
[+] google.it MX: alt1.aspmx.l.google.com.
[+] google.it MX: alt2.aspmx.l.google.com.
[+] google.it MX: alt3.aspmx.l.google.com.
[+] google.it MX: alt4.aspmx.l.google.com.
[*] querying DNS SOA records for google.it
[+] google.it SOA: ns1.google.com.
[*] querying DNS TXT records for google.it
[+] google.it TXT: v=spf1 -all
[*] querying DNS SRV records for google.it
[-] Auxiliary failed: ArgumentError comparison of Fixnum with nil failed
[-] Call stack:
[-]   C:/PentestBox/bin/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:144:in `<'
[-]   C:/PentestBox/bin/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:144:in `dns_reverse'
[-]   C:/PentestBox/bin/metasploit-framework/modules/auxiliary/gather/enum_dns.rb:73:in `run'
[*] Auxiliary module execution completed
```

### Metasploit version

Framework: 5.0.0-dev-b9192d1bdb
Console  : 5.0.0-dev-b9192d1bdb

### I installed Metasploit with:
- Pentestbox 

### OS

Windows 10 Pro 64bit

**Comment by realtebo** [comment]
Thanks. I see in the patch that I must provide an update range, right? Could you give me an example of how to set up range in the specific case of google.it ? Just to understand the nature of the problem.

Thanks

Mirko

**Comment by bcoles** [comment]
The `ENUM_RVL` option allows you to [reverse lookup](https://en.wikipedia.org/wiki/Reverse_DNS_lookup) a range of IP addresses.

To perform a reverse lookup of `127.0.0.1` you would do:

```
set ENUM_RVL true
set IPRANGE 127.0.0.1
```

If you do not wish to perform a reverse lookup you would do `set ENUM_RVL false`.

**Comment by realtebo** [comment]
Sorry, I explained not well. 

I ask if there is a way to actually have the ENUM_RVL working while waiting for patch

**Comment by realtebo** [comment]
To do a reverse lookup about google.it, what must I set as IPRANGE?

**Comment by bcoles** [comment]
Whatever IP you want.

> In computer networks, a reverse DNS lookup or reverse DNS resolution (rDNS) is the querying of the Domain Name System (DNS) to determine the domain name associated with an IP address – the reverse of the usual "forward" DNS lookup of an IP address from a domain name. The process of reverse resolving an IP address uses PTR records. The reverse DNS database of the Internet is rooted in the arpa top-level domain.
