### ISSUE TITLE
SSH modules need to require 'net/ssh/command_stream'

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#10331]
**And some don't.**

Since we unvendored the lib, the `require` for `net/ssh/command_stream` (`Net::SSH::CommandStream`) was lost. Later modules that wanted to work had to `require` it manually. Modules that weren't updated are still broken.

This is a regression from #7018, individually fixed in #9602, and noted by BrianWGray on IRC. This is **NOT** a regression from #9524, near as I can tell.

Removing the `require` simulates the error:

```
msf5 auxiliary(scanner/ssh/fortinet_backdoor) > run

[+] 172.16.249.128:22 - Logged in as Fortimanager_Access
#<Thread:0x00007fdbf83ba340@/Users/wvu/metasploit-framework/lib/msf/core/thread_manager.rb:93 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	2: from /Users/wvu/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
	1: from /Users/wvu/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
/Users/wvu/metasploit-framework/modules/auxiliary/scanner/ssh/fortinet_backdoor.rb:82:in `run_host': uninitialized constant Net::SSH::CommandStream (NameError)
[-] Auxiliary failed: NameError uninitialized constant Net::SSH::CommandStream
[-] Call stack:
[-]   /Users/wvu/metasploit-framework/modules/auxiliary/scanner/ssh/fortinet_backdoor.rb:82:in `run_host'
[-]   /Users/wvu/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
[-]   /Users/wvu/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/ssh/fortinet_backdoor) >
```

Related to #10266.

**Comment by sempervictus** [comment]
I think i added it to the whole ssh factory mixin madness to address this as a stop-gap a while back. I'll take a look, but i do remember this coming up.
