### ISSUE TITLE
AFP Login Scanner nil error

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#10355]
This is against netatalk 2.2.5.  Not sure if the module is just broken against netatalk only or Apple as well.  The server_info module works fine though (working on docs).
```
[*] 1.1.1.1:548 - Scanning IP: 1.1.1.1
#<Thread:0x000055d4a1d032b8@/metasploit-framework/lib/msf/core/thread_manager.rb:93 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	10: from /metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
	 9: from /metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
	 8: from /metasploit-framework/modules/auxiliary/scanner/afp/afp_login.rb:78:in `run_host'
	 7: from /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
	 6: from /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
	 5: from /metasploit-framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
	 4: from /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
	 3: from /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
	 2: from /metasploit-framework/lib/metasploit/framework/login_scanner/afp.rb:35:in `attempt_login'
	 1: from /metasploit-framework/lib/metasploit/framework/afp/client.rb:83:in `login'
/metasploit-framework/lib/metasploit/framework/afp/client.rb:235:in `parse_header': undefined method `unpack' for nil:NilClass (NoMethodError)
[-] 1.1.1.1:548 - Auxiliary failed: NoMethodError undefined method `unpack' for nil:NilClass
[-] 1.1.1.1:548 - Call stack:
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/afp/client.rb:235:in `parse_header'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/afp/client.rb:83:in `login'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/login_scanner/afp.rb:35:in `attempt_login'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-] 1.1.1.1:548 -   /metasploit-framework/modules/auxiliary/scanner/afp/afp_login.rb:78:in `run_host'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
[-] 1.1.1.1:548 -   /metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

**Comment by ccondon-r7** [comment]
Is this still an issue?

**Comment by h00die** [comment]
I never fixed it, I would assume it still is though.  However, now that I have a mac, i could test to see if its just netatalk or apples as well

**Comment by h00die** [comment]
this module works correctly against macOS Catalina 10.15.4.  I'm going to go ahead and close it, i think `afp` is enough of a dead protocol that it's not worth fixing.  Most people would run it on macOS anyways.  Even on macOS SMB is the default and afp is buried in the options.
