### ISSUE TITLE
msfvenom --list-options bug in linux/x86/shell_reverse_tcp_ipv6

### ISSUE THREAD

**Issue by securitykitten** [rapid7/metasploit-framework#10360]
## Steps to reproduce
```
# msfvenom -p linux/x86/shell_reverse_tcp_ipv6 --list-options
Options for payload/linux/x86/shell_reverse_tcp_ipv6:
=========================

Traceback (most recent call last):
	7: from /usr/bin/msfvenom:371:in `<main>'
	6: from /usr/share/metasploit-framework/lib/msf/base/serializer/readable_text.rb:24:in `dump_module'
	5: from /usr/share/metasploit-framework/lib/msf/base/serializer/readable_text.rb:330:in `dump_payload_module'
	4: from /usr/share/metasploit-framework/lib/msf/core/payload.rb:204:in `size'
	3: from /usr/share/metasploit-framework/lib/msf/core/payload/single.rb:36:in `generate'
	2: from /usr/share/metasploit-framework/modules/payloads/singles/linux/x86/shell_reverse_tcp_ipv6.rb:42:in `generate_stage'
	1: from /usr/share/metasploit-framework/modules/payloads/singles/linux/x86/shell_reverse_tcp_ipv6.rb:42:in `new'
/usr/lib/ruby/2.5.0/ipaddr.rb:565:in `initialize': address family must be specified (IPAddr::AddressFamilyError)

```

## Expected behavior

List options of `linux/x86/shell_reverse_tcp_ipv6`

## Current behavior

Error is thrown

### Metasploit version

```
metasploit v4.17.2-dev  
```

### I installed Metasploit with:
- [ x] Kali package via apt

### OS

What OS are you running Metasploit on?
Kali Linux

**Comment by wvu-r7** [comment]
#10167
