### ISSUE TITLE
Writing module, error.

### ISSUE THREAD

**Issue by Roganced** [rapid7/metasploit-framework#10465]
Hello! I trying to write module:
`    print_status("Running module against #{sysinfo['Computer']}")
      File.open(['/root/rec.rc'], "rb").each_line do |cmd|
        next if cmd.strip.length < 1
        next if cmd[0,1] == "#"
          print_status "Running command #{cmd.chomp}"
          session.console.run_single(cmd.chomp)
          print_status("Error Running Command #{cmd.chomp}: #{e.class} #{e}")`

After run i receive a error message:

> [*] Running module against OS
[-] Post failed: TypeError no implicit conversion of Array into String
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/checkvm.rb:32:in `initialize'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/checkvm.rb:32:in `open'
[-]   /usr/share/metasploit-framework/modules/post/windows/gather/checkvm.rb:32:in `run'

**Comment by kkirsche** [comment]
You should be able to rewrite the code block using three backticks instead of a single one to maintain formatting. For example:

```
print_status("Running module against #{sysinfo['Computer']}")
File.open(['/root/rec.rc'], "rb").each_line do |cmd|
  next if cmd.strip.length < 1
  next if cmd[0,1] == "#"
  print_status "Running command #{cmd.chomp}"
  session.console.run_single(cmd.chomp) 
  print_status("Error Running Command #{cmd.chomp}: #{e.class} #{e}")
  ....
```

Which is written as:

    ```
    print_status("Running module against #{sysinfo['Computer']}")
    File.open(['/root/rec.rc'], "rb").each_line do |cmd|
      next if cmd.strip.length < 1
      next if cmd[0,1] == "#"
      print_status "Running command #{cmd.chomp}"
      session.console.run_single(cmd.chomp) 
      print_status("Error Running Command #{cmd.chomp}: #{e.class} #{e}")
      ....
    ```

**Comment by kkirsche** [comment]
With that said, the specific issue is:

`File.open(['/root/rec.rc'], "rb").each_line do |cmd|`

You are trying to open a single file, which should be a string argument to `File.open()` but you have passed it an array (noted by the use of `[` and `]`. The error is a ruby error saying that `File.open()` is expecting a string argument, when you gave it an array.

Take a look at https://ruby-doc.org/core-2.2.0/File.html#method-c-open for more details on how `File.open` works and what arguments it expects

**Comment by Roganced** [comment]
May i ask you a question?
I try to stop a script if meterpreter doesn't have admin rights.
Behold:

**def run**
check_rights
def check_if_exit
end

**def check_rights**
unless is_admin?
print_error("Error!")
end
end     ##### **Here I want to make an exit.**

**def check_if_exit**
print("Work!")
end

How can i make that after an unsuccessful rights check the program stopped. (Work should not be displayed)
