### ISSUE TITLE
Stack trace while running jobs -K

### ISSUE THREAD

**Issue by wvu-r7** [rapid7/metasploit-framework#10499]
@Green-m, @jmartin-r7:

```
msf5 > jobs -K
Stopping all jobs...
[-] Error while running command jobs: No such file or directory @ rb_file_s_truncate - /Users/wvu/.msf4/persist

Call stack:
/Users/wvu/metasploit-framework/lib/msf/ui/console/command_dispatcher/jobs.rb:142:in `truncate'
/Users/wvu/metasploit-framework/lib/msf/ui/console/command_dispatcher/jobs.rb:142:in `block in cmd_jobs'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:58:in `block (3 levels) in parse'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:48:in `each_pair'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:48:in `block (2 levels) in parse'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:47:in `each'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:47:in `block in parse'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:40:in `each'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:40:in `each_with_index'
/Users/wvu/metasploit-framework/lib/rex/parser/arguments.rb:40:in `parse'
/Users/wvu/metasploit-framework/lib/msf/ui/console/command_dispatcher/jobs.rb:127:in `cmd_jobs'
/Users/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:481:in `run_command'
/Users/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:443:in `block in run_single'
/Users/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:437:in `each'
/Users/wvu/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:437:in `run_single'
/Users/wvu/metasploit-framework/lib/rex/ui/text/shell.rb:208:in `run'
/Users/wvu/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/wvu/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
msf5 >
```

#10203

**Comment by Green-m** [comment]
Sorry for not anticipating this situation, I will fix it soon.

**Comment by wvu-r7** [comment]
Lol, bugs happen. I'm not worried.

**Comment by jmartin-r7** [comment]
Thanks to both of you, I should have caught that scenario. ¯\_(ツ)_/¯
