### ISSUE TITLE
Intermittent/frequent errors when using several modules

### ISSUE THREAD

**Issue by rwhitcroft** [rapid7/metasploit-framework#10600]
Running certain/many? modules results in an error sometimes/often.

Errors were originally observed with this setup:
* msf on kali, 4.17.9-0kali1
* session 1 on 10.0.0.23 (Win10) with payload windows/x64/meterpreter/reverse_https
* `route add 10.0.0.0/8 1`
* run smb_login against 10.0.0.29 (Win2008) routing through session 1

The same errors occur when using a different payload (win/x64/meterp/rtcp), and different modules - aux/scanner/smb/smb_ms17_010 and aux/scanner/portscan/tcp were the only ones I tried, both exhibit same errors.

Here's smb_login:
```
msf auxiliary(scanner/smb/smb_login) > options

Module options (auxiliary/scanner/smb/smb_login):

   Name               Current Setting  Required  Description
   ----               ---------------  --------  -----------
   ABORT_ON_LOCKOUT   false            yes       Abort the run when an account lockout is detected
   BLANK_PASSWORDS    false            no        Try blank passwords for all users
   BRUTEFORCE_SPEED   5                yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS       false            no        Try each user/password couple stored in the current database
   DB_ALL_PASS        false            no        Add all passwords in the current database to the list
   DB_ALL_USERS       false            no        Add all users in the current database to the list
   DETECT_ANY_AUTH    false            no        Enable detection of systems accepting any authentication
   DETECT_ANY_DOMAIN  false            no        Detect if domain is required for the specified user
   PASS_FILE                           no        File containing passwords, one per line
   PRESERVE_DOMAINS   true             no        Respect a username that contains a domain name.
   Proxies                             no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST       false            no        Record guest-privileged random logins to the database
   RHOSTS             10.0.0.29        yes       The target address range or CIDR identifier
   RPORT              445              yes       The SMB service port (TCP)
   SMBDomain          test             no        The Windows domain to use for authentication
   SMBPass            test             no        The password for the specified username
   SMBUser            test             no        The username to authenticate as
   STOP_ON_SUCCESS    false            yes       Stop guessing when a credential works for a host
   THREADS            1                yes       The number of concurrent threads
   USERPASS_FILE                       no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS       false            no        Try the username as the password for all users
   USER_FILE                           no        File containing usernames, one per line
   VERBOSE            true             yes       Whether to print output for all attempts

msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.0.29:445         - 10.0.0.29:445 - Starting SMB login bruteforce
[-] 10.0.0.29:445         - 10.0.0.29:445 - Failed: 'test\test:test',
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.0.29:445         - 10.0.0.29:445 - Starting SMB login bruteforce
[-] 10.0.0.29:445         - 10.0.0.29:445 - Failed: 'test\test:test',
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.0.29:445         - 10.0.0.29:445 - Starting SMB login bruteforce
[-] 10.0.0.29:445         - 10.0.0.29:445 - Failed: 'test\test:test',
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.0.29:445         - 10.0.0.29:445 - Starting SMB login bruteforce
[-] 10.0.0.29:445         - 10.0.0.29:445 - Failed: 'test\test:test',
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.0.29:445         - 10.0.0.29:445 - Starting SMB login bruteforce
[-] 10.0.0.29:445         - 10.0.0.29:445 - Failed: 'test\test:test',
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/smb/smb_login) > run

[*] 10.0.0.29:445         - 10.0.0.29:445 - Starting SMB login bruteforce
[-] 10.0.0.29:445         - 10.0.0.29:445 - Failed: 'test\test:test',
#<Thread:0x000055e16762e1b8@/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:93 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        17: from /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
        16: from /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
        15: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:121:in `block in monitor_rsock'
        14: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:121:in `loop'
        13: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:188:in `block (2 levels) in monitor_rsock'
        12: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:90:in `close_write'
        11: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:106:in `shutdown'
        10: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:220:in `send_request'
         9: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:248:in `send_packet_wait_response'
         8: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:181:in `send_packet'
         7: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:823:in `to_r'
         6: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:823:in `call'
         5: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:595:in `to_r'
         4: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:453:in `each'
         3: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:453:in `each'
         2: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:596:in `block in to_r'
         1: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:323:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:323:in `pack': no implicit conversion of nil into Integer (TypeError)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

Here's portscan/tcp:
```
msf auxiliary(scanner/portscan/tcp) > run

[+] 10.0.0.29:            - 10.0.0.29:445 - TCP OPEN
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/portscan/tcp) > run

[+] 10.0.0.29:            - 10.0.0.29:445 - TCP OPEN
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/portscan/tcp) > run

[+] 10.0.0.29:            - 10.0.0.29:445 - TCP OPEN
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf auxiliary(scanner/portscan/tcp) > run

[+] 10.0.0.29:            - 10.0.0.29:445 - TCP OPEN
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
#<Thread:0x0000558f364ffdd8@/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:93 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	17: from /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
	16: from /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
	15: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:121:in `block in monitor_rsock'
	14: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:121:in `loop'
	13: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:188:in `block (2 levels) in monitor_rsock'
	12: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:90:in `close_write'
	11: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:106:in `shutdown'
	10: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:220:in `send_request'
	 9: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:248:in `send_packet_wait_response'
	 8: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:181:in `send_packet'
	 7: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:823:in `to_r'
	 6: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:823:in `call'
	 5: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:595:in `to_r'
	 4: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:453:in `each'
	 3: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:453:in `each'
	 2: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:596:in `block in to_r'
	 1: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:323:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:323:in `pack': no implicit conversion of nil into Integer (TypeError)
```

Here's production.log from the smb_login run:
```
[09/06/2018 20:55:15] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 20:59:07] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 20:59:11] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 20:59:27] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 20:59:29] [w(0)] core: monitor_rsock: exception during read: IOError closed stream
[09/06/2018 20:59:51] [w(0)] core: Session 2 has died
[09/06/2018 21:04:06] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 21:04:09] [d(0)] core: monitor_rsock: EOF in rsock
[09/06/2018 21:04:12] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 21:04:14] [w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[09/06/2018 21:04:17] [d(0)] core: monitor_rsock: EOF in rsock
[09/06/2018 21:04:21] [w(0)] core: monitor_rsock: exception during select: Rex::StreamClosedError Stream #<TCPSocket:0x000055e167665e60> is closed.
[09/06/2018 21:04:21] [e(0)] core: thread exception: StreamMonitorRemote  critical=false  error: TypeError no implicit conversion of nil into Integer
  source:
    /usr/share/metasploit-framework/lib/metasploit/framework/thread_factory_provider.rb:24:in `spawn'
    /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `spawn'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:120:in `monitor_rsock'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream_abstraction.rb:26:in `initialize_abstraction'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/channels/socket_abstraction.rb:94:in `initialize'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:75:in `initialize'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/channel.rb:125:in `new'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/channel.rb:125:in `create'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:36:in `open'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket.rb:104:in `create_tcp_client_channel'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket.rb:73:in `create'
    /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:588:in `create'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket.rb:49:in `create_param'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket/tcp.rb:37:in `create_param'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.15/lib/rex/socket/tcp.rb:28:in `create'
    /usr/share/metasploit-framework/lib/metasploit/framework/tcp/client.rb:84:in `connect'
    /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/smb.rb:155:in `connect'
    /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/smb.rb:80:in `attempt_login'
    /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
    /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:154:in `block in each_credential'
    /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
    /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
    /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
    /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_login.rb:114:in `run_host'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
    /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[09/06/2018 21:04:21] [e(0)] core: Call Stack
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:323:in `pack'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:323:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:596:in `block in to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:453:in `each'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:453:in `each'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:595:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:823:in `call'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:823:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:181:in `send_packet'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:248:in `send_packet_wait_response'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:220:in `send_request'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:106:in `shutdown'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:90:in `close_write'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:188:in `block (2 levels) in monitor_rsock'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:121:in `loop'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/socket_abstraction.rb:121:in `block in monitor_rsock'
/usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```

**Comment by rwhitcroft** [comment]
Re-opening this, apparently it's not just me - see #10177 and #10160 .

This bug makes doing anything over a route pretty infuriating due to backtrace spam.
