### ISSUE TITLE
lib/msf/core/payload/android.rb Throws random error on startup when calculating size

### ISSUE THREAD

**Issue by acammack-r7** [rapid7/metasploit-framework#10636]
Just ran across this starting msfconsole:
```
$ rbenv exec bundle exec ruby ./msfconsole 
Traceback (most recent call last):ork console.../
	26: from ./msfconsole:49:in `<main>'
	25: from /Users/acammack/rapid7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	24: from /Users/acammack/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	23: from /Users/acammack/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	22: from /Users/acammack/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	21: from /Users/acammack/rapid7/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize'
	20: from /Users/acammack/rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	19: from /Users/acammack/rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	18: from /Users/acammack/rapid7/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	17: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	16: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	15: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	14: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	13: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `each'
	12: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	11: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:248:in `load_modules'
	10: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:248:in `each'
	 9: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:251:in `block in load_modules'
	 8: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:98:in `recalculate'
	 7: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:98:in `each_pair'
	 6: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:102:in `block in recalculate'
	 5: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:102:in `each_pair'
	 4: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload_set.rb:158:in `block (2 levels) in recalculate'
	 3: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload.rb:204:in `size'
	 2: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload/android.rb:38:in `generate'
	 1: from /Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload/android.rb:121:in `generate_jar'
/Users/acammack/rapid7/metasploit-framework/lib/msf/core/payload/android.rb:121:in `gsub!': invalid group name reference format (RuntimeError)
```

**Comment by timwr** [comment]
Why do we bother calculating the payload size for larger payloads on startup? 
Perhaps we could increase the startup time by ignoring larger (> 10kb?) payloads.

**Comment by acammack-r7** [comment]
Yeah, it's a bit weird, but here it helped find a place where we need to use the block version of `gsub!` to avoid the config being mistaken for back references (which we probably need to use in more places). I'm just working on a reliable repro case.

**Comment by ccondon-r7** [comment]
@acammack-r7 is this still an issue?

**Comment by acammack-r7** [comment]
@ccondon-r7 that code is still liable to throw this error, though I was never able to repro this crash.

**Comment by adfoster-r7** [comment]
This hasn't come up in multiple years, will close
