### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by Ridter** [rapid7/metasploit-framework#10780]
## Expected behavior

What should happen?
Run normally

## Current behavior
```
Traceback (most recent call last):ork consOle...-
	30: from /usr/local/bin/msfconsole:49:in `<main>'
	29: from /usr/local/share/metasploit/lib/metasploit/framework/command/base.rb:82:in `start'
	28: from /usr/local/share/metasploit/lib/metasploit/framework/command/console.rb:48:in `start'
	27: from /usr/local/share/metasploit/lib/metasploit/framework/command/console.rb:62:in `driver'
	26: from /usr/local/share/metasploit/lib/metasploit/framework/command/console.rb:62:in `new'
	25: from /usr/local/share/metasploit/lib/msf/ui/console/driver.rb:161:in `initialize'
	24: from /usr/local/share/metasploit/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	23: from /usr/local/share/metasploit/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	22: from /usr/local/share/metasploit/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	21: from /usr/local/share/metasploit/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	20: from /usr/local/share/metasploit/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	19: from /usr/local/share/metasploit/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	18: from /usr/local/share/metasploit/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	17: from /usr/local/share/metasploit/lib/msf/core/module_manager/loading.rb:117:in `each'
	16: from /usr/local/share/metasploit/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	15: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:238:in `load_modules'
	14: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:30:in `each_module_reference_name'
	13: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:30:in `foreach'
	12: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:40:in `block in each_module_reference_name'
	11: from /Users/love/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `find'
	10: from /Users/love/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `catch'
	 9: from /Users/love/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:133:in `block in find'
	 8: from /usr/local/share/metasploit/lib/msf/core/modules/loader/directory.rb:49:in `block (2 levels) in each_module_reference_name'
	 7: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:239:in `block in load_modules'
	 6: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:177:in `load_module'
	 5: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:535:in `namespace_module_transaction'
	 4: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:365:in `current_module'
	 3: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:365:in `inject'
	 2: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:365:in `each'
	 1: from /usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:370:in `block in current_module'
/usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:370:in `const_defined?': wrong constant name Post__Windows__My-auxiliary__Hashdump (NameError)
```

### Metasploit version

9436821f344e217e9b394d12fb956fd70956c2af

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

Macos

**Comment by timwr** [comment]
`/usr/local/share/metasploit/lib/msf/core/modules/loader/base.rb:370:in `const_defined?': wrong constant name Post__Windows__My-auxiliary__Hashdump (NameError)`
Did you modify any of the source?

**Comment by Ridter** [comment]
@timwr no, just clone the newest source.

**Comment by wvu-r7** [comment]
Run `msftidy` on your module and see what it says.

#10729

**Comment by wvu-r7** [comment]
@Ridter: You should be seeing a nicer error message now. The `NameError: wrong constant name` was accurate, though.

**Comment by Ridter** [comment]
@wvu-r7  Solved， thank you ！
