### ISSUE TITLE
Meterpreter sessions not working in latest msf

### ISSUE THREAD

**Issue by rwhitcroft** [rapid7/metasploit-framework#10813]
Originally posted this as #10710 but realized that stage encoding was the culprit before. It now seems that no sessions will establish properly.

Kali rolling, rubies 2.4.2 and 2.5.1.

Steps:
1. venom win/x64/meterp/r{https,tcp}
2. run latest git's ./msfconsole, run handler for rtcp/rhttps
3. run .exe on Win10
4. watch stage 2 fail
5. run system msfconsole (kali), same handler as above
6. run same .exe on Win10
7. watch stage 2 succeed into working meterp

framework.log:
```
[10/15/2018 01:22:54] [e(0)] core: Problem reporting session: No registered data_service
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:149:in `get_data_service'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/session_data_proxy.rb:14:in `report_session'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/framework.rb:419:in `on_session_open'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:183:in `block in method_missing'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/session_manager.rb:225:in `register'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/handler.rb:253:in `register_session'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/handler.rb:239:in `create_session'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/handler/reverse_http.rb:385:in `on_request'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/handler/reverse_http.rb:234:in `block in setup_handler'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/proto/http/handler/proc.rb:38:in `on_request'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/proto/http/server.rb:368:in `dispatch_request'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/proto/http/server.rb:302:in `on_client_data'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/proto/http/server.rb:161:in `block in start'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/.rvm/gems/ruby-2.5.1@metasploit-framework/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:48:in `on_client_data'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/.rvm/gems/ruby-2.5.1@metasploit-framework/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:199:in `block in monitor_clients'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/.rvm/gems/ruby-2.5.1@metasploit-framework/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/.rvm/gems/ruby-2.5.1@metasploit-framework/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:197:in `monitor_clients'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/.rvm/gems/ruby-2.5.1@metasploit-framework/gems/rex-core-0.1.13/lib/rex/io/stream_server.rb:73:in `block in start'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[10/15/2018 01:22:54] [w(0)] core: Exception in on_session_open event handler: Exception: Problem reporting session: No registered data_service. See log for more details.
[10/15/2018 01:22:54] [w(0)] core: Call Stack
[10/15/2018 01:22:54] [e(0)] core: Problem reporting session event: No registered data_service
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:149:in `get_data_service'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/session_event_data_proxy.rb:5:in `report_session_event'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/framework.rb:465:in `on_session_command'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:183:in `block in method_missing'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/session_manager.rb:232:in `block in register'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:452:in `block in run_single'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `run_single'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:391:in `load_stdapi'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:157:in `block in bootstrap'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/session_manager.rb:162:in `block (2 levels) in initialize_scheduler_threads'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[10/15/2018 01:22:54] [e(0)] core: Problem reporting session event: No registered data_service
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:149:in `get_data_service'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/metasploit/framework/data_service/proxy/session_event_data_proxy.rb:5:in `report_session_event'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/framework.rb:487:in `block in on_session_output'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/framework.rb:485:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/framework.rb:485:in `on_session_output'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:183:in `block in method_missing'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/session_manager.rb:233:in `block in register'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/shell.rb:213:in `print_error'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `rescue in block in run_single'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:450:in `block in run_single'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `each'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:447:in `run_single'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:391:in `load_stdapi'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:157:in `block in bootstrap'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/session_manager.rb:162:in `block (2 levels) in initialize_scheduler_threads'
[10/15/2018 01:22:54] [e(0)] core: /home/msfdev/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[10/15/2018 01:22:54] [w(0)] core: Exception in scheduler thread Exception Problem reporting session event: No registered data_service. See log for more details.
```

**Comment by rwhitcroft** [comment]
Would love to know if this is just me... is this reproducible for anyone?

**Comment by wvu-r7** [comment]
Are you sure it's not #10129?

**Comment by rwhitcroft** [comment]
Wow, yep.

Sessions work *only* when database is connected.

**Comment by wvu-r7** [comment]
Closing as duplicate.
