### ISSUE TITLE
scanner/http/jenkins_login: saving valid credentials

### ISSUE THREAD

**Issue by syrius01** [rapid7/metasploit-framework#10978]
Hi,

I am currently trying to figure out how to save the valid credentials found with jenkins_login.rb. I've added the following code below line 70;

```
print_good "#{ip}:#{rport} - Login Successful: #{result.credential}"
report_cred(ip: datastore['RHOST'], port: datastore['RPORT'], user:user, password: pass, proof: res.code.to_s)
```

Unfortunately, I've failed;

```
[+] 192.168.1.103:8080 - Login Successful: jenkins:admin
[-] Auxiliary failed: NameError undefined local variable or method `user' for #<Msf::Modules::Mod617578696c696172792f7363616e6e65722f687474702f6a656e6b696e735f6c6f67696e32::MetasploitModule:0xdff0020>
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/jenkins_login2.rb:71:in `block in run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:234:in `block in scan!'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:177:in `block (2 levels) in each'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:170:in `each_line'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:170:in `block in each'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:169:in `open'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:169:in `each'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/http/jenkins_login2.rb:59:in `run_host'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

Now just to see if the credentials were saved;

`msf auxiliary(scanner/http/jenkins_login2) > db_export -f pwdump -a /home/user/test1.txt`

0 results in the output text file :(

Any help would be very appreciated.

Thanks

**Comment by wvu-r7** [comment]
This is not a bug report. Continue on IRC where you started.
