### ISSUE TITLE
Issues with pry in encoders and msfvenom

### ISSUE THREAD

**Issue by pussinboots1992** [rapid7/metasploit-framework#11185]
More a question than a real issue, whenever I try to debug an encoder using pry, I simply add the "bindings.pry" statement in for example zutto_dekiru.rb. However when I run msfvenom it simply freezes...any ideas on how to go around debugging an encoder ? I suspect that this is because msfvenom is a shell script so pry is probably doing it's job...any thoughts ?

**Comment by pussinboots1992** [comment]
From my understanding, the msfvenom shell script calls the msfvenom binary which then calls the encoders and the payload generator...but how can I trigger the whole process directly from ruby so I can debug using pry ?

Can someone point me to some documentation on how the msfvenom binary works ? How it interacts with ruby ?

This is what I have in my logs:
/opt/metasploit-framework/embedded/framework/modules/encoders/x64/zutto_dekiru.rb:200:in `<<'
/opt/metasploit-framework/embedded/framework/modules/encoders/x64/zutto_dekiru.rb:200:in `encode_block'
/opt/metasploit-framework/embedded/framework/lib/msf/core/encoder.rb:342:in `do_encode'
/opt/metasploit-framework/embedded/framework/lib/msf/core/encoder.rb:287:in `encode'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:496:in `block in run_encoder'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:495:in `times'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:495:in `run_encoder'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:246:in `block in encode_payload'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:242:in `each'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:242:in `encode_payload'
/opt/metasploit-framework/embedded/framework/lib/msf/core/payload_generator.rb:362:in `generate_payload'
/opt/metasploit-framework/bin/../embedded/framework/msfvenom:433:in `<main>'

**Comment by pussinboots1992** [comment]
forget it...was being stupid...ran msfvenom ruby file directly :-S
