### ISSUE TITLE
MSF web service appears to be started, but may not operate as expected.

### ISSUE THREAD

**Issue by Open-Sec** [rapid7/metasploit-framework#11252]
## Steps to reproduce

Trying to test new API Restful in Metasploit 5
After initialization or reinitialization or just starting, I got this messages :

**Starting database at /home/osboxes/.msf4/db...success
Attempting to start MSF web service...
MSF web service appears to be started, but may not operate as expected.

Please see /home/xxx/.msf4/logs/msf-ws.log for additional details.**

When hitting the API, an Internal Server Error is shown.

**msf-ws.log** shows :
```
Writing PID to /home/xxx/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:8080, CTRL+C to stop
2019-01-13 23:17:28 - ActiveRecord::ConnectionNotEstablished - ActiveRecord::ConnectionNotEstablished:
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:109:in `connection_pool'
	/opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/user.rb:10:in `users'
	/opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/metasploit_api_app.rb:66:in `block in <class:MetasploitApiApp>'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `block in filter!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `each'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:966:in `filter!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-1.6.11/lib/rack/nulllogger.rb:9:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	/opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	/opt/metasploit-framework/embedded/bin/thin:23:in `load'
	/opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
```

## Expected behavior
I expected to have the web running and the API working.

## Current behavior

What happens instead?

You might also want to check the last ~1k lines of
`/opt/metasploit/apps/pro/engine/config/logs/framework.log` or
`~/.msf4/logs/framework.log` for relevant stack traces
### Metasploit version : 5 (from installer and from this repo)

Framework: 5.0.1-dev-
Console  : 5.0.1-dev-

### I installed Metasploit with:
- Omnibus installer (nightly)
- Source install (from ruby 2.3 to 2.4.3)

### OS

Linux from Ubuntu 16.04 to 18.10

**Comment by Zayado** [comment]
maybe  you  not  install postgresql

**Comment by darkoperator** [comment]
In my case same error but it happened when msfdb was symlinked, If I ran msfdb with the current dir being the framework folder I got no errors.

**Comment by jbarnett-r7** [comment]
The web service was unable to connect to the database for some reason. It's possible that it's not running, or not accepting connections for some reason. Can you please post the output of `~/.msf4/db/log`?

**Comment by nohkoomote** [comment]
create a new msf database with _msfdb reinit_ and run msfconsole again.

don't forget to start msfdb when opening msfconsole, with _msfdb start_ and _msfdb stop_ to stop it
