### ISSUE TITLE
#11312 msfconsole libruby.so.2.3: cannot open shared object file

### ISSUE THREAD

**Issue by mrx0010** [rapid7/metasploit-framework#11312]
i tried to run msfconsole 
i got that message  : 
```
mrx001@linux:~$ msfconsole
Traceback (most recent call last):
	24: from /usr/local/bin/msfconsole:48:in `<main>'
	23: from /usr/local/bin/msfconsole:48:in `require'
	22: from /opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	21: from /opt/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	20: from /opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	19: from /opt/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	18: from /opt/metasploit-framework/lib/msf/core.rb:17:in `<top (required)>'
	17: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	16: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	15: from /opt/metasploit-framework/lib/rex.rb:102:in `<top (required)>'
	14: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	13: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	12: from /opt/metasploit-framework/lib/rex/proto.rb:2:in `<top (required)>'
	11: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	10: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	 9: from /opt/metasploit-framework/lib/rex/proto/http.rb:4:in `<top (required)>'
	 8: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	 7: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	 6: from /opt/metasploit-framework/lib/rex/proto/http/response.rb:5:in `<top (required)>'
	 5: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
	 4: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require'
	 3: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/nokogiri-1.10.1/lib/nokogiri.rb:28:in `<top (required)>'
	 2: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/nokogiri-1.10.1/lib/nokogiri.rb:32:in `rescue in <top (required)>'
	 1: from /home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require_with_backports'
/home/mrx001/.rvm/gems/ruby-2.3.5/gems/backports-3.11.4/lib/backports/std_lib.rb:9:in `require': libruby.so.2.3: cannot open shared object file: No such file or directory - /home/mrx001/.rvm/gems/ruby-2.3.5/gems/nokogiri-1.10.1/lib/nokogiri/nokogiri.so (LoadError)

```

**Comment by mkienow-r7** [comment]
@mrx0010 When you created the new issue it was populated with a number of questions. Please update this issue with all of those details in order to help us analyze the issue.

**Comment by mrx0010** [comment]
done

**Comment by mkienow-r7** [comment]
@mrx0010 I'm only seeing the title changed. Please copy what you see populated when creating a new issue and update your original comment to include those details.

**Comment by busterb** [comment]
It looks like you are simultaneously using the pre-built installer, and trying to use .rvm, _and_ have a copy of Metasploit Pro or Community installed (maybe 3 completely different versions of Metasploit?) and they are stepping on each other.

Suggestion: remove /usr/local/bin/msf*. The wrapper files under /usr/bin/ should sanitize your environment so your .rvm versions are not considered when Metasploit loads. In other words, remove one or more copies of Metasploit and just stick to one. Thanks.

**Comment by mmuncan1980** [comment]
i did what you suggested and got this:
$ sudo msfdb init && msfconsole
[sudo] Passwort für jamy: 
Metasploit running on Kali Linux as root, using system database
A database appears to be already configured, skipping initialization
Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.
Could not find rake-13.0.6 in any of the sources
Run `bundle install` to install missing gems.
