### ISSUE TITLE
tools/module_author.rb fails with latest git

### ISSUE THREAD

**Issue by pedrib** [rapid7/metasploit-framework#11441]
```
metasploit-framework` > tools/modules/module_author.rb
Traceback (most recent call last):
        3: from tools/modules/module_author.rb:116:in `<main>'
        2: from /var/lib/gems/2.5.0/gems/rex-text-0.2.21/lib/rex/text/table.rb:111:in `to_s'
        1: from /var/lib/gems/2.5.0/gems/rex-text-0.2.21/lib/rex/text/table.rb:111:in `each'
/var/lib/gems/2.5.0/gems/rex-text-0.2.21/lib/rex/text/table.rb:115:in `block in to_s': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

Running the latest git version as of today.

**Comment by jmartin-r7** [comment]
This tool should probably be updated to simply pull authors from the json cache @ `db/modules_metadata_base.json` instead of instantiating each module.
