### ISSUE TITLE
Failed to connect to the HTTP data service

### ISSUE THREAD

**Issue by Acidical** [rapid7/metasploit-framework#11490]
## What I did

1. `msfconsole`

## Expected behavior

The Metasploit console starts normally

## Current behavior

Metasploit fails to connect to the HTTP data service but the console still works normally

```
Found a database at /Users/person/.msf4/db, checking to see if it is started
Starting database at /Users/person/.msf4/db...success
MSF web service is already running as PID 834
[-] Error while running command db_connect: Failed to connect to the HTTP data service: Data Service does not appear to be responding

Call stack:
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2088:in `rescue in db_connect_http'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2083:in `db_connect_http'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1837:in `cmd_db_connect'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:522:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:473:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:467:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:467:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:252:in `block in load_db_config'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:239:in `each_pair'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:239:in `load_db_config'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:133:in `initialize'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `new'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:62:in `driver'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'
```

`db_status` returns this

`[*] Connected to msf. Connection type: postgresql.`

I have tried reinitialising the database using `msfdb reinit` but that has this error

```
Attempting to start MSF web service...failed
[!] MSF web service appears to be started, but may not operate as expected.
```

### Metasploit version

Framework: 5.0.9-dev-aa0ba91d92ae9324c1c0014d39d1372ed8f789c6
Console  : 5.0.9-dev-aa0ba91d92ae9324c1c0014d39d1372ed8f789c6

### I installed Metasploit with:
- [ ] Kali package via apt
- [X] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Mac OS 10.13.6

**Comment by mkienow-r7** [comment]
@Acidical Please provide any errors found in `~/.msf4/logs/msf-ws.log`.

**Comment by mkienow-r7** [comment]
In addition, if you have a moment run `msfdb --debug reinit` and provide the full output.

**Comment by Acidical** [comment]
The latest entry in `~/.msf4/logs/msf-ws.log`:
```
Writing PID to /Users/person/.msf4/msf-ws.pid
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on localhost:5443, CTRL+C to stop
Exiting!
/opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/connection.rb:430:in `block in start_tls': Could not find /Users/person/.msf4/msf-ws-key.pem for start_tls (EventMachine::FileNotFoundException)
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/connection.rb:428:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/connection.rb:428:in `start_tls'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:152:in `initialize_connection'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1527:in `event_callback'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /opt/metasploit-framework/embedded/bin/thin:23:in `load'
	from /opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
```
From this I'm guessing the problem is the missing TLS certificate but I don't see a reason why it would have suddenly disappeared?

This is output of `msfdb --debug reinit`
```
run_cmd: cmd=pg_ctl -o "-p 5433" -D /Users/person/.msf4/db status, input=, env={}
Stopping database at /Users/person/.msf4/db
run_cmd: cmd=pg_ctl -o "-p 5433" -D /Users/person/.msf4/db stop, input=, env={}
Found a database at /Users/person/.msf4/db, checking to see if it is started
run_cmd: cmd=pg_ctl -o "-p 5433" -D /Users/person/.msf4/db status, input=, env={}
'pg_ctl -o "-p 5433" -D /Users/person/.msf4/db status' returned 3
pg_ctl: no server running

Starting database at /Users/person/.msf4/db...run_cmd: cmd=pg_ctl -o "-p 5433" -D /Users/person/.msf4/db -l /Users/person/.msf4/db/log start, input=, env={}
run_cmd: cmd=pg_ctl -o "-p 5433" -D /Users/person/.msf4/db status, input=, env={}
success
MSF web service is no longer running
[?] Initial MSF web service account username? [acidical]:
[?] Initial MSF web service account password? (Leave blank for random password):
Attempting to start MSF web service...run_cmd: cmd=thin --rackup /opt/metasploit-framework/embedded/framework/msf-ws.ru --address localhost --port 5443 --ssl --ssl-key-file /Users/person/.msf4/msf-ws-key.pem --ssl-cert-file /Users/person/.msf4/msf-ws-cert.pem --ssl-disable-verify --environment production --daemonize --log /Users/person/.msf4/logs/msf-ws.log --pid /Users/person/.msf4/msf-ws.pid --tag msf-ws start, input=, env={}
Problem with HTTP get request /api/v1/msf/version, message: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)
web_service_online: expect_auth=false, response_msg={:response=>nil, :exception=>#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)>, :state=>:offline}
MSF web service doesn't appear to be online. Sleeping 5.0s until check 1/10
Problem with HTTP get request /api/v1/msf/version, message: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)
web_service_online: expect_auth=false, response_msg={:response=>nil, :exception=>#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)>, :state=>:offline}
MSF web service doesn't appear to be online. Sleeping 5.0s until check 2/10
Problem with HTTP get request /api/v1/msf/version, message: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)
web_service_online: expect_auth=false, response_msg={:response=>nil, :exception=>#<Errno::ECONNREFUSED: Failed to open TCP connection to localhost:5443 (Connection refused - connect(2) for "localhost" port 5443)>, :state=>:offline}
MSF web service doesn't appear to be online. Sleeping 5.0s until check 3/10
Problem with HTTP get request /api/v1/msf/version, message: Connection reset by peer - SSL_connect
web_service_online: expect_auth=false, response_msg={:response=>nil, :exception=>#<Errno::ECONNRESET: Connection reset by peer - SSL_connect>, :state=>:error}
failed
[!] MSF web service appears to be started, but may not operate as expected.

Please see /Users/person/.msf4/logs/msf-ws.log for additional details.
```

The command to start the Metasploit web service points to `/Users/person/.msf4/msf-ws-key.pem` for the TLS certificate but for some reason it is not there on my system. I know it used to be there and did not delete it.

**Comment by mkienow-r7** [comment]
@Acidical I'm unable to recreate your issue using the latest nightly installer. Have you edited that log in away that would have removed a line? If you note from the console output using the nightly installer on macOS there is a line "Generating SSL key and certificate for MSF web service". I don't see this in your output. That step of `msfdb` creates the certificate.

**Version:**
```
msf5 > version
Framework: 5.0.9-dev-7394b5bf2507c17cb255ee658074fb2a75c740b2
Console  : 5.0.9-dev-7394b5bf2507c17cb255ee658074fb2a75c740b2
```

**`msfdb` output:**
```
...
[?] Initial MSF web service account username? [msfdev]: 
[?] Initial MSF web service account password? (Leave blank for random password): 
Generating SSL key and certificate for MSF web service
Attempting to start MSF web service...success
MSF web service started and online
...
```

Would you provide output for the following?
* `which msfdb`
* `lsof -nP -i4TCP:5443 -i6TCP:5443 | grep LISTEN`
* Using the PID output from the above command: `ps aux <PID>`

**Comment by Acidical** [comment]
The reason that `Generating SSL key and certificate for MSF web service` didn't print seems to be because I specified no to deleting my existing data and configurations. I tried specifying yes and that line did print, and the certificate generated successfully. I could then start Metasploit without errors and `db_status` returns:
`[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.`

After this I tried reinitiating again but specifying no to deleting my existing data and configurations. During the reinit process the files `msf-ws-cert.pem` and `msf-ws-key.pem` were deleted. They were then not recreated afterwards. This is the problem.

```
[?] Would you like to delete your existing data and configurations?: no
Stopping database at /Users/person/.msf4/db
Found a database at /Users/person/.msf4/db, checking to see if it is started
Starting database at /Users/person/.msf4/db...success
Stopping MSF web service PID 2663
[?] Initial MSF web service account username? [acidical]: acidical
[?] Initial MSF web service account password? (Leave blank for random password): 
Attempting to start MSF web service...failed
[!] MSF web service appears to be started, but may not operate as expected.
```
The certificates seem to be deleted at this command:
`run_cmd: cmd=thin --rackup /opt/metasploit-framework/embedded/framework/msf-ws.ru --address localhost --port 5443 --ssl --ssl-key-file /Users/person/.msf4/msf-ws-key.pem --ssl-cert-file /Users/person/.msf4/msf-ws-cert.pem --ssl-disable-verify --environment production --daemonize --log /Users/person/.msf4/logs/msf-ws.log --pid /Users/person/.msf4/msf-ws.pid --tag msf-ws stop, input=, env={}` in `msfdb reinit --debug` and are not recreated afterwards, so then the web service cannot start correcly as the specified certificate doesn't exist in the start command.

I attempted clean installing using the osx nightly installer and this did not affect the problem.

**Comment by mkienow-r7** [comment]
@Acidical Thank you for your assessment of the issue. Following the steps you provided I've been able to recreate the issue.

**Comment by LuoooB** [comment]
我也是这个问题 有什么有效的解决方法嘛？希望您能分享一下 @mkienow-r7 @Acidical

**Comment by mkienow-r7** [comment]
@LuoooB This issue was resolved back in March. Please ensure you are using the latest version of Metasploit framework. If the issue persists open a new issue providing all of the requested information.

**Comment by nickkostov** [comment]
Weird I allowed the db port with ufw and it worked without any errors;
