### ISSUE TITLE
New payload data model assumes workspaces exist (esp. when using the web service?)

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-framework#11620]
## Steps to reproduce

How'd you do it?

1. Follow setup steps for #11616 
2. Specifically, 'save' your configuration, so your ~/.msf4/config file looks something this:

```
[framework/core]
LHOST=lo
LPORT=4343
PayloadUUIDTracking=true
HandlerSSLCert=/home/bcook/projects/metasploit-framework/cert.pem
StagerVerifySSLCert=true
IgnoreUnknownPayloads=true
LURI=/multi
```

3. run `msfdb reinit`

4. observe msfconsole can no longer start:

```
$ ./msfconsole -q
Traceback (most recent call last):
	25: from ./msfconsole:49:in `<main>'
	24: from /home/bcook/projects/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	23: from /home/bcook/projects/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	22: from /home/bcook/projects/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	21: from /home/bcook/projects/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	20: from /home/bcook/projects/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize'
	19: from /home/bcook/projects/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths'
	18: from /home/bcook/projects/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each'
	17: from /home/bcook/projects/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths'
	16: from /home/bcook/projects/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	15: from /home/bcook/projects/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	14: from /home/bcook/projects/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	13: from /home/bcook/projects/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `load_modules'
	12: from /home/bcook/projects/metasploit-framework/lib/msf/core/module_manager/loading.rb:117:in `each'
	11: from /home/bcook/projects/metasploit-framework/lib/msf/core/module_manager/loading.rb:119:in `block in load_modules'
	10: from /home/bcook/projects/metasploit-framework/lib/msf/core/modules/loader/base.rb:256:in `load_modules'
	 9: from /home/bcook/projects/metasploit-framework/lib/msf/core/modules/loader/base.rb:256:in `each'
	 8: from /home/bcook/projects/metasploit-framework/lib/msf/core/modules/loader/base.rb:259:in `block in load_modules'
	 7: from /home/bcook/projects/metasploit-framework/lib/msf/core/payload_set.rb:78:in `recalculate'
	 6: from /home/bcook/projects/metasploit-framework/lib/msf/core/payload_set.rb:78:in `each_pair'
	 5: from /home/bcook/projects/metasploit-framework/lib/msf/core/payload_set.rb:91:in `block in recalculate'
	 4: from /home/bcook/projects/metasploit-framework/lib/msf/core/payload.rb:204:in `size'
	 3: from /home/bcook/projects/metasploit-framework/lib/msf/core/payload/android.rb:38:in `generate'
	 2: from /home/bcook/projects/metasploit-framework/modules/payloads/singles/android/meterpreter_reverse_http.rb:48:in `generate_jar'
	 1: from /home/bcook/projects/metasploit-framework/lib/msf/core/payload/uuid/options.rb:47:in `generate_uri_uuid_mode'
/home/bcook/projects/metasploit-framework/lib/msf/core/payload/uuid/options.rb:119:in `record_payload_uuid_url': undefined method `urls' for nil:NilClass (NoMethodError)
```

## Expected behavior

It appears that when metasploit does its traditional (though something we should probably kill soon) 'startup and generate every payload with dynamic size', and if you have UUID checking enabled, it dutifully tries to store all of those things in the database as well. The failure here is opaque, but if we look at the web service, you can see what's happening:

```
[-] Error handling request: Mdm::Workspace(#47180525736260) expected, got Hash(#47180485101240).
    Call Stack:
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/associations/association.rb:218:in `raise_on_type_mismatch!'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/associations/belongs_to_association.rb:12:in `replace'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/associations/singular_association.rb:17:in `writer'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/associations/builder/association.rb:123:in `workspace='
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:54:in `public_send'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:65:in `block in assign_nested_parameter_attributes'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:65:in `each'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:65:in `assign_nested_parameter_attributes'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/attribute_assignment.rb:45:in `assign_attributes'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/core.rb:566:in `init_attributes'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/core.rb:281:in `initialize'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/inheritance.rb:61:in `new'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/inheritance.rb:61:in `new'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/persistence.rb:50:in `create!'
	 /home/bcook/projects/metasploit-framework/lib/msf/core/db_manager/payload.rb:11:in `block in create_payload'
	 /home/bcook/.rvm/gems/ruby-2.6.1@metasploit-framework/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
	 /home/bcook/projects/metasploit-framework/lib/msf/core/db_manager/payload.rb:4:in `create_payload'
	 /home/bcook/projects/metasploit-framework/lib/msf/core/web_services/servlet/payload_servlet.rb:27:in `block in create_payload'
```

It appears that the new 'payload' database object has a workspace associated with it, and it's failing to create the payload because the workspace 1 doesn't exist yet. I believe it's a reality of Metasploit's general design that payloads cannot actually have workspaces, because payloads are associated with sessions, and sessions also don't have workspaces. Also, you of course can't specify a workspace with tools like msfvenom, etc.

I see a few questions that probably need addressing:

 - Should any `setg` options from your config file really affect how any 'boot-time' payload generations are processed? I believe a goal of that 'boot time' generation originally was to cache any missing module sizes, but using anything other than defaults probably doesn't make sense.
 - Even better, can we completely kill 'boot-time' payload generation in the first place?
 - Can we remove the 'workspace' association with payloads entirely?
 - Why does this work fine with a local database connection, but fails with a remote web service connection? It's unclear why both don't fail, or both don't succeed.
 - It appears there's a way to tell db_manager workspace is optional, but this appears to have no effect on the error. What does this parameter do if there's still a failure? Does something have to be changed in metasploit_data_models instead?

```diff
--- a/lib/msf/core/db_manager/payload.rb
+++ b/lib/msf/core/db_manager/payload.rb
@@ -18,7 +18,7 @@ module Msf::DBManager::Payload
         return Array.wrap(Mdm::Payload.find(opts[:id]))
       end
 
-      wspace = Msf::Util::DBManager.process_opts_workspace(opts, framework)
+      wspace = Msf::Util::DBManager.process_opts_workspace(opts, framework, false)
       return wspace.payloads.where(opts)
     end
   end
```

**Comment by busterb** [comment]
BTW, to get call stack out of the web service (usually you get a condensed message in `~/.msf4/logs/framework.log`), I ran it as an independent program from the command line instead. To do this, I ran:

```
$ ./tools/dev/msfdb_ws -i 127.0.0.1
[!] SSL Disabled
Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 127.0.0.1:8080, CTRL+C to stop
```

Then modified my ~/.msf4/config file to point to that 

```
[framework/database/local-https-data-service]
url=http://127.0.0.1:8080
```

It makes iterating development nice and easy for debug.
