### ISSUE TITLE
sql query error 

### ISSUE THREAD

**Issue by ver007** [rapid7/metasploit-framework#12016]
in cobaltstrike 2.5 run server view

`"SELECT DISTINCT * FROM notes WHERE ntype = 'cloudstrike.listeners' ORDER BY id ASC"`

```
            // java code
            String var13;
            if (methodName.equals("db.key_values")) {
                HashMap var12 = new HashMap();
                var13 = params[0] + "";
                if (!var13.matches("[0-9a-zA-Z\\._]+")) {
                    ArmitageMain.print_error("DatabaseImpl.java - Key \'" + var13 + "\' did not validate!");
                    return new HashMap();
                }

                var12.put("values", this.executeQuery("SELECT DISTINCT * FROM notes WHERE ntype = \'" + var13 + "\' ORDER BY id ASC"));
                return var12;
            }




[-] DatabaseImpl.java - exception: null
java.lang.NullPointerException
	at msf.DatabaseImpl.executeQuery(DatabaseImpl.java:103)
	at msf.DatabaseImpl.execute(DatabaseImpl.java:384)
	at msf.RpcConnectionImpl.execute(RpcConnectionImpl.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sleep.engine.atoms.ObjectAccess$MethodCallRequest.execute(Unknown Source)
```

Through debugging, it is found that a SQL statement is executed and returned as NULL.

How can I solve it, thank you

**Comment by ver007** [comment]
database connet
