### ISSUE TITLE
FTP Client Fuzzer auxiliary module not running

### ISSUE THREAD

**Issue by mukesh610** [rapid7/metasploit-framework#12053]
## Steps to reproduce

    msf> use auxiliary/fuzzers/ftp/client_ftp
    msf auxiliary (fuzzers/ftp/client_ftp)> run

## Expected behavior

FTP Server for fuzzing should start up.

## Current behavior

Fails to start with following exception:

    [-] Auxiliary failed: NoMethodError undefined method `match' for {:check_empty=>false}:Hash
    [-] Call stack:
    [-]   /usr/share/metasploit-framework/lib/msf/core/opt_base.rb:118:in `valid?'
    [-]   /usr/share/metasploit-framework/lib/msf/core/opt_string.rb:34:in `valid?'
    [-]   /usr/share/metasploit-framework/lib/msf/core/option_container.rb:200:in `block in validate'
    [-]   /usr/share/metasploit-framework/lib/msf/core/option_container.rb:199:in `each_pair'
    [-]   /usr/share/metasploit-framework/lib/msf/core/option_container.rb:199:in `validate'

## System stuff

    Linux 4.19.0-kali3-amd64 #1 SMP Debian 4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux

### Metasploit version

    Framework: 5.0.34-dev
    Console  : 5.0.34-dev

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer
- [ ] Commercial/Community installer
- [ ] Source install

**Comment by mukesh610** [comment]
I don't know if this is a valid workaround, but I was able to get rid of the error by modifying line number 32, which was:
```ruby
OptString.new('FUZZCMDS', [ true, "Comma separated list of commands to fuzz (Uppercase).", "LIST,NLST,LS,RETR", nil, /(?:[A-Z]+,?)+/ ]),
```

to:

```ruby
OptString.new('FUZZCMDS', [ true, "Comma separated list of commands to fuzz (Uppercase).", "LIST,NLST,LS,RETR", nil]),
```

**Comment by adfoster-r7** [comment]
Looks like this should be fixed:

```
msf6 auxiliary(fuzzers/ftp/client_ftp) > run
[*] Running module against 127.0.0.1

[*] Started service listener on 0.0.0.0:21 
[*] Server started.
```
