### ISSUE TITLE
alphastor_devicemanager stack trace

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#12061]
## Steps to reproduce

How'd you do it?
```
resource (hotel-ext/master.rc)> use auxiliary/admin/emc/alphastor_devicemanager

Matching Modules
================

   #  Name                                              Disclosure Date  Rank    Check  Description
   -  ----                                              ---------------  ----    -----  -----------
   0  auxiliary/admin/emc/alphastor_devicemanager_exec  2008-05-27       normal  No     EMC AlphaStor Device Manager Arbitrary Command Execution


[*] Using auxiliary/admin/emc/alphastor_devicemanager_exec
resource (hotel-ext/master.rc)> run
[*] Running module against 172.21.49.143
[*] 172.21.49.143:3000 - Sending command: hostname
[-] 172.21.49.143:3000 - Auxiliary failed: EOFError EOFError
[-] 172.21.49.143:3000 - Call stack:
[-] 172.21.49.143:3000 -   /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream.rb:203:in `get_once'
[-] 172.21.49.143:3000 -   /usr/share/metasploit-framework/modules/auxiliary/admin/emc/alphastor_devicemanager_exec.rb:48:in `run'
[*] Auxiliary module execution completed
```
## Current behavior
Call stack

## System stuff
Kali latest patches as of

### Metasploit version
Framework: 5.0.35-dev
Console  : 5.0.35-dev

### I installed Metasploit with:
- [ ] Kali package via apt

### OS
Kali Linux

**Comment by bcoles** [comment]
Patch:

```diff
diff --git a/modules/auxiliary/admin/emc/alphastor_devicemanager_exec.rb b/modules/auxiliary/admin/emc/alphastor_devicemanager_exec.rb
index c7517ac200..2fafc02fa9 100644
--- a/modules/auxiliary/admin/emc/alphastor_devicemanager_exec.rb
+++ b/modules/auxiliary/admin/emc/alphastor_devicemanager_exec.rb
@@ -52,6 +52,9 @@ class MetasploitModule < Msf::Auxiliary
     end
 
     disconnect
-
+  rescue ::Rex::ConnectionError => e
+    print_error 'Connection failed'
+  rescue ::EOFError => e
+    print_error 'No reply'
   end
 end
```
