### ISSUE TITLE
strange error when using multi thread in “cve_2019_0708_bluekeep”

### ISSUE THREAD

**Issue by qwx** [rapid7/metasploit-framework#12069]
When using multi threads (more than 30 or 16 in windows), the result of scan is error, some hosts which NOT vulnerable are regarded as vulnerable and show on the list. 
When using 1 thread, the result is right.
There are about 200+ vulnerable hosts in the network.
## Example
10.6.0.1 is not vulnerable when set rhosts 10.6.0.1 or set rhosts 10.6.0.0/16 and thread 1
10.6.0.1 is vulnerable when set rhosts 10.6.0.0/16 and threads 30
when run next time, hosts are changed. (though some real vulnerable hosts are always on the list)

How'd you do it?
1.set rhosts 10.6.0.0/16
2.set ConnectTimeout 3
3.set threads 30
4. run

## Expected behavior
only vulnerable hosts are show on the list.
What should happen?

## Current behavior

NOT vulnerable hosts are regarded as vulnerable and show on the list.

`~/.msf4/logs/framework.log` 
[07/08/2019 12:16:01] [e(0)] core: EOFError
/opt/metasploit-framework/embedded/lib/ruby/gems/2.5.0/gems/rex-core-0.1.13/lib/rex/io/stream.rb:203:in `get_once'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:395:in `rdp_recv'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:403:in `rdp_send_recv'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:290:in `check_rdp_vuln'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:93:in `check_host'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb:65:in `run_host'
/opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'

### Metasploit version
Framework: 5.0.36-dev-
Console  : 5.0.36-dev-

### I installed Metasploit with:
install using rpm package
metasploit-framework-5.0.36+20190707102508~1rapid7-1.el6.x86_64.rpm

### OS

What OS are you running Metasploit on?
Centos7

sorry for my English

If need more log, i can upload in the issue!
Thanks

**Comment by qwx** [comment]
I don't know what will happen if I use another module. I only test with cve_2019_0708_bluekeep
