### ISSUE TITLE
/2.5.0/x64-mingw32/stringio.so (LoadError)

### ISSUE THREAD

**Issue by MrWhits** [rapid7/metasploit-framework#12186]
Hello I have a Problem..

This is the log !

```
Traceback (most recent call last):
        6: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        5: from <internal:gem_prelude>:2:in `require'
        4: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms.rb:117:in `<top (required)>'
        3: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms.rb:1366:in `<module:Gem>'
        2: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms.rb:1366:in `require'
        1: from D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubyge
ms/specification.rb:18:in `<top (required)>'
D:/metasploit-framework/embedded/lib/ruby/site_ruby/2.5.0/rubygems/specification
.rb:18:in `require': 126: The specified module could not be found.   - D:/metasp
loit-framework/embedded/lib/ruby/2.5.0/x64-mingw32/stringio.so (LoadError)
```

My OS
-Windows 7 Ultimate
Ruby Version
-ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-cygwin]

**Comment by bwatters-r7** [comment]
Can you tell us what you were trying to do and what installer/version of metasploit you are using?

**Comment by MrWhits** [comment]
My metasploit version is 
~ Metasploit Framework 5.0.40

**Comment by bcook-r7** [comment]
Hi, we only support Windows 8 and up, due to incompatibilities with the build toolchain. Please try a newer version of Windows or a VM. Thanks!
