### ISSUE TITLE
[bug]workspace -v error

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#12224]
Mac OS
metasploit v5.0.42-dev-015651dd088a0d9932d4ddb5386cd73c0f689d28
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin15]
```
workspace -v
[-] Error while running command workspace: Problem with HTTP request for type/path: GET /api/v1/hosts message: Net::OpenTimeout

Call stack:
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:63:in `json_to_mdm_object'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/remote_host_data_service.rb:12:in `hosts'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/host_data_proxy.rb:10:in `block in hosts'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/host_data_proxy.rb:5:in `hosts'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:242:in `block in cmd_workspace'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:238:in `each'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:238:in `cmd_workspace'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:151:in `run'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'
```

**Comment by hktalent** [comment]
services -p 3306
```
services -p 3306
[-] Error while running command services: Problem with HTTP request for type/path: GET /api/v1/services message: Net::OpenTimeout

Call stack:
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:63:in `json_to_mdm_object'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/remote_service_data_service.rb:7:in `services'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:7:in `block in services'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/service_data_proxy.rb:5:in `services'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:770:in `block in cmd_services'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2130:in `block in each_host_range_chunk'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each_host_range_chunk'
/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:765:in `cmd_services'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:151:in `run'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit-framework/bin/../embedded/framework/msfconsole:49:in `<main>'
```
very slow

**Comment by dustineichler** [comment]
I was able to test this locally on `015651dd088` using `2.5.3`. unable to reproduce as reported. both commands return successfully.
