### ISSUE TITLE
Trying to display tags for hosts raises exception

### ISSUE THREAD

**Issue by michaelkruglos** [rapid7/metasploit-framework#12232]
## Steps to reproduce

1. start msfconsole
2. hosts -a 10.1.1.0/24
3. hosts 10.1.1.0/24 -c 'address,tags'

## Expected behavior

List addresses and tags (if available)

## Current behavior

Exception with the following message and stack trace:
```
[-] Error while running command hosts: undefined method `find_host_tags' for #<Msf::DBManager:0x000055b027de8b68>
Did you mean?  add_host_tag

Call stack:
/root/dev/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:340:in `find_host_tags'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:562:in `block (3 levels) in cmd_hosts'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:554:in `map'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:554:in `block (2 levels) in cmd_hosts'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
/var/lib/gems/2.5.0/gems/activerecord-4.2.11.1/lib/active_record/relation/delegation.rb:46:in `each'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:552:in `block in cmd_hosts'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2130:in `block in each_host_range_chunk'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2111:in `each_host_range_chunk'
/root/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:549:in `cmd_hosts'
/root/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/root/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/root/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/root/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/root/dev/metasploit-framework/lib/rex/ui/text/shell.rb:151:in `run'
/root/dev/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/root/dev/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/root/dev/metasploit-framework/msfconsole:49:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
/usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
/usr/lib/ruby/vendor_ruby/thor.rb:369:in `dispatch'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/share/rubygems-integration/all/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
```

### Metasploit version

apt install:
Framework: 5.0.41-dev
Console : 5.0.41-dev

source install:
c000625

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

Kali 64 bit.

**Comment by agalway-r7** [comment]
Fixed with the PR https://github.com/rapid7/metasploit-framework/pull/13316.
