### ISSUE TITLE
Java meterpeter: cannot "ls <relative_path>"

### ISSUE THREAD

**Issue by cnotin** [rapid7/metasploit-framework#12241]
[I'm working on it, please ignore for now :) ]

## Steps to reproduce

1. obtain a java meterpreter
2. list content of current folder with "ls"
3. observe that a folder called "folder" is present. This folder must be empty!
4. instead of opening it ("cd"), just try to list its content with "ls folder"
No issue when listing it with absolute path...

I open the issue here, instead of in the metasploit-payloads repo, because I yet do not know where the issue is located...

## Expected behavior

See the content of the "folder" folder

## Current behavior

Error message:
> [-] stdapi_fs_ls: Operation failed: 1

## Debug
Based on my basic tests, the error is triggered by this line:
https://github.com/rapid7/metasploit-framework/blob/768e3b497195fa3d4ca91795c93f10138203152e/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb#L629

### Metasploit version

> Framework: 5.0.34-dev
> Console  : 5.0.34-dev

### I installed Metasploit with:
- Kali package via apt

### OS
Kali

**Comment by cnotin** [comment]
Origin if the issue confirmed.
I opened an irb shell and this works:
> fs.dir.entries_with_info(".")

This crashes:
> irb(#<Msf::Sessions::Meterpreter_Java_Java:0xredacted>):005:0>
```
fs.dir.entries_with_info("folder")
Traceback (most recent call last):
       16: from /usr/share/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'
       15: from /usr/share/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:575:in `_interact'
       14: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
       13: from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:146:in `run'
       12: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
       11: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
       10: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
        9: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
        8: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
        7: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
        6: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:580:in `cmd_irb'
        5: from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
        4: from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
        3: from /usr/share/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
        2: from (irb):5
        1: from /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/fs/dir.rb:82:in `entries_with_info'
```

**Comment by cnotin** [comment]
I tried to replicate the code from https://github.com/rapid7/metasploit-payloads/blob/18ed237c1d9ae70030d1b01e64eb67b2c75fa9db/java/meterpreter/stdapi/src/main/java/com/metasploit/meterpreter/stdapi/stdapi_fs_ls.java in an empty Java project and it works fine. Even on empty folders with absolute path...

**Comment by cnotin** [comment]
Replaced by
https://github.com/rapid7/metasploit-payloads/issues/357
