### ISSUE TITLE
msfrpcd fails with "-j" option, missing certs

### ISSUE THREAD

**Issue by makinbakonpancakes** [rapid7/metasploit-framework#12356]
## Steps to reproduce

1. After succesfully running `msfdb init` and verifying `msfdb status` is running
2. `msfrpcd -U msf -P msf123 -j` thinks db isn't running
3. Runs correctly without the -j option

msfrpcd is checking for cert files which were not created by the msfdb init. Is the error in msfdb not creating them when it should? msfrpc json isn't restricted to the non-free msf is it? Perhaps the error message or the check for the db should be different here as well?

Line 204-209 of msfrpcd
```ruby
    if json_rpc

      if !File.file?(ws_ssl_key_default) || !File.file?(ws_ssl_cert_default)
        $stdout.puts "[-] It doesn't appear msfdb has been run; please run 'msfdb init' first."
        abort
      end
```

## Expected behavior

msf rpc service using json rather than message pack should be started.

## Current behavior

prints error message `[-] It doesn't appear msfdb has been run; please run 'msfdb init' first.`

Nothing relevant in framework.log file

### Metasploit version

5.0.49-dev

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Kali Linux Rolling

**Comment by makinbakonpancakes** [comment]
So I moved past the erorr by just creating those files with:

```sh
openssl req -newkey rsa:2048 -nodes -keyout msf-ws-key.pem -x509 -days 365 -out msf-ws-cert.pem
```

But the above questions still remain. Should msfdb be doing that already? And should I expect msfrpcd to work correctly now that I've made this cert and key?

Let me know if this should be in a different issue but it doesn't seem to have started. It prints out:
```sh
[*] JSON-RPC starting on 0.0.0.0:55553 (SSL)...
[*] URI: /api/v1/json-rpc
[*] JSON-RPC server log: /root/.msf4/logs/msf-json-rpc.log
[*] JSON-RPC server PID file: /root/.msf4/msf-json-rpc.pid
```
But there is nothing on port 55553 and the log file has the following erorr:
```
Writing PID to /root/.msf4/msf-json-rpc.pid
Exiting!
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require': cannot load such file -- swagger/blocks (LoadError)
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/share/metasploit-framework/lib/msf/core/web_services/json_rpc_app.rb:3:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/backports-3.15.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/share/metasploit-framework/msf-json-rpc.ru:19:in `block in <main>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `initialize'
	from /usr/share/metasploit-framework/msf-json-rpc.ru:1:in `new'
	from /usr/share/metasploit-framework/msf-json-rpc.ru:1:in `<main>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:72:in `start'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/thin-1.7.2/bin/thin:6:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/bin/thin:23:in `load'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/bin/thin:23:in `<main>'
```

I tried `gem install swagger-blocks` but with the same result.

**Comment by Explorer1092** [comment]
@ebleiweiss-r7

**Comment by bYasmine96** [comment]
any response?

**Comment by jk0101-afk** [comment]
How to solve this problem? @makinbakonpancakes

**Comment by jk0101-afk** [comment]
@makinbakonpancakes   
You need to execute `sudo bundle install --with development test` install the extension
