### ISSUE TITLE
#report_web_vuln and other #report_web_* methods missing for HTTP data service

### ISSUE THREAD

**Issue by cdelafuente-r7** [rapid7/metasploit-framework#12523]
It appears that `#report_web_vuln` and other `#report_web_*` methods are only available when using the database and not when using the HTTP data service.

## Steps to reproduce
As an example, I will use #12486 PR (scanner/http/host_header_injection aux module), which makes use of `#report_web_vuln`:
```
msf5 auxiliary(scanner/http/host_header_injection) > db_status
[*] Connected to remote_data_service: (https://localhost:5443). Connection type: http. Connection name: local-https-data-service.
msf5 auxiliary(scanner/http/host_header_injection) > run

[+] 1.2.3.4:80/drupal/ (1.2.3.4)(200)(GET)(evidence into body) is vulnerable to HTTP Host header injection
[-] Auxiliary failed: NoMethodError undefined method `report_web_vuln' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x00007ff08da2b900>
Did you mean?  report_vuln
               report_web_site
[-] Call stack:
[-]   /r7/src/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
[-]   /r7/src/metasploit-framework/lib/msf/core/auxiliary/report.rb:363:in `report_web_vuln'
[-]   /r7/src/metasploit-framework/modules/auxiliary/scanner/http/host_header_injection.rb:99:in `run_host'
[-]   /r7/src/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:111:in `block (2 levels) in run'
[-]   /r7/src/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[*] Auxiliary module execution completed
```

## Expected behavior
```
msf5 auxiliary(scanner/http/host_header_injection) > db_status
[*] Connected to msf. Connection type: postgresql.
msf5 auxiliary(scanner/http/host_header_injection) > run

[+] 1.2.3.4:80/drupal/ (1.2.3.4)(200)(GET)(evidence into body) is vulnerable to HTTP Host header injection
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
```

**Comment by busterb** [comment]
I believe that things reported by `report_web_vuln` are not accessible anywhere from `msfconsole` except in the wmap plugin. I wonder if it makes sense to migrate web_vuln to just be a regular vuln, and/or make the 'vulns' command also understand these.
