### ISSUE TITLE
Failure/Error Msf::OptAddressLocal behaves like an option with valid values en0

### ISSUE THREAD

**Issue by dustineichler** [rapid7/metasploit-framework#12525]
`bundle exec rspec spec/lib/msf/core/opt_address_local_spec.rb`

This assertion fails:

https://github.com/rapid7/metasploit-framework/blob/master/spec/support/shared/examples/an_option.rb#L34

Stack trace:

```
 1) Msf::OptAddressLocal behaves like an option with valid values should be valid and normalize appropriately: en0
     Failure/Error: expect(subject.normalize(valid_value)).to eq normalized_value

       expected: "192.168.1.136"
            got: "fd92:24f0:6e87:b43e"

       (compared using ==)
     Shared Example Group: "an option" called from ./spec/lib/msf/core/opt_address_local_spec.rb:57
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-support-3.9.0/lib/rspec/support.rb:97:in `block in <module:Support>'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-support-3.9.0/lib/rspec/support.rb:106:in `notify_failure'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-expectations-3.9.0/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:38:in `handle_failure'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-expectations-3.9.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-expectations-3.9.0/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/support/shared/examples/an_option.rb:34:in `block (5 levels) in <top (required)>'
     # ./spec/support/shared/examples/an_option.rb:40:in `block (4 levels) in <top (required)>'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:257:in `instance_exec'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:257:in `block in run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:503:in `block in with_around_and_singleton_context_hooks'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:460:in `block in with_around_example_hooks'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:472:in `block in run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:612:in `block in run_around_example_hooks_for'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:345:in `call'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-rails-3.9.0/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:450:in `instance_exec'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:381:in `execute_with'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:614:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:345:in `call'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:615:in `run_around_example_hooks_for'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/hooks.rb:472:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:460:in `with_around_example_hooks'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:503:in `with_around_and_singleton_context_hooks'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example.rb:254:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:633:in `block in run_examples'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:629:in `map'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:629:in `run_examples'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:595:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `block in run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `map'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `block in run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `map'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/example_group.rb:596:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:121:in `map'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/configuration.rb:2031:in `with_suite_hooks'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/reporter.rb:74:in `report'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:89:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:71:in `run'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/gems/rspec-core-3.9.0/exe/rspec:4:in `<top (required)>'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/bin/rspec:23:in `load'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/bin/rspec:23:in `<main>'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/bin/ruby_executable_hooks:24:in `eval'
     # /Users/dustin/.rvm/gems/ruby-2.6.5@metasploit-framework/bin/ruby_executable_hooks:24:in `<main>'
```
## Expected behavior

Expect `normalize` to map and return first ip4 address.

### Metasploit version

`b7acbfe8b6fe4060e1494003b31c627b94f2fb5e (HEAD -> master, upstream/master) automatic module_metadata_base.json update`

### Installed with:

- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
```

**Comment by wvu-r7** [comment]
Confirmed locally on OS X. Passing in Travis.
