### ISSUE TITLE
Metasploit fails at OpenVAS Connect

### ISSUE THREAD

**Issue by zagwalker** [rapid7/metasploit-framework#12612]
## Steps to reproduce

How'd you do it?

1. msfconsole
2. load openvas
3. openvas_connect admin ****** 10.0.132.138 9392 ok

```
[*] Connecting to OpenVAS instance at 10.0.132.138:9392 with username admin...
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/openvas-omp-0.0.4/lib/openvas-omp.rb:201: warning: Object#timeout is deprecated, use Timeout.timeout instead.
[-] Error while running command openvas_connect: uninitialized constant OpenVASOMP::OMPConnectionError

Call stack:
/usr/share/metasploit-framework/plugins/openvas.rb:195:in `rescue in cmd_openvas_connect'
/usr/share/metasploit-framework/plugins/openvas.rb:189:in `cmd_openvas_connect'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:49:in `<main>'
```
Port 9392 is open and OpenVAS works well.

### I installed Metasploit with:
- [X] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Linux kali 5.3.0-kali1-amd64 #1 SMP Debian 5.3.7-1kali2 (2019-11-04) x86_64 GNU/Linux

**Comment by bcoles** [comment]
Looks like a dupe of #12596

**Comment by bcoles** [comment]
Are you still receiving this error?

I was only able to reproduce the error when OpenVAS was not listening.

```
msf5 > load openvas
[*] Welcome to OpenVAS integration by kost and averagesecurityguy.
[*] 
[*] OpenVAS integration requires a database connection. Once the 
[*] database is ready, connect to the OpenVAS server using openvas_connect.
[*] For additional commands use openvas_help.
[*] 
[*] Successfully loaded plugin: OpenVAS
msf5 > openvas_connect admin admin 127.0.0.1 9390
[*] Connecting to OpenVAS instance at 127.0.0.1:9390 with username admin...
[-] Error while running command openvas_connect: uninitialized constant OpenVASOMP::OMPConnectionError

Call stack:
/root/Desktop/metasploit-framework/plugins/openvas.rb:195:in `rescue in cmd_openvas_connect'
/root/Desktop/metasploit-framework/plugins/openvas.rb:189:in `cmd_openvas_connect'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/root/Desktop/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/root/Desktop/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/root/Desktop/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/root/Desktop/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
msf5 > lsof -i :9390
[*] exec: lsof -i :9390

msf5 > service openvas-manager start
[*] exec: service openvas-manager start

msf5 > lsof -i :9390
[*] exec: lsof -i :9390

COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
openvasmd 34750 root    4u  IPv4 733149      0t0  TCP localhost:9390 (LISTEN)
msf5 > openvas_connect admin admin 127.0.0.1 9390
[*] Connecting to OpenVAS instance at 127.0.0.1:9390 with username admin...
/var/lib/gems/2.5.0/gems/openvas-omp-0.0.4/lib/openvas-omp.rb:201: warning: Object#timeout is deprecated, use Timeout.timeout instead.
[+] OpenVAS connection successful
msf5 > 
```

**Comment by zagwalker** [comment]
Since I havent managed to make it work I decided to use another vulnerability scanner :(

We should be having another project soon, I'll try again.

**Comment by bcoles** [comment]
I haven't been able to reproduce this error (unless OpenVAS is not listening). There has been some other work related to the OpenVAS plugin performed recently too, and the error was not encountered.

Which version of OpenVAS were you using?

I'm going to close this issue, but if you can reproduce again, please re-open.
