### ISSUE TITLE
windows/encrypted_shell.rb cannot be loaded

### ISSUE THREAD

**Issue by Q1984** [rapid7/metasploit-framework#12709]
## Steps to reproduce

How'd you do it?

1. ... Starting metasploit v5.0.63-dev

## Expected behavior

Load without errors

## Current behavior

WARNING! The following modules could not be loaded!
[-] 	/usr/share/metasploit-framework/modules/payloads/stages/windows/encrypted_shell.rb
[-] Please see /root/.msf4/logs/framework.log for details.

[12/12/2019 09:23:08] [e(0)] core: /usr/share/metasploit-framework/modules/payloads/stages/windows/encrypted_shell.rb failed to load due to the following error: NameError uninitialized constant Msf::Payload::Windows::EncryptedPayloadOpts Call stack: /usr/share/metasploit-framework/modules/payloads/stages/windows/encrypted_shell.rb:12:in `<module:MetasploitModule>' /usr/share/metasploit-framework/modules/payloads/stages/windows/encrypted_shell.rb:9:in `module_eval_with_lexical_scope' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:51:in `module_eval' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:51:in `module_eval_with_lexical_scope' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:140:in `block in load_module' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:567:in `namespace_module_transaction' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:178:in `load_module' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:246:in `block in load_modules' /usr/share/metasploit-framework/lib/msf/core/modules/loader/directory.rb:49:in `block (2 levels) in each_module_reference_name' /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:133:in `block in find' /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `catch' /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-core-0.1.13/lib/rex/file.rb:132:in `find' /usr/share/metasploit-framework/lib/msf/core/modules/loader/directory.rb:40:in `block in each_module_reference_name' /usr/share/metasploit-framework/lib/msf/core/modules/loader/directory.rb:30:in `foreach' /usr/share/metasploit-framework/lib/msf/core/modules/loader/directory.rb:30:in `each_module_reference_name' /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:245:in `load_modules' /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:135:in `block in load_modules' /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:133:in `each' /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:133:in `load_modules' /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path' /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each' /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path' /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `block in init_module_paths' /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `each' /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:49:in `init_module_paths' /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:161:in `initialize' /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new' /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver' /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start' /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start' /usr/bin/msfconsole:49:in `<main>'

### Metasploit version
metasploit v5.0.63-dev

### I installed Metasploit with:
- [X ] Kali package via apt

### OS

Kali

**Comment by space-r7** [comment]
I wasn't able to reproduce this error, but I put up a PR for what is likely the fix.
