### ISSUE TITLE
Route Add/ Autoroute failing to execute

### ISSUE THREAD

**Issue by Nightbringer21** [rapid7/metasploit-framework#12805]
## Steps to reproduce

Trying to use the route add/delete or the autoroute post module leads to an error.  As a result, new routes can't be added on the console for pivoting purposes due to a potential rename of a function call.
This was replicated with both windows meterprete x86 and x64 reverse_tcp payloads.

Potentially associated with issue: #11491 

## Expected behavior
What should happen?
```
msf5 post(multi/manage/autoroute) > route add 192.168.34.1/24 6
[*] Route added
```

## Current behavior

What happens instead?

```
msf5 post(multi/manage/autoroute) > route add 192.168.34.1/24 6
[-] undefined method `report_session_route' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x000000000964c478>
Did you mean?  report_session_event
```
autoroute
```
msf5 post(multi/manage/autoroute) > run

[!] SESSION may not be compatible with this module.
[*] Running module against WIN10
[*] Searching for subnets to autoroute.
[-] Post failed: NoMethodError undefined method `report_session_route' for #<Metasploit::Framework::DataService::RemoteHTTPDataService:0x000000000964c478>
Did you mean?  report_session_event
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/framework.rb:503:in `on_session_route'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/event_dispatcher.rb:183:in `block in method_missing'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/event_dispatcher.rb:181:in `each'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
[-]   /opt/metasploit-framework/embedded/framework/lib/msf/core/session.rb:424:in `<<'
[-]   /opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/rex-socket-0.1.21/lib/rex/socket/switch_board.rb:80:in `add_route'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/multi/manage/autoroute.rb:232:in `add_route'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/multi/manage/autoroute.rb:299:in `block in autoadd_routes'
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/net/config.rb:174:in `each'
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/net/config.rb:174:in `each_route'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/multi/manage/autoroute.rb:293:in `autoadd_routes'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/multi/manage/autoroute.rb:73:in `run'
[*] Post module execution completed
```

### Metasploit version

Framework: 5.0.68-dev-
Console  : 5.0.68-dev-

### I installed Metasploit with:
- [ x] Kali package via apt

### OS

Kali Linux

**Comment by space-r7** [comment]
I think you're correct in this being associated with #11491. Just looks like the data service doesn't have `report_session_route()` implemented.

**Comment by dwelch-r7** [comment]
Sorry, shouldn't have been closed, working on this now
