### ISSUE TITLE
termux metasploit error

### ISSUE THREAD

**Issue by canxx99** [rapid7/metasploit-framework#13097]
![Screenshot_20200319_182456_com termux](https://user-images.githubusercontent.com/52892904/77084173-a7c54b00-6a0f-11ea-92a4-7d3aa55b1625.jpg)

`$ cat framework.log
[03/19/2020 18:18:51] [d(0)] core: Created user based module store
[03/19/2020 18:19:00] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:19:00] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:19:01] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:19:01] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:19:03] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[03/19/2020 18:21:25] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:21:25] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:21:26] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:21:26] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:21:29] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[03/19/2020 18:23:18] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:23:18] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:23:19] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:23:19] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:23:21] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[03/19/2020 18:24:26] [e(0)] core: Exception 1/30 in monitor thread ActiveRecord::StatementInvalid PG::ConnectionBad: PQsocket() can't get socket descriptor: SET client_min_messages TO 'warning'
[03/19/2020 18:24:26] [e(0)] core: Call stack:
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:286:in `client_min_messages='
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `configure_connection'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:277:in `reconnect!'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:340:in `verify!'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:456:in `block in checkout_and_verify'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_checkout_callbacks'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager/connection.rb:120:in `connection_established?'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager/connection.rb:6:in `active'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:47:in `active'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/session_manager.rb:104:in `block in initialize'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[03/19/2020 18:24:45] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:24:45] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:24:46] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:24:47] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:24:48] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[03/19/2020 18:33:49] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:33:49] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:33:51] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:33:51] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:38:19] [e(0)] core: Exception 2/30 in monitor thread ActiveRecord::StatementInvalid PG::UnableToSend: no connection to the server
: SET client_min_messages TO 'warning'
[03/19/2020 18:38:19] [e(0)] core: Call stack:
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:286:in `client_min_messages='
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `configure_connection'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:277:in `reconnect!'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:340:in `verify!'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:456:in `block in checkout_and_verify'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_checkout_callbacks'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager/session.rb:204:in `remove_stale_sessions'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/session_manager.rb:132:in `block in initialize'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[03/19/2020 18:38:48] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:38:48] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:38:49] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:38:49] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:38:51] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[03/19/2020 18:40:11] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:40:11] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:40:12] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:40:12] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:40:24] [e(0)] core: Exception 3/30 in monitor thread ActiveRecord::StatementInvalid PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
: SET client_min_messages TO 'warning'
[03/19/2020 18:40:24] [e(0)] core: Call stack:
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:286:in `client_min_messages='
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:673:in `configure_connection'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:277:in `reconnect!'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract_adapter.rb:340:in `verify!'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:456:in `block in checkout_and_verify'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_checkout_callbacks'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:455:in `checkout_and_verify'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
/data/data/com.termux/files/usr/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/data/data/com.termux/files/usr/lib/ruby/gems/2.7.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager/connection.rb:120:in `connection_established?'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager/connection.rb:6:in `active'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/db_manager/session.rb:202:in `remove_stale_sessions'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:136:in `method_missing'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/session_manager.rb:132:in `block in initialize'
/data/data/com.termux/files/usr/opt/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[03/19/2020 18:40:47] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:40:47] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:40:48] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:40:48] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:40:51] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type
[03/19/2020 18:41:24] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:41:24] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:41:25] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:41:25] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:42:33] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:42:33] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/19/2020 18:42:34] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/19/2020 18:42:34] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/19/2020 18:42:37] [e(0)] core: Unable to load module /data/data/com.termux/files/usr/opt/metasploit-framework/modules/auxiliary/gather/office365userenum.py, unknown module type`

termux metasploit I do not know if I am in the right place for this problem when these errors start after the last update, but can you help me?

**Comment by ccondon-r7** [comment]
Hi there! We do not actually support Termux at this time. The community has a few resources on Metasploit and Termux if you Google around, though. Best of luck!
