### ISSUE TITLE
Auxiliary failed: NoMethodError undefined method `>=' for nil:NilClass

### ISSUE THREAD

**Issue by blakeboy01** [rapid7/metasploit-framework#13217]
## Steps to reproduce
 
 1.
```
use auxiliary/scanner/postgres/postgres_login
```

 2.
```
set RHOST <TARGET>
```

 3.
```
run
```

## Expected behavior

To run without error and have success if vulnerability it found. 

## Current behavior

```
Auxiliary failed: NoMethodError undefined method `>=' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/message.rb:49:in `read'
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/connection.rb:71:in `block in initialize'
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/connection.rb:70:in `loop'
[-]   /usr/share/metasploit-framework/lib/postgres/postgres-pr/connection.rb:70:in `initialize'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/postgres.rb:44:in `new'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/postgres.rb:44:in `attempt_login'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:154:in `block in each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:157:in `block (3 levels) in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:155:in `each_line'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:155:in `block (2 levels) in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:143:in `each_line'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:143:in `block in each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:142:in `open'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/credential_collection.rb:142:in `each'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-]   /usr/share/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/postgres/postgres_login.rb:78:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:117:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version

```
5.0.83
```

### I installed Metasploit with:

- [ ] Kali package via apt

### OS

Kali Linux.

**Comment by gwillcox-r7** [comment]
@blakeboy01 Did you try replacing <TARGET> with the IP address? Or did you literally just type <TARGET> for the IP address value?

**Comment by Blakeboy02** [comment]
@gwillcox-r7 Hi, yes I did replace <TARGET> with the victim IP.

**Comment by gwillcox-r7** [comment]
Hmm odd that shouldn't be happening. Let me see if I can't repo this quickly.

**Comment by gwillcox-r7** [comment]
Its working fine for me from the Git repo clone on the latest updates. No login succeeded since I didn't provide it with the right password but otherwise working fine for the most part:
```
msf5 > use auxiliary/scanner/postgres/postgres_login 
msf5 auxiliary(scanner/postgres/postgres_login) > show options

Module options (auxiliary/scanner/postgres/postgres_login):

   Name              Current Setting                                                                Required  Description
   ----              ---------------                                                                --------  -----------
   BLANK_PASSWORDS   false                                                                          no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                                                                              yes       How fast to bruteforce, from 0 to 5
   DATABASE          template1                                                                      yes       The database to authenticate against
   DB_ALL_CREDS      false                                                                          no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false                                                                          no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                                                                          no        Add all users in the current database to the list
   PASSWORD                                                                                         no        A specific password to authenticate with
   PASS_FILE         /opt/rapid7/metasploit-framework/data/wordlists/postgres_default_pass.txt      no        File containing passwords, one per line
   Proxies                                                                                          no        A proxy chain of format type:host:port[,type:host:port][...]
   RETURN_ROWSET     true                                                                           no        Set to true to see query result sets
   RHOSTS                                                                                           yes       The target host(s), range CIDR identifier, or hosts file with syntax 'file:<path>'
   RPORT             5432                                                                           yes       The target port
   STOP_ON_SUCCESS   false                                                                          yes       Stop guessing when a credential works for a host
   THREADS           1                                                                              yes       The number of concurrent threads (max one per host)
   USERNAME                                                                                         no        A specific username to authenticate as
   USERPASS_FILE     /opt/rapid7/metasploit-framework/data/wordlists/postgres_default_userpass.txt  no        File containing (space-separated) users and passwords, one pair per line
   USER_AS_PASS      false                                                                          no        Try the username as the password for all users
   USER_FILE         /opt/rapid7/metasploit-framework/data/wordlists/postgres_default_user.txt      no        File containing users, one per line
   VERBOSE           true                                                                           yes       Whether to print output for all attempts

msf5 auxiliary(scanner/postgres/postgres_login) > set RHOST 127.0.0.1
RHOST => 127.0.0.1
msf5 auxiliary(scanner/postgres/postgres_login) > run
*cut for brevity*
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:@template1 (Incorrect: FATAL	VFATAL	C28000	Mrole "postgres" does not exist	Fmiscinit.c	L607	RInitializeSessionUserId)
[-] 127.0.0.1:5432 - LOGIN FAILED: postgres:tiger@template1 (Incorrect: FATAL	VFATAL	C28000	Mrole "postgres" does not exist	Fmiscinit.c	L607	RInitializeSessionUserId)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:admin@template1 (Incorrect: FATAL	VFATAL	C28000	Mrole "admin" does not exist	Fmiscinit.c	L607	RInitializeSessionUserId)
[-] 127.0.0.1:5432 - LOGIN FAILED: admin:password@template1 (Incorrect: FATAL	VFATAL	C28000	Mrole "admin" does not exist	Fmiscinit.c	L607	RInitializeSessionUserId)
[*] Scanned 1 of 1 hosts (100% complete)
[*] Auxiliary module execution completed
msf5 auxiliary(scanner/postgres/postgres_login) > 

```

**Comment by Blakeboy02** [comment]
@gwillcox-r7 Hi again, I should've stated above that this thread is about the dev version but the one problem is that I can't downgrade since my system is 64 bit but for some reason right now it doesn't let me download 64 bit applications and you can only download 64 bit Metasploit versions directly.

**Comment by gwillcox-r7** [comment]
@Blakeboy02 Whether your system or OS is x64 or x86 shouldn't matter. The code for Metasploit is written in Ruby so so long as your system has a Ruby interpreter and you've cloned the latest updates to this repository, you should be fine.

If you can't upgrade/downgrade, simply open up a command prompt, create a new directory, and then enter `git clone https://github.com/rapid7/metasploit-framework/` and you should be able to clone the repository with the latest updates included.

**Comment by Blakeboy02** [comment]
@gwillcox-r7 So the X64 on the file doesn't matter?

**Comment by gwillcox-r7** [comment]
@Blakeboy02 Sorry I'm not sure which file you are referring to, can you give me the file name or the link to the file you are referencing?

**Comment by Blakeboy02** [comment]
@gwillcox-r7 https://github.com/rapid7/metasploit-framework/wiki/Downloads-by-Version

**Comment by gwillcox-r7** [comment]
@Blakeboy02 In your original issue you said you were installing this via apt on Kali, now your stating that you are downloading it via the link above, and I was talking about the git clone method.

Assuming you are using `git`, the x64 etc doesn't matter as you are cloning the repo and running it via Ruby, so my comments above apply.

Assuming you are using `apt`, again, same comments apply as `apt` should identify things for you automatically.

Assuming you are using the links above, this is a different question as those are the Metasploit Pro links so this changes the nature of your question. In this case yes, the x64 installer would be needed for an x64 system, x86 for an x86 system, and then same applies to running a .exe on a Windows system only and .run for a Linux system only.

If you have a specific file link for what you were using for testing, say something like https://downloads.metasploit.com/data/releases/archive/metasploit-4.17.0-2020013101-linux-x64-installer.run, then this would be much more helpful in diagnosing your issues.

**Comment by gwillcox-r7** [comment]
@Blakeboy02  Also if you can confirm if you are using `git`, `apt`, or the `MSF Pro Installers` this will be helpful in determining your environment so the issue can be verified.

**Comment by Blakeboy02** [comment]
Apt.

**Comment by gwillcox-r7** [comment]
Ok do you have the command that you used to install Metasploit using `apt`?

**Comment by Blakeboy02** [comment]
Yes, can you specify which version to download of Metasploit because it automatically wants to download the -dev version.

**Comment by gwillcox-r7** [comment]
If your using `apt`, it should just download the latest version. Are you looking to download a specific release?

**Comment by Blakeboy02** [comment]
Yes because it keeps downloading the -dev release.

**Comment by gwillcox-r7** [comment]
After further review @Blakeboy02 seems like there is an edge case in the code at https://github.com/rapid7/metasploit-framework/blame/master/lib/postgres/postgres-pr/message.rb#L49 whereby `length` could wind up becoming `nil` and the code isn't appropriately checking for this case.

In most normal circumstances this error will not be encountered but in cases such as yours its possible that `length` may be set to `nil` and thus the code will error out.

Thanks for reporting this, I've passed on the info to our team :)
