### ISSUE TITLE
rpc_session.rb  Argument Error

### ISSUE THREAD

**Issue by troyam** [rapid7/metasploit-framework#13287]
## Steps to reproduce

1.  RPC - API
2. ARGS : 
`[ 'session.meterpreter_write', 'session.number', 'pkill', 'process' ];
`

ERROR: 
```
{
  error: true,
  error_class: 'ArgumentError',
  error_string: 'wrong number of arguments (given 3, expected 2)',
  error_backtrace: {
    '0': "lib/msf/core/rpc/v10/rpc_session.rb:263:in `rpc_meterpreter_write'",
    '1': "lib/msf/core/rpc/v10/service.rb:155:in `block in process'",
    '2': "lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'",
    '3': "lib/ruby/2.6.0/timeout.rb:33:in `block in catch'",
    '4': "lib/ruby/2.6.0/timeout.rb:33:in `catch'",
    '5': "lib/ruby/2.6.0/timeout.rb:33:in `catch'",
    '6': "lib/ruby/2.6.0/timeout.rb:108:in `timeout'",
    '7': "lib/msf/core/rpc/v10/service.rb:155:in `process'",
    '8': "lib/msf/core/rpc/v10/service.rb:93:in `on_request_uri'",
    '9': "lib/msf/core/rpc/v10/service.rb:74:in `block in start'",
    '10': "lib/rex/proto/http/handler/proc.rb:38:in `on_request'",
    '11': "lib/rex/proto/http/server.rb:368:in `dispatch_request'",
    '12': "lib/rex/proto/http/server.rb:302:in `on_client_data'",
    '13': "lib/rex/proto/http/server.rb:161:in `block in start'",
    '14': "lib/rex/io/stream_server.rb:48:in `on_client_data'",
    '15': "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'",
    '16': "lib/rex/io/stream_server.rb:197:in `each'",
    '17': "lib/rex/io/stream_server.rb:197:in `monitor_clients'",
    '18': "lib/rex/io/stream_server.rb:73:in `block in start'",
    '19': "lib/rex/thread_factory.rb:22:in `block in spawn'",
    '20': "lib/msf/core/thread_manager.rb:106:in `block in spawn'"
  },
  error_message: 'wrong number of arguments (given 3, expected 2)'
}
```

**Comment by troyam** [comment]
Sorry, Wrong way...
`{
    action: 'msf',
    execute: [ 'session.meterpreter_write', 'session.number', 'pkill', 'process' ],
    query: 'msf',
    args: 4
  }
`
The way:
`{
    action: 'msf',
    execute: [ 'session.meterpreter_write', 'session.number', 'pkill process' ],
    query: 'msf',
    args: 3
  }
`
