### ISSUE TITLE
Metasploit Console.bat not starting wtf help me

### ISSUE THREAD

**Issue by LOOF-sys** [rapid7/metasploit-framework#13302]
```
C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Traceback (most recent call last):
        61: from C:/metasploit/apps/pro/engine/msfpro:17:in `<main>'
        60: from C:/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:65:in `start'
        59: from C:/metasploit/apps/pro/engine/lib/metasploit/pro/engine/command/base.rb:49:in `require_environment!'
        58: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/application.rb:328:in `require_environment!'
        57: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
        56: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        55: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
        54: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        53: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        52: from C:/metasploit/apps/pro/engine/config/environment.rb:5:in `<top (required)>'
        51: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
        50: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
        49: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
        48: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'
        47: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        46: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        45: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        44: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:347:in `call'
        43: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:347:in `each'
        42: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        41: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        40: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:415:in `call'
        39: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:44:in `tsort_each_child'
        38: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:44:in `each'
        37: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        36: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        35: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        34: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        33: from C:/metasploit/ruby/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        32: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:55:in `block in run_initializers'
        31: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `run'
        30: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/initializable.rb:30:in `instance_exec'
        29: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
        28: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/engine.rb:615:in `each'
        27: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
        26: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/engine.rb:651:in `load_config_initializer'
        25: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:166:in `instrument'
        24: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/railties-4.2.11.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
        23: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
        22: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        21: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
        20: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
        19: from C:/metasploit/apps/pro/ui/config/initializers/delete_delayed_jobs.rb:2:in `<top (required)>'
        18: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/model_schema.rb:230:in `table_exists?'
        17: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:87:in `connection'
        16: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
        15: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
        14: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
        13: from C:/metasploit/ruby/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
        12: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
        11: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
        10: from C:/metasploit/ruby/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
         9: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
         8: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
         7: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
         6: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
         5: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
         4: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
         3: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
         2: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
         1: from C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
C:/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize': could not connect to server: Connection refused (0x0000274D/10061) (PG::ConnectionBad)
|      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      |      
```

Any fixes? Please anyone? Im trying to hack roblox

**Comment by adfoster-r7** [comment]
@LOOF-sys If you have Metasploit Pro, you should be able to get customer support directly from Rapid7. 

https://www.rapid7.com/for-customers/

This is the issue tracker for the Metasploit Framework open source project, not an appropriate place for Metasploit Pro support.

**Comment by adfoster-r7** [comment]
> could not connect to server: Connection refused (0x0000274D/10061) (PG::ConnectionBad)

From the attached error it seems like you may have database connectivity issues, but please see see https://www.rapid7.com/for-customers/ to start a support request.
