### ISSUE TITLE
 bundle install  error in metasploit installition 

### ISSUE THREAD

**Issue by Ahmed9204** [rapid7/metasploit-framework#13397]
when i run this command   `bundle install`

return this output : 

```
Traceback (most recent call last):
	10: from /usr/local/bin/bundle:23:in `<main>'
	 9: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:304:in `activate_bin_path'
	 8: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:304:in `synchronize'
	 7: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:306:in `block in activate_bin_path'
	 6: from /usr/local/lib/site_ruby/2.7.0/rubygems.rb:243:in `finish_resolve'
	 5: from /usr/local/lib/site_ruby/2.7.0/rubygems/request_set.rb:435:in `resolve_current'
	 4: from /usr/local/lib/site_ruby/2.7.0/rubygems/request_set.rb:435:in `new'
	 3: from /usr/local/lib/site_ruby/2.7.0/rubygems/resolver/set.rb:24:in `initialize'
	 2: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:42:in `require'
	 1: from /usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
/usr/local/lib/site_ruby/2.7.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize': deadlock; recursive locking (ThreadError)
```

**Comment by Prady2006** [comment]
I would suggest you to check for other ruby versions present in your system or you can create a virtual env using rbenv for installation . This way metasploit will compile successfully .

**Comment by bcoles** [comment]
Metasploit does not yet officially support Ruby 2.7.

You might have a `bundle2.5` or `bundle2.6` in your `$PATH`. Try those.
