### ISSUE TITLE
When I concurrently call RPC, the rpc return error

### ISSUE THREAD

**Issue by akkuman** [rapid7/metasploit-framework#13408]
## Steps to reproduce

How'd you do it?

1. start msfrpcd
2. concurrently rpc.call('module.platforms')

## Expected behavior

```
{
    "data": [
        "aix",
        "android",
        "apple_ios",
        "brocade",
        "bsd",
        "bsdi",
        "cisco",
        "firefox",
        "freebsd",
        "hardware",
        "hpux",
        "irix",
        "java",
        "javascript",
        "juniper",
        "linux",
        "mainframe",
        "multi",
        "netbsd",
        "netware",
        "nodejs",
        "openbsd",
        "osx",
        "php",
        "python",
        "r",
        "ruby",
        "solaris",
        "unifi",
        "unix",
        "unknown",
        "windows"
    ]
}
```

## Current behavior

```
{
    "data": {
        "error": true,
        "error_class": "ArgumentError",
        "error_string": "wrong number of arguments (given 2, expected 0)",
        "error_backtrace": [
            "lib/msf/core/rpc/v10/rpc_module.rb:586:in `rpc_platforms'",
            "lib/msf/core/rpc/v10/service.rb:155:in `block in process'",
            "lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'",
            "lib/ruby/2.6.0/timeout.rb:33:in `block in catch'",
            "lib/ruby/2.6.0/timeout.rb:33:in `catch'",
            "lib/ruby/2.6.0/timeout.rb:33:in `catch'",
            "lib/ruby/2.6.0/timeout.rb:108:in `timeout'",
            "lib/msf/core/rpc/v10/service.rb:155:in `process'",
            "lib/msf/core/rpc/v10/service.rb:93:in `on_request_uri'",
            "lib/msf/core/rpc/v10/service.rb:74:in `block in start'",
            "lib/rex/proto/http/handler/proc.rb:38:in `on_request'",
            "lib/rex/proto/http/server.rb:368:in `dispatch_request'",
            "lib/rex/proto/http/server.rb:302:in `on_client_data'",
            "lib/rex/proto/http/server.rb:161:in `block in start'",
            "lib/rex/io/stream_server.rb:48:in `on_client_data'",
            "lib/rex/io/stream_server.rb:199:in `block in monitor_clients'",
            "lib/rex/io/stream_server.rb:197:in `each'",
            "lib/rex/io/stream_server.rb:197:in `monitor_clients'",
            "lib/rex/io/stream_server.rb:73:in `block in start'",
            "lib/rex/thread_factory.rb:22:in `block in spawn'",
            "lib/msf/core/thread_manager.rb:106:in `block in spawn'"
        ],
        "error_message": "wrong number of arguments (given 2, expected 0)"
    }
}
```

### Metasploit version

```
"data": {
   "version": "5.0.87-dev-2dc26db9e1",
   "ruby": "2.6.6 x86_64-linux 2020-03-31",
   "api": "1.0"
}
```

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

```
OS: Manjaro 20.0 Lysia
Kernel: x86_64 Linux 5.4.35-1-MANJARO
Disk: 7.3G / 37G (21%)
CPU: Intel Core i7-8700 @ 4x 3.192GHz
GPU: VMware SVGA II Adapter
RAM: 1281MiB / 1961MiB
```

**Comment by akkuman** [comment]
sorry, this is https://github.com/DanMcInerney/pymetasploit3 bug
