### ISSUE TITLE
msf pro install problem

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#13528]
docker run -it -v Downloads/xxx:/xxx ubuntu:18.04 /bin/bash
<img width="363" alt="image" src="https://user-images.githubusercontent.com/18223385/83086493-77f68b80-a0c1-11ea-91d7-6d4010dafbfc.png">
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/18223385/83086768-3f0ae680-a0c2-11ea-9ea7-540822fc54c7.png">

```
root@4b77adf767b0:/opt/metasploit# ./createuser msf5 -P
Traceback (most recent call last):
	11: from /opt/metasploit/apps/pro/ui/script/createuser:57:in `<main>'
	10: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:291:in `save!'
	 9: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	 8: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:220:in `transaction'
	 7: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	 6: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	 5: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	 4: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	 3: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/transactions.rb:291:in `block in save!'
	 2: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
	 1: from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/validations.rb:43:in `save!'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.6.0/gems/activerecord-4.2.11.1/lib/active_record/validations.rb:79:in `raise_record_invalid': Validation failed: Password is too short (minimum is 8 characters), Password is too short (minimum is 8 characters), Password must contain letters, numbers, and at least one special character, Password must not be a predictable sequence of characters, Password confirmation is too short (minimum is 8 characters), Password confirmation is too short (minimum is 8 characters), Password confirmation must contain letters, numbers, and at least one special character, Password confirmation must not be a predictable sequence of characters (ActiveRecord::RecordInvalid)

```
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/18223385/83086833-66fa4a00-a0c2-11ea-9d61-917112baa983.png">

**Comment by acammack-r7** [comment]
Metasploit's `createuser` utility does not take any option flags. The preferred way to run it is with no options or flags: https://metasploit.help.rapid7.com/docs/installing-metasploit-pro#section-creating-a-user-account-on-headless-servers. `createuser admin -P` tells Metasploit to create the user with a password of `-P`, which does not meet the password requirements.
