### ISSUE TITLE
JSON::ParserError 783: unexpected token at '<h1>Internal Server Error</h1>'

### ISSUE THREAD

**Issue by sportshead** [rapid7/metasploit-framework#13542]
## Steps to reproduce

How'd you do it?

1. `use auxiliary/scanner/ssh/ssh_login`
2. `set rhosts <insert host here>`
3. `set stop_on_success true`
4. `set USERPASS_FILE /usr/share/metasploit-framework/data/wordlists/root_userpass.txt`
5. `run`

## Expected behavior

It works

## Current behavior

It breaks
```
[05/30/2020 16:36:31] [e(0)] core: Error running against host [redacted]: 783: unexpected token at '<h1>Internal Server Error</h1>'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:45:in `json_to_mdm_object'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/remote/http/remote_credential_data_service.rb:13:in `creds'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:54:in `block in creds'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/core.rb:166:in `data_service_operation'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:52:in `creds'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/data_service/proxy/login_data_proxy.rb:44:in `invalidate_login'
/opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/report.rb:63:in `invalidate_login'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/ssh/ssh_login.rb:149:in `block in run_host'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:234:in `block in scan!'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:177:in `block (2 levels) in each'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:170:in `each_line'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:170:in `block in each'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:169:in `open'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/credential_collection.rb:169:in `each'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
/opt/metasploit-framework/embedded/framework/modules/auxiliary/scanner/ssh/ssh_login.rb:121:in `run_host'
/opt/metasploit-framework/embedded/framework/lib/msf/core/auxiliary/scanner.rb:117:in `block (2 levels) in run'
/opt/metasploit-framework/embedded/framework/lib/msf/core/thread_manager.rb:106:in `block in spawn'
```

### Metasploit version

```
Framework: 5.0.92-dev-334d65a565c1c2ca68d994d7ff675cbb68782400
Console  : 5.0.92-dev-334d65a565c1c2ca68d994d7ff675cbb68782400
```

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly) https://osx.metasploit.com/metasploitframework-latest.pkg
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

What OS are you running Metasploit on?

macOS Catalina 1.15.1

**Comment by bcoles** [comment]
Possible dupe of #12654 or #11469

**Comment by sportshead** [comment]
Yeah I looked at those issues, didn't help

**Comment by sportshead** [comment]
wrong button
