### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by falassion86** [rapid7/metasploit-framework#13742]
Hi, I'm starting to learn how to use metasploit. I have a problem with the database.

```
msf5 > service postgresql status
[*] exec: service postgresql status

● postgresql.service - PostgreSQL RDBMS
     Loaded: loaded (/lib/systemd/system/postgresql.service; enabled; vendor preset: disabled)
     Active: active (exited) since Sat 2020-06-20 04:27:27 EDT; 2min 23s ago
    Process: 57734 ExecStart=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 57734 (code=exited, status=0/SUCCESS)

Jun 20 04:27:27 kali systemd[1]: Starting PostgreSQL RDBMS...
Jun 20 04:27:27 kali systemd[1]: Finished PostgreSQL RDBMS.

msf5 > db_status
[*] postgresql selected, no connection
```

I think the problem can be here:

```
msf5 > msfdb init
[*] exec: msfdb init

[+] Starting database
psql: error: could not connect to server: connessione al server fallita: File o directory non esistente
        Verifica che il server locale sia in funzione e che
        accetti connessioni sul socket di dominio Unix "/var/run/postgresql/.s.PGSQL.5432"
[+] Creating database user 'msf'
createuser: error: could not connect to database postgres: connessione al server fallita: File o directory non esistente
        Verifica che il server locale sia in funzione e che
        accetti connessioni sul socket di dominio Unix "/var/run/postgresql/.s.PGSQL.5432"
psql: error: could not connect to server: connessione al server fallita: File o directory non esistente
        Verifica che il server locale sia in funzione e che
        accetti connessioni sul socket di dominio Unix "/var/run/postgresql/.s.PGSQL.5432"
[+] Creating databases 'msf'
createdb: error: could not connect to database template1: connessione al server fallita: File o directory non esistente
        Verifica che il server locale sia in funzione e che
        accetti connessioni sul socket di dominio Unix "/var/run/postgresql/.s.PGSQL.5432"
psql: error: could not connect to server: connessione al server fallita: File o directory non esistente
        Verifica che il server locale sia in funzione e che
        accetti connessioni sul socket di dominio Unix "/var/run/postgresql/.s.PGSQL.5432"
[+] Creating databases 'msf_test'
createdb: error: could not connect to database template1: connessione al server fallita: File o directory non esistente
        Verifica che il server locale sia in funzione e che
        accetti connessioni sul socket di dominio Unix "/var/run/postgresql/.s.PGSQL.5432"
[+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
[+] Creating initial database schema
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/connection_handling.rb:87:in `connection'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:941:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Can someone help me to resolve it? I searched for a long on google :(

**Comment by jmartin-r7** [comment]
The `Kali` team maintains their own [fork](https://gitlab.com/kalilinux/packages/metasploit-framework/) in part specifically due to managing and interacting with the database differently than how the core framework project does. You may find that Kali support forums as a better resource for getting the database layer working on that specific OS.

One initial item looking at your output here is that `msfdb init` is intended to configure the db before starting `msfconsole`, this may or may not be related to your issue.

**Comment by JonathanBergendahl** [comment]
Had the same error, just installed a new update and ran msfdb init before launching msf and it worked.
