### ISSUE TITLE
Access Denied when decrypting data from enum_chrome on Windows 10

### ISSUE THREAD

**Issue by cbrnrd** [rapid7/metasploit-framework#13902]
## Steps to reproduce

How'd you do it?

1. Get a session and elevate it to `SYSTEM` (Target: Windows 10 18362.959, Chrome 84.0.4147.89)
2. `use post/windows/gather/enum_chrome`
3. `set SESSION #` 
4. `run`
5. Here is the output I get, the module seems to be successfully downloading the encrypted data, but fails when decrypting:
```
[*] Impersonating token: 8416
[*] Running as user 'DESKTOP-J5V2TDV\Carter'...
[*] Extracting data for user 'Carter'...
[+] Downloaded Web Data to '/home/carter/.msf4/loot/20200724171441_default_10.0.0.63_chrome.raw.WebD_375228.txt'
[+] Downloaded Cookies to '/home/carter/.msf4/loot/20200724171442_default_10.0.0.63_chrome.raw.Cooki_297747.txt'
[+] Downloaded History to '/home/carter/.msf4/loot/20200724171444_default_10.0.0.63_chrome.raw.Histo_379302.txt'
[+] Downloaded Login Data to '/home/carter/.msf4/loot/20200724171502_default_10.0.0.63_chrome.raw.Login_786115.txt'
[+] Downloaded Bookmarks to '/home/carter/.msf4/loot/20200724171503_default_10.0.0.63_chrome.raw.Bookm_741739.txt'
[+] Downloaded Preferences to '/home/carter/.msf4/loot/20200724171503_default_10.0.0.63_chrome.raw.Prefe_697568.txt'
[-] Post failed: Rex::Post::Meterpreter::RequestError stdapi_sys_process_attach: Operation failed: Access is denied.
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:97:in `_open'
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:78:in `open'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:102:in `decrypt_data'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:159:in `block (3 levels) in process_files'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:156:in `each'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:156:in `block (2 levels) in process_files'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:152:in `map!'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:152:in `block in process_files'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:136:in `each'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:136:in `process_files'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:327:in `block in run'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:324:in `each'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/enum_chrome.rb:324:in `run'
[*] Post module execution completed
```

## Expected behavior

The module successfully decrypts the gathered chrome data.

## Current behavior

It fails on the decryption step

### Metasploit version

`5.0.101-dev-`

### I installed Metasploit with:
- [ ] Kali package via apt
- [x] Omnibus installer (nightly) (installed today 7/24)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

WSL

**Comment by timwr** [comment]
It wouldn't surprise me if Chrome has updated or changed the encryption since this module was written. I'm sure there is some code on github that can handle the latest version though?
Alternatively there is a `modules/post/multi/gather/chrome_cookies` module that might be useful.

**Comment by cbrnrd** [comment]
I'll look into it and see if I can make it work and I'll post info/updates here

**Comment by cbrnrd** [comment]
Both [SharpWeb](https://github.com/djhohnstein/SharpWeb) and [Lazagne](https://github.com/AlessandroZ/LaZagne) still work on recent versions of chrome, so I don't think theyve changed the encryption from what it was when this module was written (using some windows user-based encryption iirc)
