### ISSUE TITLE
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager

### ISSUE THREAD

**Issue by z3dc0ps** [rapid7/metasploit-framework#14184]
```
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
	23: from /usr/bin/msfconsole:21:in `<main>'
	22: from /usr/bin/msfconsole:21:in `require'
	21: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	20: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	19: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	18: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	17: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
	16: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `require'
	15: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
	14: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
	13: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
	12: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
	11: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
	10: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:22:in `require'
	 9: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-credential-3.0.4/lib/metasploit/credential.rb:11:in `<top (required)>'
	 8: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-credential-3.0.4/lib/metasploit/credential.rb:11:in `require'
	 7: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:15:in `<top (required)>'
	 6: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:15:in `require'
	 5: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record.rb:27:in `<top (required)>'
	 4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activerecord-4.2.11.3/lib/active_record.rb:27:in `require'
	 3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-6.0.4/lib/arel.rb:14:in `<top (required)>'
	 2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-6.0.4/lib/arel.rb:14:in `require'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-6.0.4/lib/arel/visitors.rb:6:in `<top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/arel-6.0.4/lib/arel/visitors.rb:6:in `require': cannot load such file -- arel/visitors/mysql (LoadError)
	13: from /usr/bin/msfconsole:21:in `<main>'
	12: from /usr/bin/msfconsole:21:in `require'
	11: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
	10: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
	 9: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
	 8: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
	 7: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
	 6: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `require'
	 5: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
	 4: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
	 3: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
	 2: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
	 1: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:20:in `optionally'
/usr/share/metasploit-framework/lib/metasploit/framework/require.rb:25:in `rescue in optionally': undefined method `without' for #<Bundler::Settings:0x000055be914c38d0> (NoMethodError)
```

![1](https://user-images.githubusercontent.com/61974788/94286188-46f46d80-ff72-11ea-82ad-885dcb5c1835.JPG)

**Comment by z3dc0ps** [comment]
i tried with this method and problem solved :

 https://www.linkedin.com/pulse/getting-armitage-running-kali-latest-free-metasploit-framework-davis?articleId=6651195604640808961
