### ISSUE TITLE
require: cannot load such file -- sqlite3/2.7/sqlite3_native

### ISSUE THREAD

**Issue by Smith127** [rapid7/metasploit-framework#14603]
## Steps to reproduce

sudo msfconsole

## Expected behavior
msfconsole

What should happen?
msfconsole should start.
## Current behavior
```
sudo msfconsole
Traceback (most recent call last):
	13: from /usr/bin/msfconsole:23:in `<main>'
	12: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	11: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:55:in `require_environment!'
	10: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:55:in `require'
	 9: from /usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
	 8: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	 7: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	 6: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	 5: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
	 4: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
	 3: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	 2: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `<top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.7/sqlite3_native (LoadError)
	14: from /usr/bin/msfconsole:23:in `<main>'
	13: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	12: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:55:in `require_environment!'
	11: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:55:in `require'
	10: from /usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
	 9: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	 8: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	 7: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	 6: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
	 5: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
	 4: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	 3: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
	 2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:2:in `<top (required)>'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:6:in `rescue in <top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:6:in `require': /u
```

version (6.0.16-0parrot1)

**Comment by gwillcox-r7** [comment]
Looks like you have a missing file: 

```
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.7/sqlite3_native
```

Looking online, I can see there are some similar problems that have been reported before. Here are the recommended steps:

First try this:

```
bundle update sqlite3
```

If this doesn't work then try this:

```
gem uninstall sqlite3 --all
gem install sqlite3 --platform=ruby
```

**Comment by Smith127** [comment]
> Looks like you have a missing file:
> 
> ```
> /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.3.13/lib/sqlite3.rb:4:in `require': cannot load such file -- sqlite3/2.7/sqlite3_native
> ```
> 
> Looking online, I can see there are some similar problems that have been reported before. Here are the recommended steps:
> 
> First try this:
> 
> ```
> bundle update sqlite3
> ```
> 
> If this doesn't work then try this:
> 
> ```
> gem uninstall sqlite3 --all
> gem install sqlite3 --platform=ruby
> ```

Tested as root in directory /usr/share/metasploit-framework/


bundle update sqlite3
```
Unable to find a spec satisfying sqlite3 (~> 1.3.0) in the set. Perhaps the lockfile is corrupted?
```
gem uninstall sqlite3 --all
```
Successfully uninstalled sqlite3-1.4.2
```
gem install sqlite3 --platform=ruby
```
Fetching sqlite3-1.4.2.gem
Building native extensions. This could take a while...
Successfully installed sqlite3-1.4.2
Parsing documentation for sqlite3-1.4.2
Installing ri documentation for sqlite3-1.4.2
Done installing documentation for sqlite3 after 0 seconds
1 gem installed
```
bundle -v
ruby -v
gem -v
```
Bundler version 2.2.5
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
3.2.5
```

**Comment by gwillcox-r7** [comment]
Hmm odd which OS are you using to run this? The logs under `Current behavior` suggest you are running Ruby 2.7.0 with Bundler version `2.1.4` so its possible something has messed up on your operating system and its using the wrong version of Ruby?
