### ISSUE TITLE
Traceback (most recent call last) error after upgrading from msf5 to msf6 

### ISSUE THREAD

**Issue by Kurrupt68** [rapid7/metasploit-framework#14752]
## Steps to reproduce
sudo msfconsole

## Expected behavior
msfconsole should startup
###### **Traceback** (most recent call last):
        13: from /usr/bin/msfconsole:18:in `<main>'
        12: from /usr/bin/msfconsole:18:in `require'
        11: from /usr/share/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        10: from /usr/share/metasploit-framework/lib/msfenv.rb:17:in `require'
         9: from /usr/share/metasploit-framework/config/environment.rb:2:in `<top (required)>'
         8: from /usr/share/metasploit-framework/config/environment.rb:2:in `require'
         7: from /usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
         6: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler.rb:173:in `require'
         5: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:50:in `require'
         4: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:50:in `each'
         3: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:61:in `block in require'
         2: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:61:in `each'
         1: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:66:in `block (2 levels) in     require'
        /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:66:in `require': cannot load such file --   metasploit-framework (LoadError)
        16: from /usr/bin/msfconsole:18:in `<main>'
        15: from /usr/bin/msfconsole:18:in `require'
        14: from /usr/share/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        13: from /usr/share/metasploit-framework/lib/msfenv.rb:17:in `require'
        12: from /usr/share/metasploit-framework/config/environment.rb:2:in `<top (required)>'
        11: from /usr/share/metasploit-framework/config/environment.rb:2:in `require'
        10: from /usr/share/metasploit-framework/config/application.rb:10:in `<top (required)>'
         9: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler.rb:173:in `require'
         8: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:50:in `require'
         7: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:50:in `each'
         6: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:57:in `block in require'
      5: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:79:in `rescue in block in  require'
         4: from /root/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.5/lib/bundler/runtime.rb:79:in `require'
         3: from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
         2: from /usr/share/metasploit-framework/lib/metasploit/framework.rb:9:in `require'
         1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/bcrypt-3.1.16/lib/bcrypt.rb:12:in `<top (required)>'
          /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/bcrypt-3.1.16/lib/bcrypt.rb:12:in `require': incompatible    library version - /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/bcrypt-3.1.16/lib/bcrypt_ext.so (LoadError)

## Additional Information
OS
bundle -v
ruby -v
gem -v
######Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
            Bundler version 2.2.5
            ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
             3.1.4

**Comment by Kurrupt68** [comment]
Couldn't fix the issue to do a full dist upgrade, fixed the issue
