### ISSUE TITLE
 Failed to connect to the database: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by MohabMosdak** [rapid7/metasploit-framework#14859]
##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/core]
loglevel=3
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
165    set loglevel 3
166    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/07/2021 12:25:07] [e(0)] core: RuntimeError : Unable to rebuild apk with apktool
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:282:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:467:in `<main>'
[03/07/2021 12:27:03] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[03/07/2021 12:27:03] [e(0)] core: Failed to connect to the database: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[03/07/2021 12:27:33] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:27:33] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:27:34] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/07/2021 12:27:34] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/07/2021 12:27:41] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/07/2021 12:27:41] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/07/2021 12:27:41] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/07/2021 11:58:23] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/07/2021 11:58:23] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/07/2021 11:59:10] [e(0)] core: RuntimeError : Unable to rebuild apk with apktool
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:282:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:467:in `<main>'
[03/07/2021 12:07:17] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:07:17] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:07:18] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/07/2021 12:07:18] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/07/2021 12:08:35] [e(0)] core: RuntimeError : Unable to rebuild apk with apktool
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:282:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:467:in `<main>'
[03/07/2021 12:23:43] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:23:43] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:23:44] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/07/2021 12:23:44] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/07/2021 12:25:07] [e(0)] core: RuntimeError : Unable to rebuild apk with apktool
/usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:282:in `backdoor_apk'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:412:in `generate_payload'
/usr/bin/msfvenom:467:in `<main>'
[03/07/2021 12:27:03] [i(0)] core: Trying to continue despite failed database creation: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[03/07/2021 12:27:03] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[03/07/2021 12:27:03] [e(0)] core: Failed to connect to the database: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

[03/07/2021 12:27:33] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:27:33] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/07/2021 12:27:34] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/07/2021 12:27:34] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/07/2021 12:27:41] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/07/2021 12:27:41] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[03/07/2021 12:27:41] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.31-dev
Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Other - Please specify
```

</details>

**Comment by bcoles** [comment]
This might help:

https://github.com/rapid7/metasploit-framework/issues/12538#issuecomment-608405628

**Comment by adfoster-r7** [comment]
Closing as it looks like there's a known workaround posted above, please reach out again if you're still having difficulties :+1:
