### ISSUE TITLE
Creds command throws stack traces when trying to add credentials without providing appropriate information

### ISSUE THREAD

**Issue by gwillcox-r7** [rapid7/metasploit-framework#14884]
## Steps to reproduce

```
msf6 auxiliary(scanner/http/wordpress_login_enum) > creds add wordpress:fake
[-] Unknown key: "wordpress". Valid keys are: "user", "password", "realm", "realm-type", "ntlm", "ssh-key", "hash", "address", "port", "protocol", "service-name", "jtr", "postgres"
[-] Error while running command creds: There was an error creating the record: Validation failed: can't have private and public blank - at least one must be present.

Call stack:
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/remote/http/response_data_helper.rb:60:in `json_to_mdm_object'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/remote/http/remote_credential_data_service.rb:34:in `create_credential'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:6:in `block in create_credential'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:164:in `data_service_operation'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb:5:in `create_credential'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:320:in `creds_add'
/home/gwillcox/git/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:107:in `cmd_creds'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:542:in `run_command'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:491:in `block in run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:485:in `each'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:485:in `run_single'
/home/gwillcox/git/metasploit-framework/lib/rex/ui/text/shell.rb:157:in `run'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/home/gwillcox/git/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
```

## Were you following a specific guide/tutorial or reading documentation?

Was testing https://github.com/rapid7/metasploit-framework/pull/14882

## Expected behavior

Error messages appear, but no stack trace occurs.

## Current behavior

Get a confusing stack trace in addition to the actual error that helps us out.

### Metasploit version

6.0.34-dev-37eaf7944b

**Comment by adfoster-r7** [comment]
This stack trace only appears if you're connected to the remote dataservice.

The current also code only catches `ActiveRecord::RecordInvalid` being raised when adding credentials:

https://github.com/rapid7/metasploit-framework/blob/d744f65dbc33d7284452d2f9f9a85e24bc1300cf/lib/msf/ui/console/command_dispatcher/creds.rb#L283-L294

Whilst it seems like the remote data service doesn't propagate any particular error classes, just runtime exceptions:
```
    58:     elsif response_wrapper.is_a?(Metasploit::Framework::DataService::RemoteHTTPDataService::ErrorResponse)
    59:       # raise a local exception with the message of the server-side error
    60:       require 'pry'; binding.pry
 => 61:       raise parsed_body[:error][:message]
    62:     end
[1] pry(#<Metasploit::Framework::DataService::RemoteHTTPDataService>)> parsed_body[:error]
=> {:code=>500,
 :message=>
  "There was an error creating the record: Validation failed: can't have private and public blank - at least one must be present."}
```

I haven't poked further into whether the http service could return the correct error class, but it seems like it might be a can of worms. We could fix this particular stack trace, but there's probably similar issues in lots of places. Easiest fix might be to catch with a wider net, call `elog(e)` and stop the stack trace from being output

**Comment by adfoster-r7** [comment]
The remote DB isn't enabled by default, and it looks like no one else has ran into this - closing for now.
