### ISSUE TITLE
Running Netgear r6700 Pass Reset Returns NoMethodError undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by LotsOfBlochs** [rapid7/metasploit-framework#14909]
## Steps to reproduce

How'd you do it?

1. use auxiliary/admin/http/netgear_r6700_pass_reset
2. set RHOSTS ###.###.###.###
3. run

The victim was a Netgear r6700v3

## Were you following a specific guide/tutorial or reading documentation?

https://www.rapid7.com/db/modules/auxiliary/admin/http/netgear_r6700_pass_reset/

## Expected behavior

I expect it to run and reset the password as stated in the documentation.

## Current behavior

It returns an error 

### Metasploit version

Framework: 6.0.35-dev-50ef32c12144bdd03688f3db753e6464fb7c71f7
Console  : 6.0.35-dev-50ef32c12144bdd03688f3db753e6464fb7c71f7

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[admin/http/netgear_r6700_pass_reset]
WORKSPACE=
VERBOSE=false
RHOSTS=###.###.###.###
RPORT=5000
VHOST=
SSL=false
Proxies=
UserAgent=Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)
HttpUsername=
HttpPassword=
HttpRawHeaders=
DigestAuthIIS=true
SSLVersion=Auto
FingerprintCheck=true
DOMAIN=WORKSTATION
HttpClientTimeout=
HttpTrace=false
HttpTraceHeadersOnly=false
HttpTraceColors=red/blu
HTTP::uri_encode_mode=hex-normal
HTTP::uri_full_url=false
HTTP::pad_method_uri_count=1
HTTP::pad_uri_version_count=1
HTTP::pad_method_uri_type=space
HTTP::pad_uri_version_type=space
HTTP::method_random_valid=false
HTTP::method_random_invalid=false
HTTP::method_random_case=false
HTTP::version_random_valid=false
HTTP::version_random_invalid=false
HTTP::uri_dir_self_reference=false
HTTP::uri_dir_fake_relative=false
HTTP::uri_use_backslashes=false
HTTP::pad_fake_headers=false
HTTP::pad_fake_headers_count=0
HTTP::pad_get_params=false
HTTP::pad_get_params_count=16
HTTP::pad_post_params=false
HTTP::pad_post_params_count=16
HTTP::uri_fake_end=false
HTTP::uri_fake_params_start=false
HTTP::header_folding=false

[framework/core]
log=level 3

[framework/ui/console]
ActiveModule=auxiliary/admin/http/netgear_r6700_pass_reset
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
89     set log level 3
90     use auxiliary/admin/http/netgear_r6700_pass_reset
91     set RHOSTS ###.###.###.###
92     run
93     debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/16/2021 12:46:34] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 12:46:34] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 12:47:12] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
[03/16/2021 12:50:25] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[03/16/2021 12:50:25] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 12:52:01] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
No matching patterns were found in msf-ws.log.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/16/2021 10:58:42] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 10:58:54] [d(0)] core: Module generic/custom is incompatible with linux/telnet/netgear_telnetenable for PayloadType: limiter was cmd_interact
[03/16/2021 10:58:54] [d(0)] core: Module generic/shell_bind_tcp is incompatible with linux/telnet/netgear_telnetenable for PayloadType: limiter was cmd_interact
[03/16/2021 10:58:54] [d(0)] core: Module generic/shell_reverse_tcp is incompatible with linux/telnet/netgear_telnetenable for PayloadType: limiter was cmd_interact
[03/16/2021 10:59:36] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 10:59:36] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 10:59:36] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 10:59:36] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 11:03:09] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
[03/16/2021 11:16:29] [e(0)] core: Failed to connect to the database: No database YAML file
[03/16/2021 11:16:35] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 11:16:35] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 11:16:35] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 11:16:35] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 11:16:49] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
[03/16/2021 11:20:30] [e(0)] core: Failed to connect to the database: No database YAML file
[03/16/2021 11:20:36] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 11:20:36] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 11:20:36] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 11:20:36] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 11:44:29] [e(0)] core: Failed to connect to the database: No database YAML file
[03/16/2021 11:44:35] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 11:44:35] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 11:44:35] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 11:44:36] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 11:45:25] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
[03/16/2021 11:48:09] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
[03/16/2021 12:46:27] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[03/16/2021 12:46:27] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[03/16/2021 12:46:27] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[03/16/2021 12:46:27] [d(0)] core: Updated user based module store
[03/16/2021 12:46:34] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 12:46:34] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 12:46:34] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 12:46:34] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 12:47:12] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
[03/16/2021 12:50:25] [i(0)] core: Trying to continue despite failed database creation: FATAL:  password authentication failed for user "msf"

[03/16/2021 12:50:25] [e(0)] core: DB.connect threw an exception - PG::ConnectionBad FATAL:  password authentication failed for user "msf"

[03/16/2021 12:50:25] [e(0)] core: Failed to connect to the database: FATAL:  password authentication failed for user "msf"

[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[03/16/2021 12:50:31] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[03/16/2021 12:52:01] [e(0)] core: Auxiliary failed - NoMethodError undefined method `gsub' for nil:NilClass
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
2021-03-16 12:46:09 -0700 Writing PID to /home/LotsOfBlochs/.msf4/msf-ws.pid
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/actionpack-5.2.4.5/lib/action_dispatch/middleware/static.rb:111: warning: The called method `initialize' is defined here
2021-03-16 12:46:15 -0700 Thin web server (v1.8.0 codename Possessed Pickle)
2021-03-16 12:46:15 -0700 Maximum connections set to 1024
2021-03-16 12:46:15 -0700 Listening on localhost:5443, CTRL+C to stop
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
2021-03-16 12:46:20 - PG::ConnectionBad - FATAL:  password authentication failed for user "msf"
:
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `new'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:413:in `with_connection'
        /opt/metasploit-framework/embedded/framework/lib/msf/core/db_manager/user.rb:10:in `users'
        /opt/metasploit-framework/embedded/framework/lib/msf/core/web_services/metasploit_api_app.rb:44:in `block in <class:MetasploitApiApp>'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1000:in `block in filter!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `each'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:999:in `filter!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1126:in `block in dispatch!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:86:in `block in pre_process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `catch'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:84:in `pre_process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:53:in `process'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/connection.rb:39:in `receive_data'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/backends/base.rb:75:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/server.rb:162:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/controllers/controller.rb:87:in `start'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/runner.rb:203:in `run_command'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/lib/thin/runner.rb:159:in `run!'
        /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/thin-1.8.0/bin/thin:6:in `<top (required)>'
        /opt/metasploit-framework/embedded/bin/thin:23:in `load'
        /opt/metasploit-framework/embedded/bin/thin:23:in `<main>'
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.0.35-dev-50ef32c12144bdd03688f3db753e6464fb7c71f7
Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [aarch64-linux]
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: postgresql selected, no connection
Install Method: Omnibus Installer
```

</details>

**Comment by bcoles** [comment]
The module is performing a `nil` check on an empty array `[]` (which will never be `nil`) then trying to access the zeroeth element of the empty array, which can be `nil`, causing the `NoMethodError`.

This should fix it.

```diff
diff --git a/modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb b/modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
index e1ab5f8734..1d06653eb7 100644
--- a/modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
+++ b/modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
@@ -94,13 +94,11 @@ class MetasploitModule < Msf::Auxiliary
       fail_with(Failure::UnexpectedReply, 'Failed to obtain device version: Unexpected response code')
     end
 
-    version = res.body.to_s
-    version = version.scan(/V\d\.\d\.\d\.\d{1,2}/) # Try find a version number in the format V1.2.3.48 or similar.
+    version = res.body.to_s.scan(/V(\d\.\d\.\d\.\d{1,2})/).flatten.first # Try find a version number in the format V1.2.3.48 or similar.
     if version.nil? # Check we actually got a result.
       fail_with(Failure::UnexpectedReply, 'Failed to obtain device version: no version number found in response') # Taken from https://stackoverflow.com/questions/4115115/extract-a-substring-from-a-string-in-ruby-using-a-regular-expression
     end
-    raw_version_number = version[0].gsub('V', '') # If we got a result, then take the first result from the returned array, and remove the leading 'V'.
-    Rex::Version.new(raw_version_number) # Finally lets turn it into a Rex::Version object for later use in other parts of the code.
+    Rex::Version.new(version) # Finally lets turn it into a Rex::Version object for later use in other parts of the code.
   end
 
   def check
```

**Comment by bcoles** [comment]
@LotsOfBlochs did the patch above work for you?
