### ISSUE TITLE
Whats the Zeitwerk debug process for modified frameworks?

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#15029]
## Summary
I rather thoroughly broke something related to loading, seemingly forcing ruby_smb to load twice redefining the read request structure. Whats the procedure for deconflicting this sort of issue?
## Relevant information
My wonderful stacktrace:
```
$ msfconsole 
Using ruby-2.7.2 with gemset metasploit-framework
Traceback (most recent call last):
	78: from /opt/metasploit4/msf4/msfconsole:23:in `<main>'
	77: from /opt/metasploit4/msf4/lib/metasploit/framework/command/base.rb:82:in `start'
	76: from /opt/metasploit4/msf4/lib/metasploit/framework/command/console.rb:50:in `start'
	75: from /opt/metasploit4/msf4/lib/metasploit/framework/command/console.rb:62:in `driver'
	74: from /opt/metasploit4/msf4/lib/metasploit/framework/command/console.rb:62:in `new'
	73: from /opt/metasploit4/msf4/lib/msf/ui/console/driver.rb:157:in `initialize'
	72: from /opt/metasploit4/msf4/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
	71: from /opt/metasploit4/msf4/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
	70: from /opt/metasploit4/msf4/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
	69: from /opt/metasploit4/msf4/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	68: from /opt/metasploit4/msf4/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	67: from /opt/metasploit4/msf4/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	66: from /opt/metasploit4/msf4/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
	65: from /opt/metasploit4/msf4/lib/msf/core/module_manager/loading.rb:168:in `each'
	64: from /opt/metasploit4/msf4/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
	63: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/base.rb:244:in `load_modules'
	62: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/directory.rb:33:in `each_module_reference_name'
	61: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/directory.rb:33:in `foreach'
	60: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/directory.rb:43:in `block in each_module_reference_name'
	59: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/bundler/gems/rex-core-d309de482fd0/lib/rex/file.rb:132:in `find'
	58: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/bundler/gems/rex-core-d309de482fd0/lib/rex/file.rb:132:in `catch'
	57: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/bundler/gems/rex-core-d309de482fd0/lib/rex/file.rb:133:in `block in find'
	56: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/directory.rb:52:in `block (2 levels) in each_module_reference_name'
	55: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/base.rb:245:in `block in load_modules'
	54: from /opt/metasploit4/msf4/lib/msf/core/modules/loader/base.rb:190:in `load_module'
	53: from /opt/metasploit4/msf4/lib/msf/core/module_manager/loading.rb:108:in `on_module_load'
	52: from /opt/metasploit4/msf4/lib/msf/core/payload_set.rb:208:in `add_module'
	51: from /opt/metasploit4/msf4/lib/msf/core/payload_set.rb:208:in `new'
	50: from /opt/metasploit4/msf4/modules/payloads/stagers/windows/bind_named_pipe.rb:21:in `initialize'
	49: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	48: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	47: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	46: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	45: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	44: from /opt/metasploit4/msf4/lib/msf/core/handler/bind_named_pipe.rb:23:in `<top (required)>'
	43: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	42: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	41: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	40: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	39: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	38: from /opt/metasploit4/msf4/lib/rex/proto/smb/simple_client.rb:2:in `<top (required)>'
	37: from /opt/metasploit4/msf4/lib/rex/proto/smb/simple_client.rb:3:in `<module:Rex>'
	36: from /opt/metasploit4/msf4/lib/rex/proto/smb/simple_client.rb:4:in `<module:Proto>'
	35: from /opt/metasploit4/msf4/lib/rex/proto/smb/simple_client.rb:6:in `<module:SMB>'
	34: from /opt/metasploit4/msf4/lib/rex/proto/smb/simple_client.rb:10:in `<class:SimpleClient>'
	33: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	32: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	31: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	30: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	29: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	28: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb.rb:13:in `<top (required)>'
	27: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb.rb:25:in `<module:RubySMB>'
	26: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	25: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	24: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	23: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	22: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	21: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2.rb:1:in `<top (required)>'
	20: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2.rb:5:in `<module:RubySMB>'
	19: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2.rb:14:in `<module:SMB2>'
	18: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	17: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	16: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	15: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	14: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	13: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet.rb:1:in `<top (required)>'
	12: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet.rb:2:in `<module:RubySMB>'
	11: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet.rb:5:in `<module:SMB2>'
	10: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet.rb:23:in `<module:Packet>'
	 9: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
	 8: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency'
	 7: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
	 6: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 5: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 4: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet/read_request.rb:1:in `<top (required)>'
	 3: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet/read_request.rb:2:in `<module:RubySMB>'
	 2: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet/read_request.rb:3:in `<module:SMB2>'
	 1: from /home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet/read_request.rb:6:in `<module:Packet>'
/home/username/.rvm/gems/ruby-2.7.2@metasploit-framework/gems/ruby_smb-2.0.8/lib/ruby_smb/smb2/packet/read_request.rb:11:in `<class:ReadRequest>': duplicate field 'smb2_header' in RubySMB::SMB2::Packet::ReadRequest (SyntaxError)
```

**Comment by adfoster-r7** [comment]
Nothing immediately springs to mind on why this would be happening, how custom are the differences? Is there a fork/branch to check out to replicate the error? 👀

**Comment by adfoster-r7** [comment]
Is there a custom module that's using `load` instead of `require` maybe?

**Comment by sempervictus** [comment]
I shall check for load vs require, thank you.
The fork is not something you want to see without a team of therapists present, it goes back >10y with things like DriveSploit and a bunch of never-public hackage-cache-bits in it (without an audit, and some redaction, can't be released)....
```
$ git diff rapid7/master|wc -l
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 2510 and retry the command.
695032
```
I might have some cleanup to do from this zeitwerk thing. My own fault for not keeping up with development pace.

**Comment by adfoster-r7** [comment]
Could always put a `require 'pry'; binding.pry` just before the crash and use the `up` command within the irb prompt to explore the current/previous stack frames that led up to the crash - that might give you a hint as to what's going wrong 🕵️

**Comment by sempervictus** [comment]
Yeah, or wrap the load line with a rescue block that dumps to pry. Shall try to allocate an hour and a bucket of sanity later this week :)
