### ISSUE TITLE
zeitwerk/kernel.rb:34:in `require': cannot load such file -- rex/ui (LoadError)

### ISSUE THREAD

**Issue by VikasUpadhyay0** [rapid7/metasploit-framework#15245]
every time i run msfconsole after upgrading my kali i received this error.
```
msfconsole 
Traceback (most recent call last):ork console.../
	14: from /usr/bin/msfconsole:23:in `<main>'
	13: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	12: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	11: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
	10: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
	 9: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	 8: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
	 7: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	 6: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	 5: from /usr/share/metasploit-framework/lib/msf/ui.rb:7:in `<top (required)>'
	 4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
	 3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
	 2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require': cannot load such file -- rex/ui (LoadError)
```

**Comment by dwelch-r7** [comment]
Hi @VikasUpadhyay0 I think this might be caused by an issue with how metasploit is updated, could you try reinstalling metasploit and letting us know if that solves the problem for you?
something like this should work
`sudo apt install --reinstall metasploit-framework`

**Comment by VikasUpadhyay0** [comment]
not worked same error.

**Comment by gwillcox-r7** [comment]
@VikasUpadhyay0 Can you confirm which version of Metasploit you are using and how you have installed it? I am unable to replicate this issue on my side using the latest code from GitHub.

**Comment by VikasUpadhyay0** [comment]
i am using Framework Version: 6.0.50-dev this version and coming same error.
