### ISSUE TITLE
How to get persistence on Android 11?

### ISSUE THREAD

**Issue by chusmagain** [rapid7/metasploit-framework#15529]
Hi, I have an android/meterpreter/reverse_tcp paylaod on Android 11, when i try to get persistence i execute this script
`!/bin/bash
while :
do am start --user 0 -a android.intent.action.MAIN -n com.metasploit.stage/.MainActivity
sleep 20
done`
but I receive this error
`Starting: Intent { act=android.intent.action.MAIN cmp=com.metasploit.stage/.MainActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: package=com.android.shell does not belong to uid=10463
        at com.android.server.wm.ActivityTaskManagerService.assertPackageMatchesCallingUid(ActivityTaskManagerService.java:2741)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1126)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1117)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3751)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:554)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:186)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10879)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5258)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2951)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)

`
I read that this happens because `am start` its broken so i tried to replace it for `am start-foreground-service` but i get this error 'Error: Can't start from invalid source: 10463' .

Someone know how to create the backdoor for persistence in Android 11?

**Comment by timwr** [comment]
The Android payload should already by persistent (it should reconnect when the device is restarted). If the session keeps dying it's probably the battery saver/OS killing it. Have a look at: dontkillmyapp.com

**Comment by coderscoding** [comment]
Any another way to do this?

**Comment by shk-trix** [comment]
Lograron solucionar el error?

managed to fix the error

**Comment by Aggelos11** [comment]
Same for me … any idea how to make persistent in android 11 and above ?

**Comment by h00die** [comment]
#19154 is how.

**Comment by Aggelos11** [comment]
Unfortunately it does not work. I get this error: 
![IMG_9561](https://github.com/rapid7/metasploit-framework/assets/62383412/ced1e5ee-0f5e-44a8-a439-e3f3ea2ade36)
