### ISSUE TITLE
Unable to load the EventMachine C extension

### ISSUE THREAD

**Issue by 0xDanielll** [rapid7/metasploit-framework#15571]
Hi. After installing the latest Metasploit version on the latest version of Windows 10 19043, I run the msfconsole command, and I receive this error.

```
D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        48: from D:/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `<main>'
        47: from D:/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `require'
        46: from D:/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `<top (required)>'
        45: from D:/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `require'
        44: from D:/metasploit-framework/embedded/framework/config/environment.rb:4:in `<top (required)>'
        43: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/railtie.rb:207:in `method_missing'
        42: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/railtie.rb:207:in `public_send'
        41: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/application.rb:391:in `initialize!'
        40: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/initializable.rb:60:in `run_initializers'
        39: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        38: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        37: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        36: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `call'
        35: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `each'
        34: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        33: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        32: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        31: from D:/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        30: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/initializable.rb:61:in `block in run_initializers'
        29: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `run'
        28: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/initializable.rb:32:in `instance_exec'
        27: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        26: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
        25: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
        24: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
        23: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
        22: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
        21: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
        20: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
        19: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
        18: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
        17: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
        16: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        15: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        14: from D:/metasploit-framework/embedded/framework/lib/msf/core/rpc/json/request.rb:1:in `<top (required)>'
        13: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        12: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        11: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/em-http-request-1.1.7/lib/em-http-request.rb:1:in `<top (required)>'
        10: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         9: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         8: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/em-http-request-1.1.7/lib/em-http.rb:1:in `<top (required)>'
         7: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         6: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         5: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         4: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         3: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
         2: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
D:/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError)
```

I have disabled all antivirus and firewalls. Any ideas?

**Comment by emeierg** [comment]
Which version did you install? Did you install latest? Which is some build of 6.1.1.
I installed 6.0.57 that opened the console without error for me.

**Comment by 0xDanielll** [comment]
> Which version did you install? Did you install latest? Which is some build of 6.1.1.
> I installed 6.0.57 that opened the console without error for me.

Thanks, that version works for me. However, when I run MSFD, it hangs when it gets to "Background mode is not available on this platform". Does this work for you?

**Comment by 999e** [comment]
> 
> 
> Which version did you install? Did you install latest? Which is some build of 6.1.1.
> I installed 6.0.57 that opened the console without error for me.

where can I find version 6.0.57

**Comment by 9fj** [comment]
> 
> 
> Which version did you install? Did you install latest? Which is some build of 6.1.1.
> I installed 6.0.57 that opened the console without error for me.

could you please share the link to download 6.0.57
the older builds links seems to have only one older version

**Comment by je5442804** [comment]
I have same in the problem in windows metasploit-framework-6.1.2+20210824153221 
Now unable to use msfconsole due to the BUG

**Comment by adfoster-r7** [comment]
We've just merged a fix for this now: https://github.com/rapid7/metasploit-framework/pull/15629

It should be available in the next release, version 6.1.3. If you need the fix sooner, you can also apply those fixes to your local copy of Metasploit too :+1:

**Comment by adfoster-r7** [comment]
Closing, as I believe the original issue is resolved now

**Comment by COOLIRON2311** [comment]
> Closing, as I believe the original issue is resolved now

No it's not. I am experiancing it right now in `6.4.21` on Windows 11.

**Comment by adfoster-r7** [comment]
Could you raise a new issue please - thank you
