### ISSUE TITLE
Function cmd_exec in Metasploit 6.x

### ISSUE THREAD

**Issue by kerszl** [rapid7/metasploit-framework#15649]
## Steps to reproduce

1. It is about the **multi/gather/ping_sweep** module, when I was playing with it in **pivoting**, an error popped up in the Metasploit. I figured it through **Msf::Post::File"** or similar library is missing. Some modules without this library and with the **cmd_exec** command behave similarly.

## Expected behavior

```
msf6 post(multi/gather/ping_sweep) > set rhosts 172.18.0.1-3
rhosts => 172.18.0.1-3
msf6 post(multi/gather/ping_sweep) > set session 2
session => 2
msf6 post(multi/gather/ping_sweep) > run

[*] Performing ping sweep for IP range 172.18.0.1-3
[+]     172.18.0.1 host found
[+]     172.18.0.2 host found
[+]     172.18.0.3 host found
[*] Post module execution completed
```

## Current behavior
```
msf6 post(multi/gather/ping_sweep) > set rhosts 172.18.0.1-3
rhosts => 172.18.0.1-3
msf6 post(multi/gather/ping_sweep) > set session 2
session => 2
msf6 post(multi/gather/ping_sweep) > run

[*] Performing ping sweep for IP range 172.18.0.1-3
[*] The following Error was encountered: NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[*] Post module execution completed
```

### Metasploit version

Metasploit v6.1.2-dev

## Additional Information
To fix it, you can add between **"class MetasploitModule < Msf::Post"**  and **def initialize(info={})**
  **include Msf::Post::File**

It should look something like this:

```
class MetasploitModule < Msf::Post
  include Msf::Post::File

  def initialize(info={})
```
This error also occurs in other modules like: **multi/gather/dns_reverse_lookup** and I think many others.

**Comment by adfoster-r7** [comment]
Thanks for raising an issue! Unfortunately I wasn't able to replicate against a unix target:
```
msf6 post(multi/gather/ping_sweep) > set rhosts 172.18.0.1-3
rhosts => 172.18.0.1-3
msf6 post(multi/gather/ping_sweep) > run

[!] SESSION may not be compatible with this module (incompatible session platform: unix)
[*] Performing ping sweep for IP range 172.18.0.1-3
[*] Post module execution completed
msf6 post(multi/gather/ping_sweep) > version
Framework: 6.1.4-dev-c0e81acc92
Console  : 6.1.4-dev-c0e81acc92
```

The issue has either been fixed in the latest release, or you're potentially a different session type than me

**Comment by kerszl** [comment]
Its all debug log

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
[framework/features]

[framework/ui/console]
ActiveModule=post/multi/gather/ping_sweep
ActiveWorkspace=Vulnerable Docker: 1: easy

[multi/gather/ping_sweep]
WORKSPACE=
VERBOSE=false
SESSION=
RHOSTS=
loglevel=3
```

</details>


##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
2000   set loglevel 3
2001   debug
```

</details>


##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[09/06/2021 22:37:29] [e(0)] core: Thread Exception: Module(multi/gather/ping_sweep)  critical=false    source:
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:57:in `block in run'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `upto'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:112:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:82:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:91:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/post.rb:85:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__                               Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[09/06/2021 22:37:29] [e(0)] core: Thread Exception: Module(multi/gather/ping_sweep)  critical=false    source:
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:57:in `block in run'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `upto'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:112:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:82:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:91:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/post.rb:85:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__                               Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[09/06/2021 22:37:29] [e(0)] core: Thread Exception: Module(multi/gather/ping_sweep)  critical=false    source:
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:57:in `block in run'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `upto'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:112:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:82:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:91:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/post.rb:85:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__                               Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/07/2021 18:30:23] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go                                failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your enviro                               nment.
[09/07/2021 18:30:23] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go f                               ailed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environm                               ent.
[09/07/2021 18:30:23] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go faile                               d to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
```

</details>


##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>


##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/post.rb:85:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__                               Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[09/06/2021 22:37:29] [e(0)] core: Thread Exception: Module(multi/gather/ping_sweep)  critical=false    source:
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:57:in `block in run'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `upto'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:112:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:82:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:91:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/post.rb:85:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__                               Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[09/06/2021 22:37:29] [e(0)] core: Thread Exception: Module(multi/gather/ping_sweep)  critical=false    source:
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:57:in `block in run'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `upto'
    /usr/share/metasploit-framework/modules/post/multi/gather/ping_sweep.rb:56:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:112:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:82:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/post.rb:91:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/post.rb:85:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:555:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:504:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:498:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:162:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__                               Gather__Ping_sweep::MetasploitModule:0x000055630c2f5fc0>
[09/07/2021 00:00:38] [d(0)] core: HistoryManager.pop_context name: :msfconsole
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[09/07/2021 18:30:22] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/07/2021 18:30:23] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/exchange_enum.go                                failed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your enviro                               nment.
[09/07/2021 18:30:23] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/onprem_enum.go f                               ailed to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environm                               ent.
[09/07/2021 18:30:23] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/msmail/host_id.go faile                               d to load - LoadError Failed to execute external Go module. Please ensure you have Go installed on your environment.
[09/07/2021 18:30:23] [d(0)] core: HistoryManager.push_context name: :msfconsole
```

</details>


##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>


##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.1.2-dev
Ruby: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-gnu]
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

</details>

**Comment by adfoster-r7** [comment]
@kerszl As weird as it it sounds, is this still an issue if you uninstall and reinstall metasploit? We've had issues in the past were files don't get updated correctly after upgrades

Just to confirm as well, are you using Kali?

**Comment by kerszl** [comment]
you're right. I installed Kali (VERSION="2021.2") from the beginning and everything went fine, but when I upgraded Metasploit (apt update ; apt install metasploit-framework) then an error started popping up.
#---
Metasploit - 6.0.45-dev - ok

msf6 post(multi/gather/ping_sweep) > mkdir vulnerable_docker_containement
[*] exec: mkdir vulnerable_docker_containement

msf6 post(multi/gather/ping_sweep) > set SESSION 1
SESSION => 1
msf6 post(multi/gather/ping_sweep) > set RHOSTS  172.18.0.0/24
RHOSTS => 172.18.0.0/24
msf6 post(multi/gather/ping_sweep) > run

[*] Performing ping sweep for IP range 172.18.0.0/24
[+]     172.18.0.1 host found
[+]     172.18.0.3 host found
[+]     172.18.0.2 host found
[+]     172.18.0.4 host found
#----
After upgrade to Framework: 6.1.5-dev Console  : 6.1.5-dev is error

msf6 post(multi/gather/ping_sweep) > run -j
[*] Post module running as background job 1.

[*] Performing ping sweep for IP range 172.18.0.0/24
msf6 post(multi/gather/ping_sweep) > [*] The following Error was encountered: NoMethodError undefined method `cmd_exec' for #<Msf::Modules::Post__Multi__Gather__Ping_sweep::MetasploitModule:0x00007fbb84452828>

**Comment by kerszl** [comment]
Can I close Issue?

**Comment by adfoster-r7** [comment]
Thanks for the update!

As long as it's working on master as it stands right now, I'm happy to close this :+1:

**Comment by Cyclic3** [comment]
For people who don't want to rebuild from master, I've hacked together the following script to detect and patch it for ping_sweep that seems to work on my machine.
{{standard disclaimer about it's complete lack of auditing and me taking no responsibility for any evil acts it may perform}}
https://github.com/Cyclic3/msf-15649-fix
