### ISSUE TITLE
An error occurred when I started the program after executing msfupdate

### ISSUE THREAD

**Issue by hkzj** [rapid7/metasploit-framework#15716]
An error occurred when I started the program after executing msfupdate.
It happened on my macOS.

```
➜  ~ msfconsole
Traceback (most recent call last):
	35: from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `<main>'
	34: from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:18:in `require'
	33: from /opt/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `<top (required)>'
	32: from /opt/metasploit-framework/embedded/framework/lib/msfenv.rb:17:in `require'
	31: from /opt/metasploit-framework/embedded/framework/config/environment.rb:4:in `<top (required)>'
	30: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `method_missing'
	29: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/railtie.rb:207:in `public_send'
	28: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/application.rb:391:in `initialize!'
	27: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:60:in `run_initializers'
	26: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	25: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	24: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	23: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `call'
	22: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:347:in `each'
	21: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	20: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	19: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	18: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	17: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	16: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `run'
	15: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/initializable.rb:32:in `instance_exec'
	14: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/railties-6.1.4.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
	13: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
	12: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
	11: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
	10: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
	 9: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
	 8: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
	 7: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
	 6: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
	 5: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
	 4: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
	 3: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
	 2: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `tap'
	 1: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:27:in `block in require'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader/callbacks.rb:18:in `on_file_autoloaded': expected file /opt/metasploit-framework/embedded/framework/lib/msf/core/opt_http_rhost_url.rb to define constant Msf::OptHttpRhostUrl, but didn't (Zeitwerk::NameError)
```

**Comment by hkzj** [comment]
When I uninstalled and reinstalled, it looked okay
```
➜  ~ cd /opt/metasploit-framework/bin
➜  bin sudo ./msfremove
```
download： https://osx.metasploit.com/metasploitframework-latest.pkg

**Comment by gwillcox-r7** [comment]
Closing as this was a temporary error and a solution was found but if you manage to replicate this again reliably, feel free to let us know and we will be happy to reopen this again.
