### ISSUE TITLE
Downgrade metasploit framework 5

### ISSUE THREAD

**Issue by gnu-like** [rapid7/metasploit-framework#15815]
### metasploit-framework_5.0.101
-------------------------------------------------------------------------------------------------------------------------------
```
Traceback (most recent call last):
        27: from /usr/bin/msfconsole:21:in `<main>'
        26: from /usr/bin/msfconsole:21:in `require'
        25: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        24: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        23: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        22: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        21: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `<top (required)>'
        20: from /usr/share/metasploit-framework/lib/msf/core.rb:44:in `require'
        19: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:24:in `<top (required)>'
        18: from /usr/share/metasploit-framework/lib/msf/core/db_manager.rb:66:in `<class:DBManager>'
        17: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        16: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        15: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
        14: from /usr/share/metasploit-framework/lib/metasploit/framework/require.rb:22:in `require'
        13: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-credential-3.0.4/lib/metasploit/credential.rb:11:in `<top (required)>'
        12: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit-credential-3.0.4/lib/metasploit/credential.rb:11:in `require'
        11: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:17:in `<top (required)>'
        10: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/metasploit_data_models-3.0.10/lib/metasploit_data_models.rb:17:in `require'
         9: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `<top (required)>'
         8: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/all.rb:3:in `require'
         7: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `<top (required)>'
         6: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:1:in `each'
         5: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
         4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext.rb:2:in `require'
         3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
         2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object.rb:3:in `require'
         1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)
```
**added** `gem 'bigdecimal' ` Gemfile & bundle install
```
msfconsole 
Traceback (most recent call last):
        11: from /usr/bin/msfconsole:21:in `<main>'
        10: from /usr/bin/msfconsole:21:in `require'
         9: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
         8: from /usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
         7: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
         6: from /usr/share/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
         5: from /usr/share/metasploit-framework/lib/msf/core.rb:14:in `<top (required)>'
         4: from /usr/share/metasploit-framework/lib/msf/core.rb:14:in `require'
         3: from /usr/share/metasploit-framework/lib/rex.rb:46:in `<top (required)>'
         2: from /usr/share/metasploit-framework/lib/rex.rb:46:in `require'
         1: from /var/lib/gems/2.7.0/gems/rex-text-0.2.37/lib/rex/text.rb:5:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rex-text-0.2.37/lib/rex/text.rb:5:in `require': superclass mismatch for class StringIO (TypeError)
```

**Comment by adfoster-r7** [comment]
Metasploit 5.0.101 was released on 30 Jul 2020, and is very old. Is there a reason for not using the latest release of Metasploit?

**Comment by gnu-like** [comment]
> Metasploit 5.0.101 was released on 30 Jul 2020, and is very old. Is there a reason for not using the latest release of Metasploit?

[Important note](https://www.rapid7.com/blog/post/2020/08/06/metasploit-6-now-under-active-development/): Metasploit 6 incorporates backwards-incompatible changes for payload communication, meaning payloads generated with previous Metasploit versions will be unable to connect to Metasploit 6 and vice versa. Because of this incompatibility, users should not update to Metasploit 6 during active operations unless they are prepared to lose their sessions.

**Comment by timwr** [comment]
@gnu-like I don't think this is really a reason not to upgrade. I suspect it only prevents stageless payloads generated with msf5 from giving a valid session to an msf6 handler. You can of course generate payloads with msf6 and have them connect just fine to msf6 handlers.
Additionally (I think) staged payloads (and non-meterpreter) payloads generated with msf5 will still be able to connect to msf6 handlers.
If in doubt you can just re-generate the payload with msf6.
