### ISSUE TITLE
job.info could not get results, rpc server did not return results

### ISSUE THREAD

**Issue by Lcys** [rapid7/metasploit-framework#15930]
```
>> rpc.call('job.info', 0)

Traceback (most recent call last):
	... 3 levels...
	27: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
	15: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	14: from /opt/metasploit-framework/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `readmultiline'
	13: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:175:in `readmultiline'
	12: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:243:in `inner_readline'
	11: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:243:in `loop'
	10: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:245:in `block in inner_readline'
	 9: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:286:in `read_io'
	 8: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:286:in `loop'
	 7: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:287:in `block in read_io'
	 6: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:120:in `getc'
	 5: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:75:in `inner_getc'
	 4: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:75:in `raw'
	 3: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:75:in `getbyte'
	 2: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/line_editor.rb:161:in `block in reset'
	 1: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:45:in `block in run'
/opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/irb-1.3.6/lib/irb.rb:739:in `signal_handle': Terminate Line Input (RubyLex::TerminateLineInput)
	... 6 levels...
	28: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:175:in `readmultiline'
	27: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:243:in `inner_readline'
	26: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:243:in `loop'
	25: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:245:in `block in inner_readline'
	24: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:286:in `read_io'
	23: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:286:in `loop'
	22: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline.rb:287:in `block in read_io'
	21: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:120:in `getc'
	20: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:75:in `inner_getc'
	19: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:75:in `raw'
	18: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/ansi.rb:75:in `getbyte'
	17: from /opt/metasploit-framework/embedded/lib/ruby/gems/2.7.0/gems/reline-0.2.5/lib/reline/line_editor.rb:161:in `block in reset'
	16: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:44:in `block in run'
	15: from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/irb_shell.rb:47:in `rescue in block in run'
	 2: from (irb):48:in `<main>'
	 1: from /opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:104:in `call'
/opt/metasploit-framework/embedded/framework/lib/msf/core/rpc/v10/client.rb:162:in `send_rpc_request': nil (RuntimeError)

```

Reproducible in both macos and kali

**Comment by Lcys** [comment]
After testing, it only appears when the handler command is used to create a listener
