### ISSUE TITLE
msfdb init fails with error when choosing to not init webservice

### ISSUE THREAD

**Issue by whudson** [rapid7/metasploit-framework#15981]
## Steps to reproduce

How'd you do it?

1. Install MSF on windows 10 using latest MSI installer
2. MSF BIN directory added to `%PATH%`
2. Run `msfdb init`
3. when asked to init webservice pick no

## Were you following a specific guide/tutorial or reading documentation?
No

## Expected behavior

The init script should continue to init databse

## Current behavior

Init script fails with the following error:
```
Clearing http web data service credentials in msfconsole
E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `spawn': No such file or directory - ./msfconsole -qx 'db_disconnect --clear; exit' (Errno::ENOENT)
        from E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:221:in `popen_run'
        from E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
        from E:/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:398:in `capture2e'
        from E:/metasploit-framework/embedded/framework/lib/msfdb_helpers/db_interface.rb:55:in `run_cmd'
        from E:/metasploit-framework/bin/../embedded/framework/msfdb:653:in `run_msfconsole_command'
        from E:/metasploit-framework/bin/../embedded/framework/msfdb:672:in `clear_default_data_service'
        from E:/metasploit-framework/bin/../embedded/framework/msfdb:1067:in `<main>'
```

### Metasploit version

Framework: 6.1.21-dev-69e67db13575983983b4011eb9f5a203733827f0
Console  : 6.1.21-dev-69e67db13575983983b4011eb9f5a203733827f0

## Additional Information
N/A

**Comment by 3V3RYONE** [comment]
Hey, I was working on this issue.  
Got this issue fixed, that is, `msfdb init` now does not result in a crash (when not opting for webservices).  
It attempts to create the database, but hangs there forever. (Mentioned in sister issue #15980 )  
Will be working on issue #15980 now, while creating a PR for this issue! :)
