### ISSUE TITLE
 Metasploit v6.1.30 for windows, shodan_search.rb have bug

### ISSUE THREAD

**Issue by NLL-CN** [rapid7/metasploit-framework#16189]
When I type "run" and press enter, an error message is output.

```
=======================error message ==========================================
msf6 auxiliary(gather/shodan_search) > run

[-] Auxiliary failed: JSON::ParserError 859: unexpected token at '<!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; color: #000000; font-family:-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, "Helvetica Neue",Aria
l, sans-serif; font-size: 16px; line-height: 1.7em;-webkit-font-smoothing: antialiased;}
    h1 { text-align: center; font-weight:700; margin: 16px 0; font-size: 32px; color:#000000; line-height: 1.25;}
    p {font-size: 20px; font-weight: 400; margin: 8px 0;}
    p, .attribution, {text-align: center;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 32px;}
    @keyframes fader     { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    @-webkit-keyframes fader { 0% {opacity: 0.2;} 50% {opacity: 1.0;} 100% {opacity: 0.2;} }
    #cf-bubbles > .bubbles { animation: fader 1.6s infinite;}
    #cf-bubbles > .bubbles:nth-child(2) { animation-delay: .2s;}
    #cf-bubbles > .bubbles:nth-child(3) { animation-delay: .4s;}
    .bubbles { background-color: #f58220; width:20px; height: 20px; margin:2px; border-radius:100%; display:inline-block; }
    a { color: #2c7cb0; text-decoration: none; -moz-transition: color 0.15s ease; -o-transition: color 0.15s ease; -webkit-transition: color 0.15s ease; transition: col
or 0.15s ease; }
    a:hover{color: #f4a15d}
    .attribution{font-size: 16px; line-height: 1.5;}
    .ray_id{display: block; margin-top: 8px;}
    #cf-wrapper #challenge-form { padding-top:25px; padding-bottom:25px; }
    #cf-hcaptcha-container { text-align:center;}
    #cf-hcaptcha-container iframe { display: inline-block;}
  </style>

      <meta http-equiv="refresh" content="35">
  <script type="text/javascript">
    //<![CDATA[
    (function(){

      window._cf_chl_opt={
        cvId: "2",
        cType: "non-interactive",
        cNounce: "52689",
        cRay: "6dd71e4a4e49ed3b",
        cHash: "c6be941c54e40f2",
        cPMDTk: "i_71KedmMzcHdgVjv0q5vbjhb9SY38i_Eth_lAuRA3A-1644850326-0-gaNycGzNBz0",
        cUPMDTk: "\/shodan\/host\/search?key=7flbXbK5XHXIuafcGSSIH2v8UIhDTqyT&query=windows&page=1&__cf_chl_tk=i_71KedmMzcHdgVjv0q5vbjhb9SY38i_Eth_lAuRA3A-1644850326-0-
gaNycGzNBz0",
        cFPWv: "b",
        cTTimeMs: "1000",
        cRq: {
          ru: "aHR0cHM6Ly9hcGkuc2hvZGFuLmlvL3Nob2Rhbi9ob3N0L3NlYXJjaD9rZXk9N2ZsYlhiSzVYSFhJdWFmY0dTU0lIMnY4VUloRFRxeVQmcXVlcnk9d2luZG93cyZwYWdlPTE=",
          ra: "TW96aWxsYS81LjAgKGlQYWQ7IENQVSBPUyAxNV8zXzEgbGlrZSBNYWMgT1MgWCkgQXBwbGVXZWJLaXQvNjA1LjEuMTUgKEtIVE1MLCBsaWtlIEdlY2tvKSBWZXJzaW9uLzE1LjIgTW9iaWxlLzE1RTE0O
CBTYWZhcmkvNjA0LjE=",
          rm: "R0VU",
          d: "qFIlOLgaqvsuN5ecbfsxXCaXWTfitZVeNaK0mne66cCwoCoTgcLLb/sNfijfFvgANbnpcVp8/HU0ciVb8+t9guDmErT6zKzScUFbTqXsMG5iQ9Lk4ihhWVu/L7haHVuFuo/kBZrh9hUVBxsCLFzPbk/M4C
RDkc6nKRao9nZn4SOjGqzAj5uxJq5pWl6YROikL/qB1XmuIOQpEvm74m/msAla4VUYor8ZUfFhwNOzB/DlFQcpEoEK+rl6ZqvMuJGBHimSXH3f5lKivpqCxdcq42fno/ufPhmBVopKwu/pdfEQQX4Od/wx6+1AJYCujkplYc
oyi1wVrRVJQObKt7M/h1WEVfA69Eg/P41b46Yu4mbj2uA6ORh2ug/prLaNIhlCnVxXjqJxghRsdKLELGaFVqCeTEs649amM+rMepd+B24FW3wb4a+HJQ5TW591z1E9jFN+MQ0dJ3QZ41XYEJaXZ7P4jUMndv2DRY4/WBGmXE
aO4c99x3M96EpMYdq0IcDWQgcxmpmrGoiS292dPqXEsEEC0HD+OfNetw/qYHGIfiM3rAIdqaEbK0AwJIkH68KUoZOkmBoN7C/o8AdC+5SZrHvqn8dTJbYJaHbXvtNQfnM=",
          t: "MTY0NDg1MDMyNi4xNTcwMDA=",
          m: "kHWrW5zVGoOG9sD1TOQGMiWf7oPWgCYeySEAQyosyRc=",
          i1: "iW6VVjEtSsK6ShMuqzig2A==",
          i2: "w3KKNkvw6460/PN6z8z4MA==",
          zh: "zpoBT3b5nT+7dn2MYptQW3Qw4o/KBIuo0Jm2+aY2obg=",
          uh: "95q3NyLZBf7ZOd7tWKLzf+BCK9q8Fre8pG5GO+774ok=",
          hh: "vIXvjh5Yg3o69EcoDBPMms9777/6djv1fQDRsk/vVr4=",
        }
      }
      window._cf_chl_enter = function(){window._cf_chl_opt.p=1};

    })();
    //]]>
  </script>


</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript>
    <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>
  </noscript>
  <div id="cf-content" style="display:none">

    <div id="cf-bubbles">
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before accessing</span> api.shodan.io.</h1>

    <div id="no-cookie-warning" class="cookie-warning" data-translate="turn_on_cookies" style="display:none">
      <p data-translate="turn_on_cookies" style="color:#bd2426;">Please enable Cookies and reload the page.</p>
    </div>
    <p data-translate="process_is_automatic">This process is automatic. Your browser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs" id="cf-spinner-allow-5-secs" >Please allow up to 5 seconds&hellip;</p>
    <p data-translate="redirecting" id="cf-spinner-redirecting" style="display:none">Redirecting&hellip;</p>
  </div>

  <form class="challenge-form" id="challenge-form" action="/shodan/host/search?key=7flbXbK5XHXIuafcGSSIH2v8UIhDTqyT&amp;query=windows&amp;page=1&amp;__cf_chl_f_tk=i_71K
edmMzcHdgVjv0q5vbjhb9SY38i_Eth_lAuRA3A-1644850326-0-gaNycGzNBz0" method="POST" enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="md" value="Z6VSefqNxQ6F_RGbTtc_9AZYctROwCQeYChb2cGUzFE-1644850326-0-AfZA_3TyHLJDyMJzvVccTKPRG0Y0v0IEch1Z87EnfwLDROrHDYcPaoZzX3ABXc3YgpUXM
c395cvOmf9I8y_kDK1qWCSlIUlwopnMwRQeWFlODsNkjIkNMzJ67SXFH2SdnukELkbEHbFwcUvfKu-_3nO10BO61FICLRoxrZUvi_Bu4ll2UnRht_NzGYtlYwMfyl04Dvdv0getYNQoVBkQPxsRguuGeESlmgCgTpyS7i9sz
T7MCHts7Q5LX9dbtxkEW828kLij6Z0cO4VWn236Q9O-52KSKXqIvEpPpx6VjlMSrzDu4qKe6g5dyZOrdnRzOpcYYxogjuhp6f409scY7q0dWLBobu_yt2Jx9wey3lsOJIU6JqLkJRInMQrA_T343TnZyinyJHLmaxLDbNYJf
o2DG7BTH_mmh55KbHBD0SylgladDiUYk4njcyKCf9UTzeh6qvmDmYd7hxxX93R2F5h_U7U38Bi0xjkt4YiHbc5YEhsp-ltlpg2LQ2So6oi_ihrmy7DDwWnmGZoKULbD56tLtWWZsoQFZLcA4nvqY_jRim3LarV7fbZP9Cto8
LoQwAMFbIt8bQb97eJjhEgDNW1Jix8jdvLfM-8gCyp4Sa8at-lVxxW-edvFnIjcSOGePQ08T98wQp4ogTWFJ0htlETbHACN-lApnd_FgCKMK18U6VQsMSSZT9oUzYmubOD_jJSPAq3uk-u5r0J-gzEFaKhGJcgYflRZDvz0v
6y7yjx25q0Z-abnX1oObg6yJNSu__t_WsuHVW1BKaEDMkF4DhSnpqnuRQZh55E5epCmCI2aMWft2nYwt4E6GmAXjw_2nbfTJPknhiwmTOGWTUnhHDY" />
    <input type="hidden" name="r" value="526q3M8ZQEExACbVE0Yi_SCHZ._USeAsGVtkVhWMVaI-1644850326-0-ARofNQ48afHmw9welliFfvEVsBx9YDTzAyu5APe+FtmTHBTtI+nLpz6sN+vYlEAVhgzBDE
n2j+UifSSPnBbzOptGSIpX2bv3tK4BhQ9XX62tgvBLr/kAmRa3e8af8u9QTu+L/HNfBPUC9VCB00K3w9HdY21M0cbEx5/X0lZrlx6J6P6MOYDz0czIk7PQKw5v9GwjZYhd6rEwWDpROYQ66LAI0QLciWbaC4tr12jiaZGEzz
PrMy1cn9k9IeFt8JTvXHOybuqCzbh/c0URCzUYqrGHccLRmwgHqCkXz6gqpnnA9y6ZJw0IS6MhMbfqFW0V5CfRLx+MrzzYM/a7PgDJRQeLGqvrraQcEUBzsb/Zd+UhvicTun/qSFcIvdtU5MHe2tjttrMsa7jzKwA9lFdglL
sVVM5pRPGJ+LB83SGfWiSjEHRuRE1d1T4DMK91w63mGOvuHxRi5ybPmx3WEOE2kHd4Fss7+QrZNfKh1tpL3ezHuO6hlnbMmQ0OWCl0tUuIxpjNRGoUsNZDVlCW3+tkuic7N34dkSpM/owNjYMBxqphlEuIFucmNrgbNrX6RQ
gv2VocMDKPRWqjJz/38CCwtp64wWJf0ycDeT1uq//tY4TAFYkI0c8FRRgqOTr/dqQ/SLF6P8gb32kww1VjGFpUX+egrU0K/Z0iOVxzpVzQQ1KOn7pxGQyaeujbPM3eONnQFN4u4+4HiNY5uk7k7z0BwntoW646twl92IVCGS
oqT+K8TKxMSkE2XMYERjasq7E2ItRaDMm3eN9aEBLokRcH+p+HVpu6zPCGH2SM5+v+ObuX4A8l+FndDmO/zrbaO3RZnXdDVdPVsVK7oQuazQDyaK9XZoUY2dN0XguyHdS/rIQABMUlcY/aInxFH3VkA3PrxuQk2gnsJ3R7Ni
zpAy9Ku8ib97UDkgDs+F5tX7+nRvEh+8kh8NbUo1lPCNlTGGJKn4AeDz3DeebZASFO4+VnVsK4ghg9mT1WirOCXbUhtTtHZU01oI+6HTcuiD5aun5QmytKGE7ip6T47Ra7YBcv07VxzwMQkk9FhJXpEjZrlzn6G+B6yFK57d
PU2+x2uVha/nvaJNqsfQIQmHEKwbr8h0RxfDpPhALPmK8Xce8Jys3evVXOWRgMWWBQK43QjMGL3rIHBsPmBpSt5sQzAHPerhPtdLMqhUp/54d6ilGCyzj1pxVnbKQSm7egycmqtsWzoaE5+DgxN006R0WzgpiSjF8mTm3Qb0
9TSysqhZyVXmM9SzgvpBi652ESrFMh+8cmTFvn6/acTZTnGw5bPym+1aaSTB9IH0y4+FhnqInI4L1Tk42s4psH4k8NroEUnDE+ob0xSAuDoG++4XztNEqUfffjP4K7QoY8wMDsAFkgxaqRia6NoARDHS4ZMisEe9Rn9+c9CA
j4ybF6ubYtka8zwDPTOL8/BPH6kozNp0gesdDLH48QJplfaQVl8MLCACrDwyxJ6UQNmPjTx86U1C88x+oKSALSPZqYHuJHp3LxzqchC8aKbe1WjPZZS9D+qwjXZFdh21bt9ou60awlp+3rW1OyVHU812fZQMhchZnmuW1NrS
miURhG16t1lKpzHNlkTzdpQthl18hLGwiZigwFRXBVtH7hyjPR8Rx1fVlzx1r5y/tvwUY03aMCKOGbPaa2YS7bLixoJLMaC4mqIzLCVy2+Dw8RsZQeyMdI9XKtStoIke7xvqmrxKoRp4NlLRvs8m/868NDQaLZMX8OPBfE7C
yKwZxYCc8I+g4n4/j0XEf2g+mTGyYWEhy+HpT6FLYjeQ=="/>
    <input type="hidden" value="d1653a4a500a23318cfa0d6c9bd0a18c" id="jschl-vc" name="jschl_vc"/>
    <!-- <input type="hidden" value="" id="jschl-vc" name="jschl_vc"/> -->
    <input type="hidden" name="pass" value="1644850327.157-VqzgFAAWmY"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>

    <script type="text/javascript">
      //<![CDATA[
      (function(){
          var a = document.getElementById('cf-content');
          a.style.display = 'block';
          var isIE = /(MSIE|Trident\/|Edge\/)/i.test(window.navigator.userAgent);
          var trkjs = isIE ? new Image() : document.createElement('img');
          trkjs.setAttribute("src", "/cdn-cgi/images/trace/jschal/js/transparent.gif?ray=6dd71e4a4e49ed3b");
          trkjs.id = "trk_jschal_js";
          trkjs.setAttribute("alt", "");
          document.body.appendChild(trkjs);
          var cpo=document.createElement('script');
          cpo.type='text/javascript';
          cpo.src="/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=6dd71e4a4e49ed3b";

          window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.indexOf('?') !== -1 ? '?' : location.search;
          window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;
          if (window._cf_chl_opt.cUPMDTk && window.history && window.history.replaceState) {
            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;
            history.replaceState(null, null, "\/shodan\/host\/search?key=7flbXbK5XHXIuafcGSSIH2v8UIhDTqyT&query=windows&page=1&__cf_chl_rt_tk=i_71KedmMzcHdgVjv0q5vbjhb9
SY38i_Eth_lAuRA3A-1644850326-0-gaNycGzNBz0" + window._cf_chl_opt.cOgUHash);
            cpo.onload = function() {
              history.replaceState(null, null, ogU);
            };
          }

          document.getElementsByTagName('head')[0].appendChild(cpo);
        }());
      //]]>
    </script>



  <div id="trk_jschal_nojs" style="background-image:url('/cdn-cgi/images/trace/jschal/nojs/transparent.gif?ray=6dd71e4a4e49ed3b')"> </div>
</div>


          <div class="attribution">
            DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>
            <br />
            <span class="ray_id">Ray ID: <code>6dd71e4a4e49ed3b</code></span>
          </div>
      </td>

    </tr>
  </table>
</body>
</html>
'
[-] Call stack:
[-]   L:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/json-2.6.1/lib/json/common.rb:216:in `parse'
[-]   L:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/json-2.6.1/lib/json/common.rb:216:in `parse'
[-]   L:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.4/lib/active_support/json/decoding.rb:23:in `decode'
[-]   L:/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:72:in `shodan_query'
[-]   L:/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:117:in `run'
[*] Auxiliary module execution completed            
=========================error message end=====================================
```

========》Note that the version numbers mentioned below are all my own, not official.===========

I don't know what's going on, but it seems that it should be the problem of JSON. I don't know whether it's due to the problem of windows system or my module. You can try it on your Kali Linux (with Metasploit v6.1.30), but this module is in Metasploit V6 1.9 (windows10) for windows can run.

Or the ruby and JSON versions? My Metasploit v6. 1.30 uses ruby 3.0.0 and JSON 2.6.1, but my Metasploit V6.0 Ruby in 1.9 is 2.7 and JSON is 2.5.1.

I really don't know what's going on. I hope you and developers can help. By the way, my English is not very good. I write these with a translator. It's inevitable that there will be some grammatical errors. Thank you!

**Comment by adfoster-r7** [comment]
Looks like Cloudflare is blocking the request. This _might_ happen if your Shodan token is not correctly set.

**Comment by AstroZombieSG** [comment]
This is related to the user-agent specified in advanced options.
do "show advanced"
look at UserAgent
do "set UserAgent Wget/1.21.2"
run it again.

shodan is checking user-agent
