### ISSUE TITLE
Post/Windows/Powershell_Exec bug error

### ISSUE THREAD

**Issue by Reversing26** [rapid7/metasploit-framework#16400]
[+] Compressed size: 1088
[+] Final command JgAoAFsAcwBjAHIAaQBwAHQAYgBsAG8AYwBrAF0AOgA6AGMAcgBlAGEAdABlACgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBJAE8ALgBTAHQAcgBlAGEAbQBSAGUAYQBkAGUAcgAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgAuAEcAegBpAHAAUwB0AHIAZQBhAG0AKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtACgALABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAKAAoACcASAA0AHMASQBBAEsAeABKAFIAewAxAH0ASQBDAEEAMAB0AE4AegBzAGgAWAA4AEsANwB7ADAAfQAnACsAJwBLAEgAWgBNAFMAOABxADAAegBrAHMAdABLAGMANQBRAFMARQB3AHAAUwA4AHMAcwBTAGkAMQBQAHoATQBsAFIASwBFADQAdABVAFEARABTAEIAVQBYADUAYQBaAGsANQBxACcAKwAnAGMAVQBLAHgAUwBXAEoASgBhAGsASwArAFcAbABwADEAZwBxAHAASQBLADAAVgBxAFUAbABCAEwAdQBsACsAeABRAEMAOQBzAE0AMwBvAFMAQQBBAEEAQQBBAD0APQAnACkALQBmACcAeQAnACwAJwAyACcAKQApACkAKQAsAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ATQBvAGQAZQBdADoAOgBEAGUAYwBvAG0AcAByAGUAcwBzACkAKQApAC4AUgBlAGEAZABUAG8ARQBuAGQAKAApACkAKQBlAGMAaABvACAAJwBzAEgAZQBlAGIAYQBTAFEAJwA7AA==
[+] EXECUTING:
powershell.exe -EncodedCommand JgAoAFsAcwBjAHIAaQBwAHQAYgBsAG8AYwBrAF0AOgA6AGMAcgBlAGEAdABlACgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBJAE8ALgBTAHQAcgBlAGEAbQBSAGUAYQBkAGUAcgAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgAuAEcAegBpAHAAUwB0AHIAZQBhAG0AKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtACgALABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAKAAoACcASAA0AHMASQBBAEsAeABKAFIAewAxAH0ASQBDAEEAMAB0AE4AegBzAGgAWAA4AEsANwB7ADAAfQAnACsAJwBLAEgAWgBNAFMAOABxADAAegBrAHMAdABLAGMANQBRAFMARQB3AHAAUwA4AHMAcwBTAGkAMQBQAHoATQBsAFIASwBFADQAdABVAFEARABTAEIAVQBYADUAYQBaAGsANQBxACcAKwAnAGMAVQBLAHgAUwBXAEoASgBhAGsASwArAFcAbABwADEAZwBxAHAASQBLADAAVgBxAFUAbABCAEwAdQBsACsAeABRAEMAOQBzAE0AMwBvAFMAQQBBAEEAQQBBAD0APQAnACkALQBmACcAeQAnACwAJwAyACcAKQApACkAKQAsAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ATQBvAGQAZQBdADoAOgBEAGUAYwBvAG0AcAByAGUAcwBzACkAKQApAC4AUgBlAGEAZABUAG8ARQBuAGQAKAApACkAKQBlAGMAaABvACAAJwBzAEgAZQBlAGIAYQBTAFEAJwA7AA== -InputFormat None
[-] Post failed: NoMethodError undefined method `strip' for nil:NilClass
[-] Call stack:
[-]   c:/metasploit-framework/embedded/framework/lib/msf/core/post/windows/powershell.rb:356:in `psh_exec'
[-]   c:/metasploit-framework/embedded/framework/modules/post/windows/manage/exec_powershell.rb:49:in `run'
[*] Post module execution completed

Other details: Metasploit for Windows 10
Target: Windows 10 x64 with Defender disabled;
Attacker: Windows 10 x64 with Metasploit installed.
Session type: NT/AUTHORITY SYSTEM (Meterpreter)

**Comment by bwatters-r7** [comment]
Huh; that appears to be a straightforward bug, though possibly not the underlying issue for you,
`framework/embedded/framework/lib/msf/core/post/windows/powershell.rb:356`:
`ps_output = ps_output[/#{start}(.*?)#{stop}/m, 1].strip  #https://stackoverflow.com/a/9661504`
For some reason, the regex is returning `nil`, and then when we call `strip`, it results in an unhandled exception.  I am not sure why the regex does not match on anything, but if it is possible for the regex to return `nil` (as you have proved), we should check for that before we call `strip`
I'd need to dig a little more to find out why the regex is failing.  Can you run 
```
powershell.exe -EncodedCommand JgAoAFsAcwBjAHIAaQBwAHQAYgBsAG8AYwBrAF0AOgA6AGMAcgBlAGEAdABlACgAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBJAE8ALgBTAHQAcgBlAGEAbQBSAGUAYQBkAGUAcgAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAEMAbwBtAHAAcgBlAHMAcwBpAG8AbgAuAEcAegBpAHAAUwB0AHIAZQBhAG0AKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAEkATwAuAE0AZQBtAG8AcgB5AFMAdAByAGUAYQBtACgALABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAKAAoACcASAA0AHMASQBBAEsAeABKAFIAewAxAH0ASQBDAEEAMAB0AE4AegBzAGgAWAA4AEsANwB7ADAAfQAnACsAJwBLAEgAWgBNAFMAOABxADAAegBrAHMAdABLAGMANQBRAFMARQB3AHAAUwA4AHMAcwBTAGkAMQBQAHoATQBsAFIASwBFADQAdABVAFEARABTAEIAVQBYADUAYQBaAGsANQBxACcAKwAnAGMAVQBLAHgAUwBXAEoASgBhAGsASwArAFcAbABwADEAZwBxAHAASQBLADAAVgBxAFUAbABCAEwAdQBsACsAeABRAEMAOQBzAE0AMwBvAFMAQQBBAEEAQQBBAD0APQAnACkALQBmACcAeQAnACwAJwAyACcAKQApACkAKQAsAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ALgBDAG8AbQBwAHIAZQBzAHMAaQBvAG4ATQBvAGQAZQBdADoAOgBEAGUAYwBvAG0AcAByAGUAcwBzACkAKQApAC4AUgBlAGEAZABUAG8ARQBuAGQAKAApACkAKQBlAGMAaABvACAAJwBzAEgAZQBlAGIAYQBTAFEAJwA7AA== -InputFormat None

```
Locally at the command prompt and have it work?
