### ISSUE TITLE
./msfdb init [MSF-DEV]

### ISSUE THREAD

**Issue by rafalohaki** [rapid7/metasploit-framework#16546]
i tried to set up metasploit dev env from:
https://github.com/rapid7/metasploit-framework/wiki/Setting-Up-a-Metasploit-Development-Environment
got this problem on:
Optional: Set up the REST API and PostgreSQL database
3. Initialize the Metasploit database:
```
┌──(aniota㉿DESKTOP-NMQS9MO)-[~/git/metasploit-framework]
└─$ ./msfdb init
/home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/digest-3.1.0/lib/digest.rb:20: warning: already initialized constant Digest::REQUIRE_MUTEX
/home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/digest.rb:6: warning: previous definition of REQUIRE_MUTEX was here
Traceback (most recent call last):
        51: from ./msfdb:32:in `<main>'
        50: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        49: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        48: from /home/aniota/git/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        47: from /home/aniota/git/metasploit-framework/lib/msfenv.rb:17:in `require'
        46: from /home/aniota/git/metasploit-framework/config/environment.rb:4:in `<top (required)>'
        45: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/railtie.rb:207:in `method_missing'
        44: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/railtie.rb:207:in `public_send'
        43: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/application.rb:391:in `initialize!'
        42: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:60:in `run_initializers'
        41: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        40: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        39: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        38: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `call'
        37: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each'
        36: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        35: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        34: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        33: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        32: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
        31: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `run'
        30: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `instance_exec'
        29: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        28: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
        27: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
        26: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        25: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        24: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        23: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        22: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        21: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        20: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
        19: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        18: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
        17: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        16: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        15: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:2:in `<top (required)>'
        14: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:3:in `<module:Msf>'
        13: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:4:in `<module:Ui>'
        12: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:9:in `<module:Web>'
        11: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/explicit_namespace.rb:76:in `tracepoint_class_callback'
        10: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:75:in `on_namespace_loaded'
         9: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:75:in `each'
         8: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:76:in `block in on_namespace_loaded'
         7: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:335:in `set_autoloads_in_dir'
         6: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
         5: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
         4: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
         3: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:340:in `block in set_autoloads_in_dir'
         2: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:411:in `autoload_file'
         1: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:89:in `cdef?'
/home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:89:in `const_defined?': wrong constant name 49788 (NameError)
        49: from ./msfdb:32:in `<main>'
        48: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        47: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        46: from /home/aniota/git/metasploit-framework/lib/msfenv.rb:17:in `<top (required)>'
        45: from /home/aniota/git/metasploit-framework/lib/msfenv.rb:17:in `require'
        44: from /home/aniota/git/metasploit-framework/config/environment.rb:4:in `<top (required)>'
        43: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/railtie.rb:207:in `method_missing'
        42: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/railtie.rb:207:in `public_send'
        41: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/application.rb:391:in `initialize!'
        40: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:60:in `run_initializers'
        39: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
        38: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
        37: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
        36: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `call'
        35: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:347:in `each'
        34: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
        33: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
        32: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        31: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
        30: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
        29: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `run'
        28: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `instance_exec'
        27: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/railties-6.1.5/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        26: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
        25: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
        24: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
        23: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
        22: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
        21: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        20: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        19: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        18: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:244:in `block (2 levels) in eager_load'
        17: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        16: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
        15: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        14: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
        13: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:2:in `<top (required)>'
        12: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:3:in `<module:Msf>'
        11: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:4:in `<module:Ui>'
        10: from /home/aniota/git/metasploit-framework/lib/msf/ui/web.rb:9:in `<module:Web>'
         9: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/explicit_namespace.rb:76:in `tracepoint_class_callback'
         8: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:75:in `on_namespace_loaded'
         7: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:75:in `each'
         6: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:76:in `block in on_namespace_loaded'
         5: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:335:in `set_autoloads_in_dir'
         4: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
         3: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
         2: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
         1: from /home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:336:in `block in set_autoloads_in_dir'
/home/aniota/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:360:in `rescue in block in set_autoloads_in_dir': wrong constant name 49788 inferred by MsfAutoload::TempInflector from file (Zeitwerk::NameError)

  /home/aniota/git/metasploit-framework/lib/msf/ui/web/49788.rb

Possible ways to address this:

  * Tell Zeitwerk to ignore this particular file.
  * Tell Zeitwerk to ignore one of its parent directories.
  * Rename the file to comply with the naming conventions.
  * Modify the inflector to handle this case.

┌──(aniota㉿DESKTOP-NMQS9MO)-[~/git/metasploit-framework]
└─$`
```

**Comment by tekwizz123** [comment]
@rafalohaki Please format your output, this is very hard to read. You can use markdown syntax to format this as code blocks, which will make it easier for reviewers to review your problem.

**Comment by adfoster-r7** [comment]
I've formatted the issue request; From the stacktrace it's not entirely clear what's gone wrong, other than a number is somehow triggering a constant load as part of the web namespace. All I can really suggest is deleting the git clone and trying again, or reaching out via slack for more interactive debugging.
