### ISSUE TITLE
Unsupported error

### ISSUE THREAD

**Issue by panditji102** [rapid7/metasploit-framework#16715]
/var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `initialize': unsupported (OpenSSL::Cipher::CipherError)

**Comment by bcoles** [comment]
Is there more to that error message?

Are you using Termux?

**Comment by mrdrawbot586** [comment]
> /var/lib/gems/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/encryption_algorithm/functionable.rb:13:in `initialize': unsupported (OpenSSL::Cipher::CipherError)

same issue I am using kali linux
