### ISSUE TITLE
'pkeys are immutable on OpenSSL 3.0' error when using msfvenom

### ISSUE THREAD

**Issue by Nariod** [rapid7/metasploit-framework#16782]
## Steps to reproduce

How'd you do it?

1. Install Kali Linux from the official website
2. Update with `sudo apt update && sudo apt dist-upgrade -y` and reboot
3. Try to generate a payload with `msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.49.201 LPORT=443 -f exe -o met64.exe`

## Were you following a specific guide/tutorial or reading documentation?

No.

## Expected behavior

Generating the expected payload/binary.

## Current behavior

Msvenom crashed with the following error:

```
msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.49.201 LPORT=443 -f exe -o met64.exe

/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in `generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in `<class:EcdsaSha2Nistp256>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:10:in `<class:ServerHostKeyAlgorithm>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:9:in `<class:Transport>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:8:in `<module:HrrRbSsh>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:7:in `<top (required)>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm.rb:19:in `<top (required)>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:16:in `<top (required)>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in `<top (required)>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in `<top (required)>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in `default_version_string'
        from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in `initialize'
        from /usr/share/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
        from /usr/share/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in `initialize'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in `new'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in `block (2 levels) in recalculate'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in `each_pair'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in `block in recalculate'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in `each_pair'
        from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in `recalculate'
        from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in `block in load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `each'
        from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `each'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
        from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework.rb:124:in `simplify'
        from /usr/share/metasploit-framework/lib/msf/base/simple/framework.rb:72:in `create'
        from /usr/bin/msfvenom:54:in `init_framework'
        from /usr/bin/msfvenom:67:in `framework'
        from /usr/bin/msfvenom:472:in `<main>'
```

### Metasploit version

Framework Version: 6.2.6-dev

**Comment by Nariod** [comment]
Bug has been reported on the official Kali bug tracker:
https://bugs.kali.org/view.php?id=7804

**Comment by X0RW3LL** [comment]
Hi team,

I was able to fix this issue, and here's what needs to change.

`/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb` line 14

```diff
- SECRET_KEY = OpenSSL::PKey::EC.new('prime256v1').generate_key.to_pem
+ SECRET_KEY = OpenSSL::PKey::EC.generate('prime256v1').to_pem
```

`/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb` line 14

```diff
- SECRET_KEY = OpenSSL::PKey::EC.new('secp384r1').generate_key.to_pem
+ SECRET_KEY = OpenSSL::PKey::EC.generate('secp384r1').to_pem
```

`/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb` line 14

```diff
- SECRET_KEY = OpenSSL::PKey::EC.new('secp521r1').generate_key.to_pem
+ SECRET_KEY = OpenSSL::PKey::EC.generate('secp521r1').to_pem
```

**Comment by waleedzafar68** [comment]
> Hi team,
> 
> I was able to fix this issue, and here's what needs to change.
> 
> `/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb` line 14
> 
> ```diff
> - SECRET_KEY = OpenSSL::PKey::EC.new('prime256v1').generate_key.to_pem
> + SECRET_KEY = OpenSSL::PKey::EC.generate('prime256v1').to_pem
> ```
> 
> `/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp384.rb` line 14
> 
> ```diff
> - SECRET_KEY = OpenSSL::PKey::EC.new('secp384r1').generate_key.to_pem
> + SECRET_KEY = OpenSSL::PKey::EC.generate('secp384r1').to_pem
> ```
> 
> `/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp521.rb` line 14
> 
> ```diff
> - SECRET_KEY = OpenSSL::PKey::EC.new('secp521r1').generate_key.to_pem
> + SECRET_KEY = OpenSSL::PKey::EC.generate('secp521r1').to_pem
> ```

This worked like a charm. Be mindful it is generate not new after EC. That was my mistake and could not figure it for an hour

**Comment by adfoster-r7** [comment]
Closing as duplicate; This patch should work for now if you are on Kali - https://github.com/rapid7/metasploit-framework/issues/16767#issuecomment-1185395510

**Comment by enlalibreta** [comment]
**The same thing happened to me that is happening
"After updating kali to latest version, I got this error. Can someone provide help here?"
Error:**
# msfconsole
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in `generate_key!': pkeys are immutable on OpenSSL 3.0 (OpenSSL::PKey::PKeyError)
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:14:in `<class:EcdsaSha2Nistp256>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:10:in `<class:ServerHostKeyAlgorithm>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:9:in `<class:Transport>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:8:in `<module:HrrRbSsh>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm/ecdsa_sha2_nistp256.rb:7:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport/server_host_key_algorithm.rb:19:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh/transport.rb:16:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/hrr_rb_ssh-0.4.2/lib/hrr_rb_ssh.rb:15:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/lib/rex/proto/ssh/hrr_rb_ssh.rb:3:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/lib/rex/proto/ssh/connection.rb:2:in `<top (required)>'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:146:in `default_version_string'
	from /usr/share/metasploit-framework/lib/msf/core/handler/reverse_ssh.rb:40:in `initialize'
	from /usr/share/metasploit-framework/lib/msf/base/sessions/command_shell_options.rb:16:in `initialize'
	from /usr/share/metasploit-framework/modules/payloads/singles/cmd/unix/reverse_ssh.rb:16:in `initialize'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in `new'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:95:in `block (2 levels) in recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in `each_pair'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:93:in `block in recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in `each_pair'
	from /usr/share/metasploit-framework/lib/msf/core/payload_set.rb:73:in `recalculate'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:258:in `block in load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/modules/loader/base.rb:255:in `load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:170:in `block in load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/loading.rb:168:in `load_modules'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:41:in `block in add_module_path'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `each'
	from /usr/share/metasploit-framework/lib/msf/core/module_manager/module_paths.rb:40:in `add_module_path'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:51:in `block in init_module_paths'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `each'
	from /usr/share/metasploit-framework/lib/msf/base/simple/framework/module_paths.rb:50:in `init_module_paths'
	from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:160:in `initialize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `new'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:60:in `driver'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/bin/msfconsole:23:in `<main>'
**please can someone support us**

**Comment by bcoles** [comment]
> The same thing happened to me that is happening
> please can someone support us

This issue was closed as a duplicate of #16767. The patch should be present in the 6.2.8 release later this week.

A workaround is available if you're using Kali: https://github.com/rapid7/metasploit-framework/issues/16767#issuecomment-1185395510
