### ISSUE TITLE
cmd_exec() crashes after ~300 calls on Linux Meterpreter

### ISSUE THREAD

**Issue by space-r7** [rapid7/metasploit-framework#16966]
As mentioned in https://github.com/rapid7/metasploit-framework/pull/16688, it looks like `cmd_exec()` will fail after a little over 300 calls on Linux meterpreter. Windows does not appear to be affected; however, I haven't checked MacOS yet. After hitting the limit, the session is still useable, but no more `cmd_exec()` calls can be made.

```
[-] Post failed: Rex::Post::Meterpreter::RequestError stdapi_sys_process_execute: Operation failed: 1
[-] Call stack:
[-]   /Users/space/rapid7/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:176:in `execute'
[-]   /Users/space/rapid7/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:199:in `capture_output'
[-]   /Users/space/rapid7/metasploit-framework/lib/msf/core/post/common.rb:119:in `cmd_exec'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:280:in `block (2 levels) in check_for_valid_passwords'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:254:in `each'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:254:in `block in check_for_valid_passwords'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:253:in `each'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:253:in `check_for_valid_passwords'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:358:in `block (2 levels) in run'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:349:in `each'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:349:in `block in run'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:337:in `each'
[-]   /Users/space/rapid7/metasploit-framework/modules/post/linux/gather/mimipenguin.rb:337:in `run'
[*] Post module execution completed
```

```
...
[09/01/2022 11:20:36] [w(0)] core: monitor_rsock: the remote socket has been closed, exiting loop
[09/01/2022 11:20:37] [w(0)] core: monitor_rsock: the remote socket has been closed, exiting loop
[09/01/2022 11:20:37] [w(0)] core: monitor_rsock: the remote socket has been closed, exiting loop
[09/01/2022 11:20:38] [w(0)] core: monitor_rsock: the remote socket has been closed, exiting loop
[09/01/2022 11:20:38] [e(0)] core: Post failed - Rex::Post::Meterpreter::RequestError stdapi_sys_process_execute: Operation failed: 1
```

## Steps to reproduce

I tested `cmd_exec()` with the `post/test/cmd_exec` module and modified the `echo` test to call echo 500 times
instead of 10. You should expect a crash at around 334 calls.

<details><summary>Diff</summary>

```
msf6 post(test/cmd_exec) > git diff test/modules/post/test/cmd_exec.rb
[*] exec: git diff test/modules/post/test/cmd_exec.rb

diff --git a/test/modules/post/test/cmd_exec.rb b/test/modules/post/test/cmd_exec.rb
index 1456f9b49b..45970b4c44 100644
--- a/test/modules/post/test/cmd_exec.rb
+++ b/test/modules/post/test/cmd_exec.rb
@@ -51,10 +51,11 @@ class MetasploitModule < Msf::Post
         output.delete("\r") == "#{test_string}\n#{test_string2}"
       end
 
-      it "should return the result of echo 10 times" do
-        10.times do
+      it "should return the result of echo 500 times" do
+        500.times do |i|
           test_string = Rex::Text.rand_text_alpha(4)
           output = cmd_exec("echo #{test_string}")
+          puts "Echo ##{i}"
           return false unless output == test_string
         end
         true
```

</details>

**Comment by bwatters-r7** [comment]
This is not a bug, but a limitation.  We're hitting the target kernel's limits of file descriptors, so short of tracking the number of open file descriptors and staying below that, we can't fix this.

**Comment by adfoster-r7** [comment]
Looks like a file descriptor leak to me; Verified with:

Generate payload and create the handler:

```
msf6 payload(osx/x64/meterpreter/reverse_tcp) > generate lhost=192.168.123.1 -f macho -o shell
[*] Writing 17204 bytes to shell...
msf6 payload(osx/x64/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 192.168.123.1:4444 
```

Execute the payload:
```
chmod +x ./shell
./shell
```

Grab the pid:
```
$ pgrep shell
80938
```

Grab the list of open files:
```
lsof -p 80938
COMMAND   PID     USER   FD   TYPE             DEVICE SIZE/OFF                NODE NAME
shell   80938 user       cwd    DIR                1,4     2688              824906 /Users/adfoster/Documents/code/metasploit-framework
shell   80938 user      txt    REG                1,4    17204           105799530 /Users/adfoster/Documents/code/metasploit-framework/shell
shell   80938 user      txt    REG                1,4  2547856 1152921500312766754 /usr/lib/dyld
shell   80938 user        0u   CHR               16,0    0t593                1585 /dev/ttys000
shell   80938 user        1u   CHR               16,0    0t593                1585 /dev/ttys000
shell   80938 user        2u   CHR               16,0    0t593                1585 /dev/ttys000
shell   80938 user        3u  IPv4 0x55ccb0d1826dcff3      0t0                 TCP 192.168.123.1:65408->192.168.123.1:krb524 (ESTABLISHED)
shell   80938 user        4   PIPE 0xdcc716983e3ff8c1    16384                     ->0x6034dcb9c91d10e8
shell   80938 user        5   PIPE 0x6034dcb9c91d10e8    16384                     ->0xdcc716983e3ff8c1
shell   80938 user        6u   CHR               16,0    0t593                1585 /dev/ttys000
shell   80938 user        8u  unix 0x55ccb0d19acef16b      0t0                     ->0x55ccb0d19acef61b
```

Make a note of the starting fd count:
```
lsof -p 80938 | wc -l
      12
```

Jumping to msfconsole and run a command once with `cmd_exec`
```
msf6 post(linux/gather/enum_system) > set session -1
session => -1
msf6 post(linux/gather/enum_system) > irb
[*] Starting IRB shell...
[*] You are in post/linux/gather/enum_system

irb: warn: can't alias ls from irb_ls.
>> cmd_exec('whoami')
=> "user"
>> 
```

Verify the fd count has increased from 12 to 15, as the temporary stdin/stdout/stderr pipes haven't been closed correctly:
```
$ lsof -p 80938 | wc -l
      15

$ lsof -p 80938
... previous fds ommitted ...
shell   80938 user        9   PIPE 0x46f830665be0e5f9    16384                     
shell   80938 user       10   PIPE 0xfa6616f6e655719f    16384                     
shell   80938 user       13   PIPE 0xf3f8773e45de65c7    16384 
```

This looks like a similar bug to the python implementation: https://github.com/rapid7/metasploit-payloads/issues/569

**Comment by bwatters-r7** [comment]
Yup; the pipes are clear as day this morning.  :shrug:  and yup; that's the location in mettle where it loos like a lot of it is happening.

**Comment by bwatters-r7** [comment]
Thoughts....
1) We have a `free_process` method to clean up the process and associated pipes here: https://github.com/rapid7/mettle/blob/706a1319ba399d94469a03b099b366107254eb4b/mettle/src/process.c#L76

I notice that if there is a problem, we're killing the mettle process structs by calling `process_kill`, which has no associated call to `free_process` which I think we should be doing there.  Offhand, I think that's where a few minor fd leaks might come into play.
See https://github.com/rapid7/mettle/blob/706a1319ba399d94469a03b099b366107254eb4b/mettle/src/stdapi/sys/process.c#L321

2) I also think that based on the callbacks listed here 
https://github.com/rapid7/mettle/blob/706a1319ba399d94469a03b099b366107254eb4b/mettle/src/stdapi/sys/process.c#L331
We need to somehow call `free_process` after the channel exits.  I'm pretty sure once the channel is gone, we don't need the process struct.

3) Another interesting issue is that when we call `process_create`, we immediately create and dup the stdin/out/err, but only set the callbacks if it is channelized.  We'll have to make sure that the duped fds get removed from non-channelized processes, too.

**Comment by space-r7** [comment]
Fixed in https://github.com/rapid7/mettle/pull/235
