### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Techymaster** [rapid7/metasploit-framework#17038]
Traceback (most recent call last):
        14: from ./beef:44:in `<main>'
        13: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from /data/data/com.termux/files/home/beef/core/loader.rb:16:in `<top (required)>'
        10: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
         9: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
         8: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
         7: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
         6: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
         5: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
         4: from /data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
         3: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/dm-core-1.2.1/lib/dm-core.rb:3:in `<top (required)>'
         2: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/dm-core-1.2.1/lib/dm-core.rb:3:in `require'
         1: from /data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `<top (required)>'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/bigdecimal/util.rb:9:in `require': dlopen failed: invalid ELF file "/data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so" load segment[8]: p_offset (0x2000) + p_filesz (0x2ec) ( = 0x22ec) past end of file (0x22ec) - /data/data/com.termux/files/usr/lib/ruby/2.6.0/arm-linux-androideabi/bigdecimal/util.so (LoadError)

_Originally posted by @jsn-OO7 in https://github.com/rapid7/metasploit-framework/issues/11492#issuecomment-545089716_

**Comment by Techymaster** [comment]
Iam also facing same issue.... Please help😓
