### ISSUE TITLE
module not found error in msfconsole

### ISSUE THREAD

**Issue by C4ssif3r** [rapid7/metasploit-framework#17151]
Hi rapid7 team !
I have this error when type `msfconsole` in my terminal...
Error :
```
rake aborted!
NoMethodError: undefined method `>' for nil:NilClass
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `each'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `block in require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler.rb:187:in `require'
/usr/share/metasploit-framework/config/application.rb:13:in `<top (required)>'
/usr/share/metasploit-framework/Rakefile:2:in `require'
/usr/share/metasploit-framework/Rakefile:2:in `<top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by bcoles** [comment]
> module not found error in msfconsole

Where does the "module not found" error come from? This message is not shown in the stack trace.

**Comment by kwyxz** [comment]
I am seeing this very same error in the latest Kali Linux trying to initialize the db.
To replicate : msfdb reinit as root.

```
┌──(kwyxz㉿kali)-[~]
└─$ sudo msfdb reinit        
[i] Database already started
[+] Dropping databases 'msf'
[+] Dropping databases 'msf_test'
[+] Dropping database user 'msf'
[+] Deleting configuration file /usr/share/metasploit-framework/config/database.yml
[+] Stopping database
[+] Starting database
[+] Creating database user 'msf'
[+] Creating databases 'msf'
[+] Creating databases 'msf_test'
[+] Creating configuration file '/usr/share/metasploit-framework/config/database.yml'
[+] Creating initial database schema
rake aborted!
NoMethodError: undefined method `>' for nil:NilClass
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `each'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:55:in `block in require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `each'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler/runtime.rb:44:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.3.15/lib/bundler.rb:187:in `require'
/usr/share/metasploit-framework/config/application.rb:13:in `<top (required)>'
/usr/share/metasploit-framework/Rakefile:2:in `require'
/usr/share/metasploit-framework/Rakefile:2:in `<top (required)>'
/usr/share/metasploit-framework/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by gwillcox-r7** [comment]
Not seeing any issues on this on my Ubuntu install, is this still occurring with latest release?

```
~/git/metasploit-framework │master *1 ?16> ./msfdb reinit
[?] Would you like to reinit the webservice? (Not Required) [no]: 
[?] Would you like to delete your existing data and configurations? []: 
Please answer yes or no.
[?] Would you like to delete your existing data and configurations? []: no
Clearing http web data service credentials in msfconsole
Running the 'reinit' command for the database:
MSF web service is no longer running
Existing database found, attempting to start it
Starting database at /home/gwillcox/.msf4/db...success
~/git/metasploit-framework │master *1 ?16 >
```
