### ISSUE TITLE
msfconsole crash at startup

### ISSUE THREAD

**Issue by nsh3ll** [rapid7/metasploit-framework#17326]
## Steps to reproduce

start msfconsole

## Were you following a specific guide/tutorial or reading documentation?

I've searched for something similar, but found nothing.

## Expected behavior

metasploit starts

## Current behavior

crash

### Metasploit version

metasploit v6.2.29-dev-

## Additional Information
at startup metasploit displays the following lines and then crashes
```
/opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/reline-0.3.1/lib/reline/terminfo.rb:106:in `setupterm': The terminal could not be found, or that it is a generic type, having too little information for curses applications to run. (Reline::Terminfo::TerminfoError)
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/reline-0.3.1/lib/reline/ansi.rb:21:in `<class:ANSI>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/reline-0.3.1/lib/reline/ansi.rb:6:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/reline-0.3.1/lib/reline.rb:580:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/irb-1.4.3/lib/irb.rb:13:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/byebug-11.1.3/lib/byebug/commands/irb.rb:4:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/byebug-11.1.3/lib/byebug/commands.rb:20:in `require_relative'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/byebug-11.1.3/lib/byebug/commands.rb:20:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/byebug-11.1.3/lib/byebug/core.rb:10:in `require_relative'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/byebug-11.1.3/lib/byebug/core.rb:10:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:3:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:3:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-byebug-3.9.0/lib/pry-byebug/cli.rb:4:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `load_cli_options'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry/cli.rb:40:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry/cli.rb:40:in `add_plugin_options'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry/cli.rb:134:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/pry-0.13.1/lib/pry.rb:78:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:126:in `run'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```

**Comment by gwillcox-r7** [comment]
@nsh3ll What terminal are you using? If I start the msfconsole on my machine it doesn't crash and this is with the latest code aka 6.2.29-dev-07a91df7a1. I'm not sure if your using some specific terminal that is causing this or how your involking the console but without more detail this is going to be hard to replicate.

**Comment by nsh3ll** [comment]
> @nsh3ll What terminal are you using? If I start the msfconsole on my machine it doesn't crash and this is with the latest code aka 6.2.29-dev-07a91df7a1. I'm not sure if your using some specific terminal that is causing this or how your invoking the console but without more detail this is going to be hard to replicate.

I use kitty, I've already used msf with it without issues. Anyway I've tried to use a different terminal and msf starts  correctly.

**Comment by gwillcox-r7** [comment]
@nsh3ll Given this sounds like a terminal specific issue that was resolved by using a different terminal, which is in line with what the error described about needing a terminal that supports Curses based applications, I'm going to close this issue as resolved for now. If you are still having issues using a more commonly used terminal then I can take another look into this but this sounds like an issue with compatibility support within the Kitty terminal itself, vs an error within Metasploit per say.
