### ISSUE TITLE
Windows Secrets Dump Crashes With Kerberos

### ISSUE THREAD

**Issue by smcintyre-r7** [rapid7/metasploit-framework#17354]
When `SMBAuth` is set to Kerberos and not NTLM, the `windows_secrets_dump` module crashes while cleaning up.

```
[*] 192.168.159.10:445 - Cleaning up...
[-] 192.168.159.10:445 - Auxiliary failed: TypeError no implicit conversion of Array into String
[-] 192.168.159.10:445 - Call stack:
[-] 192.168.159.10:445 -   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/gather/windows_secrets_dump.rb:492:in `concat'
[-] 192.168.159.10:445 -   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/gather/windows_secrets_dump.rb:492:in `print_secret'
[-] 192.168.159.10:445 -   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/gather/windows_secrets_dump.rb:509:in `block in dump_lsa_secrets'
[-] 192.168.159.10:445 -   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/gather/windows_secrets_dump.rb:508:in `each'
[-] 192.168.159.10:445 -   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/gather/windows_secrets_dump.rb:508:in `dump_lsa_secrets'
[-] 192.168.159.10:445 -   /home/smcintyre/Repositories/metasploit-framework.pr/modules/auxiliary/gather/windows_secrets_dump.rb:1071:in `run'
[*] Auxiliary module execution completed
msf6 auxiliary(gather/windows_secrets_dump) > 
```

Tested using changes form PR #17325 but I think they're unrelated. Can't really test master because Kerberos isn't there.

```
commit c6f8bae1ab732bc3de4c8121417824ed04d4866d (HEAD -> pr/17325)
Author: cdelafuente-r7 <cdelafuente-r7@github>
Date:   Fri Dec 2 15:28:08 2022 +0100

    Fix from code review and updates the KrbUseCachedCredentials logic
```

Testing on the latest changes in the kerberos branch (commit 46f7fc928899c0cba6f9f744fb6e94e8ef1de3c6 at this time) causes the same issue to come up.

## Steps to reproduce

How'd you do it?

1. Use the kerberos brach
2. Use the secrets dump module, set all of the options to authenticate using Kerberos
3. Run the module, see it crash

**Comment by adfoster-r7** [comment]
@smcintyre-r7 This is fixed by https://github.com/rapid7/metasploit-framework/pull/17344
