### ISSUE TITLE
Error: apktool execution failed

### ISSUE THREAD

**Issue by tejas051** [rapid7/metasploit-framework#17586]
Using APK template: Flappy_Bird_1.3_Apkpure.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.dotgears.flappybird.wiweo
[*] Loading /tmp/d20230203-2063-ws71dh/original/smali/com/dotgears/flappy/SplashScreen.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20230203-2063-ws71dh/output.apk
[-] I: Using Apktool 2.6.1-dirty
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
        at brut.androlib.meta.YamlStringEscapeUtils.unescapeString(YamlStringEscapeUtils.java:141)
        at brut.androlib.meta.ClassSafeConstructor$ConstructStringEx.construct(ClassSafeConstructor.java:58)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.constructStandardJavaInstance(Constructor.java:452)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructScalar.construct(Constructor.java:403)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
        at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:108)
        at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:81)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:252)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:207)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:358)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:470)
        at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:273)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.androlib.Androlib.build(Androlib.java:280)
        at brut.apktool.Main.cmdBuild(Main.java:255)
        at brut.apktool.Main.main(Main.java:82)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.text.StringEscapeUtils
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 23 more
**Error: apktool execution failed**

**Comment by rudramsaraf** [comment]
I am also getting same error.
Anyone have any fix?

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/text/StringEscapeUtils
        at brut.androlib.meta.YamlStringEscapeUtils.unescapeString(YamlStringEscapeUtils.java:141)        at

**Comment by TOXICCODER5715** [comment]
After trying all the solutions possible, I am still getting ERROR: apktool execution failed. Please help me to fix this problem because none of the solutions are working.

**Comment by DanVidLop** [comment]
I had the same problem using Kali. The apache common text library at /usr/share/apktool points to ../java/commons-text-1.9, but the library located at ../java is commons-text-1.10. So, it is enough to create the symlink to commons-text-1.10 and delete commons-text-1.9 at /usr/share/apktool.

I hope this helps you.

**Comment by bcoles** [comment]
Based on the above, this seems like an issue with apktool environment.

The error is raised by apktool. There's not much Metasploit can do about this, as a valid apktool environment is required.

**Comment by sandeep7349** [comment]
> 

its not workd bruhh

**Comment by Haaarshit010** [comment]
Can anyone fix it?

**Comment by bcoles** [comment]
Ensure you're using apktool 2.7+

**Comment by Haaarshit010** [comment]
Yup it was latest version bro but still the error is not fixed I've created an issue on GitHub of apktool and I got the answer from ibotpeaches which I didn't understanded please anyone has any idea of coding or these type of things so check this
https://github.com/iBotPeaches/Apktool/issues/3468

**Comment by bcoles** [comment]
> Yup it was latest version bro but still the error is not fixed I've created an issue on GitHub of apktool and I got the answer from ibotpeaches which I didn't understanded please anyone has any idea of coding or these type of things so check this [iBotPeaches/Apktool#3468](https://github.com/iBotPeaches/Apktool/issues/3468)

This thread is about a different issue. Your bug on the Apktool issue tracker is different. There is no fix.
