### ISSUE TITLE
APKTOOL excecution failed:  Not a valid dex magic value

### ISSUE THREAD

**Issue by J-P57** [rapid7/metasploit-framework#17631]
Using APK template: ES.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[-] I: Using Apktool 2.7.0 on original.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes2.dex...
I: Baksmaling assets/39285EFA.dex...
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd
        at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:93)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:157)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:81)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:184)
        at org.jf.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:181)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:89)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:103)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:151)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Error: apktool execution failed

**Comment by NightRidder-pixel** [comment]
Hey their..
For solving this problem you have to do a few things
1.  Install termux again
2. Install only apktool snapchat latest version
3. Then install metasploit.
4. If this error still comes then just change downloading site cz this apk is already patched and its a virus for your phone...
5. Thanks
6. Orr some apps may not compatible with repatching or modification..

**Comment by J-P57** [comment]
This error occurred in Kali Linux not in termux..

**Comment by bcoles** [comment]
This error is occurring as `assets/39285EFA.dex` is not a valid DEX file. `apktool` attempts to decompile all DEX files, including any DEX files in the `assets` directory, regardless of whether they are valid DEX files. (https://github.com/iBotPeaches/Apktool/issues/2461)

Can you tell me which APK you are using?

Alternatively, can you try again with the following diff applied, and verify that the APK is recompiled and recompiled successfully, and that the generated APK file successfully executes and returns a session?

```diff
diff --git a/lib/msf/core/payload/apk.rb b/lib/msf/core/payload/apk.rb
index f749bff18c..bf6e3ae191 100644
--- a/lib/msf/core/payload/apk.rb
+++ b/lib/msf/core/payload/apk.rb
@@ -295,7 +295,7 @@ class Msf::Payload::Apk
     end
 
     print_status "Decompiling original APK..\n"
-    apktool_output = run_cmd(['apktool', 'd', "#{tempdir}/original.apk", '-o', "#{tempdir}/original"])
+    apktool_output = run_cmd(['apktool', 'd', "#{tempdir}/original.apk", '--only-main-classes', '-o', "#{tempdir}/original"])
     check_apktool_output_for_exceptions(apktool_output)
 
     print_status "Decompiling payload APK..\n"
```
