### ISSUE TITLE
linux/x64/shell_reverse_ipv6_tcp / linux/x86/shell_reverse_tcp_ipv6 crash on info

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#17766]
## Steps to reproduce

When running the info command:

```
msf6 payload(linux/x64/shell_reverse_ipv6_tcp) > info
[-] Error while running command info: invalid address: 192.168.123.1

Call stack:
/Users/user/.rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/ipaddr.rb:598:in `rescue in initialize'
/Users/user/.rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/ipaddr.rb:557:in `initialize'
/Users/user/Documents/code/metasploit-framework/modules/payloads/singles/linux/x64/shell_reverse_ipv6_tcp.rb:53:in `new'
/Users/user/Documents/code/metasploit-framework/modules/payloads/singles/linux/x64/shell_reverse_ipv6_tcp.rb:53:in `generate'
/Users/user/Documents/code/metasploit-framework/lib/msf/core/payload.rb:195:in `size'
/Users/user/Documents/code/metasploit-framework/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/Users/user/Documents/code/metasploit-framework/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/Users/user/Documents/code/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:135:in `print_module_info'
/Users/user/Documents/code/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:159:in `cmd_info'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
/Users/user/Documents/code/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/user/Documents/code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'

```

This might be caused by an edge-case in my default LHOST being set globally to ipv4, but I feel like the `info` command shouldn't crash:

```
msf6 payload(linux/x64/shell_reverse_ipv6_tcp) > show options

Module options (payload/linux/x64/shell_reverse_ipv6_tcp):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   LHOST    192.168.123.1    yes       The listen address (an interface may be specified)

```

```
linux/x64/shell_reverse_ipv6_tcp FAILED!
linux/x86/shell_reverse_tcp_ipv6 FAILED!
```

## Additional Information

```
msf6 payload(linux/x64/shell_reverse_ipv6_tcp) > version
Framework: 6.3.6-dev-daef33fe33
Console  : 6.3.6-dev-daef33fe33
```

**Comment by adfoster-r7** [comment]
Related; The windows payload crashes - most likely due to a similar codepath in the `info` command

```
msf6 payload(cmd/windows/powershell/x64/loadlibrary) > info
[-] Error while running command info: wrong number of arguments (given 1, expected 0)

Call stack:
/Users/user/Documents/code/metasploit-framework/modules/payloads/singles/windows/x64/loadlibrary.rb:57:in `generate'
/Users/user/Documents/code/metasploit-framework/modules/payloads/adapters/cmd/windows/powershell/x64.rb:39:in `generate'
/Users/user/Documents/code/metasploit-framework/lib/msf/core/payload.rb:195:in `size'
/Users/user/Documents/code/metasploit-framework/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/Users/user/Documents/code/metasploit-framework/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/Users/user/Documents/code/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:135:in `print_module_info'
/Users/user/Documents/code/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:159:in `cmd_info'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/Users/user/Documents/code/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
/Users/user/Documents/code/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/user/Documents/code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
```

**Comment by Akhilesh9148** [comment]
I want to work on this issues please assign me this issue
