### ISSUE TITLE
Auxiliary failed: NoMethodError undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by jjack33** [rapid7/metasploit-framework#17790]
I'm attempting to run this on the Vulnhub box 'jangow'
https://www.vulnhub.com/entry/jangow-101,754/

```
msf6 auxiliary(scanner/ftp/ftp_login) > show options 

Module options (auxiliary/scanner/ftp/ftp_login):

   Name              Current Setting                                       Required  Description
   ----              ---------------                                       --------  -----------
   BLANK_PASSWORDS   false                                                 no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                                                     yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false                                                 no        Try each user/password couple stored in the current database
   DB_ALL_PASS       true                                                  no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                                                 no        Add all users in the current database to the list
   DB_SKIP_EXISTING  none                                                  no        Skip existing credentials stored in the current database (Accepted: none, user, user&realm)
   PASSWORD                                                                no        A specific password to authenticate with
   PASS_FILE         /usr/share/seclists/Passwords/probable-v2-top207.txt  no        File containing passwords, one per line
   Proxies                                                                 no        A proxy chain of format type:host:port[,type:host:port][...]
   RECORD_GUEST      false                                                 no        Record anonymous/guest logins to the database
   RHOSTS            10.0.2.10                                             yes       The target host(s), see https://docs.metasploit.com/docs/using-metasploit/basics/using-metasploit.htm
                                                                                     l
   RPORT             21                                                    yes       The target port (TCP)
   STOP_ON_SUCCESS   false                                                 yes       Stop guessing when a credential works for a host
   THREADS           10                                                    yes       The number of concurrent threads (max one per host)
   USERNAME          jangow01                                              no        A specific username to authenticate as
   USERPASS_FILE                                                           no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false                                                 no        Try the username as the password for all users
   USER_FILE                                                               no        File containing usernames, one per line
   VERBOSE           true                                                  yes       Whether to print output for all attempts


View the full module info with the info, or info -d command.

msf6 auxiliary(scanner/ftp/ftp_login) > run

[*] 10.0.2.10:21          - 10.0.2.10:21 - Starting FTP login sweep
[-] 10.0.2.10:21          - Auxiliary failed: NoMethodError undefined method `name' for nil:NilClass
[-] 10.0.2.10:21          - Call stack:
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:155:in `each_username_cred'
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:222:in `prepend_db_usernames'
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/lib/msf/core/auxiliary/auth_brute.rb:66:in `build_credential_collection'
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/modules/auxiliary/scanner/ftp/ftp_login.rb:57:in `run_host'
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:124:in `block (2 levels) in run'
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[-] 10.0.2.10:21          -   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
[*] Auxiliary module execution completed
msf6 auxiliary(scanner/ftp/ftp_login) > msfconsole --version
[-] msfconsole cannot be run inside msfconsole
msf6 auxiliary(scanner/ftp/ftp_login) > version
Framework: 6.3.4-dev
Console  : 6.3.4-dev
msf6 auxiliary(scanner/ftp/ftp_login) > debug
Please provide the below information in any Github issues you open. New issues can be opened here https://github.com/rapid7/metasploit-framework/issues/new/choose
ENSURE YOU HAVE REMOVED ANY SENSITIVE INFORMATION BEFORE SUBMITTING!
```

===8<=== CUT AND PASTE EVERYTHING BELOW THIS LINE ===8<===

##  Module/Datastore

An error occurred when trying to build this section:
<details>
<summary>Collapse</summary>

```
Failed to extract Datastore: NoMethodError - undefined method `empty?' for #<Msf::DataStoreWithFallbacks:0x00007f9e8dc3a4c8 @options={}, @aliases={}, @defaults={}, @user_defined={"HttpTrace"=>"true"}> 
 Call stack:
/usr/share/metasploit-framework/lib/msf/ui/debug.rb:349:in `add_hash_to_ini_group'
/usr/share/metasploit-framework/lib/msf/ui/debug.rb:125:in `datastore'
/usr/share/metasploit-framework/lib/msf/ui/debug.rb:102:in `all'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:347:in `cmd_debug'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:23:in `<main>'
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: Connected to msf. Connection type: postgresql.
```

| ID | Hosts | Vulnerabilities | Notes | Services |
|-:|-:|-:|-:|-:|
| 1 **(Current)** | 1 | 1 | 8 | 2 |
| 2 | 0 | 0 | 0 | 0 |
| **Total (2)** | **1** | **1** | **8** | **2** |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
188    set verbose true
189    run
190    clear
191    show advanced
192    show options
193    set path /site
194    run
195    show options
196    set path /site/
197    run
198    back
199    clear
200    use auxiliary/scanner/ftp/ftp_login
201    show advanced
202    set workspace jangow01
203    ip a
204    set chost 10.0.2.6
205    set cport 1234
206    show options
207    set rhosts 10.0.2.10
208    set username jangow01
209    show options
210    set STOP_ON_SUCCESS true
211    show options
212    set threads 10
213    show options
214    run
215    show advanced
216    set chost
217    unset CPORT
218    unset CHOST
219    set passivemode true
220    run
221    show options
222    set db_all_pass true
223    show options
224    run
225    set pass_file /usr/share/seclists/Passwords/*.txt
226    run
227    set pass_file /usr/share/seclists/Passwords/probable-v2-top.txt
228    run
229    set pass_file /usr/share/seclists/Passwords/probable-v2-top207.txt
230    run
231    show options
232    unset STOP_ON_SUCCESS
233    show options
234    run
235    msfconsole --version
236    version
237    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[03/19/2023 18:51:12] [e(0)] core: Unexpected output running /usr/share/metasploit-framework/modules/auxiliary/scanner/wproxy/att_open_proxy.py:
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

[03/19/2023 18:51:12] [e(0)] core: /usr/share/metasploit-framework/modules/auxiliary/scanner/wproxy/att_open_proxy.py failed to load - LoadError  Try running file manually to check for errors or dependency issues.
[03/19/2023 21:41:47] [e(0)] core: Error running against host 10.0.2.10 - Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::FTP)
[03/19/2023 21:44:49] [e(0)] core: Error running against host 10.0.2.10 - Metasploit::Framework::LoginScanner::Invalid Cred details can't be blank, Cred details can't be blank (Metasploit::Framework::LoginScanner::FTP)
[03/19/2023 22:09:40] [e(0)] core: Thread Exception: ScannerHost(scanner/ftp/ftp_login)-10.0.2.10  critical=false    source:
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:118:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:69:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:09:40] [e(0)] core: Auxiliary failed - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:30:44] [e(0)] core: Thread Exception: ScannerHost(scanner/ftp/ftp_login)-10.0.2.10  critical=false    source:
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:118:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:69:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:30:44] [e(0)] core: Auxiliary failed - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:36:09] [e(0)] core: Thread Exception: ScannerHost(scanner/ftp/ftp_login)-10.0.2.10  critical=false    source:
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:118:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:69:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:36:09] [e(0)] core: Auxiliary failed - NoMethodError undefined method `name' for nil:NilClass
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
/usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:118:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:69:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:09:40] [e(0)] core: Auxiliary failed - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:30:44] [e(0)] core: Thread Exception: ScannerHost(scanner/ftp/ftp_login)-10.0.2.10  critical=false    source:
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:118:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:69:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:30:44] [e(0)] core: Auxiliary failed - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:36:09] [e(0)] core: Thread Exception: ScannerHost(scanner/ftp/ftp_login)-10.0.2.10  critical=false    source:
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:118:in `block in run'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `loop'
    /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:101:in `run'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:178:in `job_run_proc'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:85:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/base/simple/auxiliary.rb:96:in `run_simple'
    /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/auxiliary.rb:69:in `cmd_run'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
    /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
    /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:168:in `run'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
    /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
    /usr/bin/msfconsole:23:in `<main>' - NoMethodError undefined method `name' for nil:NilClass
[03/19/2023 22:36:09] [e(0)] core: Auxiliary failed - NoMethodError undefined method `name' for nil:NilClass
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.4-dev
Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
OpenSSL: OpenSSL 3.0.7 1 Nov 2022
Install Root: /usr/share/metasploit-framework
Session Type: Connected to msf. Connection type: postgresql.
Install Method: Other - Please specify
```

</details>

msf6 auxiliary(scanner/ftp/ftp_login) >

**Comment by adfoster-r7** [comment]
For when someone looks into this; it's potentially a regression introduced by - https://github.com/rapid7/metasploit-framework/commit/c4b2288f52ba48229226e7ecdba60fe10ec2e61b

**Comment by adfoster-r7** [comment]
@jjack33 Looks like this is caused by setting the workspace to a value that doesn't exist

Just to confirm, it looks like you've run this with `set workspace jangow01` - was that intentional?

Does it align with the output of the `workspace` command?

```
msf6 payload(windows/meterpreter/reverse_tcp) > workspace
* default
```

**Comment by jjack33** [comment]
That is correct. I set the workspace intentionally, thinking it would also 'add workspace jangow01'

Thanks, I'll make the correction there and try it again.

Sent from Proton Mail mobile

-------- Original Message --------
