### ISSUE TITLE
Rails Error when creating new user using createuser

### ISSUE THREAD

**Issue by mai1x9** [rapid7/metasploit-framework#18037]
Below, is the error when running `createuser` command, I have done cd into metasploit, 
```
cd /opt/metasploit
./createuser
```
and it throws below error,
```
Rails Error: Unable to access log file. Please ensure that /opt/metasploit/apps/pro/ui/log/production.log exists and is writable (i.e. make it writable for user and group: chmod 0664 /opt/metasploit/apps/pro/ui/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
/opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:39:in `read': Cannot load database configuration: (Errno::EACCES)
Permission denied @ rb_sysopen - /opt/metasploit/apps/pro/ui/config/database.yml
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:39:in `read'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:14:in `initialize'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:18:in `new'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:18:in `parse'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/application/configuration.rb:335:in `database_configuration'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.3/lib/active_record/railtie.rb:266:in `block (2 levels) in <class:Railtie>'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:59:in `each'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.3/lib/active_record/railtie.rb:262:in `block in <class:Railtie>'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `public_send'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `method_missing'
        from /opt/metasploit/apps/pro/ui/config/environment.rb:5:in `<top (required)>'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
        from /opt/metasploit/apps/pro/ui/script/createuser:33:in `<main>'
/opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:39:in `read': Permission denied @ rb_sysopen - /opt/metasploit/apps/pro/ui/config/database.yml (Errno::EACCES)
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:39:in `read'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:14:in `initialize'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:18:in `new'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/configuration_file.rb:18:in `parse'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/application/configuration.rb:335:in `database_configuration'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.3/lib/active_record/railtie.rb:266:in `block (2 levels) in <class:Railtie>'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:95:in `class_eval'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:95:in `block in execute_hook'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:85:in `with_execution_control'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:90:in `execute_hook'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:60:in `block in on_load'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:59:in `each'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.4.3/lib/active_support/lazy_load_hooks.rb:59:in `on_load'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.4.3/lib/active_record/railtie.rb:262:in `block in <class:Railtie>'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /opt/metasploit/ruby/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `public_send'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/railtie.rb:226:in `method_missing'
        from /opt/metasploit/apps/pro/ui/config/environment.rb:5:in `<top (required)>'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /opt/metasploit/apps/pro/vendor/bundle/ruby/3.0.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
        from /opt/metasploit/apps/pro/ui/script/createuser:33:in `<main>'
```

**Comment by UtkarshDhagat** [comment]
The error message indicates that there is a permission issue with accessing the log file and the database configuration file in the Metasploit Pro application. To resolve this issue, you need to make sure that the necessary files and directories have the correct permissions.

Here are the steps you can follow:

1. Change the directory to the Metasploit Pro installation directory:
```
cd /opt/metasploit
```

2. Grant write permissions to the log file:
```
chmod 0664 apps/pro/ui/log/production.log
```

3. Grant read permissions to the database configuration file:
```
chmod 0644 apps/pro/ui/config/database.yml
```

4. Retry running the `createuser` command.

These commands will change the permissions of the specified files to allow the current user and group to read and write to the log file and read the database configuration file. After making these changes, you should be able to run the `createuser` command without the permission denied error.

**Comment by mai1x9** [comment]
the issue haven't been closed yet.  Set label to not stale.

**Comment by adfoster-r7** [comment]
This is an issue tracker for Metasploit Framework. We do not provide support for Metasploit Pro here or via Slack. Please contact your assigned support provider at https://www.rapid7.com/for-customers/ for help with Metasploit Pro as we are unable to provide assistance via these channels.

**Comment by mai1x9** [comment]
> The error message indicates that there is a permission issue with accessing the log file and the database configuration file in the Metasploit Pro application. To resolve this issue, you need to make sure that the necessary files and directories have the correct permissions.
> 
> Here are the steps you can follow:
> 
> 1. Change the directory to the Metasploit Pro installation directory:
> 
> ```
> cd /opt/metasploit
> ```
> 
> 2. Grant write permissions to the log file:
> 
> ```
> chmod 0664 apps/pro/ui/log/production.log
> ```
> 
> 3. Grant read permissions to the database configuration file:
> 
> ```
> chmod 0644 apps/pro/ui/config/database.yml
> ```
> 
> 4. Retry running the `createuser` command.
> 
> These commands will change the permissions of the specified files to allow the current user and group to read and write to the log file and read the database configuration file. After making these changes, you should be able to run the `createuser` command without the permission denied error.

Thank you for the inputs will try and let you know if it's resolved. sorry I have skipped the message and have checked now, my had.

**Comment by adfoster-r7** [comment]
I'm not sure if granting global read access to your database configuration file is a valid solution

**Comment by mai1x9** [comment]
> I'm not sure if granting global read access to your database configuration file is a valid solution

In that case, the issue must be open. Isn't the error generated by open source metasploit tool not the pro version.

**Comment by mai1x9** [comment]
> This error is not from the open-source tool, as noted in the stack trace this is a `Pro` install `metasploit/apps/pro` is a path that only exists when installing from the [Pro packaging](https://docs.metasploit.com/docs/development/maintainers/downloads-by-version.html) not the [Framework packaging](https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html).
> 
> Documentation for `Pro` offers [an example](https://docs.rapid7.com/metasploit/installing-metasploit-pro/#creating-a-user-account-on-headless-servers) showing the `createuser` command requires `sudo` or `root` privilege to execute successfully.

sorry my bad will check open source  version. Thank you.
