### ISSUE TITLE
Running info on fetch payloads fails with "You must set FETCH_SRVHOST to a routable IP"

### ISSUE THREAD

**Issue by smcintyre-r7** [rapid7/metasploit-framework#18048]
Run `info payload/cmd/windows/tftp/x64/vncinject/reverse_winhttp` and you'll see the error. I'm pretty sure this affects all the fetch payloads because of how they all share the `FETCH_SRVHOST` datastore option. We'll likely need to move the validation of that option so that the information can be displayed to the user.

```
msf6 > info payload/cmd/windows/tftp/x64/vncinject/reverse_winhttp
[-] Error while running command info: You must set FETCH_SRVHOST to a routable IP

Call stack:
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/payload/adapter/fetch.rb:35:in `check_srvhost'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/payload/adapter/fetch.rb:97:in `generate'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/core/payload.rb:195:in `size'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:135:in `print_module_info'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:190:in `block in cmd_info'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:170:in `each'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/msf/ui/console/command_dispatcher/modules.rb:170:in `cmd_info'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/rex/ui/text/shell.rb:168:in `run'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/command/console.rb:48:in `start'
/home/smcintyre/Repositories/metasploit-framework.pr/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
msf6 > 
```

**Comment by bwatters-r7** [comment]
We fixed this bug, then I re-added it in a later fix for something else 😆
