### ISSUE TITLE
 invalid byte sequence in UTF-8 (ArgumentError) | On Windows 10

### ISSUE THREAD

**Issue by LelouchFR** [rapid7/metasploit-framework#18352]
## Steps to reproduce

How'd you do it?

- Installed Metasploit from [https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html](https://docs.metasploit.com/docs/using-metasploit/getting-started/nightly-installers.html) for Windows because I'm on Windows 10
- Shutdown Firewalls
- Launched the Wizard
- Waited for Metasploit to end the installing
- At the end, tested to launch `msfconsole` and it gives me an error

I'm on Windows 10.0.19045 Build 19045 using Microsoft Windows 10 Professionel Education.
I used the build `Metasploit-framework v6.3.33`.

## Expected behavior

Should open me the `msfconsole` correctly instead of throwing an error

## Current behavior

Tried to launch the `msfconsole` from the command prompt but got this error instead:

```
C:\Users\Admin>msfconsole

C:/metasploit-framework/embedded/lib/ruby/3.0.0/pathname.rb:50:in `match?': invalid byte sequence in UTF-8 (ArgumentError)

from C:/metasploit-framework/embedded/lib/ruby/3.0.0/pathname.rb:50:in `chop_basename'

from C:/metasploit-framework/embedded/lib/ruby/3.0.0/pathname.rb:374:in `plus'

from C:/metasploit-framework/embedded/lib/ruby/3.0.0/pathname.rb:354:in `+'

from C:/metasploit-framework/embedded/lib/ruby/3.0.0/pathname.rb:420:in `join'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:245:in `block in user_bundle_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:257:in `fetch'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:257:in `user_bundle_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:249:in `block in user_bundle_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:257:in `fetch'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:257:in `user_bundle_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/settings.rb:382:in `global_config_file'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/settings.rb:80:in `initialize'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:317:in `new'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:317:in `settings'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:99:in `configured_bundle_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:455:in `use_system_gems?'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:645:in `configure_gem_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:638:in `configure_gem_home_and_path'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:81:in `configure'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:194:in `definition'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler.rb:143:in `setup'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `block in <top (required)>'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'

from C:/metasploit-framework/embedded/lib/ruby/gems/3.0.0/gems/bundler-2.1.4/lib/bundler/setup.rb:10:in `<top (required)>'

from <internal:C:/metasploit-framework/embedded/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

from <internal:C:/metasploit-framework/embedded/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

from C:/metasploit-framework/embedded/framework/config/boot.rb:26:in `<top (required)>'

from <internal:C:/metasploit-framework/embedded/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

from <internal:C:/metasploit-framework/embedded/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'

from C:/metasploit-framework/bin/../embedded/framework/msfconsole:17:in `<main>'
```

### Metasploit version

I used the build `Metasploit-framework v6.3.33`.

**Comment by adfoster-r7** [comment]
I think based on the error, potentially there are files on the file system with invalid byte code sequences - is your host machine in a difference language maybe?

**Comment by LelouchFR** [comment]
What do you mean by that ?

**Comment by adfoster-r7** [comment]
What language pack is your windows host using?

**Comment by LelouchFR** [comment]
How to know that ?
