### ISSUE TITLE
`msfdb init` and `msfdb reinit` hang on "Verifying msfconsole data service"

### ISSUE THREAD

**Issue by dreshfield** [rapid7/metasploit-framework#18459]
## Steps to reproduce

How'd you do it?

1. Run `msfdb init` (and, when that didn't work, `msfdb reinit`)

**OS:** MacOS Sonoma 14.0
**Shell:** Bash 5.2.15(1)-release (installed through Homebrew)
**Postgres:** 16.0 (Homebrew)

## Were you following a specific guide/tutorial or reading documentation?

No.

## Expected behavior

I should get the prompt to set up the `msf` user and database.

## Current behavior

My shell hangs at `Verifying msfconsole data service`. I waited for it to resolve for 30 minutes before sending an interrupt.

### Metasploit version

`6.3.39-dev-ec5648f6c50fc0af779f3b2a3ac7afa9fdca9344` (installed through Homebrew)

## Additional information

Running `msfdb --debug init` only additionally prints `run_cmd: cmd=msfconsole -qx 'db_disconnect --clear; exit', input=, env={}` before hanging.

Sending a SIGINT during this yields the following:
```
#<Thread:0x00000001158ef920 /opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:403 run> terminated with exception (report_on_exception is true):
/opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:403:in `read': stream closed in another thread (IOError)
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:403:in `block (2 levels) in capture2e'
/opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:415:in `value': Interrupt
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:415:in `block in capture2e'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:227:in `popen_run'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/open3.rb:398:in `capture2e'
	from /opt/metasploit-framework/embedded/framework/lib/msfdb_helpers/db_interface.rb:55:in `run_cmd'
	from msfdb:660:in `run_msfconsole_command'
	from msfdb:679:in `clear_default_data_service'
	from msfdb:1061:in `<main>'
```

Because running `msfconsole` without `sudo` yields the same behavior as described above, I tried running `sudo msfdb init`, which simply tells me to re-run the command as a non-root user.

**Comment by dreshfield** [comment]
Bizarrely, just a minute or two after interrupting the `msfdb init` process in one terminal window, the `msfconsole` command I apparently had running in another terminal window resolved with `Existing database running` and entered me right into the console. `db_status` shows it is indeed connected to `msf` with connection type `postgresql`. Running `msfconsole` in the original terminal window yields the same result. Not sure what happened, but since this seems solved, I'll close this out.

**Comment by ClutchReboot** [comment]
Not sure if this should be closed yet. If a user disconnects from the db mid session or scan like using `ctrl + c`, they'll get this behavior all over again.

**Comment by ClutchReboot** [comment]
When rolling back this specific commit, starting msfconsole works as expected with no hang ups.

https://github.com/rapid7/metasploit-framework/commit/0875cc8f7349901f23e820e0f1720ba2c8ca0e24

**Comment by dreshfield** [comment]
Reopening, per the above.

**Comment by adfoster-r7** [comment]
I believe this should be fixed by https://github.com/rapid7/metasploit-framework/pull/18479

**Comment by 0xJustus** [comment]
I have been experiencing this same issue on Linux Mint. Checking in system monitor after executing `msfconsole` reveals multiple `msfdb` and `msfconsole` processes spawning indefinitely, leading to an eventual crash.

**Comment by adfoster-r7** [comment]
Does this patch work for you @0xJustus https://github.com/rapid7/metasploit-framework/pull/18479

**Comment by 0xJustus** [comment]
> Does this patch work for you @0xJustus #18479

Yes, I confirmed the patch fixes the issue!

**Comment by ClutchReboot** [comment]
> Does this patch work for you @0xJustus #18479

This patch also works for me. Ty!

**Comment by bruno-1337** [comment]
Maybe theres also a memory leak, when I use any command on msfdb such as init, restart or anything else, it displays a message "Verifying msfconsole data service" and launches several processes of msfconsole and msfdb. This continues until the computer runs out of resources. (Using the latest version of the metasploit framework)

**Comment by 0xJustus** [comment]
@bruno-1337 try applying the patch in #18479 for the time being.

**Comment by Ahmed3457** [comment]
update: same keeps spawning multiple msfdb and msfconsole processes as shown on htop and almost consuming all the available ram.

**Comment by adfoster-r7** [comment]
This should be fixed in the latest version 6.3.41 now

**Comment by Ahmed3457** [comment]
working alright after updating to the latest version. ty

**Comment by serome111** [comment]
on m1 my solution are:
`arch -arm64 brew reinstall --cask metasploit`
