### ISSUE TITLE
The enum_chrome module crashes when run as SYSTEM

### ISSUE THREAD

**Issue by smcintyre-r7** [rapid7/metasploit-framework#18559]
When running the `post/windows/gather/enum_chrome` module, it will crash when run as `NT 
AUTHORITY\SYSTEM`. I noticed this issue while making the changes in #18558. After the module fails, it should also be noted that the sessions is left in a pretty unusable state until the user runs `rev2self` to revert the `steal_token` call.

The target is a 64-bit Server 2019 instance and the changes from #18558 are loaded on my test branch.
```
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 9
Meterpreter     : x64/windows
meterpreter > run post/windows/gather/enum_chrome

[*] Impersonating token: 1332
[-] Cannot impersonate: stdapi_sys_config_steal_token: Operation failed: Access is denied.
[-] Post failed: Rex::Post::Meterpreter::RequestError stdapi_sys_config_getsid: Operation failed: Access is denied.
[-] Call stack:
[-]   /home/smcintyre/Repositories/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/config.rb:46:in `getsid'
[-]   /home/smcintyre/Repositories/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/sys/config.rb:54:in `is_system?'
[-]   /home/smcintyre/Repositories/metasploit-framework/lib/msf/core/post/windows/priv.rb:128:in `is_system?'
[-]   /home/smcintyre/Repositories/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:349:in `run'
meterpreter > getuid
[-] stdapi_sys_config_getuid: Operation failed: Access is denied.
meterpreter > sysinfo
[-] stdapi_sys_config_getuid: Operation failed: Access is denied.
meterpreter > rev2self
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 9
Meterpreter     : x64/windows
meterpreter > 
```

After implementing the following quick workaround the module runs as `NT AUTHORITY\SYSTEM` but with a warning about automatic decryption not being possible. The module also works as intended after migrating into a process running as a local admin.

```
diff --git a/modules/post/windows/gather/enum_chrome.rb b/modules/post/windows/gather/enum_chrome.rb
index 6e7e169425..181d87028c 100644
--- a/modules/post/windows/gather/enum_chrome.rb
+++ b/modules/post/windows/gather/enum_chrome.rb
@@ -326,9 +326,9 @@ class MetasploitModule < Msf::Post
 
     # If we can impersonate a token, we use that first.
     # If we can't, we'll try to MIGRATE (more aggressive) if the user wants to
-    got_token = steal_token
+    got_token = false # steal_token
     if !got_token && datastore['MIGRATE']
-      migrate_success = migrate
+      migrate_success = false # migrate
     end
 
     host = session.session_host
```

<details>
<summary>Testing Output</summary>

```
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > sysinfo
Computer        : DC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
Logged On Users : 9
Meterpreter     : x64/windows
meterpreter > run post/windows/gather/enum_chrome

[*] Running as SYSTEM, extracting user list...
[!] (Automatic decryption will not be possible. You might want to manually migrate, or set "MIGRATE=true")
[*] Users found: smcintyre
[*] Extracting data for user 'smcintyre'...
[+] Downloaded Web Data to '/home/smcintyre/.msf4/loot/20231120171644_default_192.168.159.10_chrome.raw.WebD_079520.txt'
[-] Cookies not found
[+] Downloaded History to '/home/smcintyre/.msf4/loot/20231120171645_default_192.168.159.10_chrome.raw.Histo_048081.txt'
[+] Downloaded Login Data to '/home/smcintyre/.msf4/loot/20231120171646_default_192.168.159.10_chrome.raw.Login_624182.txt'
[-] Bookmarks not found
[+] Downloaded Preferences to '/home/smcintyre/.msf4/loot/20231120171646_default_192.168.159.10_chrome.raw.Prefe_808569.txt'
[*] Extensions installed: 
[*] => Web Store
[*] => Google Docs Offline
[*] => Chrome PDF Viewer
[*] => Google Network Speech
[*] => Google Hangouts
[*] => Chrome Web Store Payments
meterpreter > 
```
</details>

I'm not sure why the token impersonation or automatic migration is required. But it looks like removing it causes the module work work as I would expect it to work. It should be noted that if the session is running as SYSTEM and the module migrates into a process running as a user, it won't be able to migrate back into the SYSTEM process due to the loss of privileges. My guess is that the `MIGRATE` option was originally intended to be used to migrate into the `explorer.exe` process owned by the current non-SYSTEM user.

Further testing for edge cases should probably take place before just removing the token impersonation and migration logic.

**Comment by kx7m2qd** [comment]
Hi @smcintyre-r7, I'd like to work on this. Based on the issue description and the code, I can see the crash happens because steal_token fails when running as SYSTEM, leaving the token in a broken state which causes the subsequent is_system? call to also fail with "Access is denied".

My plan is to:
- Check is_system? before attempting steal_token and skip it if already SYSTEM
- Track whether a token was stolen with @token_stolen
- Add a cleanup method that calls revert_to_self if a token was stolen, following the pattern used in post/multi/manage/zip.rb

Happy to open a PR if this approach sounds reasonable.
