### ISSUE TITLE
System Stack Error

### ISSUE THREAD

**Issue by edwin-liew** [rapid7/metasploit-framework#18639]
Today, i did an upgrade via kali. 

I hit the following errors. Any advise please? 

Thank you.

Ed

```
/opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:622:in `match': stack level too deep (SystemStackError)
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:622:in `block in in_addr'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:620:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:620:in `inject'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:620:in `in_addr'
	from /opt/metasploit-framework/embedded/lib/ruby/3.0.0/ipaddr.rb:580:in `initialize'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:332:in `new'
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:332:in `block in nameservers='
	from /opt/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:328:in `each'
	... 11217 levels...
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `driver'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```

**Comment by dwelch-r7** [comment]
Looks like the same/similar issue as to here #18624

**Comment by adfoster-r7** [comment]
Hi there, could you add logging to your framework like this:

https://github.com/rapid7/metasploit-framework/issues/18574#issuecomment-1865029818

And let us know what the results are

**Comment by edwin-liew** [comment]
hi guys, 

looks like it is working fine now. I did another update this morning and the errors no longer appear. It looks like it is updating some libraries. 

Thank you for responding and Merry Christmas!

**Comment by kishwordulal1234** [comment]
i also have same issue did you fix it
