### ISSUE TITLE
Stacktrace on `show info`

### ISSUE THREAD

**Issue by jvoisin** [rapid7/metasploit-framework#18788]
## Steps to reproduce

```
msf6 payload(cmd/linux/https/x64/meterpreter/bind_tcp) > version
Framework: 6.3.55-dev-aec2a82af4
Console  : 6.3.55-dev-aec2a82af4
msf6 > use payload/cmd/linux/https/x64/meterpreter/bind_tcp
msf6 payload(cmd/linux/https/x64/meterpreter/bind_tcp) > show info 
[-] Error while running command show: bad-config: FETCH_SRVHOST required

Call stack:
/home/jvoisin/dev/metasploit-framework/lib/msf/core/module.rb:319:in `fail_with'
/home/jvoisin/dev/metasploit-framework/lib/msf/core/payload/adapter/fetch.rb:82:in `generate'
/home/jvoisin/dev/metasploit-framework/lib/msf/core/payload.rb:195:in `size'
/home/jvoisin/dev/metasploit-framework/lib/msf/base/serializer/readable_text.rb:500:in `dump_payload_module'
/home/jvoisin/dev/metasploit-framework/lib/msf/base/serializer/readable_text.rb:26:in `dump_module'
/home/jvoisin/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:138:in `print_module_info'
/home/jvoisin/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:178:in `cmd_info'
/home/jvoisin/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:688:in `block in cmd_show'
/home/jvoisin/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:661:in `each'
/home/jvoisin/dev/metasploit-framework/lib/msf/ui/console/command_dispatcher/modules.rb:661:in `cmd_show'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:581:in `run_command'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:530:in `block in run_single'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `each'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:524:in `run_single'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/shell.rb:165:in `block in run'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/shell.rb:309:in `block in with_history_manager_context'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/shell/history_manager.rb:33:in `with_context'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/shell.rb:306:in `with_history_manager_context'
/home/jvoisin/dev/metasploit-framework/lib/rex/ui/text/shell.rb:133:in `run'
/home/jvoisin/dev/metasploit-framework/lib/metasploit/framework/command/console.rb:54:in `start'
/home/jvoisin/dev/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:23:in `<main>'
msf6 payload(cmd/linux/https/x64/meterpreter/bind_tcp) > 
```

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
The local config file is empty, no global variables are set, and there is no active module.
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: postgresql selected, no connection
```

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```

```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[02/05/2024 16:37:17] [e(0)] core: Failed to connect to the database: No database YAML file
[02/05/2024 16:37:18] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:37:18] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:37:20] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/05/2024 16:37:22] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/05/2024 16:40:14] [e(0)] core: Failed to connect to the database: No database YAML file
[02/05/2024 16:40:15] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:40:15] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:40:17] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/05/2024 16:40:18] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[02/05/2024 16:27:33] [e(0)] core: Failed to connect to the database: No database YAML file
[02/05/2024 16:27:35] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:27:35] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:27:37] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/05/2024 16:27:39] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/05/2024 16:36:54] [w(0)] core: Failed to reload: undefined method `loader' for Object:Class
[02/05/2024 16:37:17] [e(0)] core: Failed to connect to the database: No database YAML file
[02/05/2024 16:37:18] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:37:18] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:37:20] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/05/2024 16:37:22] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[02/05/2024 16:40:14] [e(0)] core: Failed to connect to the database: No database YAML file
[02/05/2024 16:40:15] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:40:15] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[02/05/2024 16:40:17] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[02/05/2024 16:40:18] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.3.55-dev-aec2a82af4
Ruby: ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
OpenSSL: OpenSSL 1.1.1w  11 Sep 2023
Install Root: /home/jvoisin/dev/metasploit-framework
Session Type: postgresql selected, no connection
Install Method: Git Clone
```

</details>

**Comment by adfoster-r7** [comment]
Thanks for the error report; Looks like it will be fixed by https://github.com/rapid7/metasploit-framework/pull/18664 :+1:

**Comment by nrathaus** [comment]
Can be closed:

```
msf6 > version
Framework: 6.4.1-dev-
Console  : 6.4.1-dev-
msf6 > use payload/cmd/linux/https/x64/meterpreter/bind_tcp
msf6 payload(cmd/linux/https/x64/meterpreter/bind_tcp) > show info 

       Name: HTTPS Fetch, Bind TCP Stager
     Module: payload/cmd/linux/https/x64/meterpreter/bind_tcp
   Platform: Linux, Linux
       Arch: cmd
Needs Admin: No
 Total size: 125
       Rank: Normal

Provided by:
  Brendan Watters
  Brent Cook <bcook@rapid7.com>
  ricky

Basic options:
Name                Current Setting  Required  Description
----                ---------------  --------  -----------
FETCH_CHECK_CERT    false            yes       Check SSL certificate
FETCH_COMMAND       CURL             yes       Command to fetch payload (Accep
                                               ted: CURL, FTP, TFTP, TNFTP, WG
                                               ET)
FETCH_DELETE        false            yes       Attempt to delete the binary af
                                               ter execution
FETCH_FILENAME      steLUrpxEmy      no        Name to use on remote system wh
                                               en storing payload; cannot cont
                                               ain spaces or slashes
FETCH_SRVHOST                        yes       Local IP to use for serving pay
                                               load
FETCH_SRVPORT       8080             yes       Local port to use for serving p
                                               ayload
FETCH_URIPATH                        no        Local URI to use for serving pa
                                               yload
FETCH_WRITABLE_DIR  /tmp             yes       Remote writable dir to store pa
                                               yload; cannot contain spaces
LPORT               4444             yes       The listen port
RHOST                                no        The target address

Description:
  Fetch and execute an x64 payload from an HTTPS server.
  Listen for a connection



View the full module info with the info -d command.
```

**Comment by adfoster-r7** [comment]
Thanks for the confirmation! :+1:
