### ISSUE TITLE
Armitage: Auxiliary failed: Net::SSH::Disconnect connection closed by remote host

### ISSUE THREAD

**Issue by alyaparan** [rapid7/metasploit-framework#18991]
```
msf6 auxiliary(scanner/ssh/ssh_version) > run -j
[*] Auxiliary module running as background job 19.
[-] Auxiliary failed: Net::SSH::Disconnect connection closed by remote host
[-] Call stack:
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:57:in `rescue in block (2 levels) in negotiate!'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:53:in `block (2 levels) in negotiate!'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:52:in `loop'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:52:in `block in negotiate!'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:50:in `loop'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:50:in `negotiate!'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/server_version.rb:33:in `initialize'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:85:in `new'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:85:in `initialize'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_version.rb:224:in `new'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_version.rb:224:in `block in run_host'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:41:in `handle_timeout'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/timeout-0.4.1/lib/timeout.rb:195:in `timeout'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_version.rb:223:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:128:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:105:in `block in spawn'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/3.1.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by adfoster-r7** [comment]
Does nmap work?

```
nmap -p 22 your_target_here
```
