### ISSUE TITLE
Running Metasploit in WSL Kali Linux throws an error.

### ISSUE THREAD

**Issue by rmenai** [rapid7/metasploit-framework#19011]
## Steps to reproduce

How'd you do it?

1. Install Kali linux WSL.
2. Install the kali-linux-default metapackage.
3. Run msfconsole

## Expected behavior

Metasploit should run normally.

## Current behavior

```
┌──(rami㉿DESKTOP-P12DNFQ)-[~]
└─$ msfconsole
Metasploit tip: Use help <command> to learn more about any command
/opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/static_hostnames.rb:84:in `add': Invalid hostname: DESKTOP-P12DNFQ. (ArgumentError)
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/static_hostnames.rb:48:in `block (2 levels) in parse_hosts_file'
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/static_hostnames.rb:47:in `each'
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/static_hostnames.rb:47:in `block in parse_hosts_file'
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/static_hostnames.rb:42:in `foreach'
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/static_hostnames.rb:42:in `parse_hosts_file'
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:88:in `initialize'
        from /opt/metasploit-framework/embedded/framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:86:in `new'
        from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:86:in `initialize'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```
I should mention that I manually renamed my windows 11 hostname to DESKTOP-P12DNFQ.

### Metasploit version

Framework Version: 6.4.1-dev-

**Comment by rmenai** [comment]
After updating my system this is no longer an issue.
