### ISSUE TITLE
Post failed: NoMethodError undefined method `unpack' for nil:NilClass

### ISSUE THREAD

**Issue by kokxxoo** [rapid7/metasploit-framework#19222]
run  post/windows/gather/hashdump

```
[*] Obtaining the boot key...

[*] Calculating the hboot key using SYSKEY feafa24f2f975fdc62f236r899999999...
[*] Obtaining the user list and keys...
[*] Decrypting user keys...
[-] Post failed: NoMethodError undefined method `unpack' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:261:in `decrypt_user_hash'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:233:in `block in decrypt_user_keys'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:222:in `each_key'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:222:in `decrypt_user_keys'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/hashdump.rb:55:in `run'
```

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```
