### ISSUE TITLE
DNS Resolver crash when starting Metasploit console

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#19464]
## Steps to reproduce

Installed Metasploit framework omnibus installer onto a VM without internet accesss and opened msfconsole:

```
C:\Users\Administrator>msfconsole
C:/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/rex-core-0.1.32/lib/rex/compat.rb:381: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
Metasploit tip: Start commands with a space to avoid saving them to history
C:/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1274:in `valid?': undefined method `=~' for ["localdomain"]:Array (NoMethodError)
        from C:/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:359:in `domain='
        from C:/metasploit-framework/embedded/framework/lib/net/dns/resolver.rb:1084:in `parse_config_file'
        from C:/metasploit-framework/embedded/framework/lib/rex/proto/dns/resolver.rb:66:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/rex/proto/dns/cached_resolver.rb:25:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:86:in `new'
        from C:/metasploit-framework/embedded/framework/lib/msf/ui/console/driver.rb:86:in `initialize'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `new'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:66:in `driver'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
        from C:/metasploit-framework/bin/../embedded/framework/msfconsole:23:in `<main>'
```

![image](https://github.com/user-attachments/assets/410b380d-a7d9-408d-ab9b-a7b0929d53f2)

## Were you following a specific guide/tutorial or reading documentation?

No
## Expected behavior

No crash; potentially a warning - but msfconsole should still open

## Current behavior

Full crash

### Metasploit version

```
v6.4.27-dev
```

**Comment by adfoster-r7** [comment]
Result:

```
msf6 > irb -e 'puts Win32::Resolv.get_resolv_info.inspect'
[["localdomain"], ["192.168.123.2"]]
```

**Comment by cgranleese-r7** [comment]
I happened to hit this today while testing a PR. 

> Installed Metasploit framework omnibus installer onto a VM without internet accesss and opened msfconsole:

Mine was on a WM with internet access, happened on latest but not on the older build (`metasploit-framework-6.4.27-20240915103549-1rapid7-1-x64.msi`)

![image](https://github.com/user-attachments/assets/f62f2258-8593-4596-b99f-ad763a92485a)

**Comment by sfewer-r7** [comment]
I ran into this this morning and have opened a pull request #19474 with a potential solution.

**Comment by smcintyre-r7** [comment]
Closing this since the PR has been merged with the fix.
