### ISSUE TITLE
Java Metasploit payload stdapi_fs_ls error

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-framework#19496]
## Steps to reproduce

When running the Java Meterpreter against a host the following error occurs:

```
payload(java/meterpreter/reverse_tcp) > sessions -i -1
[*] Starting interaction with 2...

meterpreter > cd /
meterpreter > dir
[-] stdapi_fs_ls: Operation failed: 1
meterpreter > 
```

It might be because of the file names on the target:

```
$ ls -la
total 129
-rw-r--r--   1 root root     0 2022-08-22 09:18 ,
drwxr-xr-x  21 root root  4096 2024-08-25 10:01 .
drwxr-xr-x  21 root root  4096 2024-08-25 10:01 ..
...etc...
drwxr-xr-x  13 root root 13740 2022-11-25 02:55 dev
-rw-rw-rw-   1 root root     0 2015-05-28 08:05 ??ǆ????????H,??t?VP???V???????_^?????̋L$??y??u???%??u??AX??t???l??3?Ë????u???؋????????????????h?h?4
-rw-r--r--   1 root root     0 2022-07-17 15:46 *#E
...etc...
-rw-r--r--   1 root root     0 2024-05-13 09:00 ??????????????????????????????????s!
```

## Expected behavior

No error and the files are listed

## Current behavior

An error occurs and the files aren't listed

### Metasploit version

```
Framework: 6.4.25-dev
Console  : 6.4.25-dev
```

**Comment by smcintyre-r7** [comment]
Can you tell us any information about the target? Is it a Windows or a Linux server and what is the character set that's being used? If it's Linux can you check the LC_* variables and if it's Windows, what language pack is in use?

**Comment by dledda-r7** [comment]
I'm trying to replicate the issue locally and I think we are having some issues with the Java Meterpreter in general with some open JDK.

```
msf6 > use java/meterpreter/reverse_tcp
msf6 payload(java/meterpreter/reverse_tcp) > set lhost 127.0.0.1
lhost => 127.0.0.1
msf6 payload(java/meterpreter/reverse_tcp) > to_handler
[*] Payload Handler Started as Job 0
msf6 payload(java/meterpreter/reverse_tcp) > set MeterpreterDebugBuild true
MeterpreterDebugBuild => true
msf6 payload(java/meterpreter/reverse_tcp) > generate -f jar -o /home/kali/Documents/github/pr/19496/metsrv.jar
[*] Writing 5258 bytes to /home/kali/Documents/github/pr/19496/metsrv.jar...
msf6 payload(java/meterpreter/reverse_tcp) > 
[*] Sending stage (57971 bytes) to 127.0.0.1
[*] 127.0.0.1 - Meterpreter session 3 closed.  Reason: Died
[-] Meterpreter session 3 is not valid and will be closed
```

```
──(kali㉿kali)-[~/Documents/github/pr/19496]
└─$ java -jar metsrv.jar 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
                                                                                                                                             
┌──(kali㉿kali)-[~/Documents/github/pr/19496]
└─$ _JAVA_OPTIONS=""                      
                                                                                                                                             
┌──(kali㉿kali)-[~/Documents/github/pr/19496]
└─$ java -jar metsrv.jar
Picked up _JAVA_OPTIONS: 
                                                                                                                                             
┌──(kali㉿kali)-[~/Documents/github/pr/19496]
└─$ java -version       
Picked up _JAVA_OPTIONS: 
openjdk version "23-ea" 2024-09-17
OpenJDK Runtime Environment (build 23-ea+37-Debian-1)
OpenJDK 64-Bit Server VM (build 23-ea+37-Debian-1, mixed mode, sharing)
```

Working on having a local Java Meterpreter dev setup running...

**Comment by bwatters-r7** [comment]
Random data point......

```
meterpreter > sysinfo
Computer        : Win10x64-1607
OS              : Windows 10 10.0 (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/windows
meterpreter > getuid
Server username: msfuser
meterpreter > ls
Listing: C:\Users\msfuser
=========================

Mode              Size     Type  Last modified              Name
----              ----     ----  -------------              ----
040777/rwxrwxrwx  0        dir   2017-06-19 09:37:39 -0500  AppData
..
..
..
100777/rwxrwxrwx  245760   fil   2017-06-19 09:37:39 -0500  ntuser.dat.LOG1
100777/rwxrwxrwx  284672   fil   2017-06-19 09:37:39 -0500  ntuser.dat.LOG2
100777/rwxrwxrwx  20       fil   2017-06-19 09:37:39 -0500  ntuser.ini

meterpreter > cd C:
[-] stdapi_fs_chdir: Operation failed: 1
Interrupt: use the 'exit' command to quit
meterpreter > cd 'C:\'
meterpreter > pwd
C:\
meterpreter > 

```
![image](https://github.com/user-attachments/assets/bf8aac12-923b-427d-9385-60d03478510e)

**Comment by smcintyre-r7** [comment]
I was able to reproduce the issue on the same system and log this stack trace for it:

```
msfadmin@metasploitable-201-3-1:~$ cat /tmp/stacktrace.log 
java.lang.NullPointerException
   at com.metasploit.meterpreter.stdapi.stdapi_fs_ls.execute(Unknown Source)
   at com.metasploit.meterpreter.CommandManager.executeCommand(Unknown Source)
   at com.metasploit.meterpreter.TcpTransport.dispatch(Unknown Source)
   at com.metasploit.meterpreter.Meterpreter.startExecuting(Unknown Source)
   at com.metasploit.meterpreter.Meterpreter.<init>(Unknown Source)
   at com.metasploit.meterpreter.Meterpreter.<init>(Unknown Source)
   at java.lang.reflect.Constructor.newInstance(libgcj.so.81)
   at javapayload.stage.Meterpreter.start(Unknown Source)
```
