### ISSUE TITLE
Crash at startup in reline

### ISSUE THREAD

**Issue by jvoisin** [rapid7/metasploit-framework#19498]
## Steps to reproduce

```console
$ rbenv local
3.1.5
$ bundle install
Bundle complete! 18 Gemfile dependencies, 216 gems now installed.
Bundled gems are installed into `/home/jvoisin/.gems`
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
$  ./msfconsole --version
Framework Version: 6.4.28-dev-9b4c2fea2b
$ ./msfconsole --quiet
/home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:284:in `both_tty?': undefined method `tty?' for #<Rex::Ui::Text::Output::Stdio:0x0000ffff0bb7d850 @config={:color=>:auto}, @io=nil, @input=#<Rex::Ui::Text::Input::Readline:0x0000ffff09ce36d8 @rl_saved_proc=#<Proc:0x0000ffff09ce34a8 /home/jvoisin/app/msf/lib/rex/ui/text/input/readline.rb:159>, @output=#<Rex::Ui::Text::Output::Stdio:0x0000ffff0bb7d850 ...>, @prompt="\\x01\\e[4m\\x02msf6\\x01\\e[0m\\x02 \\x01\\e[0m\\x02> ">, @at_prompt=true> (NoMethodError)
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:361:in `prep'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:308:in `inner_readline'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:280:in `block (2 levels) in readline'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:164:in `block in with_raw_input'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:164:in `raw'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:164:in `with_raw_input'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:279:in `block in readline'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:278:in `synchronize'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:278:in `readline'
	from /home/jvoisin/.rbenv/versions/3.1.5/lib/ruby/3.1.0/forwardable.rb:238:in `readline'
	from /home/jvoisin/app/msf/lib/rex/ui/text/input/readline.rb:146:in `readline_with_output'
	from /home/jvoisin/app/msf/lib/rex/ui/text/input/readline.rb:91:in `pgets'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:344:in `get_input_line'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:145:in `block in run'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:312:in `block in with_history_manager_context'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:309:in `with_history_manager_context'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:136:in `run'
	from /home/jvoisin/app/msf/lib/metasploit/framework/command/console.rb:54:in `start'
	from /home/jvoisin/app/msf/lib/metasploit/framework/command/base.rb:82:in `start'
	from ./msfconsole:25:in `<main>'
[1]
$
```

cc @sjanusz-r7

**Comment by adfoster-r7** [comment]
I haven't been able to replicate this yet - but I understand that it's definitely an issue :+1:

Does this workaround resolve the crash?
https://github.com/rapid7/metasploit-framework/pull/19500

**Comment by jvoisin** [comment]
Nope: 

```console
$ ./msfconsole --quiet
▽/home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:270:in `cursor_pos': undefined method `pos' for #<Rex::Ui::Text::Output::Stdio:0x0000fffebf595bc8 @config={:color=>:auto}, @io=#<IO:<STDOUT>>, @input=#<Rex::Ui::Text::Input::Readline:0x0000fffebfe15cd0 @rl_saved_proc=#<Proc:0x0000fffebfe157d0 /home/jvoisin/app/msf/lib/rex/ui/text/input/readline.rb:159>, @output=#<Rex::Ui::Text::Output::Stdio:0x0000fffebf595bc8 ...>, @prompt="\\x01\\e[4m\\x02msf6\\x01\\e[0m\\x02 \\x01\\e[0m\\x02> ">, @at_prompt=true> (NoMethodError)
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:424:in `may_req_ambiguous_char_width'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:310:in `inner_readline'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:280:in `block (2 levels) in readline'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:164:in `block in with_raw_input'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:164:in `raw'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline/io/ansi.rb:164:in `with_raw_input'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:279:in `block in readline'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:278:in `synchronize'
	from /home/jvoisin/.gems/ruby/3.1.0/gems/reline-0.5.10/lib/reline.rb:278:in `readline'
	from /home/jvoisin/.rbenv/versions/3.1.5/lib/ruby/3.1.0/forwardable.rb:238:in `readline'
	from /home/jvoisin/app/msf/lib/rex/ui/text/input/readline.rb:146:in `readline_with_output'
	from /home/jvoisin/app/msf/lib/rex/ui/text/input/readline.rb:91:in `pgets'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:344:in `get_input_line'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:145:in `block in run'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:312:in `block in with_history_manager_context'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:309:in `with_history_manager_context'
	from /home/jvoisin/app/msf/lib/rex/ui/text/shell.rb:136:in `run'
	from /home/jvoisin/app/msf/lib/metasploit/framework/command/console.rb:54:in `start'
	from /home/jvoisin/app/msf/lib/metasploit/framework/command/base.rb:82:in `start'
	from ./msfconsole:25:in `<main>'
[1]
$ git diff
diff --git a/lib/rex/ui/text/input.rb b/lib/rex/ui/text/input.rb
index cf3aeded67..5bebb1b16c 100644
--- a/lib/rex/ui/text/input.rb
+++ b/lib/rex/ui/text/input.rb
@@ -79,6 +79,10 @@ class Input
     false
   end
 
+  def tty?
+    false
+  end
+
   def update_prompt(new_prompt = '', new_prompt_char = '')
     self.prompt = new_prompt + new_prompt_char
   end
diff --git a/lib/rex/ui/text/output.rb b/lib/rex/ui/text/output.rb
index ef8f8fd030..0cec81a0d4 100644
--- a/lib/rex/ui/text/output.rb
+++ b/lib/rex/ui/text/output.rb
@@ -86,6 +86,10 @@ class Output < Rex::Ui::Output
 
     nil
   end
+
+  def tty?
+    false
+  end
 end
 
 end
$
```

**Comment by adfoster-r7** [comment]
Just noticing that your stacktrace has:

> reline-0.5.10

The code that crashes is only in 0.5.9 and 0.5.10 ([commit](https://github.com/ruby/reline/commit/f9227b5c8963bdd53ea5050a5b8730459977d4c1))

Whilst our Gemfile.lock requires 0.5.8:

https://github.com/rapid7/metasploit-framework/blob/9b4c2fea2b5a91ee57b82b5b842fab16243436c7/Gemfile.lock#L402

If I bump the version I replicate the crash:

```
/Users/foo/.rvm/gems/ruby-3.1.5@metasploit-framework/gems/reline-0.5.10/lib/reline/io/ansi.rb:284:in `both_tty?': undefined method `tty?' for #<Rex::Ui::Text::Output::Stdio:0x000000010ecc74c8 @config={:color=>:auto}, @io=#<IO:<STDOUT>>, @input=#<Rex::Ui::Text::Input::Readline:0x0000000110477190 @rl_saved_proc=#<Proc:0x0000000110476b00 /Users/foo/metasploit-framework/lib/rex/ui/text/input/readline.rb:159>, @output=#<Rex::Ui::Text::Output::Stdio:0x000000010ecc74c8 ...>, @prompt="\\x01\\e[4m\\x02msf6\\x01\\e[0m\\x02 auxiliary(\\x01\\e[1m\\x02\\x01\\e[31m\\x02scanner/ssh/ssh_login\\x01\\e[0m\\x02) \\x01\\e[0m\\x02> ">, @at_prompt=true> (NoMethodError)
```

Not sure why your reline version isn't the same as framework's required version 👀

**Comment by jvoisin** [comment]
I'd love to understand why as well :/

I would blame rbenv I think

**Comment by adfoster-r7** [comment]
This patch should work now I think: https://github.com/rapid7/metasploit-framework/pull/19500

We'll have to look into upgrading the reline gem for framework users, but I think that patch should unblock you until you're able to work out why bundler or rbenv isn't grabbing the right reline version 🤔

**Comment by adfoster-r7** [comment]
Does using `bundle exec ruby ./msfconsole --quiet` explicitly work for yourself?

For me:

```
$ bundle exec ruby ./msfconsole --quiet -x 'irb -e "puts Reline::VERSION"; exit'
[*] You are executing expressions in #<Msf::Ui::Console::CommandDispatcher::Developer:0x000000010b25f2b8>
0.5.8
```

**Comment by jvoisin** [comment]
Issue fixed when using the right version indeed. It seems that having `ruby-lsp` in a `Gemfile.local` brought a bunch of unwanted dependencies.

**Comment by adfoster-r7** [comment]
Awesome; I'll close my draft pull request as it looks like a local env issue.

I'm happy to close this issue, or we can keep it around as a reminder for a developer to either update our reline support to the latest version or to add an explicit library pin to reline version 0.5.8 explicitly in our gemspec file

**Comment by adfoster-r7** [comment]
Thanks! 🎉
