### ISSUE TITLE
crash caused by 'spool' command

### ISSUE THREAD

**Issue by synack420** [rapid7/metasploit-framework#19504]
steps to reproduce: 
run metasploit, latest nightly built
run spool msflog.txt
crash occurs immediately, repeated with various working dirs etc crash occurs everytime you spool

--

```
msf6 > spool msl
[*] Spooling to file msl...
/opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/ansi.rb:254:in `block in cursor_pos': undefined method `<<' for #<Rex::Ui::Text::Output::Tee:0x0000150f405b3588 @fd=#<File:msl>, @config={:color=>:auto}, @input=#<Rex::Ui::Text::Input::Readline:0x0000150f405ee200 @rl_saved_proc=#<Proc:0x0000150f405ee098 /opt/metasploit-framework/embedded/framewo
rk/lib/rex/ui/text/input/readline.rb:159>, @output=#<Rex::Ui::Text::Output::Tee:0x0000150f405b3588 ...>, @prompt="\x01\e[4m\x02msf6\x01\e[0m\x02 \x01\e[0m\x02> ">, @at_prompt=true> (NoMethodError)
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/ansi.rb:253:in `raw'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/ansi.rb:253:in `cursor_pos'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/line_editor.rb:141:in `reset'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline.rb:322:in `inner_readline'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline.rb:291:in `block (2 levels) in readline'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/ansi.rb:162:in `block in with_raw_input'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/ansi.rb:162:in `raw'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline/ansi.rb:162:in `with_raw_input'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline.rb:290:in `block in readline'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline.rb:288:in `synchronize'
   from /opt/metasploit-framework/embedded/lib/ruby/gems/3.2.0/gems/reline-0.5.8/lib/reline.rb:288:in `readline'
   from /opt/metasploit-framework/embedded/lib/ruby/3.2.0/forwardable.rb:240:in `readline'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/input/readline.rb:146:in `readline_with_output'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/input/readline.rb:91:in `pgets'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:344:in `get_input_line'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:145:in `block in run'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:312:in `block in with_history_manager_context'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell/history_manager.rb:35:in `with_context'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:309:in `with_history_manager_context'
   from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:136:in `run'
   from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:54:in `start'
   from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
   from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:25:in `<main>'
```

Get this with the `version` command in msfconsole (or `git log -1 --pretty=oneline` for a source install).

## Additional Information
If your version is less than `5.0.96`, please update to the latest version and ensure your issue is still present.

If the issue is encountered within `msfconsole`, please run the `debug` command using the instructions below. If the issue is encountered outisde `msfconsole`, or the issue causes `msfconsole` to crash on startup, please delete this section.

##  Module/Datastore

The following global/module datastore, and database setup was configured before the issue occurred:
<details>
<summary>Collapse</summary>

```
The local config file is empty, no global variables are set, and there is no active module.
```

</details>

##  Database Configuration

The database contains the following information:
<details>
<summary>Collapse</summary>

```
Session Type: postgresql selected, no connection
```

</details>

##  Framework Configuration

The features are configured as follows:
<details>
<summary>Collapse</summary>

| name | enabled |
|-:|-:|
| wrapped_tables | true |
| fully_interactive_shells | false |
| manager_commands | false |
| datastore_fallbacks | true |
| metasploit_payload_warnings | true |
| defer_module_loads | false |
| smb_session_type | true |
| postgresql_session_type | true |
| mysql_session_type | true |
| mssql_session_type | true |
| ldap_session_type | false |
| show_successful_logins | false |
| dns | true |
| hierarchical_search_table | true |

</details>

##  History

The following commands were ran during the session and before this issue occurred:
<details>
<summary>Collapse</summary>

```
490    debug
```

</details>

##  Framework Errors

The following framework errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
[09/26/2024 12:25:17] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/26/2024 12:25:17] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/26/2024 12:25:21] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/26/2024 12:25:22] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
[09/26/2024 12:25:47] [e(0)] core: Errno::ENOENT No such file or directory - git
[09/26/2024 12:25:47] [e(0)] core: Failed to connect to the database: No database YAML file
[09/26/2024 12:25:50] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/26/2024 12:25:50] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/26/2024 12:25:54] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/26/2024 12:25:55] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
```

</details>

##  Web Service Errors

The following web service errors occurred before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Framework Logs

The following framework logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/x64/custom have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/x64/shell have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/x64/peinject have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/x64/vncinject have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/x64/meterpreter have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/shell have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/peinject have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/patchupmeterpreter have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/upexec have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/vncinject have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/meterpreter have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage windows/patchupdllinject have incompatible platforms: ["Linux"] - ["Windows"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage bsd/x86/shell have incompatible platforms: ["Linux"] - ["BSD"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage python/meterpreter have incompatible platforms: ["Linux"] - ["Python"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage java/shell have incompatible platforms: ["Linux"] - ["Java"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage java/meterpreter have incompatible platforms: ["Linux"] - ["Java"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage bsdi/x86/shell have incompatible platforms: ["Linux"] - ["BSDi"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage android/shell have incompatible platforms: ["Linux"] - ["Android"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage android/meterpreter have incompatible platforms: ["Linux"] - ["Android"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/aarch64/meterpreter have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/x64/dupandexecve have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/x64/meterpreter have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/ppc/shell have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/x86/isight have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/x86/vforkshell have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/x86/bundleinject have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/armle/shell have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage osx/armle/execute have incompatible platforms: ["Linux"] - ["OSX"]
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/aarch64/shell have incompatible architectures: mipsle - aarch64
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/aarch64/meterpreter have incompatible architectures: mipsle - aarch64
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/mipsbe/shell have incompatible architectures: mipsle - mipsbe
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/mipsbe/meterpreter have incompatible architectures: mipsle - mipsbe
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/x64/shell have incompatible architectures: mipsle - x64
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/x64/meterpreter have incompatible architectures: mipsle - x64
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/x86/shell have incompatible architectures: mipsle - x86
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/x86/meterpreter have incompatible architectures: mipsle - x86
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/armle/shell have incompatible architectures: mipsle - armle
[09/26/2024 12:25:27] [d(2)] core: Stager linux/mipsle/reverse_tcp and stage linux/armle/meterpreter have incompatible architectures: mipsle - armle
[09/26/2024 12:25:27] [d(1)] core: Module  is compatible with 
[09/26/2024 12:25:27] [d(1)] core: Module  is compatible with 
[09/26/2024 12:25:27] [d(2)] core: Built staged payload linux/mipsle/shell/reverse_tcp.
[09/26/2024 12:25:27] [d(1)] core: Module  is compatible with 
[09/26/2024 12:25:27] [d(1)] core: Module  is compatible with 
[09/26/2024 12:25:27] [d(2)] core: Built staged payload linux/mipsle/meterpreter/reverse_tcp.
[09/26/2024 12:25:47] [e(0)] core: Errno::ENOENT No such file or directory - git
[09/26/2024 12:25:47] [e(0)] core: Failed to connect to the database: No database YAML file
[09/26/2024 12:25:50] [e(0)] core: Dependency for windows/x64/encrypted_shell_reverse_tcp is not supported
[09/26/2024 12:25:50] [e(0)] core: Dependency for windows/encrypted_shell_reverse_tcp is not supported
[09/26/2024 12:25:54] [e(0)] core: Dependency for windows/encrypted_reverse_tcp is not supported
[09/26/2024 12:25:55] [e(0)] core: Dependency for windows/x64/encrypted_reverse_tcp is not supported
```

</details>

##  Web Service Logs

The following web service logs were recorded before the issue occurred:
<details>
<summary>Collapse</summary>

```
msf-ws.log does not exist.
```

</details>

##  Version/Install

The versions and install method of your Metasploit setup:
<details>
<summary>Collapse</summary>

```
Framework: 6.4.28-dev-
Ruby: ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]
OpenSSL: OpenSSL 1.1.1t  7 Feb 2023
Install Root: /opt/metasploit-framework/embedded/framework
Session Type: postgresql selected, no connection
Install Method: Omnibus Installer
```

</details>

**Comment by Leaf45** [comment]
I'm going to look into this bug for you, is there anywhere that I need to confirm ill work on this bug?

**Comment by sjanusz-r7** [comment]
The issue can be temporarily worked-around with this diff:
```diff
diff --git a/lib/rex/ui/text/output/tee.rb b/lib/rex/ui/text/output/tee.rb
index ebfbb4034a..f94c3b32b6 100644
--- a/lib/rex/ui/text/output/tee.rb
+++ b/lib/rex/ui/text/output/tee.rb
@@ -49,6 +49,8 @@ class Output::Tee < Rex::Ui::Text::Output
     self.fd.close if self.fd
     self.fd = nil
   end
+
+  alias << print_raw
 end
 
 end
```

However Reline inputs extra characters into the logfile which was not the case with Readline previously. I'm investigating it more 👍

**Comment by adfoster-r7** [comment]
Is fixed on the latest release, thanks!
