### ISSUE TITLE
NoMethod Error with dir_scanner Module

### ISSUE THREAD

**Issue by todb-r7** [rapid7/metasploit-framework#3952]
*This issue was [RM8834](https://dev.metasploit.com/redmine/issues/8834), originally filed by by Erik Dominguez*

Environment: meterpreter session opened, set as pivot point to 10.1.1.x network from 192.168.x.x network

Target is on 10.1.1.251:10000 http

`auxiliary/scanner/http/dir_scanner` module loaded and ran produces output:

```
[*] Detecting error code
[*] Using code '404' as not found for 10.1.1.251
[-] Auxiliary failed: NoMethodError undefined method `find_or_initialize_by_web_site_id_and_path_and_method_and_pname_and_name_and_category_and_query' for #<Class:0x9d56d2c>
[-] Call stack:
[-]   /opt/metasploit/apps/pro/ui/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/dynamic_matchers.rb:27:in `method_missing'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/db.rb:2570:in `block in report_web_vuln'
[-]   /opt/metasploit/apps/pro/ui/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/db.rb:2508:in `report_web_vuln'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/auxiliary/report.rb:184:in `report_web_vuln'
[-]   /opt/metasploit/apps/pro/msf3/modules/auxiliary/scanner/http/dir_scanner.rb:157:in `block (2 levels) in run_host'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit/apps/pro/msf3/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

Per user @Meatballs1 in #metasploit channel, a fix could be to simply comment out lines 144 - 158 in module 

This fixes the problem, module works with this configuration

**Comment by todb-r7** [comment]
Just bumped, @lsanchez-r7 is on the case.

**Comment by kgray-r7** [comment]
I cannot reproduce this issue.
 
Here's what I tried:
Got a session on a Windows vm
Created a proxy pivot
Ran auxiliary/scanner/http/dir_scanner against an internal webtarget with no stacktrace.
Please let me know if I am doing something wrong.

**Comment by wchen-r7** [comment]
This might not be a problem anymore, can anybody confirm?

**Comment by bcook-r7** [comment]
I'm closing due to inactivity. If it is still a problem, let's create a new issue to track it.
