### ISSUE TITLE
Msf::Modules::Loader::Base rspec occasionally fails

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#4172]
From:

https://travis-ci.org/rapid7/metasploit-framework/jobs/40500607
https://travis-ci.org/rapid7/metasploit-framework/jobs/40310580
<many others that were restarted and passed>

```
Msf::Modules::Loader::Base ........................................./home/travis/build/rapid7/metasploit-framework/lib/msf/core/modules/loader/base.rb:600: warning: already initialized constant Mod0
.../home/travis/build/rapid7/metasploit-framework/spec/lib/msf/core/modules/loader/base_spec.rb:1193: warning: already initialized constant Mod0
..........................................F.....................
  1) Msf::Modules::Loader::Base CONSTANTS NAMESPACE_MODULE_CONTENT derived module module_eval_with_lexical_scope should capture the lexical scope
     Failure/Error: expect {
       expected no Exception, got #<TypeError: superclass mismatch for class Metasploit3> with backtrace:
         # ./modules/auxiliary/rspec/mock.rb:1:in `module_eval_with_lexical_scope'
         # (eval):26:in `module_eval'
         # (eval):26:in `module_eval_with_lexical_scope'
         # ./spec/lib/msf/core/modules/loader/base_spec.rb:135:in `block (7 levels) in <top (required)>'
         # ./spec/lib/msf/core/modules/loader/base_spec.rb:134:in `block (6 levels) in <top (required)>'
     # ./spec/lib/msf/core/modules/loader/base_spec.rb:134:in `block (6 levels) in <top (required)>'
```

**Comment by jvazquez-r7** [comment]
@jhart-r7 is there any follow-up here? Are experiencing the travis failures or can we close this?

**Comment by jhart-r7** [comment]
Haven't seen this fail in forever.  Closing.
