### ISSUE TITLE
ActiveRecord errors during msfconsole startup (master/ruby-2.1.5)

### ISSUE THREAD

**Issue by hdm** [rapid7/metasploit-framework#4250]
These show up in the error log during startup. There is no visible indicator, but we should probably investigate and/or squash these.

```
./msfconsole:48:in `<main>'
[11/22/2014 15:57:24] [e(0)] core: Connection not established: ActiveRecord::ConnectionNotEstablished ActiveRecord::ConnectionNotEstablished:
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/connection_specification.rb:167:in `connection_pool'
/data/work/msf-hdm/lib/msf/core/db_manager/connection.rb:123:in `connection_established?'
/data/work/msf-hdm/lib/msf/core/db_manager/connection.rb:54:in `connect'
/data/work/msf-hdm/lib/msf/ui/console/driver.rb:179:in `initialize'
/data/work/msf-hdm/lib/metasploit/framework/command/console.rb:44:in `new'
/data/work/msf-hdm/lib/metasploit/framework/command/console.rb:44:in `driver'
/data/work/msf-hdm/lib/metasploit/framework/command/console.rb:30:in `start'
/data/work/msf-hdm/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

**Comment by crmaxx** [comment]
Next patch fixes the problem:
```ruby
diff --git a/lib/msf/core/db_manager.rb b/lib/msf/core/db_manager.rb
index 2c2d55b..32c0e3e 100644
--- a/lib/msf/core/db_manager.rb
+++ b/lib/msf/core/db_manager.rb
@@ -10,6 +10,7 @@ require 'rex/socket'
 # Project
 #

+require 'active_record/railtie'
 require 'metasploit/framework/require'
 require 'msf/base/config'
 require 'msf/core'
```

**Comment by void-in** [comment]
@crmaxx This is not how patches are accepted here. Create a new git branch, edit the original file in your fork, generate a pull request. 

For example, in your own fork
git checkout -b patch-4250
nano lib/msf/core/db_manager.rb
<edit the file, add the line and save>
git add lib/msf/core/db_manager.rb
git commit -m "Add missing require in db_manager"
git push origin patch-4250

Go to your Metasploit fork branches, select the patch-4250 branch and generate a pull request.

**Comment by busterb** [comment]
Ah, this is fixed!
