### ISSUE TITLE
Credentials Exception Hashdump/SmartHashdump

### ISSUE THREAD

**Issue by Meatballs1** [rapid7/metasploit-framework#4279]
Following exception observed:

```
[*] [2014.11.28-14:53:41] Obtaining the boot key...
[*] [2014.11.28-14:53:43] Calculating the hboot key using SYSKEY 6d4d416fc21596604b55501cfa48a833...
[*] [2014.11.28-14:53:43] Obtaining the user list and keys...
[*] [2014.11.28-14:53:56] Decrypting user keys...
[*] [2014.11.28-14:53:56] Dumping password hints...

No users with password hints on this system

[*] [2014.11.28-14:53:56] Dumping password hashes...


Administrator:500:blaah
Another User:BLaah

[-] [2014.11.28-14:53:57] Post failed: ActiveRecord::RecordInvalid Validation failed: Last attempted at can't be set if status is untried.
[-] [2014.11.28-14:53:57] Call stack:
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/validations.rb:56:in `save!'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/attribute_methods/dirty.rb:33:in `save!'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:264:in `block in save!'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:208:in `transaction'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/activerecord-3.2.19/lib/active_record/transactions.rb:264:in `save!'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/metasploit-credential-0.13.3/lib/metasploit/credential/creation.rb:203:in `block in create_credential_login'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/metasploit-credential-0.13.3/lib/metasploit/credential/creation.rb:502:in `retry_transaction'
[-] [2014.11.28-14:53:57]   /var/lib/gems/1.9.1/gems/metasploit-credential-0.13.3/lib/metasploit/credential/creation.rb:192:in `create_credential_login'
[-] [2014.11.28-14:53:57]   /root/git/metasploit-framework/modules/post/windows/gather/hashdump.rb:108:in `block in run'
[-] [2014.11.28-14:53:57]   /root/git/metasploit-framework/modules/post/windows/gather/hashdump.rb:90:in `each'
[-] [2014.11.28-14:53:57]   /root/git/metasploit-framework/modules/post/windows/gather/hashdump.rb:90:in `run'
```

**Comment by dmaloney-r7** [comment]
this issue was fixed on Metasploit-Credential by https://github.com/rapid7/metasploit-credential/pull/82 
as part of MSP-11782
