### ISSUE TITLE
RSpec tests fail without an active database connection

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#4505]
With the current master branch, the `rspec` command is failing:

```
root@firefart:~/hacking/metasploit-framework# rspec
/usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:157:in `expand_path': can't convert nil into String (TypeError)
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:157:in `block in expanded'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:156:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:156:in `expanded'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:128:in `first'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/application/configuration.rb:115:in `database_configuration'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/base.rb:720:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/metasploit_data_models-0.21.3/config/initializers/arel_helper.rb:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:592:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /root/hacking/metasploit-framework/config/environment.rb:5:in `<top (required)>'
	from /root/hacking/metasploit-framework/spec/spec_helper.rb:14:in `require'
	from /root/hacking/metasploit-framework/spec/spec_helper.rb:14:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `block in setup_load_path_and_require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `each'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `setup_load_path_and_require'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration_options.rb:25:in `configure'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/command_line.rb:17:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/runner.rb:103:in `run'
	from /usr/local/rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by FireFart** [comment]
Same on my Macbook:
```
macbook:metasploit-framework firefart$ rspec
/Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:157:in `expand_path': can't convert nil into String (TypeError)
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:157:in `block in expanded'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:156:in `each'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:156:in `expanded'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:128:in `first'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/application/configuration.rb:115:in `database_configuration'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/base.rb:720:in `<top (required)>'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/metasploit_data_models-0.21.3/config/initializers/arel_helper.rb:4:in `<top (required)>'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:592:in `each'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/firefart/Coding/metasploit-framework/config/environment.rb:5:in `<top (required)>'
	from /Users/firefart/Coding/metasploit-framework/spec/spec_helper.rb:14:in `require'
	from /Users/firefart/Coding/metasploit-framework/spec/spec_helper.rb:14:in `<top (required)>'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `require'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `block in setup_load_path_and_require'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `each'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `setup_load_path_and_require'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration_options.rb:25:in `configure'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/command_line.rb:17:in `run'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/runner.rb:103:in `run'
	from /Users/firefart/.rvm/gems/ruby-1.9.3-p551@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by disenchant** [comment]
OK, I'm at least not alone with this one :smiley:
Tested on an OS X Yosemite and Kali installation - exact same problem as @FireFart

**Comment by todb-r7** [comment]
How does it look on Ruby 2.1.5? Also, travis isn't barfing on `rake spec`...

**Comment by todb-r7** [comment]
For me, both `rake spec` and `rspec` seem to be fine under 2.1.5. You'll want to move over anyway in prep for #4506. That said, under 1.9.3, I also have success with `rspec` and `rake spec`, on Ubuntu, given a fresh `bundle install`. I wonder if there are path-specific problems with OSX and (weirdly) Kali.

**Comment by todb-r7** [comment]
Looks like it all starts at `config/environment.rb` which is passing a relative directory.

**Comment by todb-r7** [comment]
Try this for debugging, if you please, @FireFart and/or @disenchant:

```diff
todb@mazikeen:~/git/rapid7/metasploit-framework$ git diff --patch-with-stat 
 config/application.rb | 1 +
 config/environment.rb | 1 +
 2 files changed, 2 insertions(+)

diff --git a/config/application.rb b/config/application.rb
index f4eaab5..11061c6 100644
--- a/config/application.rb
+++ b/config/application.rb
@@ -1,4 +1,5 @@
 require 'rails'
+puts "[!] 'DEBUG: #{File.expand_path('../boot', __FILE__)}"
 require File.expand_path('../boot', __FILE__)
 
 all_environments = [
diff --git a/config/environment.rb b/config/environment.rb
index 4aa3412..0a4f11a 100644
--- a/config/environment.rb
+++ b/config/environment.rb
@@ -1,4 +1,5 @@
 # Load the rails application
+puts "[!] 'DEBUG: #{File.expand_path('../application', __FILE__)}"
 require File.expand_path('../application', __FILE__)
 
 # Initialize the rails application
```

**Comment by disenchant** [comment]
@todb-r7 sorry my fault, on Kali the error was a different one :sweat:

**Comment by FireFart** [comment]
With ruby 2.1.5:
```
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:157:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:157:in `block in expanded'
```

With debug output:
```
macbook:metasploit-framework firefart$ rspec
[!] 'DEBUG: /Users/firefart/Coding/metasploit-framework/config/application
[!] 'DEBUG: /Users/firefart/Coding/metasploit-framework/config/boot
```

Tested on OSX Yosemite and Ubuntu 14.04 Server.

Running `rake rspec` or `rake spec` only one debug output is shown before it crashes:
```
macbook:metasploit-framework firefart$ rake rspec
[!] 'DEBUG: /Users/firefart/Coding/metasploit-framework/config/boot
rake aborted!
TypeError: no implicit conversion of nil into String
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:157:in `expand_path'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:157:in `block in expanded'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:156:in `each'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:156:in `expanded'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:128:in `first'
/Users/firefart/Coding/metasploit-framework/lib/metasploit/framework/require.rb:52:in `optionally_active_record_railtie'
/Users/firefart/Coding/metasploit-framework/Rakefile:10:in `<top (required)>'
/Users/firefart/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/firefart/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
macbook:metasploit-framework firefart$ rake spec
[!] 'DEBUG: /Users/firefart/Coding/metasploit-framework/config/boot
rake aborted!
TypeError: no implicit conversion of nil into String
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:157:in `expand_path'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:157:in `block in expanded'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:156:in `each'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:156:in `expanded'
/Users/firefart/.rvm/gems/ruby-2.1.5/gems/railties-3.2.21/lib/rails/paths.rb:128:in `first'
/Users/firefart/Coding/metasploit-framework/lib/metasploit/framework/require.rb:52:in `optionally_active_record_railtie'
/Users/firefart/Coding/metasploit-framework/Rakefile:10:in `<top (required)>'
/Users/firefart/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/firefart/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by FireFart** [comment]
BTW: I'm using RVM for my environment

**Comment by FireFart** [comment]
Put some debug output into railties paths.rb line 157:
looks like p is nil

```
p: nil
@root.inspect: {"app"=>["app"], "app/assets"=>["app/assets"], "app/controllers"=>["app/controllers"], "app/helpers"=>["app/helpers"], "app/models"=>["app/models"], "app/mailers"=>["app/mailers"], "app/views"=>["app/views"], "lib"=>["lib"], "lib/assets"=>["lib/assets"], "lib/tasks"=>["lib/tasks"], "config"=>["config"], "config/environments"=>["config/environments"], "config/initializers"=>["config/initializers"], "config/locales"=>["config/locales"], "config/routes"=>["config/routes.rb"], "db"=>["db"], "db/migrate"=>["db/migrate"], "db/seeds"=>["db/seeds.rb"], "vendor"=>["vendor"], "vendor/assets"=>["vendor/assets"], "vendor/plugins"=>["vendor/plugins"], "config/database"=>[nil], "config/environment"=>["config/environment.rb"], "lib/templates"=>["lib/templates"], "log"=>["log/development.log"], "public"=>["public"], "public/javascripts"=>["public/javascripts"], "public/stylesheets"=>["public/stylesheets"], "tmp"=>["tmp"], "data/meterpreter"=>["data/meterpreter"], "modules"=>["modules"]}
@root.path: /Users/firefart/Coding/metasploit-framework
```

**Comment by FireFart** [comment]
This line is causing the errors:
`Rails.application.config.paths['config/database'].first`

BTW: I have no database connected or configured on both machines

**Comment by FireFart** [comment]
inspecting `Rails.application.config.paths` there is no `config/database` path, altough this error only occurs when running `rake rspec`, not when only running `rpsec`
```
{"app"=>["app"], "app/assets"=>["app/assets"], "app/controllers"=>["app/controllers"], "app/helpers"=>["app/helpers"], "app/models"=>["app/models"], "app/mailers"=>["app/mailers"], "app/views"=>["app/views"], "lib"=>["lib"], "lib/assets"=>["lib/assets"], "lib/tasks"=>["lib/tasks"], "config"=>["config"], "config/environments"=>["config/environments"], "config/initializers"=>["config/initializers"], "config/locales"=>["config/locales"], "config/routes"=>["config/routes.rb"], "db"=>["db"], "db/migrate"=>["db/migrate"], "db/seeds"=>["db/seeds.rb"], "vendor"=>["vendor"], "vendor/assets"=>["vendor/assets"], "vendor/plugins"=>["vendor/plugins"], "config/database"=>[nil], "config/environment"=>["config/environment.rb"], "lib/templates"=>["lib/templates"], "log"=>["log/development.log"], "public"=>["public"], "public/javascripts"=>["public/javascripts"], "public/stylesheets"=>["public/stylesheets"], "tmp"=>["tmp"], "data/meterpreter"=>["data/meterpreter"], "modules"=>["modules"]}
```

**Comment by todb-r7** [comment]
Master branch is no longer failing. Fixed. Also this may be 1.9.3 specific since 2.1.5 seems a-okay.

Closing.

**Comment by FireFart** [comment]
@todb-r7 sorry but the current master branch is still failing. I think it's because i have no database connected in my evironment:
```
macbook:metasploit-framework firefart$ rspec
/Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:157:in `expand_path': no implicit conversion of nil into String (TypeError)
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:157:in `block in expanded'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:156:in `each'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:156:in `expanded'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/paths.rb:128:in `first'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/application/configuration.rb:115:in `database_configuration'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/railtie.rb:84:in `block (2 levels) in <class:Railtie>'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `each'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activerecord-3.2.21/lib/active_record/base.rb:720:in `<top (required)>'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/metasploit_data_models-0.22.5/config/initializers/arel_helper.rb:4:in `<top (required)>'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:592:in `each'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /Users/firefart/Coding/metasploit-framework/config/environment.rb:5:in `<top (required)>'
	from /Users/firefart/Coding/metasploit-framework/spec/spec_helper.rb:14:in `require'
	from /Users/firefart/Coding/metasploit-framework/spec/spec_helper.rb:14:in `<top (required)>'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `require'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `block in setup_load_path_and_require'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `each'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration.rb:1036:in `setup_load_path_and_require'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/configuration_options.rb:25:in `configure'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/command_line.rb:17:in `run'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/runner.rb:103:in `run'
	from /Users/firefart/.rvm/gems/ruby-2.1.5@metasploit-framework/gems/rspec-core-2.99.1/lib/rspec/core/runner.rb:17:in `block in autorun'
Coverage report generated for RSpec to /Users/firefart/Coding/metasploit-framework/coverage. 16246 / 90101 LOC (18.03%) covered.
macbook:metasploit-framework firefart$
```

**Comment by todb-r7** [comment]
Ah, probably. I think @bcook-r7 ran into this this morning as well; to run tests, you a) need a database configured and b) your user needs the createdb right.

**Comment by bcook-r7** [comment]
My database setup script looks like this on OS X:

https://gist.github.com/bcook-r7/515e90e9166faf23c74b

I tapped the brew services manager first to make starting/stopping pgsql easier:

http://robots.thoughtbot.com/starting-and-stopping-background-services-with-homebrew

Then my database.yml file is pretty much the same as the example one with the right user/passwords inserted.

**Comment by FireFart** [comment]
i'm just wondering because some months ago it was possible to run rpsecs without having a database connected

**Comment by bcook-r7** [comment]
Poking around, it seems like there is code that was supposed to to handle that condition, but it appears to have broken.

**Comment by todb-r7** [comment]
Retitled for clarity.

**Comment by todb-r7** [comment]
Okay, so, after some discussion here, this is pretty much as-designed. Rspec, in general, needs database support.

The way to fix this, notionally anyway, is to check for database connectivity, and if it's not there, complain (but not stacktrace). But testing without database support is a fairly herculean effort. Welcome to try, but the vast majority of rspec-able cases around are going to want to check that the database bits still work.

**Comment by FireFart** [comment]
I use the rspecs for the wordpress mixin and when doing changes to lib methods. On my dev machine i have not set up a database (this sucks on osx) so i only want to be sure the main code specs run without failure. If we need a DB to run it in the future I'm also fine with that and I need to setup my database :)

**Comment by FireFart** [comment]
:cry:

**Comment by wvu-r7** [comment]
YOU NEED A DATUMSBASE.

**Comment by FireFart** [comment]
@wvu-r7 https://www.youtube.com/watch?v=-_xUIDRxdmc

**Comment by wvu-r7** [comment]
@FireFart: Es gefällt mir! :D

**Comment by bcook-r7** [comment]
alle Ihre Datenbanken sind gehören zu uns
