### ISSUE TITLE
Rex::Text.to_utf8 is outdated for Ruby 2.x due to the use of Iconv

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4510]
So I was reading this:
https://www.ruby-lang.org/en/news/2013/02/24/ruby-2-0-0-p0-is-released/

The notes state the following:
"Iconv was removed, which had already been deprecated when M17N was introduced in ruby 1.9. Use String#encode, etc. instead."

Indeed removed:

```
AUS-MAC-1039:modules sinn3r$ rvm use ruby-2.1.4
Using /Users/sinn3r/.rvm/gems/ruby-2.1.4
AUS-MAC-1039:modules sinn3r$ irb
2.1.4 :001 > require 'iconv'
LoadError: cannot load such file -- iconv
	from /Users/sinn3r/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/sinn3r/.rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from (irb):1
	from /Users/sinn3r/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
2.1.4 :002 > 
```

And then I did a grep, I found that Rex::Text.to_utf8 is still using Iconv:

```ruby
  #
  # Converts ISO-8859-1 to UTF-8
  #
  def self.to_utf8(str)

    if str.respond_to?(:encode)
      # Skip over any bytes that fail to convert to UTF-8
      return str.encode('utf-8', { :invalid => :replace, :undef => :replace, :replace => '' })
    end

    begin
      Iconv.iconv("utf-8","iso-8859-1", str).join(" ")
    rescue
      raise ::RuntimeError, "Your installation does not support iconv (needed for utf8 conversion)"
    end
  end
```

And then I did another grep, I found one module using to_utf8:

```
$ grep -iR "to_utf8" *
post/windows/gather/credentials/spark_im.rb:    password = ::Rex::Text.to_utf8(password)
```

I didn't actually test spark_im.rb, but by source code reading I'm gonna boldly say it will break in Ruby 2.

**Comment by wchen-r7** [comment]
I'll fix this, but I'm looking for more bugs at the moment.

**Comment by wchen-r7** [comment]
Ah, actually, this isn't an issue at all. The method does this:

```ruby
return str.encode('utf-8', { :invalid => :replace, :undef => :replace, :replace => '' })
```

Which will be called in Ruby 2.
