### ISSUE TITLE
Timeout exception raised by nbns_response module

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#4799]
```
msf auxiliary(nbns_response) > set INTERFACE bond0
msf auxiliary(nbns_response) > set SPOOFIP 192.168.0.11
msf auxiliary(nbns_response) > run -j
[*] Auxiliary module running as background job
[*] NBNS Spoofer started. Listening for NBNS requests...
[-] nbnspoof: Timeout::Error execution expired ["/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:45:in `rescue in exception'", "/usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:41:in `exception'", "/data/work/msf-hdm/modules/auxiliary/spoof/nbns/nbns_response.rb:69:in `recvfrom'", "/data/work/msf-hdm/modules/auxiliary/spoof/nbns/nbns_response.rb:69:in `run'", "/data/work/msf-hdm/lib/msf/base/simple/auxiliary.rb:140:in `job_run_proc'", "/data/work/msf-hdm/lib/msf/base/simple/auxiliary.rb:76:in `block in run_simple'", "/data/work/msf-hdm/lib/rex/job_container.rb:37:in `call'", "/data/work/msf-hdm/lib/rex/job_container.rb:37:in `block in start'", "/data/work/msf-hdm/lib/rex/thread_factory.rb:22:in `call'", "/data/work/msf-hdm/lib/rex/thread_factory.rb:22:in `block in spawn'", "/data/work/msf-hdm/lib/msf/core/thread_manager.rb:100:in `call'", "/data/work/msf-hdm/lib/msf/core/thread_manager.rb:100:in `block in spawn'"]
```

**Comment by jlee-r7** [comment]
This looks to be superceded by #4827.  Feel free to reopen if I'm mistaken.
