### ISSUE TITLE
undefined method `ancestors' for nil:NilClass during payload generation

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#4865]
To reproduce, do:

```
$ ./msfvenom -p generic/shell_reverse_tcp arch=x86 platform=Windows -f raw
No platform was selected, choosing Msf::Module::Platform from the payload
No Arch selected, selecting Arch: x86 from the payload
undefined method `ancestors' for nil:NilClass
```

```
[03/02/2015 18:55:22] [e(0)] core: NoMethodError : undefined method `ancestors' for nil:NilClass
/Users/sinn3r/rapid7/msf/lib/msf/core/payload_set.rb:239:in `block in find_payload'
/Users/sinn3r/rapid7/msf/lib/msf/core/module_set.rb:274:in `call'
/Users/sinn3r/rapid7/msf/lib/msf/core/module_set.rb:274:in `block in each_module_list'
/Users/sinn3r/rapid7/msf/lib/msf/core/module_set.rb:247:in `each'
/Users/sinn3r/rapid7/msf/lib/msf/core/module_set.rb:247:in `each_module_list'
/Users/sinn3r/rapid7/msf/lib/msf/core/module_set.rb:91:in `each_module'
/Users/sinn3r/rapid7/msf/lib/msf/core/payload_set.rb:226:in `find_payload'
/Users/sinn3r/rapid7/msf/lib/msf/core/payload/generic.rb:247:in `find_actual_payload'
/Users/sinn3r/rapid7/msf/lib/msf/core/payload/generic.rb:160:in `redirect_to_actual'
/Users/sinn3r/rapid7/msf/lib/msf/core/payload/generic.rb:60:in `generate'
/Users/sinn3r/rapid7/msf/lib/msf/core/encoded_payload.rb:93:in `generate_raw'
/Users/sinn3r/rapid7/msf/lib/msf/core/encoded_payload.rb:68:in `generate'
/Users/sinn3r/rapid7/msf/lib/msf/core/encoded_payload.rb:25:in `create'
/Users/sinn3r/rapid7/msf/lib/msf/base/simple/payload.rb:53:in `generate_simple'
/Users/sinn3r/rapid7/msf/lib/msf/base/simple/payload.rb:137:in `generate_simple'
/Users/sinn3r/rapid7/msf/lib/msf/core/payload_generator.rb:300:in `generate_raw_payload'
/Users/sinn3r/rapid7/msf/lib/msf/core/payload_generator.rb:264:in `generate_payload'
```

Possible root cause:
https://github.com/rapid7/metasploit-framework/blob/2f4ad9716cce0bba14696d4a135847e74e72a1a3/lib/msf/core/payload_generator.rb#L303

**Comment by bcook-r7** [comment]
```
./msfvenom -p generic/shell_reverse_tcp arch=x86 platform=Windows -f raw |disasm
No platform was selected, choosing Msf::Module::Platform from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload

   0:   fc                      cld
   1:   e8 82 00 00 00          call   0x88
   6:   60                      pusha
   7:   89 e5                   mov    ebp,esp
   9:   31 c0                   xor    eax,eax
   b:   64 8b 50 30             mov    edx,DWORD PTR fs:[eax+0x30]
   f:   8b 52 0c                mov    edx,DWORD PTR [edx+0xc]
  12:   8b 52 14                mov    edx,DWORD PTR [edx+0x14]
  15:   8b 72 28                mov    esi,DWORD PTR [edx+0x28]
  18:   0f b7 4a 26             movzx  ecx,WORD PTR [edx+0x26]
  1c:   31 ff                   xor    edi,edi
  1e:   ac                      lods   al,BYTE PTR ds:[esi]
  1f:   3c 61                   cmp    al,0x61
  21:   7c 02                   jl     0x25
  23:   2c 20                   sub    al,0x20
  25:   c1 cf 0d                ror    edi,0xd
  28:   01 c7                   add    edi,eax
  2a:   e2 f2                   loop   0x1e
  2c:   52                      push   edx
  2d:   57                      push   edi
...
```
