### ISSUE TITLE
`msfconsole -o test.txt` leads to crash

### ISSUE THREAD

**Issue by reider-roque** [rapid7/metasploit-framework#4971]
Platform/Version information:
```
root@kali:/tmp# lsb_release -d
Description:	Kali GNU/Linux 1.1.0
root@kali:/tmp# uname -a
Linux kali 3.18.0-kali3-amd64 #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) x86_64 GNU/Linux
root@kali:/tmp# apt-cache show metasploit-framework | grep Version
Version: 4.11.1-2015031701-1kali0
```

Bug:
```
root@kali: /tmp# msfconsole -o test.txt
[*] Starting the Metasploit Framework console...-
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/rb-readline-r7-0.5.2.0/lib/rbreadline.rb:3872:in `_rl_output_some_chars': undefined method `write' for #<Rex::Ui::Text::Output::File:0x000000029303f8> (NoMethodError)
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/rb-readline-r7-0.5.2.0/lib/rbreadline.rb:3051:in `update_line'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/rb-readline-r7-0.5.2.0/lib/rbreadline.rb:3542:in `rl_redisplay'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/rb-readline-r7-0.5.2.0/lib/rbreadline.rb:3960:in `readline_internal_setup'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/rb-readline-r7-0.5.2.0/lib/rbreadline.rb:4807:in `readline_internal'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/rb-readline-r7-0.5.2.0/lib/rbreadline.rb:4830:in `readline'
	from /usr/share/metasploit-framework/lib/rex/ui/text/input/readline.rb:132:in `readline_with_output'
	from /usr/share/metasploit-framework/lib/rex/ui/text/input/readline.rb:86:in `pgets'
	from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:184:in `run'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'
```

**Comment by wchen-r7** [comment]
Confirmed backtrace.

**Comment by wvu-r7** [comment]
Confirmed here, too.

Doesn't blow up with GNU Readline:

```
wvu@kharak:~/metasploit-framework:master$ ./msfconsole -Lol
[*] Starting the Metasploit Framework console...-
msf > 
```

**Comment by bcook-r7** [comment]
We need to add a write alias method to File here?
