### ISSUE TITLE
db_nmap command save directive references a nonexistent myworkspace variable

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#4999]
Example:
```
[*] Nmap: Host is up (0.033s latency).
[*] Nmap: Nmap done: 1 IP address (1 host up) scanned in 1.06 seconds
[-] Error while running command db_nmap: undefined method `workspace' for #<Msf::Ui::Console::CommandDispatcher::Db:0x0000000392b488>

Call stack:
/opt/metasploit4/msf4/lib/msf/core/auxiliary/report.rb:58:in `myworkspace'
/opt/metasploit4/msf4/lib/msf/core/auxiliary/report.rb:154:in `report_note'
/opt/metasploit4/msf4/lib/msf/core/auxiliary/report.rb:456:in `store_local'
/opt/metasploit4/msf4/lib/msf/ui/console/command_dispatcher/db.rb:1928:in `report_store_local'
/opt/metasploit4/msf4/lib/msf/ui/console/command_dispatcher/db.rb:1878:in `block in cmd_db_nmap'
```
When there is no current module context, there is no myworkspace variable, and bad things happen.
My quick hack was to refence myworkspace as framework.db.workspace from the command dispatcher, but i figure there's a more elegant solution buried in the DB changes i've not caught up on.

@wvu-r7: This is what i mention in #4995

**Comment by wvu-r7** [comment]
Hmm, not seeing this in the code, and I haven't been able to repro.

**Comment by wvu-r7** [comment]
Can you provide more details?

**Comment by wvu-r7** [comment]
Might have been fixed in 509ae76dc9baac5dfa69bf325be478ebd0427953.

**Comment by wvu-r7** [comment]
Hey, closing this, @sempervictus. Lemme know if the commit works for you! If not, I can reopen. :)

**Comment by activeshadow** [comment]
@wvu-r7 I'm on commit 4a6fec7f (grabbed it last night) and I'm seeing this issue as well.

It can be reproduced by starting up `msfconsole`, creating a new workspace, and trying to run `db_nmap <remote host address> save`.

```
msf > db_nmap 172.21.21.100 save
[*] Nmap: Starting Nmap 6.47 ( http://nmap.org ) at 2015-05-31 07:47 EDT
...
[*] Nmap: Nmap done: 1 IP address (1 host up) scanned in 0.13 seconds
[-] Error while running command db_nmap: undefined method `workspace' for #<Msf::Ui::Console::CommandDispatcher::Db:0x007fa328e533a0>

Call stack:
/usr/local/share/metasploit-framework/lib/msf/core/auxiliary/report.rb:67:in `myworkspace'
/usr/local/share/metasploit-framework/lib/msf/core/auxiliary/report.rb:161:in `report_note'
/usr/local/share/metasploit-framework/lib/msf/core/auxiliary/report.rb:463:in `store_local'
/usr/local/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1876:in `report_store_local'
/usr/local/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1826:in `block in cmd_db_nmap'
/Users/activeshadow/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/usr/local/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1753:in `cmd_db_nmap'
/usr/local/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/local/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/local/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/local/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/local/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/local/share/metasploit-framework/lib/metasploit/framework/command/console.rb:38:in `start'
/usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
msf > 
```

**Comment by wvu-r7** [comment]
Thanks, @activeshadow. ```save``` it is. :)

**Comment by wvu-r7** [comment]
Oh, hey, I could have just read the title. :X

**Comment by wvu-r7** [comment]
Fixed in the linked PR. Thanks, everyone!
