### ISSUE TITLE
more fail_with improvements

### ISSUE THREAD

**Issue by FireFart** [rapid7/metasploit-framework#5200]
Another way to improve fail_with:
Using an auxiliary scanner module and using fail_with cancels the whole scan with an exception and a stacktrace:

```
sf auxiliary(test) > set RHOSTS 10.0.0.0/24
RHOSTS => 10.0.0.0/24
msf auxiliary(test) > run

[-] Auxiliary failed: RuntimeError Test: test
[-] Call stack:
[-]   /Users/firefart/Coding/metasploit-framework/lib/msf/core/module.rb:293:in `fail_with'
[-]   /Users/firefart/.msf4/modules/auxiliary/test.rb:24:in `run_host'
[-]   /Users/firefart/Coding/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /Users/firefart/Coding/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /Users/firefart/Coding/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

My suggestion would be:
- Only fail the current IP and continue with the next one
- Omit the stacktrace

Use case:
Currently we do a `vprint_error('msg')` and `return` on error. Using `fail_with` would be more intuitive on an error / unexpected reply in my opinion.

Testmodule:

```
##
# This module requires Metasploit: http://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

require 'msf/core'

class Metasploit3 < Msf::Auxiliary

  include Msf::Auxiliary::Scanner

  def initialize(info = {})
    super(update_info(info,
      'Name'           => 'Module name',
      'Description'    => %q{
        Say something that the user might want to know.
      },
      'Author'         => [ 'Name' ],
      'License'        => MSF_LICENSE
    ))
  end

  def run_host(ip)
    fail_with("Test", "test")
  end

end
```

CC @wchen-r7

**Comment by wchen-r7** [comment]
I actually like the ideas. How would you implement this? I feel like you might need a new exception class instead of raising RuntimeError?

**Comment by FireFart** [comment]
Jeah I think we need a new Exception Subclass and catch it at least in run_host

**Comment by busterb** [comment]
I think this is fixed now.
