### ISSUE TITLE
mysql_login scanner has an uncaught nil

### ISSUE THREAD

**Issue by all3g** [rapid7/metasploit-framework#5207]
**[Msf platform]**

    [root@localhost ~]# uname -a
    Linux localhost.localdomain 2.6.32-042stab104.1 #1 SMP Thu Jan 29 12:58:41 MSK 2015 i686 i686 i386 GNU/Linux
    
    [root@localhost ~]# cat /etc/issue
    CentOS release 6.6 (Final)
    Kernel \r on an \m
--------

When I try **auxiliary/scanner/mysql/mysql_login** to login mysql database, something as follow:

```
msf auxiliary(mysql_login) > show options 

Module options (auxiliary/scanner/mysql/mysql_login):

   Name              Current Setting          Required  Description
   ----              ---------------          --------  -----------
   BLANK_PASSWORDS   false                    no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                        yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      false                    no        Try each user/password couple stored in the current database
   DB_ALL_PASS       false                    no        Add all passwords in the current database to the list
   DB_ALL_USERS      false                    no        Add all users in the current database to the list
   PASSWORD          ispassnet                no        A specific password to authenticate with
   PASS_FILE                                  no        File containing passwords, one per line
   Proxies                                    no        A proxy chain of format type:host:port[,type:host:port][...]
   RHOSTS            file:///tmp/mysql_hosts  yes       The target address range or CIDR identifier
   RPORT             3306                     yes       The target port
   STOP_ON_SUCCESS   false                    yes       Stop guessing when a credential works for a host
   THREADS           1                        yes       The number of concurrent threads
   USERNAME          root                     no        A specific username to authenticate as
   USERPASS_FILE                              no        File containing users and passwords separated by space, one pair per line
   USER_AS_PASS      false                    no        Try the username as the password for all users
   USER_FILE                                  no        File containing usernames, one per line
   VERBOSE           true                     yes       Whether to print output for all attempts

msf auxiliary(mysql_login) > run

[*] 192.168.168.117:3306 MYSQL - Found remote MySQL version 5.4.3
[*] Error: 192.168.168.117: TypeError no implicit conversion of nil into String
[*] 192.168.168.133:3306 MYSQL - Found remote MySQL version 5.4.3
[-] Auxiliary failed: NoMethodError undefined method `unpack' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/lib/rbmysql/protocol.rb:237:in `block in read'
[-]   /home/centos/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
[-]   /home/centos/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
[-]   /home/centos/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[-]   /home/centos/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
[-]   /home/centos/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
[-]   /opt/metasploit-framework/lib/rbmysql/protocol.rb:235:in `read'
[-]   /opt/metasploit-framework/lib/rbmysql.rb:163:in `block in connect'
[-]   /opt/metasploit-framework/lib/rbmysql/protocol.rb:217:in `block in synchronize'
[-]   /opt/metasploit-framework/lib/rbmysql/protocol.rb:216:in `synchronize'
[-]   /opt/metasploit-framework/lib/rbmysql/protocol.rb:216:in `synchronize'
[-]   /opt/metasploit-framework/lib/rbmysql.rb:150:in `connect'
[-]   /opt/metasploit-framework/lib/rbmysql.rb:89:in `connect'
[-]   /opt/metasploit-framework/lib/metasploit/framework/login_scanner/mysql.rb:38:in `attempt_login'
[-]   /opt/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:216:in `block in scan!'
[-]   /opt/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:173:in `block in each_credential'
[-]   /opt/metasploit-framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
[-]   /opt/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:135:in `each_credential'
[-]   /opt/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:198:in `scan!'
[-]   /opt/metasploit-framework/modules/auxiliary/scanner/mysql/mysql_login.rb:71:in `run_host'
[-]   /opt/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

**Comment by bcook-r7** [comment]
Part of the plan here is to get this updated with the vendor code.
