### ISSUE TITLE
Session sync error

### ISSUE THREAD

**Issue by crmaxx** [rapid7/metasploit-framework#5233]
I use Cobalt-Strike with Metasploit Pro. After creating new meterpreter session in Cobalt-Strike, I tried to use this session in meterpreter in Metasploit Pro UI and got next error:

```
Session 12 Error: Msf::RPC::Exception Unknown Session ID 
["lib/msf/core/rpc/v10/rpc_base.rb:16:in `error'", 
"lib/msf/core/rpc/v10/rpc_session.rb:224:in `_valid_session'", 
"lib/msf/core/rpc/v10/rpc_session.rb:81:in `rpc_meterpreter_read'", 
"lib/msf/core/rpc/v10/service.rb:152:in `block in process'", 
"lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'", 
"lib/ruby/2.1.0/timeout.rb:35:in `block in catch'", 
"lib/ruby/2.1.0/timeout.rb:35:in `catch'", 
"lib/ruby/2.1.0/timeout.rb:35:in `catch'", 
"lib/ruby/2.1.0/timeout.rb:106:in `timeout'", 
"lib/msf/core/rpc/v10/service.rb:152:in `process'", 
"lib/msf/core/rpc/v10/service.rb:90:in `on_request_uri'", 
"lib/msf/core/rpc/v10/service.rb:72:in `block in start'", 
"lib/rex/proto/http/handler/proc.rb:38:in `call'", 
"lib/rex/proto/http/handler/proc.rb:38:in `on_request'", 
"lib/rex/proto/http/server.rb:364:in `dispatch_request'", 
"lib/rex/proto/http/server.rb:298:in `on_client_data'", 
"lib/rex/proto/http/server.rb:157:in `block in start'", 
"lib/rex/io/stream_server.rb:48:in `call'", 
"lib/rex/io/stream_server.rb:48:in `on_client_data'", 
"lib/rex/io/stream_server.rb:192:in `block in monitor_clients'", 
"lib/rex/io/stream_server.rb:190:in `each'", 
"lib/rex/io/stream_server.rb:190:in `monitor_clients'", 
"lib/rex/io/stream_server.rb:73:in `block in start'", 
"lib/rex/thread_factory.rb:22:in `call'", 
"lib/rex/thread_factory.rb:22:in `block in spawn'", 
"lib/msf/core/thread_manager.rb:100:in `call'", 
"lib/msf/core/thread_manager.rb:100:in `block in spawn'"]
```

After investigate the problem:

In Cobalt-Strike:
```
==== 
framework.sessions: {1=>#<Session:meterpreter 10.211.55.8:1160 (10.211.55.8) "LOCAL\dc.pentest @ PENTEST-6924C7C">}; 
sid: 1; 
type: meterpreter 
====
```

In same time in Metasploit:
```
==== 
framework.sessions: {}; 
sid: 1; 
type: meterpreter 
====
```

Looks like error in threads synchronization..

**Comment by wchen-r7** [comment]
Applying the Jira label since this talks about Pro.

**Comment by hmoore-r7** [comment]
Sessions are not portable between instances of the framework (in this case CS & Pro's daemon). This is also the case where sessions created in framework are not accessible in Pro. Sessions created in Pro are accessible to other Pro users, but not to the framework. The database is shared, but access to the live session is not.

**Comment by wchen-r7** [comment]
@crmaxx Like @hmoore-r7 said, they're on different instances they govern their own sessions. So this is the expected behavior.

**Comment by bcook-r7** [comment]
Cobalt Strike will need to be updated to resolve this issue.
