### ISSUE TITLE
The ssh_enumusers module throws a stack trace on check

### ISSUE THREAD

**Issue by hmoore-r7** [rapid7/metasploit-framework#5264]
Pulled from: http://security.stackexchange.com/questions/86167/metasploit-ssh-enumusers-stops-instantly

```
[-] Error while running command check: undefined method `rhost' for #<Msf::Modules::Mod617578696c696172792f7363616e6e65722f7373682f7373685f656e756d7573657273::Metasploit3:0xefb463c>

Call stack:
/opt/metasploit/apps/pro/msf3/lib/msf/ui/console/module_command_dispatcher.rb:135:in `cmd_check'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/opt/metasploit/apps/pro/msf3/lib/rex/ui/text/shell.rb:200:in `run'
/opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/console.rb:38:in `start'
/opt/metasploit/apps/pro/msf3/lib/metasploit/framework/command/base.rb:82:in `start'
/opt/metasploit/apps/pro/msf3/msfconsole:48:in `<main>'
```

**Comment by wvu-r7** [comment]
FWIW, it's not just this module. Checking this out.

**Comment by wvu-r7** [comment]
This looks like a regression from #2906. Affects all modules.
