### ISSUE TITLE
"creds" cannot be removed from database

### ISSUE THREAD

**Issue by matterpreter** [rapid7/metasploit-framework#5467]
When attempting to remove harvested credentials from the postgres database with `creds -d`, I receive the following error:
```
msf > creds -d -t ntlm
[-] Error while running command creds: PG::UndefinedTable: ERROR:  relation "mm_domino_nodes" does not exist
LINE 5:              WHERE a.attrelid = '"mm_domino_nodes"'::regclas...
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"mm_domino_nodes"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum


Call stack:
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `async_exec'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `exec_no_cache'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:660:in `block in exec_query'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1292:in `column_definitions'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:855:in `columns'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:229:in `yield'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:229:in `columns'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:238:in `columns_hash'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/locking/optimistic.rb:131:in `locking_enabled?'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:170:in `exec_queries'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:160:in `block in to_a'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/explain.rb:26:in `logging_query_plan'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation.rb:159:in `to_a'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation/finder_methods.rb:159:in `all'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:382:in `find_target'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:335:in `load_target'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/associations/collection_association.rb:157:in `delete_all'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/associations/builder/has_and_belongs_to_many.rb:21:in `destroy_associations'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/persistence.rb:129:in `destroy'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/locking/optimistic.rb:103:in `destroy'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `block in destroy'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:414:in `_run__2343756202611334463__destroy__1544155992919693324__callbacks'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_destroy_callbacks'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/callbacks.rb:254:in `destroy'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `block in destroy'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:313:in `block in with_transaction_returning_status'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:208:in `transaction'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:311:in `with_transaction_returning_status'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:254:in `destroy'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1102:in `block (2 levels) in creds_search'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation/batches.rb:21:in `block (2 levels) in find_each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation/batches.rb:21:in `each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation/batches.rb:21:in `block in find_each'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation/batches.rb:72:in `find_in_batches'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/relation/batches.rb:20:in `find_each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1052:in `block in creds_search'
/opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:129:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1019:in `creds_search'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1148:in `cmd_creds'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/plugins/msfd.rb:130:in `block in run'
msf > 
```

**Comment by shuckins-r7** [comment]
Hi, @matterpreter, thanks for the report. I wasn't able to reproduce this on latest master (a39539f8efcde6d950c24ef449b449570592ec1e). When you get a chance, please add some [additional detail](https://github.com/rapid7/metasploit-framework/blob/master/CONTRIBUTING.md#bug-reports) about your environment and the data that you have found triggers this issue.

Here's what I did:
```
msf > creds add-ntlm foobus 5cfe4c82d9ab8c66590f5b47cd6690f1:978a2e2e1dec9804c6b936f254727f9a
msf > creds
Credentials
===========

host         service              public    private                                                            realm      private_type
----         -------              ------    -------                                                            -----      ------------
                                  foobus    5cfe4c82d9ab8c66590f5b47cd6690f1:978a2e2e1dec9804c6b936f254727f9a             NTLM hash

msf > creds -d -t ntlm
Credentials
===========

host  service  public  private                                                            realm  private_type
----  -------  ------  -------                                                            -----  ------------
               foobus  5cfe4c82d9ab8c66590f5b47cd6690f1:978a2e2e1dec9804c6b936f254727f9a         NTLM hash

[*] Deleted 1 creds
msf > creds
Credentials
===========

host         service              public    private                              realm      private_type
----         -------              ------    -------                              -----      ------------

msf >
```

**Comment by matterpreter** [comment]
Hey @shuckins-r7. Currently running framework version 4.11.2-2015052901 (pulled from the Kali repos this morning) and Ruby 2.1.6p336. Is there any other info that would be more helpful?

**Comment by matterpreter** [comment]
Hey @shuckins-r7. Currently running framework version 4.11.2-2015052901 (pulled from the Kali repos this morning) and Ruby 2.1.6p336. Is there any other info that would be more helpful?

**Comment by shuckins-r7** [comment]
@matterpreter Sorry for the delay. This issue will be resolved once we release our next update with RoR 4. We are handling the dependencies between Pro and MSF gemfiles differently in that work, and a side effect will be the undefined relation shown in the error won't get called. That is slated for release this week or early next.
