### ISSUE TITLE
Crawler cannot save to database anymore - causes stack trace, faiils to collect anything.

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#5515]
Attempting to crawl a web page with auxiliary/scanner/http/crawler results in:
```
Crawler Exception: http://website.com:80/ can't cast Array to text
[
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/quoting.rb:78:in `type_cast'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/quoting.rb:105:in `type_cast'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:807:in `block in exec_cache'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:806:in `map'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql_adapter.rb:806:in `exec_cache'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:139:in `block in exec_query'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:442:in `block in log'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract_adapter.rb:437:in `log'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_query'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/postgresql/database_statements.rb:181:in `exec_insert'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:97:in `insert'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/relation.rb:76:in `insert'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/persistence.rb:513:in `_create_record'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/attribute_methods/dirty.rb:78:in `_create_record'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:306:in `block in _create_record'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__1437797228864876589__create__callbacks'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:306:in `_create_record'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/timestamp.rb:57:in `_create_record'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/persistence.rb:481:in `create_or_update'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:302:in `block in create_or_update'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:383:in `_run__1437797228864876589__save__callbacks'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/callbacks.rb:302:in `create_or_update'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/persistence.rb:125:in `save!'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/validations.rb:57:in `save!'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/attribute_methods/dirty.rb:41:in `save!'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/transactions.rb:275:in `block in save!'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/transactions.rb:330:in `block in with_transaction_returning_status'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `block in transaction'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `within_new_transaction'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/database_statements.rb:203:in `transaction'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/transactions.rb:209:in `transaction'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/transactions.rb:327:in `with_transaction_returning_status'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/transactions.rb:275:in `save!'",
 "/opt/metasploit4/msf4/lib/msf/core/db_manager/web.rb:148:in `block in report_web_page'",
 "/home/user/.rvm/gems/ruby-2.1.6@metasploit-framework/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'",
 "/opt/metasploit4/msf4/lib/msf/core/db_manager/web.rb:109:in `report_web_page'",
 "/opt/metasploit4/msf4/lib/msf/core/auxiliary/report.rb:315:in `report_web_page'",
 "/opt/metasploit4/msf4/modules/auxiliary/scanner/http/crawler.rb:124:in `crawler_process_page'",
 "/opt/metasploit4/msf4/lib/msf/core/auxiliary/crawler.rb:203:in `block in crawl_target'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:228:in `call'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:228:in `block in do_page_blocks'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:227:in `each'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:227:in `do_page_blocks'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:166:in `block in run'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:162:in `loop'",
 "/opt/metasploit4/msf4/lib/anemone/core.rb:162:in `run'",
 "/opt/metasploit4/msf4/lib/msf/core/auxiliary/crawler.rb:223:in `crawl_target'",
 "/opt/metasploit4/msf4/lib/msf/core/auxiliary/crawler.rb:152:in `block in run'",
 "/home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'",
 "/home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'",
 "/home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:35:in `catch'",
 "/home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:35:in `catch'",
 "/home/user/.rvm/rubies/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:106:in `timeout'",
 "/opt/metasploit4/msf4/lib/msf/core/auxiliary/crawler.rb:152:in `run'",
 "/opt/metasploit4/msf4/modules/auxiliary/scanner/http/crawler.rb:47:in `run'",
 "/opt/metasploit4/msf4/lib/msf/base/simple/auxiliary.rb:140:in `job_run_proc'",
 "/opt/metasploit4/msf4/lib/msf/base/simple/auxiliary.rb:76:in `block in run_simple'",
 "/opt/metasploit4/msf4/lib/rex/job_container.rb:37:in `call'",
 "/opt/metasploit4/msf4/lib/rex/job_container.rb:37:in `block in start'",
 "/opt/metasploit4/msf4/lib/rex/thread_factory.rb:22:in `call'",
 "/opt/metasploit4/msf4/lib/rex/thread_factory.rb:22:in `block in spawn'",
 "/opt/metasploit4/msf4/lib/msf/core/thread_manager.rb:100:in `call'",
 "/opt/metasploit4/msf4/lib/msf/core/thread_manager.rb:100:in `block in spawn'"
]
```
I dont have the cycles at present to dive this, but if anyone knows off the top of their head what we changed recently to cause this, would be grand to fix it...

**Comment by trosen-r7** [comment]
I can't reproduce this using Metasploitable's vulnerable TWiki install. Can you provide any information on what might possibly make your particular scan target an edge case here, @sempervictus ? Thanks!

**Comment by void-in** [comment]
@trosen-r7 I am consistently getting the same error as @sempervictus did. I am getting it every time I receive the first HTTP 200 response.

**Comment by sempervictus** [comment]
Example:
```
(2015-06-16)04:47 (S:0 J:4)msf  auxiliary(crawler) > set RHOST www.rapid7.com
RHOST => www.rapid7.com
(2015-06-16)04:47 (S:0 J:4)msf  auxiliary(crawler) > run 

[*] [2015.06.16-04:47:53] Crawling http://www.rapid7.com:80/...
[*] [2015.06.16-04:47:54] [00001/00500]    200 - www.rapid7.com - http://www.rapid7.com/
[-] [2015.06.16-04:47:54] Crawler Exception: http://www.rapid7.com:80/ can't cast Array to text 
```

**Comment by sempervictus** [comment]
@hmoore-r7 mentioned that this may be related to a DB migration issue resulting from the lag time in QA placing the migration temporally after another potentially dependent or conflicting one, but being named appropriately for the date on which the QA cycle started for the migration itself. 

Crawler is a rather important piece of framework, is this issue present in Pro and if so, could we kick this into the R7 corporate queue to fix with at least some tracking here? I dont have cycles to dig the migrations, since MDM and cousins have appeared i'm not nearly as in-tune with whats being done on the DB end from an AR standpoint. Most importantly, if this IS a migration issue, how do we fix this without screwing up existing data in the DB? We track real data in our client-facing framework instances, and there are many GB in there, so it would suck very badly to have to export and import all of it, especially as we use workspace identifiers in some custom code which then determines which ports are assigned to workspace-specific handlers and other runtime parameters, resource scripts, etc etc.

**Comment by bcook-r7** [comment]
@trosen-r7 is this the correct thing to do?

```
diff --git a/lib/msf/core/db_manager/web.rb b/lib/msf/core/db_manager/web.rb
index 414846b..ba00798 100644
--- a/lib/msf/core/db_manager/web.rb
+++ b/lib/msf/core/db_manager/web.rb
@@ -139,7 +139,7 @@ module Msf::DBManager::Web
     page.code     = code
     page.body     = body
     page.headers  = headers
-    page.cookie   = opts[:cookie] if opts[:cookie]
+    page.cookie   = opts[:cookie].to_s if opts[:cookie]
     page.auth     = opts[:auth]   if opts[:auth]
     page.mtime    = opts[:mtime]  if opts[:mtime]
     page.ctype    = opts[:ctype]  if opts[:ctype]
```

**Comment by trosen-r7** [comment]
@bcook-r7 probably, but I want to understand what made it change first. I suspect altered behavior in the PSQL driver between Rails 3x and 4.

@sempervictus, @void-in I'll make a ticket in the R7 internal JIRA when I get to the office today. Thanks for being persistent on this.

Should have a fix for this relatively quickly.

**Comment by bcook-r7** [comment]
Note, I put a PR above in with the potential fix, but as you said, there may be more to it - we can close that if there is a better solution. Thanks!

**Comment by trosen-r7** [comment]
@bcook-r7 yeah I edited my comments above b/c I had missed the PR due to toddler distractions and lack of coffee. I think your fix is ultimately the right one. I just want to do some minor investigation here to understand why/whether AR serialization behavior stopped acting the same as it did before, as that could be the cause of multiple other bugs. If the hunt for that root cause becomes a rabbit hole, I'll land this today.

**Comment by trosen-r7** [comment]
Tracking internally as MSP-12834

**Comment by trosen-r7** [comment]
@sempervictus check out my personal fork -- I have [a branch there](https://github.com/trevrosen/metasploit-framework/tree/bug/MSP-12834/crawler-choke-on-save) that builds off a branch of metasploit_data_models that contains a simple change. 

I was able to reproduce this bug reliably by setting up a test server that sets more than one cookie in the response, and this code gets past that problem, as well as getting past choking on a simple crawl of www.rapid7.com, which was reliably happening for @bcook-r7.

If this fixes the problem you were having, we'll roll in the fix and call it a day.

**Comment by sempervictus** [comment]
Confirmed working. Thanks.
Merge @ MDM layer and push new revision?

**Comment by sempervictus** [comment]
That was odd. Spoke too soon - second run of the SAME SITE just produced the same error.

**Comment by trosen-r7** [comment]
OK back on this today. Any other info you can give me about the site you're scraping so that I can add that to my test set up?

**Comment by sempervictus** [comment]
Unfortunately I can't publish the clients site due to NDA, but I did push
the relevant sanitized MDM::website params so we can try to mock up through
that. Most tomcat/jboss setups behind an f5 should double stack cookies
like this too...

**Comment by trosen-r7** [comment]
@sempervictus Going to land the fix here just to get past the current brokenness. @bcook-r7 has seen issues w/ the crawler choking on 504s as well. In other words, I think there are other issues here, and I want to investigate those after publishing the serialization fix, since we're currently dead in the water. I think that the Heisenbug nature of this is *not* due to the multiple cookies problem.
