### ISSUE TITLE
msfrpcd crash on windows

### ISSUE THREAD

**Issue by nuxlic** [rapid7/metasploit-framework#5604]
Hi, 
I'm trying to use the msfrpcd from my system console but an exception is raised. Metasploit was installed with the windows binary installer.  I have the last update installed (2015062101).

```
C:\Users\nuxlic>"C:\metasploit\ruby\bin\ruby.exe" "C:\metasploit\apps\pro\msf3\msfrpcd" -U msf -P msf -S -f -t Web -a 127.0.0.1 -p 51922 -t 99990000000
DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at C:/metasploit/apps/pro/ui/lib/metasploit/pro/ui.rb:16)
DL is deprecated, please use Fiddle
C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:464:in `each'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:464:in `block in eager_load!'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:462:in `each'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:462:in `eager_load!'
    from C:in `eager_load!'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:56:in `each'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `call'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
    from C:/metasploit/ruby/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
    from C:/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from C:/metasploit/apps/pro/msf3/config/environment.rb:5:in `<top (required)>'
    from C:/metasploit/apps/pro/msf3/lib/msfenv.rb:18:in `require'
    from C:/metasploit/apps/pro/msf3/lib/msfenv.rb:18:in `<top (required)>'
    from C:/metasploit/ruby/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/metasploit/ruby/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/metasploit/apps/pro/msf3/msfrpcd:18:in `<main>'

C:\Users\nuxlic>
```

**Comment by nuxlic** [comment]
Any fix available? How I can solve this?

**Comment by kgray-r7** [comment]
@nuxlic we've reproduced this in house and will look into it.

**Comment by nuxlic** [comment]
@kgray-r7 Thanks. Do you have a fix available?

**Comment by nuxlic** [comment]
Hi, I've just installed Metasploit 4.11.5 and the issue is still no fixed. Are you planning to fix in the next release?
Thanks

**Comment by nuxlic** [comment]
Hi @kgray-r7, I've installed the Framework from http://windows.metasploit.com/metasploitframework-latest.msi and I followed this guide https://community.rapid7.com/docs/DOC-3163 to install it, but I have the following problem when I try to use it.
```
C:\Users\nuxlic>msfconsole.bat
[*] Metasploit requires the Bundler gem to be installed
    $ gem install bundler

C:\Users\nuxlic> cd c:\metasploit-framework\embedded\bin
C:\metasploit-framework\embedded\bin>gem install bundler
ERROR:  Loading command: install (LoadError)
        126: The specified module could not be found.   - C:/metasploit-framework/embedded/lib/ruby/2.1.0/i386-mingw32/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

C:\metasploit-framework\embedded\bin>
```
But the file C:\metasploit-framework\embedded\lib\ruby\2.1.0\i386-mingw32\openssl.so exists.
The metasploit framework is the latest and was installed in a fresh windows 7. The capture of the console is a capture of the first run.

**Comment by bcook-r7** [comment]
hmm, that is odd. will take a look at it

**Comment by busterb** [comment]
Sorry for the late update, it appears to work correctly now. Thanks!

```
c:\metasploit-framework\bin>msfrpcd.bat -U msf -P msf -S -f -t Web -a 127.0.0.1 -p 51922 -t 99990000000
[*] MSGRPC starting on 127.0.0.1:51922 (NO SSL):Msg...
[*] MSGRPC ready at 2017-02-18 09:04:57 -0800.
```
