### ISSUE TITLE
unhandled nil response in ms15_034_http_sys_memory_dump

### ISSUE THREAD

**Issue by zeknox** [rapid7/metasploit-framework#5766]
Running the latest version of metasploit from the git repo.  Commit 264bc0f9218bda163a2d8c02373dd510ed66507d is the last commit I have via `git log`.  Running RVM with version 2.1.5 currently

msfconsole states `metasploit v4.11.3-dev-264bc0f9`

```ruby
msf auxiliary(ms15_034_http_sys_memory_dump) > run

[-] Auxiliary failed: NoMethodError undefined method `code' for nil:NilClass
[-] Call stack:
[-]   /opt/metasploit-framework/modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb:91:in `block in check_host'
[-]   /opt/metasploit-framework/modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb:80:in `each'
[-]   /opt/metasploit-framework/modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb:80:in `check_host'
[-]   /opt/metasploit-framework/modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb:167:in `run_host'
[-]   /opt/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
msf auxiliary(ms15_034_http_sys_memory_dump) >
```

**Comment by void-in** [comment]
```ruby
def check_host(ip)
  upper_range = 0xFFFFFFFFFFFFFFFF
  potential_static_files_uris.each do |potential_uri|
  uri = normalize_uri(potential_uri)

  res = send_request_raw(
    'uri' => uri,
    'method' => 'GET',
    'headers' => {
      'Range' => "bytes=0-#{upper_range}"
      }
    )

  vmessage = "#{peer} - Checking #{uri} [#{res.code}]"
```
Should first check if res and then print the res.code.

**Comment by wchen-r7** [comment]
connection or response timeout.
