### ISSUE TITLE
Metasploit XML export/import issue

### ISSUE THREAD

**Issue by infosecgeek** [rapid7/metasploit-framework#5837]
Failure to import Metasploit exported XML

The ```<address>``` elements within exported MetasploitV5 XML are populated with base64 encoded data resulting in db_import error.

To reproduce (example):
```
msf > db_export -f xml -a /tmp/db_export-import_test.xml
[*] Starting export of workspace export-test to /tmp/db_export-import_test.xml [ xml ]...
[*]     >> Starting export of report
[*]     >> Starting export of hosts
[*]     >> Starting export of events
[*]     >> Starting export of services
[*]     >> Starting export of web sites
[*]     >> Starting export of web pages
[*]     >> Starting export of web forms
[*]     >> Starting export of web vulns
[*]     >> Starting export of module details
[*]     >> Finished export of report
[*] Finished export of workspace export-test to /tmp/db_export-import_test.xml [ xml ]...

msf > workspace -a db_import-test
[*] Added workspace: db_import-test

msf > db_import /tmp/db_export-import_test.xml
[*] Importing 'Metasploit XML' data
[*] Importing host BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=
[-] Error while running command db_import: getaddrinfo: Name or service not known
```
Looking at the offending XML file, we see the aforementioned ```<address>``` element which appears to be causing the import issue:
```bash
head -n 8 /tmp/db_export-import_test.xml
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<MetasploitV5>
<generated time="2015-08-13 14:30:39 UTC" user="root" project="export_test" product="framework"/>
<hosts>
  <host>
    <id>11</id>
    <created-at>2015-08-13 14:30:30 UTC</created-at>
    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
```

Manually replacing the ```<address>``` element contents as referenced in the above example (BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=) with an IP address (192.168.1.1) allows for successful importation of file:
```
msf > db_import /tmp/db_export-import_test.xml
[*] Importing 'Metasploit XML' data
[*] Importing host 192.168.1.1
[*] Successfully imported /tmp/db_export-import_test.xml
```

I've also managed to reproduce the issue within a separate host running a clean Metasploit install.

Can someone else reproduce this / is this a known issue?

**Comment by bcook-r7** [comment]
The host address is base64 for this:

```
00000000  04 08 6f 3a 0b 49 50 41  64 64 72 08 3a 0c 40 66  |..o:.IPAddr.:.@f|
00000010  61 6d 69 6c 79 69 07 3a  0a 40 61 64 64 72 6c 2b  |amilyi.:.@addrl+|
00000020  07 01 01 a8 c0 3a 0f 40  6d 61 73 6b 5f 61 64 64  |.....:.@mask_add|
00000030  72 6c 2b 07 ff ff ff ff                           |rl+.....|
00000038
```

Do you know what module might have generated this address to begin with?

**Comment by infosecgeek** [comment]
For testing purposes the export was performed following a db_import of an nmap.xml output file (run using nmap outside of Metasploit). 

I just checked again using the following within Metasploit (separate instance each):
* db_nmap
* auxiliary/scanner/portscan/tcp
* auxiliary/scanner/discovery/arp_sweep
* auxiliary/scanner/http/http_version

and then again with all of the above listed checks combined. Still getting the same results:
```bash
ag '<address>'
```
```xml
db_export-test_http_version.xml
8:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>

db_export-test_arp-tcp-http-db_nmap_combined.xml
8:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
160:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
211:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAwGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
262:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
313:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
364:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBwGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
415:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
466:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHCgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
517:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHDAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
568:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHEAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
619:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHFAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
670:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHZAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
721:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHZgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
772:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHaAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>

db_export-test_arp_sweep.xml
8:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
59:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAwGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
110:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
161:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
212:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
263:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBwGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
314:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHBgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
365:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHCgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
416:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHDAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
467:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHEAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
518:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHFAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
569:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHZAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
620:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHZgGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
671:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHaAGowDoPQG1hc2tfYWRkcmwrB/////8=</address>

db_export-test_db_nmap.xml
8:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>

db_export-test_aux-tcp.xml
8:    <address>BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=</address>
```
Here is an import attempt from a new host running a clean Metasploit install with the full call stack:
```
msf > db_import /tmp/db_export-test_arp-tcp-http-db_nmap_combined.xml
[*] Importing 'Metasploit XML' data
[*] Importing host BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHAQGowDoPQG1hc2tfYWRkcmwrB/////8=
[-] Error while running command db_import: getaddrinfo: Name or service not known

Call stack:
/usr/share/metasploit-framework/lib/rex/socket.rb:181:in `gethostbyname'
/usr/share/metasploit-framework/lib/rex/socket.rb:181:in `getaddresses'
/usr/share/metasploit-framework/lib/rex/socket.rb:165:in `getaddress'
/usr/share/metasploit-framework/lib/msf/core/db_manager/host.rb:93:in `normalize_host'
/usr/share/metasploit-framework/lib/msf/core/db_manager/host.rb:159:in `block in report_host'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/usr/share/metasploit-framework/lib/msf/core/db_manager/host.rb:150:in `report_host'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/metasploit_framework/xml.rb:260:in `block in import_msf_xml'
/usr/lib/ruby/2.1.0/rexml/element.rb:902:in `block in each'
/usr/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
/usr/lib/ruby/2.1.0/rexml/xpath.rb:67:in `each'
/usr/lib/ruby/2.1.0/rexml/element.rb:902:in `each'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import/metasploit_framework/xml.rb:240:in `import_msf_xml'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:89:in `import'
/usr/share/metasploit-framework/lib/msf/core/db_manager/import.rb:136:in `import_file'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1630:in `block (3 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1623:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1623:in `block (2 levels) in cmd_db_import'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1617:in `each'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1617:in `block in cmd_db_import'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:1612:in `cmd_db_import'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'
```

**Comment by all3g** [comment]
```
msf > version 
Framework: 4.11.4-dev-38bacb7d
Console  : 4.11.4-dev-38bacb7d.15168
```

```
msf > db_export -f xml -a /tmp/out.xml
```

```
msf > db_import /tmp/out.xml
[*] Importing 'Metasploit XML' data
[*] Importing host BAhvOgtJUEFkZHIIOgxAZmFtaWx5aQc6CkBhZGRybCsHbsX7zToPQG1hc2tfYWRkcmwrB/////8=
[-] Error while running command db_import: getaddrinfo: Name or service not known

Call stack:
/opt/metasploit-framework/lib/rex/socket.rb:181:in `gethostbyname'
/opt/metasploit-framework/lib/rex/socket.rb:181:in `getaddresses'
/opt/metasploit-framework/lib/rex/socket.rb:165:in `getaddress'
/opt/metasploit-framework/lib/msf/core/db_manager/host.rb:93:in `normalize_host'
```

**Comment by jvazquez-r7** [comment]
Thanks @infosecgeek for your report! And @all3g for verification. As @bcook-r7 pointed, on V5 reports hosts data is base64 encoded, the contain are Mdm::Hosts data marshaled. I've provided a patch to have into account this serialized/encoded data. Fix is available here: https://github.com/rapid7/metasploit-framework/pull/5857  @infosecgeek feel free to test if this patch fixes your issue. Thanks!

**Comment by infosecgeek** [comment]
Thanks @jvazquez-r7 - I can confirm that the patch fixes the issue! (tested on 3 separate installs)

Example verification:
--------------------------
```
msf > db_import /tmp/import-test.xml
[*] Importing 'Metasploit XML' data
[*] Importing host 192.168.1.110
[*] Importing host 192.168.1.1
[*] Importing host 192.168.1.10
[*] Importing host 192.168.1.7
[*] Importing host 192.168.1.20
[*] Importing host 192.168.1.114
[*] Importing host 192.168.1.5
[*] Importing host 192.168.1.3
[*] Importing host 192.168.1.112
[*] Importing host 192.168.1.16
[*] Importing host 192.168.1.11
[*] Successfully imported /tmp/test.xml
```

**Comment by jvazquez-r7** [comment]
cool, thanks @infosecgeek  :)
