### ISSUE TITLE
vnc_none_auth - Auxiliary failed: RuntimeError Handshake failed: Unable to obtain banner from server

### ISSUE THREAD

**Issue by all3g** [rapid7/metasploit-framework#6078]
When I am scanning **192.168.10.1/24** for no-auth vnc services, threads throws an exception.

```
msf auxiliary(vnc_none_auth) > show options 

Module options (auxiliary/scanner/vnc/vnc_none_auth):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   RHOSTS   192.168.10.1/24  yes       The target address range or CIDR identifier
   RPORT    5900             yes       The target port
   THREADS  10               yes       The number of concurrent threads

msf auxiliary(vnc_none_auth) > run

[-] 192.168.10.1:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.2:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.9:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.8:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.5:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.4:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.7:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.3:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.6:5900, Handshake failed: Unable to obtain banner from server
[-] 192.168.10.10:5900, Handshake failed: Unable to obtain banner from server
[-] Auxiliary failed: RuntimeError Handshake failed: Unable to obtain banner from server
[-] Call stack:
[-]   /opt/metasploit-framework/modules/auxiliary/scanner/vnc/vnc_none_auth.rb:44:in `run_host'
[-]   /opt/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:116:in `block (2 levels) in run'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `call'
[-]   /opt/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

**Comment by all3g** [comment]
Thanks.
