### ISSUE TITLE
post/windows/gather/forensics/enum_drives fails on php meterpreter

### ISSUE THREAD

**Issue by jvazquez-r7** [rapid7/metasploit-framework#6158]
Target: Vmware vm running XP SP3, session with default administrator privileges

fails when using railgun

```
msf post(enum_drives) > set session 3
session => 3
msf post(enum_drives) > run
Device Name: Type: Size (bytes):
------------ ----- -------------
<Physical Drives:>
[-] [2015.10.29-13:19:00] Post failed: Rex::Post::Meterpreter::RequestError stdapi_railgun_api: Operation failed: 1
[-] [2015.10.29-13:19:00] Call stack:
[-] [2015.10.29-13:19:00] /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb:262:in `process_function_call'
[-] [2015.10.29-13:19:00] /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb:84:in `call_function'
[-] [2015.10.29-13:19:00] /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll_wrapper.rb:24:in `method_missing'
[-] [2015.10.29-13:19:00] /Users/jvazquez/Projects/Code/metasploit-framework/modules/post/windows/gather/forensics/enum_drives.rb:37:in `print_device'
[-] [2015.10.29-13:19:00] /Users/jvazquez/Projects/Code/metasploit-framework/modules/post/windows/gather/forensics/enum_drives.rb:74:in `block in run'
[-] [2015.10.29-13:19:00] /Users/jvazquez/.rvm/gems/ruby-2.1.7@pro/gems/activesupport-4.0.13/lib/active_support/core_ext/range/each.rb:7:in `each'
[-] [2015.10.29-13:19:00] /Users/jvazquez/.rvm/gems/ruby-2.1.7@pro/gems/activesupport-4.0.13/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
[-] [2015.10.29-13:19:00] /Users/jvazquez/Projects/Code/metasploit-framework/modules/post/windows/gather/forensics/enum_drives.rb:72:in `run'
[*] Post module execution completed

```

**Comment by bcook-r7** [comment]
Duping to #6152
