### ISSUE TITLE
post/windows/gather/win_privs fails on python meterpreter

### ISSUE THREAD

**Issue by jvazquez-r7** [rapid7/metasploit-framework#6162]
Target: VMWare vm XP SP3, session with default administrator privileges

fails on railgun usage

```
msf post(win_privs) > set session 4
session => 4
msf post(win_privs) > run
[-] [2015.10.29-13:26:13] Post failed: Rex::Post::Meterpreter::RequestError stdapi_railgun_api: Operation failed: Unknown error
[-] [2015.10.29-13:26:13] Call stack:
[-] [2015.10.29-13:26:13] /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb:262:in `process_function_call'
[-] [2015.10.29-13:26:13] /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll.rb:84:in `call_function'
[-] [2015.10.29-13:26:13] /Users/jvazquez/Projects/Code/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/dll_wrapper.rb:24:in `method_missing'
[-] [2015.10.29-13:26:13] /Users/jvazquez/Projects/Code/metasploit-framework/lib/msf/core/post/windows/accounts.rb:156:in `resolve_sid'
[-] [2015.10.29-13:26:13] /Users/jvazquez/Projects/Code/metasploit-framework/lib/msf/core/post/windows/priv.rb:67:in `is_system?'
[-] [2015.10.29-13:26:13] /Users/jvazquez/Projects/Code/metasploit-framework/modules/post/windows/gather/win_privs.rb:44:in `run'
[*] Post module execution completed
msf post(win_privs) >

```

**Comment by bcook-r7** [comment]
Duping to #6148
