### ISSUE TITLE
metasploit and raild-ruby-gems not compatible

### ISSUE THREAD

**Issue by zprin0212** [rapid7/metasploit-framework#6184]
how can i fix it ???

```
==========================================================
msfconsole -qx "db_status; exit"
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'metasploit-framework' (>= 0) among 123 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.2.1@rails4.2.5:/usr/local/rvm/gems/ruby-2.2.1@global', execute `gem env` for more information
	from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec' 	from usr/local/rvm/rubies/ruby-.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/rvm/gems/ruby-2.2.1@rails4.2.5/bin/msfconsole:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1@rails4.2.5/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1@rails4.2.5/bin/ruby_executable_hooks:15:in `<main>'
=====================================================================
```

**Comment by bcook-r7** [comment]
Use Ruby 2.1.7, which is the currently-supported version.

**Comment by wchen-r7** [comment]
@zprin0212 This isn't a Metasploit bug so I will go ahead and close this. If you need help on setting up the environment correctly, you can start a discussion at the Rapid7 Community website, and there's always people happy to help: https://community.rapid7.com/community/metasploit/content?filterID=contentstatus%5Bpublished%5D~objecttype~objecttype%5Bthread%5D
