### ISSUE TITLE
Cannot stream from webcam using Meterpreter

### ISSUE THREAD

**Issue by SuicSoft** [rapid7/metasploit-framework#6361]
Hi,
When i try streaming from the webcam with ```run webcam -p ~/webcam.htm``` the light turns on for a second and then it goes off and i get:
```
[*] Starting webcam 1: USB Video Device
[*] imagepath is ~/webcam.htm/webcam-00000.jpg
[-] Error getting frame: Errno::ENOENT No such file or directory @ rb_sysopen - ~/webcam.htm/webcam.htm ["/opt/metasploit-framework/embedded/framework/lib/rex/script/base.rb:146:in `initialize'", "/opt/metasploit-framework/embedded/framework/lib/rex/script/base.rb:146:in `open'", "/opt/metasploit-framework/embedded/framework/lib/rex/script/base.rb:146:in `run'", "/opt/metasploit-framework/embedded/framework/lib/rex/script/base.rb:43:in `eval'", "/opt/metasploit-framework/embedded/framework/lib/rex/script/base.rb:43:in `run'", "/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:224:in `execute_file'", "/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/scriptable.rb:123:in `execute_script'", "/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb:1121:in `cmd_run'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'", "/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'", "/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:193:in `call'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:193:in `run'", "/opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'", "/opt/metasploit-framework/embedded/framework/lib/msf/base/sessions/meterpreter.rb:436:in `_interact'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/interactive.rb:49:in `interact'", "/opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/core.rb:1938:in `cmd_sessions'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'", "/opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:203:in `run'", "/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'", "/opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'", "/opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'"]
[*] Stopping webcam
```

I can take webcam snapshots with ```webcam_snap``` but can't stream. The box which is getting attacked is a Windows XP VirtualBox VM with Webcam enabled. The XP VM is using whatever drivers it installed by default. I am using Elementary OS Freya and an integrated laptop webcam (HP Webcam-50)

**Comment by SuicSoft** [comment]
Forgot that i could use ```webcam_stream``` :smile:
