### ISSUE TITLE
Net::DNS improperly (?) handles CNAMEs > 63 characters

### ISSUE THREAD

**Issue by jhart-r7** [rapid7/metasploit-framework#6447]
I encountered this while testing https://github.com/rapid7/metasploit-framework/pull/6187 (see https://github.com/rapid7/metasploit-framework/pull/6187#discussion_r48919944):

```
>> Net::DNS::Packet.parse(IO.read("/home/jhart/dns.bin"))
ArgumentError: Label data cannot exceed 63 chars
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/names/names.rb:50:in `pack_name'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/rr/cname.rb:31:in `build_pack'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/rr.rb:335:in `new_from_binary'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/rr.rb:176:in `parse_packet'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/rr.rb:327:in `new_from_binary'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/rr.rb:176:in `parse_packet'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/packet.rb:522:in `block in new_from_data'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/packet.rb:521:in `times'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/packet.rb:521:in `new_from_data'
	from /home/jhart/rapid7/metasploit-framework/lib/net/dns/packet.rb:153:in `parse'
	from (irb):6:in `cmd_irb'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/irb_shell.rb:53:in `block in run'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `catch'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/irb_shell.rb:52:in `run'
	from /home/jhart/rapid7/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:882:in `cmd_irb'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
	from /home/jhart/rapid7/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
	from /home/jhart/rapid7/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /home/jhart/rapid7/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
```

IIRC, the RFC makes this restriction because of how DNS labels are compressed, but this was also the same RFC which prohibited DNS names from starting with numbers which has since been relaxed.  It also appears that other tools seem to handle these longer names without issue:

```
$  host spoofed.co                                                                       
spoofed.co is an alias for pr-co-suspensions.neuweb.biz.
pr-co-suspensions.neuweb.biz is an alias for WS-PR-WEB-suspensionpages-1962938698.us-east-1.elb.amazonaws.com.
WS-PR-WEB-suspensionpages-1962938698.us-east-1.elb.amazonaws.com has address 54.174.168.184
WS-PR-WEB-suspensionpages-1962938698.us-east-1.elb.amazonaws.com has address 52.22.183.58
$  echo -n WS-PR-WEB-suspensionpages-1962938698.us-east-1.elb.amazonaws.com |wc -c  
      64
```

I'm unsure if/how we should fix this.

**Comment by all3g** [comment]
File: ```/path/to/metasploit-framework/lib/net/dns/names/names.rb```

      def pack_name(name)
        if name.size > 63
          raise ArgumentError, "Label data cannot exceed 63 chars"
        end
        arr = name.split(".")
        str = ""
        arr.each do |elem|
          str += [elem.size,elem].pack("Ca*")
        end
        str += [0].pack("C")
        str
      end

**Comment by jhart-r7** [comment]
It may be as simple as removing that check, but I don't know if there is elsewhere in the code where it is expected that names > 63 characters will be packed and (mis)represented.  A unit test should help prove if all is well enough.

**Comment by all3g** [comment]
@jhart-r7  A domain can be marked as ```label```.```label```.```label```.```label```..... 
ex: **dev.rapid7.com** has 3 labels.

- dev <= 63
- rapid 7 <= 63
- com <= 63
- dev.rapid7.com <= 255

We should give a pr to fix ```if name.size > 63``` to ```if name.size > 255```
