### ISSUE TITLE
failed to unload or get help of event_tester

### ISSUE THREAD

**Issue by all3g** [rapid7/metasploit-framework#6522]
MSF Version:

```
metasploit-framework [upstream] ruby --version
ruby 2.1.7p400 (2015-08-18 revision 51632) [x86_64-darwin15.0]
```

```
msf > version 
Framework: 4.11.9-dev-37f077c
Console  : 4.11.9-dev-37f077c.15168
```

When **event_tester** is loaded, I can not unload **event_tester**, or exit msf console.

```
msf auxiliary(tcp) > load event_tester 
[*] Successfully loaded plugin: event_tester
msf auxiliary(tcp) > help
[-] Error while running command help: wrong number of arguments (2 for 1)

Call stack:
/Users/Open-Security/Code/metasploit-framework/plugins/event_tester.rb:10:in `respond_to?'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:182:in `block in method_missing'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `each'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
/Users/Open-Security/Code/metasploit-framework/lib/msf/ui/console/command_dispatcher.rb:24:in `block in initialize'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:388:in `call'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:388:in `block in run_single'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/Users/Open-Security/Code/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/Open-Security/Code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

```
msf auxiliary(tcp) > unload event_tester 
[-] Error while running command unload: wrong number of arguments (2 for 1)

Call stack:
/Users/Open-Security/Code/metasploit-framework/plugins/event_tester.rb:10:in `respond_to?'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:182:in `block in method_missing'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `each'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
/Users/Open-Security/Code/metasploit-framework/lib/msf/ui/console/command_dispatcher.rb:24:in `block in initialize'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:388:in `call'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:388:in `block in run_single'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/Users/Open-Security/Code/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/Open-Security/Code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

```
msf > exit 
[-] Error while running command exit: wrong number of arguments (2 for 1)

Call stack:
/Users/Open-Security/Code/metasploit-framework/plugins/event_tester.rb:10:in `respond_to?'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:182:in `block in method_missing'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `each'
/Users/Open-Security/Code/metasploit-framework/lib/msf/core/event_dispatcher.rb:181:in `method_missing'
/Users/Open-Security/Code/metasploit-framework/lib/msf/ui/console/driver.rb:551:in `block in on_startup'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:388:in `call'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:388:in `block in run_single'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Users/Open-Security/Code/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/Users/Open-Security/Code/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/Open-Security/Code/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

**Comment by wchen-r7** [comment]
Fixed in https://github.com/rapid7/metasploit-framework/pull/6523 I assume.
