### ISSUE TITLE
Auxiliary failed: NameError  so. not fixed?

### ISSUE THREAD

**Issue by caspah** [rapid7/metasploit-framework#6654]
```
[-] [2016.03.08-02:22:40] Auxiliary failed: NameError undefined local variable or method `pro_john_executable' for #<Msf::Modules::Mod617578696c696172792f616e616c797a652f6a74725f637261636b5f66617374::Metasploit3:0x007f3b19385800>
[-] [2016.03.08-02:22:40] Call stack:
[-] [2016.03.08-02:22:40]   /opt/metasploit/apps/pro/engine/lib/pro/hooks/packaged_john_hook.rb:54:in `new_john_cracker'
[-] [2016.03.08-02:22:40]   /opt/metasploit/apps/pro/vendor/bundle/ruby/2.1.0/gems/metasploit-framework-4.11.12/modules/auxiliary/analyze/jtr_crack_fast.rb:31:in `run'
```

**Comment by bcook-r7** [comment]
Thanks. So we're clear, did you see this running the auxiliary/analyze/jtr_crack_fast module, or was it some other context?

**Comment by bcook-r7** [comment]
This will be in next week's Pro release. Thanks!
