### ISSUE TITLE
/usr/share/metasploit-framework/lib/metasploit/framework.rb:18:in `require': cannot load such file -- robots (LoadError)

### ISSUE THREAD

**Issue by greenhand2learn** [rapid7/metasploit-framework#6712]
```
> ./msfconsole 
/usr/share/metasploit-framework/lib/metasploit/framework.rb:18:in `require': cannot load such file -- robots (LoadError)
    from /usr/share/metasploit-framework/lib/metasploit/framework.rb:18:in `<top (required)>'
    from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `require'
    from /usr/share/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
    from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
    from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
    from /usr/share/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
    from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:228:in `const_get'
    from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:228:in `block in constantize'
    from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `each'
    from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `inject'
    from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `constantize'
    from /usr/share/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
    from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
    from ./msfconsole:48:in `<main>'
```

```
> ruby -v
ruby 2.2.4p230 (2015-12-16) [x86_64-linux-gnu]
> bundle -v
Bundler version 1.11.2
> gem -v
2.5.1

```

how could i solve the problem? i have made some changes, maybe made the wrong change, could someone tell me how to solve it ? thank you very much!

**Comment by busterb** [comment]
Permissions issue. We recommend using RVM or a pre-built package over rolling your own metasploit install, but the fix is pretty simple:

https://github.com/rapid7/metasploit-omnibus/blob/master/config/software/metasploit-framework.rb#L57

**Comment by greenhand2learn** [comment]
@busterb  thank you , you said permissions issue, so i chmod 755 robots.rb, now it's workd! never thought it' just a permissions issue.

**Comment by bcook-r7** [comment]
This issue has been unfixed in the upstream gem for almost 5 years: https://github.com/fizx/robots/issues/6

Given how simple this gem is vs all the trouble it has caused, I wonder if we shouldn't just reimplement the functionality in rex :P. Its sort of our personal left-pad :)
