### ISSUE TITLE
RHOSTS file:/ pulls entire list into field

### ISSUE THREAD

**Issue by mubix** [rapid7/metasploit-framework#6718]
## Steps to reproduce

How'd you do it?

1. Make a file with 172.16.0.0/16
2. Use makeiplist.rb to generate it into a large IP list and output as iplist.txt
3. set RHOSTS on a scanner module to the iplist.txt file you've generated

## Expected behavior

RHOSTS should stay saying `RHOSTS file:/tmp/iplist.txt`

## Current behavior

RHOSTS has (I picked the 15.210.0.0/16 range at random):
 
```
5.210.247.177 15.210.192.48 15.210.201.154 15.210.32.19 15.210.186.159 15.210.73.45 15.210.134.241 15.210.208.201 15.210.145.182 15.210.105.85 15.210.184.50 15.210.31.80 15.210.3.126 15.210.174.16 15.210.58.197 15.210.12.166 15.210.185.145 15.210.69.129 15.210.73.124 15.210.11.126 15.210.200.164 15.210.15.97 15.210.205.56 15.210.159.148 15.210.172.20 15.210.172.134 15.210.92.92 15.210.24.223 15.210.93.40 15.210.138.64 15.210.20.218 15.210.24.17 15.210.54.171 15.210.29.220 15.210.17.204 15.210.148.152 15.210.83.128 15.210.140.49 15.210.253.125 15.210.56.134 15.210.153.232 15.210.11.169 15.210.146.23 15.210.170.39 15.210.51.234 15.210.241.123 15.210.128.76 15.210.111.62 15.210.140.243 15.210.141.50 15.210.59.54 15.210.12.186 15.210.184.222 15.210.128.208 15.210.233.179 15.210.148.161 15.210.49.199 15.210.107.218 15.210.127.171 15.210.168.64 15.210.65.85 15.210.72.146 15.210.56.31 15.210.167.145 15.210.149.181 15.210.164.134 15.210.61.212 15.210.6.93 15.210.113.234 15.210.56.224 15.210.47.57 15.210.245.214 15.210.220.206 15.210.131.128 15.210.247.167 15.210.86.150 15.210.103.222 15.210.126.77 15.210.197.29 15.210.41.161 15.210.215.15 15.210.25.243 15.210.141.106 15.210.30.125 15.210.45.39 15.210.103.78 15.210.3.140 15.210.138.235 15.210.242.83 15.210.25.7 15.210.112.19 15.210.238.10 15.210.94.98 15.210.150.162 15.210.130.200 15.210.200.12 15.210.234.193 15.210.185.94 15.210.186.66 15.210.97.230 15.210.2.214 15.210.71.30 15.210.181.191 15.210.32.186 15.210.249.168 15.210.87.243 15.210.229.120 15.210.96.116 15.210.66.140 15.210.73.138 15.210.202.30 15.210.4.40 15.210.195.58 15.210.177.144 15.210.252.107 15.210.123.74 15.210.178.158 15.210.47.139 15.210.31.238 15.210.98.203 15.210.175.32 15.210.184.128 15.210.230.96 15.210.112.44 15.210.120.14 15.210.250.170 15.210.152.160 15.210.163.73 15.210.8.61 15.210.47.140 15.210.8.13 15.210.150.51 15.210.211.90 15.210.243.200 15.210.59.110 15.210.29.169 15.210.116.122 15.210.8.89 15.210.147.159 15.210.124.78 15.210.130.124 15.210.22.94 15.210.158.105 15.210.202.127 15.210.120.15 15.210.189.168 15.210.200.173 15.210.10.255 15.210.240.44 15.210.207.218 15.210.19.221 15.210.24.64 15.210.58.123 15.210.60.38 15.210.227.132 15.210.229.106 15.210.217.199 15.210.83.3 15.210.184.200 15.210.101.255 15.210.201.43 15.210.62.232 15.210.223.211 15.210.213.18 15.210.60.167 15.210.230.109 15.210.47.133 15.210.151.126 15.210.193.45 15.210.49.179 15.210.140.130 15.210.207.157 15.210.41.96 15.210.215.17 15.210.41.211 15.210.30.234 15.210.227.142 15.210.123.91 15.210.227.26 15.210.114.235 15.210.16.47 15.210.82.128 15.210.206.92 15.210.21.96 15.210.162.55 15.210.203.10 15.210.155.236 15.210.233.155 15.210.172.1 15.210.123.217 15.210.238.64 15.210.199.254 15.210.245.50 15.210.36.132 15.210.225.30 15.210.10.185 15.210.75.171 15.210.92.128 15.210.27.89 15.210.18.75 15.210.5.21 15.210.167.55 15.210.31.125 15.210.141.174 15.210.139.42 15.210.144.108 15.210.133.238 15.210.153.4 15.210.98.170 15.210.119.49 15.210.136.16 15.210.149.11 15.210.174.65 15.210.177.204 15.210.84.206 15.210.30.34 15.210.163.226 15.210.109.202 15.210.51.212 15.210.57.55 15.210.7.111 15.210.106.96 15.210.140.14 15.210.32.235 15.210.46.173 15.210.245.106 15.210.220.168 15.210.187.162 15.210.167.217 15.210.100.41 15.210.129.139 15.210.93.106 15.210.70.108 15.210.127.28 15.210.217.234 15.210.67.22 15.210.53.76 15.210.176.7 15.210.2.217 15.210.9.30 15.210.202.214 15.210.0.27 15.210.157.12 15.210.128.74 15.210.205.47 15.210.193.118 15.210.53.54 15.210.78.253 15.210.103.129 15.210.193.173 15.210.187.118 15.210.215.117 15.210.239.210 15.210.129.108 15.210.248.81 15.210.200.221 15.210.66.109 15.210.118.193 15.210.108.124 15.210.136.161 15.210.178.12 15.210.84.108 15.210.41.146 15.210.108.34 15.210.24.143 15.210.128.163 15.210.35.127 15.210.23.82 15.210.227.23 15.210.19.52 15.210.220.19 15.210.187.45 15.210.77.12 15.210.161.227 15.210.58.118 15.210.86.39 15.210.58.203 15.210.105.232 15.210.41.12 15.210.17.80 15.210.170.54 15.210.224.5 15.210.64.238 15.210.192.85 15.210.79.46 15.210.239.43 15.210.170.78 15.210.24.86 15.210.86.7 15.210.227.236 15.210.235.207 15.210.207.240 15.210.150.230 15.210.68.243 15.210.172.108 15.210.183.6 15.210.9.195 15.210.229.43 15.210.219.204 15.210.216.212 15.210.62.40 15.210.244.67 15.210.216.56 15.210.93.87 15.210.187.0 15.210.180.82 15.210.40.133 15.210.159.164 15.210.169.59 15.210.128.9 15.210.129.134 15.210.139.187 15.210.223.94 15.210.149.71 15.210.161.201 15.210.56.12 15.210.238.241 15.210.11.32 15.210.39.2 15.210.13.42 15.210.47.3 15.210.128.209 15.210.162.167 15.210.205.65 15.210.5.239 15.210.99.6 15.210.207.168 15.210.169.180 15.210.241.151 15.210.92.109 15.210.214.220 15.210.100.215 15.210.103.8 15.210.83.67 15.210.74.62 15.210.82.218 15.210.255.235 15.210.151.69 15.210.39.74 15.210.230.190 15.210.208.147 15.210.219.252 15.210.46.25 15.210.82.84 15.210.233.189 15.210.171.226 15.210.107.143 15.210.57.64 15.210.123.255 15.210.142.151 15.210.178.164 15.210.174.19 15.210.30.151 15.210.137.236 15.210.176.32 15.210.222.46 15.210.35.15 15.210.220.76 15.210.222.130 15.210.239.191 15.210.74.2 15.210.115.33 15.210.204.95 15.210.214.227 15.210.92.227 15.210.198.32 15.210.183.181 15.210.18.126 15.210.14.49 15.210.144.187 15.210.120.32 15.210.231.243 15.210.177.125 15.210.89.117 15.210.47.156 15.210.234.20 15.210.71.250 15.210.177.219 15.210.41.228 15.210.139.180 15.210.91.158 15.210.230.34 15.210.234.66 15.210.245.17 15.210.93.249 15.210.251.127 15.210.215.71 15.210.103.161 15.210.170.191 15.210.208.36 15.210.140.152 15.210.39.195 15.210.155.74 15.210.245.124 15.210.62.140 15.210.12.206 15.210.157.33 15.210.82.61 15.210.208.153 15.210.246.177 15.210.139.237 15.210.252.7 15.210.184.111 15.210.27.0 15.210.208.190 15.210.192.83 15.210.249.93 15.210.98.230 15.210.118.161 15.210.190.151 15.210.105.208 15.210.121.210 15.210.55.232 15.210.64.147 15.210.97.231 15.210.94.203 15.210.201.251 15.210.164.120 15.210.171.24 15.210.219.37 15.210.138.126 15.210.134.246 15.210.251.33 15.210.205.150 15.210.10.199 15.210.108.27 15.210.89.99 15.210.233.156 15.210.62.13 15.210.187.248 15.210.251.47 15.210.248.39 15.210.229.7 15.210.160.16 15.210.25.55 15.210.63.240 15.210.8.177 15.210.233.117 15.210.249.207 15.210.110.237 15.210.49.211 15.210.247.252 15.210.254.246 15.210.130.117 15.210.125.177 15.210.76.130 15.210.248.214 15.210.23.205 15.210.38.52 15.210.65.122 15.210.95.135 15.210.41.184 15.210.2.222 15.210.183.34 15.210.36.114 15.210.0.1 15.210.39.224 15.210.76.87 15.210.173.32 15.210.135.215 15.210.18.80 15.210.109.86 15.210.21.31 15.210.126.190 15.210.24.114 15.210.233.219 15.210.174.12 15.210.7.241 15.210.47.111 15.210.132.27 15.210.182.33 15.210.13.84 15.210.249.118 15.210.119.195 15.210.67.31 15.210.242.206 15.210.194.240 15.210.189.247 15.210.182.164 15.210.65.82 15.210.82.81 15.210.168.36 15.210.155.6 15.210.16.118 15.210.253.140 15.210.133.194 15.210.145.27 15.210.151.56 15.210.87.148 15.210.227.114 15.210.160.21 15.210.45.165 15.210.149.50 15.210.38.252 15.210.225.66 15.210.212.175 15.210.75.216 15.210.129.161 15.210.20.228 15.210.52.9 15.210.253.41 15.210.68.113 15.210.81.161 15.210.179.66 15.210.132.139 15.210.252.33 15.210.118.166 15.210.151.145 15.210.189.73 15.210.65.235 15.210.225.164 15.210.174.5 15.210.242.175 15.210.54.228 15.210.138.82 15.210.22.144 15.210.2.188 15.210.254.152 15.210.119.90 15.210.22.247 15.210.211.167 15.210.123.11 15.210.139.192 15.210.249.28 15.210.9.35 15.210.219.230 15.210.8.33 15.210.94.25 15.210.65.170 15.210.23.217 15.210.246.78 15.210.38.106 15.210.16.199 15.210.93.58 15.210.205.27 15.210.164.54 15.210.55.15 15.210.14.32 15.210.175.175 15.210.153.137 15.210.98.130 15.210.123.185 15.210.248.118 15.210.151.116 15.210.223.55 15.210.106.140 15.210.160.120 15.210.150.142 15.210.235.74 15.210.186.3 15.210.219.169
```

### Metasploit version

Latest git version as of this post

### I installed Metasploit with:
- [ ] Source install (2.1.8)

### OS

Debian/Ubuntu

**Comment by mubix** [comment]
Just got this by trying to set RHOSTS from the database
```
[-] Error while running command services: The following options failed to validate: Value 'file:/tmp/msf-db-rhosts-20160329-19094-1l4oola' is not valid for option 'RHOSTS', try harder.

Call stack:
/opt/metasploit-framework/lib/msf/core/data_store.rb:33:in `[]='
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:2080:in `set_rhosts_from_addrs'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:698:in `block in cmd_services'
/opt/rubies/ruby-2.1.8/lib/ruby/gems/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
/opt/metasploit-framework/lib/msf/ui/console/command_dispatcher/db.rb:527:in `cmd_services'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/opt/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/opt/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/opt/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/opt/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

**Comment by hdm** [comment]
The options failed to validate, what is in RHOSTS?

**Comment by bcook-r7** [comment]
Discussed on IRC, looks like we validate the file before it actually gets written to disk. It looks like we need to make validation weaker for file types.
