### ISSUE TITLE
Windows error: TZInfo::DataSourceNotFound

### ISSUE THREAD

**Issue by hawaii67** [rapid7/metasploit-framework#6884]
I downloaded the nightly build version of metasploit 4.12 for Windows on 5/17/2016:

df5da16b7d8b91b484409bf2f4131b08 *metasploit-framework-4.11.27+20160513092444-1rapid7-1.msi

Staring msfconsole spits out the following error message:

```
_C:\metasploit-framework\bin>msfconsole.bat
C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:179:in `create_default_data_source'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:40:in `block in get'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:39:in `synchronize'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:39:in `get'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:629:in `data_source'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:92:in `get'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb:67:in `real_timezone'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb:30:in `period_for_utc'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:549:in `current_period'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/values/time_zone.rb:282:in `utc_offset'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/values/time_zone.rb:243:in `block in []'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/values/time_zone.rb:243:in `tap'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/values/time_zone.rb:243:in `[]'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/core_ext/time/zones.rb:61:in `find_zone!'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/railtie.rb:20:in `block in <class:Railtie>'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from C:/metasploit-framework/embedded/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
        from C:/metasploit-framework/embedded/framework/config/environment.rb:5:in `<top (required)>'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
        from C:/metasploit-framework/embedded/lib/ruby/gems/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:63:in `require_environment!'
        from C:/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:81:in `start'
        from C:/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'_
```

First I used msfupdate, later I deinstalled everything and tried a clean install. Same behaviour!

**Comment by bcook-r7** [comment]
Thanks for the note @hawaii67, sounds like a Ruby-on-Rails upgrade fallout. Will take a look at this today.

We do keep older builds around - the 4.11.27 builds should still be fine.

**Comment by wchen-r7** [comment]
This should be resolved in https://github.com/rapid7/metasploit-framework/pull/6886, please try http://windows.metasploit.com/metasploitframework-latest.msi again. Thanks.
