### ISSUE TITLE
payload/windows/upexec/reverse_tcp_rc4 "info" error

### ISSUE THREAD

**Issue by vysec** [rapid7/metasploit-framework#6916]
## Steps to reproduce

Start msfconsole

```> use payload/windows/upexec/reverse_tcp_rc4```

followed by 

```> info```

I am using latest version git cloned from repo here.

## Expected behavior

Display information

## Current behavior

Stack trace

```
msf payload(reverse_tcp_rc4) > use payload/windows/upexec/reverse_tcp_rc4
msf payload(reverse_tcp_rc4) > info
[-] Error while running command info: no implicit conversion of nil into String

Call stack:
/usr/share/metasploit-framework/lib/msf/core/payload/windows/rc4.rb:107:in `update'
/usr/share/metasploit-framework/lib/msf/core/payload/windows/rc4.rb:107:in `digest'
/usr/share/metasploit-framework/lib/msf/core/payload/windows/rc4.rb:107:in `rc4_keys'
/usr/share/metasploit-framework/lib/msf/core/payload/windows/reverse_tcp_rc4.rb:26:in `generate'
/usr/share/metasploit-framework/lib/msf/core/payload.rb:200:in `size'
/usr/share/metasploit-framework/lib/msf/base/serializer/readable_text.rb:320:in `dump_payload_module'
/usr/share/metasploit-framework/lib/msf/base/serializer/readable_text.rb:24:in `dump_module'
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:784:in `cmd_info'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'
msf payload(reverse_tcp_rc4) > use payload/windows/upexec/reverse_tcp_dns
msf payload(reverse_tcp_dns) > info

       Name: Windows Upload/Execute, Reverse TCP Stager (DNS)
     Module: payload/windows/upexec/reverse_tcp_dns
   Platform: Windows
       Arch: x86
Needs Admin: No
 Total size: 293
       Rank: Normal

Provided by:
  vlad902 <vlad902@gmail.com>
  sf <stephen_fewer@harmonysecurity.com>
  hdm <x@hdm.io>
  skape <mmiller@hick.org>
  RageLtMan

Basic options:
Name      Current Setting  Required  Description
----      ---------------  --------  -----------
EXITFUNC  process          yes       Exit technique (Accepted: '', seh, thread, process, none)
LHOST                      yes       The DNS hostname to connect back to
LPORT     4444             yes       The listen port
PEXEC                      yes       Full path to the file to upload and execute

Description:
  Uploads an executable and runs it (staged). Connect back to the 
  attacker


msf payload(reverse_tcp_dns) > 
```

## System stuff

Kali

### Metasploit version

```
Framework: 4.12.5-dev-05680ab
Console  : 4.12.5-dev-05680ab
```

**Comment by bcook-r7** [comment]
Good call, thanks for the ticket.
