### ISSUE TITLE
metasploit-framework/modules/post/osx/capture/keylog_recorder.rb

### ISSUE THREAD

**Issue by beichenbeichen** [rapid7/metasploit-framework#6981]
can't not use under mac OS X ruby 2.0 

THE ERROR LOG :
DL is deprecated, please use Fiddle
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/dl/import.rb:68:in `rescue in block in dlload': can't load Carbon.framework/Carbon (DL::DLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/dl/import.rb:65:in `block in dlload'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/dl/import.rb:56:in `collect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/dl/import.rb:56:in `dlload'
	from test.rb:65:in `<module:Carbon>'
	from test.rb:63:in `block in <main>'
	from test.rb:2:in `fork'
	from test.rb:2:in `<main>'

**Comment by simonpunk** [comment]
Same case and same outputs here. 

Mine is running latest OSX.

**Comment by clong** [comment]
This should (hopefully) be closable now that #9868 has been merged
