### ISSUE TITLE
"Invalid number of columns" when saving a note to csv

### ISSUE THREAD

**Issue by wchen-r7** [rapid7/metasploit-framework#7019]
## To reproduce

I started off with collecting some hashes using auxiliary/server/http_ntlmrelay, and then I did this to trigger the backtrace:

```
notes -t ntlm_relay -o /tmp/test.csv
```

## Backtrace

```
[-] Error while running command notes: Invalid number of columns!

/Users/sinn3r/rapid7/msf/lib/rex/ui/text/table.rb:175:in `add_row'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/table.rb:167:in `<<'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:1385:in `block (2 levels) in cmd_notes'
/Users/sinn3r/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/Users/sinn3r/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/activerecord-4.2.6/lib/active_record/relation/delegation.rb:46:in `each'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:1350:in `block in cmd_notes'
/Users/sinn3r/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/sinn3r/rapid7/msf/lib/msf/ui/console/command_dispatcher/db.rb:1221:in `cmd_notes'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:427:in `run_command'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:389:in `block in run_single'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:383:in `each'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/dispatcher_shell.rb:383:in `run_single'
/Users/sinn3r/rapid7/msf/lib/rex/ui/text/shell.rb:203:in `run'
/Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/sinn3r/rapid7/msf/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
```

**Comment by wchen-r7** [comment]
As far as I can tell, the ```-o``` is completely broken.

**Comment by wchen-r7** [comment]
## RCA

It looks like the store_local method in msf/core/auxiliary/report.rb is causing the ```notes -o``` command to break. If the user uses a fileformat that uses store_local (which most do), then this will cause msfconsole not being to export data when that note is read.
