### ISSUE TITLE
Net::SSH broken in L3 pivots

### ISSUE THREAD

**Issue by sempervictus** [rapid7/metasploit-framework#7211]
## Steps to reproduce

1. Pivot a route over a meterpreter session
2. Execute ssh_login scanner module against a routed host with a working SSH service

## Expected behavior

Should get proper socket response, negotiation, and auth attempt

## Current behavior
```
Error: 10.1.2.3: SocketError getaddrinfo: Servname not supported for ai_socktype
```
Which is actually:
```
[e(0)] core: Error running against host 10.1.2.3: getaddrinfo: Servname not supported for ai_socktype
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:67:in `getnameinfo'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/packet_stream.rb:67:in `peer_ip'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:107:in `host_as_string'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:96:in `host_keys'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:251:in `prepare_preferred_algorithms!'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:124:in `initialize'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:86:in `new'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:86:in `initialize'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
/home/user/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
/opt/metasploit4/msf4/lib/metasploit/framework/login_scanner/ssh.rb:78:in `block in attempt_login'
/home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/opt/metasploit4/msf4/lib/metasploit/framework/login_scanner/ssh.rb:77:in `attempt_login'
/opt/metasploit4/msf4/lib/metasploit/framework/login_scanner/base.rb:222:in `block in scan!'
/opt/metasploit4/msf4/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
/opt/metasploit4/msf4/lib/metasploit/framework/credential_collection.rb:121:in `each'
/opt/metasploit4/msf4/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
/opt/metasploit4/msf4/lib/metasploit/framework/login_scanner/base.rb:204:in `scan!'
/opt/metasploit4/msf4/modules/auxiliary/scanner/ssh/ssh_login.rb:128:in `run_host'
/opt/metasploit4/msf4/lib/msf/core/auxiliary/scanner.rb:134:in `block (2 levels) in run'
/opt/metasploit4/msf4/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```

**Comment by bcook-r7** [comment]
@egypt / @dmaloney-r7 - did you guys test pivoting with Net::SSH? That was the primary thing originally that complicated pulling in the upstream gem, IIRC.

**Comment by egypt** [comment]
Yes, and it worked for me in the lab. @dmaloney-r7 can you take another look at this?

**Comment by egypt** [comment]
Tracked this down to the same `Socket#getpeername` problem we had before just in a different place.

**Comment by sempervictus** [comment]
@egypt: thanks boss. Could you ref the last hunt for this bug? I'd like to take some time this evening to get assay on the full scope of it - long term planning for rex-socket/rex-proto gems.
