### ISSUE TITLE
Install Bundle Gems Problem

### ISSUE THREAD

**Issue by lazurens** [rapid7/metasploit-framework#7249]
- What did you do?
  
  I ran the command `/home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/bin/bundle install`
- What did you expect to happen?
  
  I expected Bundler to install gems so I can run (./msfconsole)
- What happened instead?
  
  Instead, what actually happened was unexpected error showing the following details:

Error details

```
Errno::EACCES: Permission denied @ dir_s_mkdir - /home/res/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/versions20160828-15594-1gdbdcv
  /home/res/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `mkdir'
  /home/res/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `block in mktmpdir'
  /home/res/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:130:in `create'
  /home/res/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tmpdir.rb:86:in `mktmpdir'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb:29:in `update'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:64:in `update'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb:55:in `update_and_parse_checksums!'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:65:in `available?'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `call'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/fetcher.rb:154:in `use_api'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `block in api_fetchers'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `select'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:331:in `api_fetchers'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:336:in `block in remote_specs'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:335:in `remote_specs'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/source/rubygems.rb:82:in `specs'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `each'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:209:in `block in index'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/index.rb:10:in `build'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:206:in `index'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/cli/install.rb:102:in `run'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/cli.rb:175:in `install'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/bin/bundle:23:in `load'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/bin/bundle:23:in `<main>'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/bin/ruby_executable_hooks:15:in `eval'
  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/bin/ruby_executable_hooks:15:in `<main>'
```

Environment

  Bundler   1.12.5
  Rubygems  2.5.1
  Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  GEM_HOME  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework
  GEM_PATH  /home/res/.rvm/gems/ruby-2.3.1@metasploit-framework:/home/res/.rvm/gems/ruby-2.3.1@global
  RVM       1.27.0 (latest)
  Git       1.9.1
  rubygems-bundler (1.4.4)

```
  Bundler settings
```

  orig_path
    Set via BUNDLE_ORIG_PATH: "/home/res/.rvm/gems/ruby-2.3.1@metasploit-framework/bin:/home/res/.rvm/gems/ruby-2.3.1@global/bin:/home/res/.rvm/rubies/ruby-2.3.1/bin:/home/res/.rvm/bin:/home/res/.rbenv/shims:/home/res/.rbenv/bin:/home/res/.rbenv/plugins/ruby-build/bin:/home/res/.rbenv/shims:/home/res/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
  orig_gem_path
    Set via BUNDLE_ORIG_GEM_PATH: "/home/res/.rvm/gems/ruby-2.3.1@metasploit-framework:/home/res/.rvm/gems/ruby-2.3.1@global"

---
### Metasploit version

msfconsole is not running for example when I type : (sudo msfconsole):

res@res-Lenovo-G560:~/git/metasploit-framework$ sudo msfconsole
/opt/metasploit/ruby/lib/ruby/site_ruby/2.3.0/rubygems.rb:8:in `require': cannot load such file -- rbconfig (LoadError)
    from /opt/metasploit/ruby/lib/ruby/site_ruby/2.3.0/rubygems.rb:8:in`<top (required)>'
    from internal:gem_prelude:4:in `require'
    from <internal:gem_prelude>:4:in`internal:gem_prelude'
### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)
  Both didn't work for me, I think because of incompatibility of ruby versions.
  ### OS

I am using Ubuntu 14.04 to run metasploit

**Comment by bcook-r7** [comment]
It looks like you have permissions issues, if you look carefully at the top line of the backtrace. Please check that you do not have files in your home directory owned as 'root'. Likely you have mixed running 'sudo' with non-sudo, and it has installed root-owned files in random places. If you are using 'rvm' correctly, you should not ever have to specify the full path like that.

Also, please verify where 'msfconsole' actually is in your environment. Type 'which msfconsole'
