### ISSUE TITLE
Nmap: Starting Oracle bruteforce with 1035 credentials against SID 'XE'... is error

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#7275]
mac os x 10.11.6
metasploit ver: metasploit v4.12.24-dev-58112d7  

**1**
use auxiliary/scanner/oracle/oracle_login
**2**
show options
Module options (auxiliary/scanner/oracle/oracle_login):

   Name              Current Setting                                                                             Required  Description
   ----              ---------------                                                                             --------  -----------
   BLANK_PASSWORDS   true                                                                                        no        Try blank passwords for all users
   BRUTEFORCE_SPEED  5                                                                                           yes       How fast to bruteforce, from 0 to 5
   DB_ALL_CREDS      true                                                                                        no        Try each user/password couple stored in the current database
   DB_ALL_PASS       true                                                                                        no        Add all passwords in the current database to the list
   DB_ALL_USERS      true                                                                                        no        Add all users in the current database to the list
   NMAP_VERBOSE      true                                                                                        no        Display nmap output
   PASSWORD                                                                                                      no        A specific password to authenticate with
   PASS_FILE                                                                                                     no        File containing passwords, one per line
   RHOSTS            file:/var/folders/k5/n1bnf5d57lj_b_zz8zyxrdn80000gn/T/msf-db-rhosts-20160905-84546-1e7ixol  yes       The target address range or CIDR identifier
   RPORTS                                                                                                        no        Ports to target
   SID               XE                                                                                          yes       The instance (SID) to authenticate against
   STOP_ON_SUCCESS   false                                                                                       yes       Stop guessing when a credential works for a host
   THREADS           33                                                                                          yes       The number of concurrent threads
   USERNAME                                                                                                      no        A specific username to authenticate as
   USERPASS_FILE     /Users/xiatian/safe/metasploit-framework/data/wordlists/oracle_default_userpass.txt         no        File containing (space-seperated) users and passwords, one pair per line
   USER_AS_PASS      false                                                                                       no        Try the username as the password for all users
   USER_FILE                                                                                                     no        File containing usernames, one per line
   VERBOSE           true                                                             
**3**
run
[*] Nmap: Setting up credential file...
[*] Nmap: Starting Oracle bruteforce with 1035 credentials against SID 'XE'...
[-] Missing RPORTS
[-] Auxiliary failed: RuntimeError Cannot continue without a valid port list.
[-] Call stack:
[-]   /Users/*/safe/metasploit-framework/lib/msf/core/auxiliary/nmap.rb:162:in `nmap_add_ports'
[-]   /Users/*/safe/metasploit-framework/lib/msf/core/auxiliary/nmap.rb:48:in `set_nmap_cmd'
[-]   /Users/*/safe/metasploit-framework/lib/msf/core/auxiliary/nmap.rb:91:in `nmap_run'
[-]   /Users/*/safe/metasploit-framework/modules/auxiliary/scanner/oracle/oracle_login.rb:62:in `run'
[*] Auxiliary module execution completed

**Comment by hktalent** [comment]
set RPORTS 1521,49163,49161,49160
 so is Ok
