### ISSUE TITLE
nessus_db_scan_workspace: wrong number of arguments (given 4, expected 2)

### ISSUE THREAD

**Issue by dhn** [rapid7/metasploit-framework#7434]
I've try to use the new `nessus_db_scan_workspace` function but unfortunately the `mfconsole` failed with an exception (see below).

```
msf > version
Framework: 4.12.32-dev
Console  : 4.12.32-dev

```

```
msf > nessus_policy_list
Policy ID  Name     Policy UUID
---------  ----     -----------
4          advance  ad629e16-03b6-8c1d-cef6-ef8c9dd3c658d24bd260ef5f9e66

msf > workspace
* default
  tesit
msf > workspace tesit
[*] Workspace: tesit
msf > services

Services
========

host            port   proto  name         state  info
----            ----   -----  ----         -----  ----
104.24.126.249  80     tcp    http         open   Cloudflare nginx
104.24.126.249  443    tcp    ssl/http     open   Cloudflare nginx
104.24.126.249  2082   tcp    http         open   Cloudflare nginx
104.24.126.249  2083   tcp    ssl/http     open   nginx
104.24.126.249  8080   tcp    http         open   Cloudflare nginx
127.0.0.1       631    tcp    ipp          open   CUPS 2.1
127.0.0.1       4371   tcp    ssl/unknown  open
127.0.0.1       4381   tcp    unknown      open
127.0.0.1       10391  tcp                 open
127.0.0.1       17500  tcp    ssl/db-lsp   open
127.0.0.1       17600  tcp    http         open   Tornado httpd 4.2
127.0.0.1       17603  tcp                 open
127.0.0.1       57621  tcp                 open
127.0.0.1       58059  tcp    http         open   Pylons Waitress WSGI server
127.0.0.2       17500  tcp    ssl/db-lsp   open
127.0.0.2       57621  tcp                 open

msf > nessus_db_scan_workspace
[*] Usage:
[*] nessus_db_scan_workspace <policy ID> <scan name> <scan description> <workspace>
[*] Use nessus_policy_list to list all available policies with their corresponding policy IDs
msf > nessus_db_scan_workspace ad629e16-03b6-8c1d-cef6-ef8c9dd3c658d24bd260ef5f9e66 bla bla2 tesit
[*] Switched workspace: tesit
[*] Targets: 104.24.126.249,
[*] Targets: 104.24.126.249,127.0.0.1,
[*] Targets: 104.24.126.249,127.0.0.1,127.0.0.2,
[*] Creating scan from policy ad629e16-03b6-8c1d-cef6-ef8c9dd3c658d24bd260ef5f9e66, called "bla" and scanning all hosts in tesit
[-] Error while running command nessus_db_scan_workspace: wrong number of arguments (given 4, expected 2)

Call stack:
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/nessus_rest-0.1.6/lib/nessus_rest.rb:379:in `scan_create'
/usr/share/metasploit-framework/plugins/nessus.rb:1139:in `cmd_nessus_db_scan_workspace'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:428:in `run_command'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:390:in `block in run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `each'
/usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:384:in `run_single'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:203:in `run'
/usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
/usr/bin/msfconsole:48:in `<main>'
```

Tested on Kali Linux.

**Comment by pbarry-r7** [comment]
My apologies for letting this slip.  Fix looks good!

```
$ ./msfconsole -q
msf > load nessus
[*] Nessus Bridge for Metasploit
[*] Type nessus_help for a command listing
[*] Successfully loaded plugin: Nessus
msf > nessus_connect pbarry:<redacted>@127.0.0.1:8834
[*] Connecting to https://127.0.0.1:8834/ as pbarry
[*] User pbarry authenticated successfully.
msf > workspace 
  small
* default
msf > workspace small 
[*] Workspace: small
msf > hosts

Hosts
=====

address      mac  name         os_name  os_flavor  os_sp  purpose  info  comments
-------      ---  ----         -------  ---------  -----  -------  ----  --------
10.10.12.13       10.10.12.13  Unknown                    device         

msf > nessus_policy_list
Policy ID  Name            Policy UUID
---------  ----            -----------
7          my test policy  731a8e52-3ea6-a291-ec0a-d2ff0619c19d7bd788d6be818b65

msf > nessus_db_scan_workspace  731a8e52-3ea6-a291-ec0a-d2ff0619c19d7bd788d6be818b65 mynewscan "is new scan" small
[*] Switched workspace: small
[*] Targets: 10.10.12.13,
[*] Creating scan from policy 731a8e52-3ea6-a291-ec0a-d2ff0619c19d7bd788d6be818b65, called "mynewscan" and scanning all hosts in small
[*] Scan ID 9 successfully created
[*] Run nessus_scan_launch 9 to launch the scan
```

Also verified via the UI that the scan was correctly created with the 10.10.12.13 target.  Thanks, @bcook-r7!
