### ISSUE TITLE
Stack trace: use auxiliary/scanner/smb/smb_uninit_cred

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#7583]
setg RHOSTS file:/root/test2/445.txt
setg THREADS 255
setg RPORT 445
use auxiliary/scanner/smb/smb_uninit_cred
run

## Expected behavior
Results

## Current behavior
```
[-] Auxiliary failed: Rex::Proto::DCERPC::Exceptions::Fault DCERPC FAULT => nca_op_rng_error
[-] Call stack:
[-]   /usr/share/metasploit-framework/lib/rex/proto/dcerpc/client.rb:315:in `call'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_uninit_cred.rb:119:in `is_vulnerable?'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_uninit_cred.rb:228:in `block in check_host'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_uninit_cred.rb:211:in `each'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_uninit_cred.rb:211:in `check_host'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_uninit_cred.rb:256:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```
### Metasploit version
v4.12.42-dev 

### I installed Metasploit with:
Kali Linux rolling

### OS
Kali Linux rolling

Testing against Metasploitable2

**Comment by wchen-r7** [comment]
@leebaird What was the target setup when you ran this module?
