### ISSUE TITLE
Got error when running module "auxiliary/scanner/http/brute_dirs"

### ISSUE THREAD

**Issue by jinq102030** [rapid7/metasploit-framework#7585]
## Steps to reproduce

How'd you do it?
```
msf auxiliary(bmc_trackit_passwd_reset) > use auxiliary/scanner/http/brute_dirs
msf auxiliary(brute_dirs) > show missing

Module options (auxiliary/scanner/http/brute_dirs):

   Name  Current Setting  Required  Description
   ----  ---------------  --------  -----------

msf auxiliary(brute_dirs) > run

[-] Auxiliary failed: NameError undefined local variable or method `emesg' for #<Msf::Modules::Mod617578696c696172792f7363616e6e65722f687474702f62727574655f64697273::MetasploitModule:0x0000000e4bc928>
Did you mean?  emesg
[-] Call stack:
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/brute_dirs.rb:100:in `block in run_host'
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/brute_dirs.rb:70:in `each'
[-]   /home/jqian/rapid7/metasploit-framework/modules/auxiliary/scanner/http/brute_dirs.rb:70:in `run_host'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:134:in `block (2 levels) in run'
[-]   /home/jqian/rapid7/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

## Expected behavior

It should not give exception.

## Current behavior

Got exception.

### Metasploit version

Framework: 4.12.22-dev-c03f35e
Console  : 4.12.22-dev-c03f35e

### OS

Ubuntu 14.04

**Comment by wvu-r7** [comment]
Are you sure you didn't add a stray ```'```?

**Comment by wvu-r7** [comment]
Oof, misread the improperly formatted log. Couldn't repro either...
