### ISSUE TITLE
uninitialized constant Rex::Text (NameError)

### ISSUE THREAD

**Issue by ChristianSch** [rapid7/metasploit-framework#7861]
When opening metasploit via `msfconsole` I get the following error:
```
/opt/metasploit-framework/embedded/framework/lib/rex/random_identifier_generator.rb:36:in `<class:RandomIdentifierGenerator>': uninitialized constant Rex::Text (NameError)
```

Note: before the update everything was fine, I even did a clean install just before the update.
If you need something, say something. I'm glad to help.

## meta
* macOS Sierra
* installed via sources (`v4.13.16`)
* `ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`

## full dump
```
/opt/metasploit-framework/embedded/framework/lib/rex/random_identifier_generator.rb:36:in `<class:RandomIdentifierGenerator>': uninitialized constant Rex::Text (NameError)
	from /opt/metasploit-framework/embedded/framework/lib/rex/random_identifier_generator.rb:24:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/rex/powershell/payload.rb:2:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/rex/powershell.rb:2:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/rex/text.rb:6:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/rex.rb:46:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/msf/core.rb:17:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework.rb:25:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/database.rb:1:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/parsed_options/base.rb:17:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/parsed_options/console.rb:2:in `require'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `require'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `const_get'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'
```

**Comment by busterb** [comment]
Thanks, looking now.

**Comment by busterb** [comment]
Hmm, I'm a little confused about your description. It says you installed from source, but the error is clearly from the omnibus installer.

Can you please actually show how you invoked msfconsole, and what directory you did it from?

**Comment by busterb** [comment]
I'm going to guess that you installed a really old version of the omnibus package, and have entirely forgotten about it, since the files referred to above haven't existed in that location for months.

I'd recommend running 'msfupdate' from the omnibus package to upgrade it (it should be warning you if you're > 2 weeks out of date anyway). Or if you don't actually want to use it, just run 'msfremove' and it will uninstall.

**Comment by ChristianSch** [comment]
Regarding the invoking of `msfconsole`, it does not matter where I invoke it.

I think you are right indeed, I seem to have an older installation laying around somewhere. The new install actually went to `/usr/local/share/` (according to this [guide](http://www.darkoperator.com/installing-metasploit-framewor/)), and `/opt/metasploit-framework/` seems to be the old one. The new msfconsole gives me the following error, which I guess is the incompatibility with Ruby 2.4? That means I'd have to fiddle around with rvm or so.

Thanks for the help so far! Appreciate it.

```
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:125:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/activesupport-4.2.7.1/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 5524 levels...
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
	from ./msfconsole:48:in `<main>'
```

**Comment by busterb** [comment]
I actually would not recommend following that guide because it will currently lead to a broken install since Ruby 2.4 is not ready yet, see #7819. Instead, please run this if it is on your system (sounds like it is):

/opt/metasploit-framework/bin/msfupdate

or just grab the latest package here: http://osx.metasploit.com/

This is much, much simpler, includes everything you need (database, correct version of ruby, etc), and it is automatically updatable just by running msfupdate again. When installed, just run /opt/metasploit-framework/bin/msfconsole, or put /opt/metasploit-framework/bin in your path if it is not already.

**Comment by busterb** [comment]
I'm going to close this since this is more of a support issue rather than a bug in metasploit-framework.

**Comment by ChristianSch** [comment]
Thanks a bunch for your help and time!
