### ISSUE TITLE
MSF launch errors

### ISSUE THREAD

**Issue by vysec** [rapid7/metasploit-framework#7881]
## Steps to reproduce

How'd you do it?

```
root:/usr/share/metasploit-framework# msfconsole
/var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:134: syntax error, unexpected ':', expecting => (SyntaxError)
      'ssh-key':    'Private, private_type SS...
                ^
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:134: syntax error, unexpected ',', expecting keyword_end
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:135: syntax error, unexpected ',', expecting keyword_end
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:136: syntax error, unexpected ',', expecting keyword_end
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:137: syntax error, unexpected ':', expecting keyword_end
      'realm-type': "Realm, realm_type (#{Metasp...
                   ^
/usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/creds.rb:138: syntax error, unexpected '}', expecting keyword_end
    }.each_pair do |keyword, description|
     ^
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /usr/share/metasploit-framework/lib/msf/ui/console/driver.rb:129:in `initialize'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/bin/msfconsole:48:in `<main>'
```

## Expected behavior

Open

## Current behavior

Errors

### Metasploit version

Latest clone just now

### I installed Metasploit with:
Git clone
### OS

What OS are you running Metasploit on?

Kali Sana

**Comment by bwatters-r7** [comment]
This is a shot in the dark, but what version of Ruby do you have installed?

**Comment by darkbushido** [comment]
if we are going to keep supporting older versions of ruby we should add them to the travis-ci build list.
its a small change to make this 2.1 compatible if we want to do that?
