### ISSUE TITLE
metasploit does not work 

### ISSUE THREAD

**Issue by Sangooob** [rapid7/metasploit-framework#8085]
/opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``': Cannot allocate memory - stty (Errno::ENOMEM)
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.4/lib/rbreadline.rb:6968:in `block in save_tty_chars'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.4/lib/rbreadline.rb:6957:in `retry_if_interrupted'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.4/lib/rbreadline.rb:6967:in `save_tty_chars'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.4/lib/rbreadline.rb:7072:in `rl_prep_terminal'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.3.0/gems/rb-readline-0.5.4/lib/rbreadline.rb:4871:in `readline'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:188:in `run'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'

**Comment by busterb** [comment]
The `embedded` path is just where omnibus stashes private files, but your point still stands. Thanks!
