### ISSUE TITLE
bavision_cam_login

### ISSUE THREAD

**Issue by otofoto** [rapid7/metasploit-framework#8120]
## Steps to reproduce
```
 [2017.03.16-18:38:12] Warning: The Windows platform cannot reliably support more than 16 threads
[-] [2017.03.16-18:38:12] Thread count has been adjusted to 16
[-] [2017.03.16-18:38:15] Auxiliary failed: NoMethodError undefined method `gsub' for nil:NilClass
[-] [2017.03.16-18:38:15] Call stack:
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/bavision_cameras.rb:65:in `digest_auth'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/bavision_cameras.rb:40:in `try_digest_auth'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/bavision_cameras.rb:106:in `attempt_login'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/credential_collection.rb:121:in `each'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/modules/auxiliary/scanner/http/bavision_cam_login.rb:113:in `bruteforce'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/modules/auxiliary/scanner/http/bavision_cam_login.rb:134:in `run_host'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-] [2017.03.16-18:38:15]   C:/Utils/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.14.1/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[+] [2017.03.16-18:38:15] Workspace:default Progress:2/2 (100%) Complete (0 sessions opened) auxiliary/scanner/http/bavision_cam_login
```

### Metasploit version

latest

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ x] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS

Windows

**Comment by busterb** [comment]
This looks like it came from Metasploit Pro. Do you have a support contact with R7 for that?

**Comment by susliks1** [comment]
No this is community edition. Bavision_cam_login doesn't seem to run with default settings.

**Comment by wchen-r7** [comment]
Just curious, were you actually hitting a Bavision camera web server?
