### ISSUE TITLE
stack trace - canon_iradv_pwd_extract

### ISSUE THREAD

**Issue by leebaird** [rapid7/metasploit-framework#8121]
## Steps to reproduce

```
resource (/root/Desktop/test//master.rc)> use auxiliary/scanner/printer/canon_iradv_pwd_extract
resource (/root/Desktop/test//master.rc)> run
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.82
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.142
[*] Attempting to extract passwords from the address books on the MFP at 10.0.19.13
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.232
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.187
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.171
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.144
[*] Attempting to extract passwords from the address books on the MFP at 10.0.12.220
[-] Auxiliary failed: NoMethodError undefined method `code' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/printer/canon_iradv_pwd_extract.rb:73:in `login'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/printer/canon_iradv_pwd_extract.rb:52:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version
metasploit v4.14.1-dev 

### I installed Metasploit with:
- [ ] Kali package via apt

### OS
Kali rolling

**Comment by h00die** [comment]
Let me know if that PR fixes the issue, should be a simple check of the variable before trying to access it.

**Comment by tabithavolpe** [comment]
Is this module simply replicating the addressbook import/export function from the webui?
