### ISSUE TITLE
Windows meterpreter portfwd not working with TCP transport

### ISSUE THREAD

**Issue by timosupremo** [rapid7/metasploit-framework#8133]
The `portfwd` function does not appear to work correctly against Windows targets in the latest version of the framework.  TCP transports appear to be affected the most, though the issue may also affect HTTP/HTTPS transports in some circumstances.  Versions 4.14.0 and prior do not appear to be affected.

## Steps to Reproduce
1. Gain a meterpreter on a Windows machine with a `windows/meterpreter/reverse_tcp` or `windows/x64/meterpreter/reverse_tcp` payload
2. Configure `portfwd` (such as `portfwd add -l 33890 -p 3389 -r 192.168.1.15`)
3. Connect with `rdesktop localhost:33890`

## Current behavior
I have tested this against Windows 8.1 and Server 2012 R2 targets.  RDP sessions do not complete and have glitched graphics; rdesktop provides an SSL3 decryption failed or bad record mac error.  Forwarded web applications do not render properly, though the tested web application, Jupyter, is AJAX heavy and uses websockets.  This behavior is present in `4.14.1-dev` and `4.14.2-dev`.  I have tested older versions, including `4.14.0` and `4.13.26`, and they appear to be unaffected.  My best guess is that data is being truncated or reordered (perhaps related to #7403 Meterpreter's TCP forwarding uncorrectly reorders packets?)

Output from the `framework.log` file:
```
[e(0)] rex: Error in #<Rex::Services::LocalRelay:0x0056005f630028> monitor_relays read: end of file reached
[w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[e(0)] rex: Error in #<Rex::Services::LocalRelay:0x0056005f630028> monitor_relays read: Connection reset by peer
[w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[e(0)] rex: Error in #<Rex::Services::LocalRelay:0x0056005f630028> monitor_relays read: stream closed
[w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[e(0)] rex: Error in #<Rex::Services::LocalRelay:0x0056005f630028> monitor_relays read: end of file reached
[w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[e(0)] rex: Error in #<Rex::Services::LocalRelay:0x0056005f630028> monitor_relays read: Connection reset by peer
[w(0)] core: monitor_rsock: the remote socket is nil, exiting loop
[e(0)] core: thread exception: StreamMonitorRemote  critical=false  error: TypeError no implicit conversion of nil into Integer
  source:
    /usr/share/metasploit-framework/lib/metasploit/framework/thread_factory_provider.rb:24:in `spawn'
    /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `spawn'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/socket_abstraction.rb:120:in `monitor_rsock'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_abstraction.rb:26:in `initialize_abstraction'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/channels/socket_abstraction.rb:94:in `initialize'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:75:in `initialize'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/channel.rb:125:in `new'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/channel.rb:125:in `create'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:36:in `open'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket.rb:104:in `create_tcp_client_channel'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket.rb:73:in `create'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb:644:in `create_tcp_channel'
    /usr/share/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb:490:in `block in cmd_portfwd'
    /usr/share/metasploit-framework/lib/rex/services/local_relay.rb:59:in `on_local_connection'
    /usr/share/metasploit-framework/lib/rex/services/local_relay.rb:434:in `accept_relay_conn'
    /usr/share/metasploit-framework/lib/rex/services/local_relay.rb:506:in `block in monitor_relays'
    /usr/share/metasploit-framework/lib/rex/services/local_relay.rb:502:in `each'
    /usr/share/metasploit-framework/lib/rex/services/local_relay.rb:502:in `monitor_relays'
    /usr/share/metasploit-framework/lib/rex/services/local_relay.rb:185:in `block in start'
    /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
    /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[e(0)] core: Call Stack
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:291:in `pack'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:291:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:562:in `block in to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:420:in `each'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:420:in `each'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:561:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet.rb:682:in `to_r'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:160:in `send_packet'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:228:in `send_packet_wait_response'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/packet_dispatcher.rb:200:in `send_request'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:106:in `shutdown'
/usr/share/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb:90:in `close_write'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/socket_abstraction.rb:188:in `block (2 levels) in monitor_rsock'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/socket_abstraction.rb:121:in `loop'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/socket_abstraction.rb:121:in `block in monitor_rsock'
/usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```

### Metasploit version
4.14.1-dev
4.14.2-dev

### I installed Metasploit with:
Pre-installed with Kali Linux
Prior versions from https://github.com/rapid7/metasploit-framework/releases

### OS
Current Kali Linux Rolling

**Comment by busterb** [comment]
Thanks for the bisect for the known-working version, that helps a lot!

**Comment by OJ** [comment]
This makes me sad.

**Comment by busterb** [comment]
Reproduced, and my RDP session literally turned upside down. I have a hunch that the issue is on the Windows meterpreter side. I tried the same transport with mettle and python meterpreter but didn't see the problem there, forwarding RDP to the same VM.

**Comment by busterb** [comment]
Looks like it starts with e5d0370a949d940e75e0b9fda078d2bcf5589ffb, though since we already had #7403 open, I suspect it just made the underlying problem of no sequence numbers on serialized channel data more evident. I think whether the problem shows up depends on how much data gets queued at the meterpreter level before it gets sent to metasploit.

**Comment by busterb** [comment]
I reverted the commit in #8250, we'll try again later. Thanks.
