### ISSUE TITLE
Merterpreter shell dies while using Armitage commands

### ISSUE THREAD

**Issue by spiffy111** [rapid7/metasploit-framework#8150]
## Steps to reproduce
Run Armitage and compromise target using psexec with gui. 

Once a meterpreter session has been established, right click on target, "Meterpreter #"

Navigate to "Interact", "Meterpreter Shell" and issue commands and/or navigate to "Explore", "Browse Files". 

My meterpreter session immediatly dies after either action.

## How'd you do it?

Same as above.

Running Metasploit version 4.14.3-dev and Armitage is v1.4.11
Targets are Windows 7 and Windows XP SP1

Ran an older version of Metasploit, v4.12.23-dev and meterpreter session never died.

## Expected behavior

When using the Armitage gui to browse files on a compromised target it should open a window that allows you to view the targets files.

## Log Output

[03/24/2017 14:10:35] [e(0)] core: Call Stack
/usr/share/metasploit-framework/lib/rex/ui/text/input/buffer.rb:53:in `getc'
/usr/share/metasploit-framework/lib/rex/ui/text/input/buffer.rb:53:in `gets'
/usr/share/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:121:in `gets'
/usr/share/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:151:in `pgets'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:188:in `run'
/usr/share/metasploit-framework/lib/msf/ui/web/console.rb:72:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[03/24/2017 14:10:36] [e(0)] core: thread exception: WebConsoleShell  critical=false  error: TypeError no implicit conversion of nil into String
  source:
    /usr/share/metasploit-framework/lib/msf/ui/web/console.rb:72:in `initialize'
    /usr/share/metasploit-framework/lib/msf/ui/web/driver.rb:67:in `new'
    /usr/share/metasploit-framework/lib/msf/ui/web/driver.rb:67:in `create_console'
    /usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_console.rb:29:in `rpc_create'
    /usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:152:in `block in process'
    /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
    /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
    /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
    /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
    /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
    /usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:152:in `process'
    /usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:90:in `on_request_uri'
    /usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:72:in `block in start'
    /usr/share/metasploit-framework/lib/rex/proto/http/handler/proc.rb:38:in `on_request'
    /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:368:in `dispatch_request'
    /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:302:in `on_client_data'
    /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:161:in `block in start'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:48:in `on_client_data'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:192:in `block in monitor_clients'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:190:in `each'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:190:in `monitor_clients'
    /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:73:in `block in start'
    /usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'
    /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[03/24/2017 14:10:36] [e(0)] core: Call Stack
/usr/share/metasploit-framework/lib/rex/ui/text/input/buffer.rb:56:in `gets'
/usr/share/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:121:in `gets'
/usr/share/metasploit-framework/lib/rex/ui/text/bidirectional_pipe.rb:151:in `pgets'
/usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:188:in `run'
/usr/share/metasploit-framework/lib/msf/ui/web/console.rb:72:in `block in initialize'
/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[03/24/2017 14:10:47] [w(0)] core: monitor_rsock: exception during read: IOError sysread for buffered IO
[03/24/2017 14:10:48] [w(0)] core: Generating SSL certificate for Meterpreter sessions
[03/24/2017 14:10:49] [w(0)] core: Generated SSL certificate for Meterpreter sessions
[03/24/2017 14:10:59] [w(0)] core: Session 1 has died
[03/24/2017 14:10:59] [e(0)] core: RPC Exception: Msf::RPC::Exception Msf::RPC::Exception ["/usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_base.rb:25:in `error'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_session.rb:486:in `_valid_session'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_session.rb:165:in `rpc_meterpreter_read'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:152:in `block in process'", "/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:152:in `process'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:90:in `on_request_uri'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "/usr/share/metasploit-framework/lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:368:in `dispatch_request'", "/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:302:in `on_client_data'", "/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:161:in `block in start'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:48:in `on_client_data'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:192:in `block in monitor_clients'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:190:in `each'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:190:in `monitor_clients'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:73:in `block in start'", "/usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'", "/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'"] ["1"] #<Rex::Proto::Http::Request:0x00563302def5e0 @headers={"Content-Type"=>"binary/message-pack", "Cache-Control"=>"no-cache", "Pragma"=>"no-cache", "User-Agent"=>"Java/1.8.0_121", "Host"=>"127.0.0.1:55553", "Accept"=>"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", "Connection"=>"keep-alive", "Content-Length"=>"63"}, @auto_cl=true, @state=3, @transfer_chunked=false, @inside_chunk=false, @bufq="", @body="\x93\xB8session.meterpreter_read\xDA\x00 TEMP2363124838279696295672514589\xA11", @method="POST", @raw_uri="/api/1.0/", @uri_parts={"QueryString"=>{}, "Resource"=>"/api/1.0/"}, @proto="1.1", @chunk_min_size=1, @chunk_max_size=10, @uri_encode_mode="hex-normal", @relative_resource="/api/1.0/", @body_bytes_left=0>
[03/24/2017 14:10:59] [e(0)] core: RPC Exception: Msf::RPC::Exception Msf::RPC::Exception ["/usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_base.rb:25:in `error'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_session.rb:486:in `_valid_session'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/rpc_session.rb:165:in `rpc_meterpreter_read'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:152:in `block in process'", "/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'", "/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:152:in `process'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:90:in `on_request_uri'", "/usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:72:in `block in start'", "/usr/share/metasploit-framework/lib/rex/proto/http/handler/proc.rb:38:in `on_request'", "/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:368:in `dispatch_request'", "/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:302:in `on_client_data'", "/usr/share/metasploit-framework/lib/rex/proto/http/server.rb:161:in `block in start'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:48:in `on_client_data'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:192:in `block in monitor_clients'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:190:in `each'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:190:in `monitor_clients'", "/usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/rex-core-0.1.7/lib/rex/io/stream_server.rb:73:in `block in start'", "/usr/share/metasploit-framework/lib/rex/thread_factory.rb:22:in `block in spawn'", "/usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'"] ["1"] #<Rex::Proto::Http::Request:0x00563302def5e0 @headers={"Content-Type"=>"binary/message-pack", "Cache-Control"=>"no-cache", "Pragma"=>"no-cache", "User-Agent"=>"Java/1.8.0_121", "Host"=>"127.0.0.1:55553", "Accept"=>"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", "Connection"=>"keep-alive", "Content-Length"=>"63"}, @auto_cl=true, @state=3, @transfer_chunked=false, @inside_chunk=false, @bufq="", @body="\x93\xB8session.meterpreter_read\xDA\x00 TEMP2363124838279696295672514589\xA11", @method="POST", @raw_uri="/api/1.0/", @uri_parts={"QueryString"=>{}, "Resource"=>"/api/1.0/"}, @proto="1.1", @chunk_min_size=1, @chunk_max_size=10, @uri_encode_mode="hex-normal", @relative_resource="/api/1.0/", @body_bytes_left=0>

## Current behavior

The meterpreter session dies unexpectedly after trying to use a meterpreter shell.

## System stuff

Kali-Linux Vbox-edition

### Metasploit version

Metasploit version 4.14.3-dev

### I installed Metasploit with:
- [ ] Kali package via apt

### OS

Linux

**Comment by void-in** [comment]
@spiffy111 This looks like you will have to report it to @rsmudge on the Armitage forums. This is not the appropriate place to report since meterpreter works fine when used outside the Armitage. I am going to close this issue.
