### ISSUE TITLE
problem with ruby [windows]

### ISSUE THREAD

**Issue by Ghostboy-287** [rapid7/metasploit-framework#8377]
i was using metasploit without any problem but i had error messages when i tested it with newest ruby version ( strictly high than >2.2.4) : 

### Error message while running `msfconsole` 

```
C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- bcrypt_ext (LoadError)
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x86-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x86-mingw32/lib/bcrypt.rb:12:in `<top (required)>'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework.rb:9:in `<top (required)>'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/database.rb:1:in `<top (required)>'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/parsed_options/base.rb:17:in `<top (required)>'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/parsed_options/console.rb:2:in `<top (required)>'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:263:in `const_get'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:263:in `block in constantize'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `each'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `inject'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/inflector/methods.rb:259:in `constantize'
        from C:/PentestBox/base/ruby/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/command/base.rb:73:in `parsed_options_class'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/command/base.rb:69:in `parsed_options'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/command/base.rb:47:in `require_environment!'
        from C:/PentestBox/bin/metasploit-framework/lib/metasploit/framework/command/base.rb:81:in `start'
        from C:/PentestBox/bin/metasploit-framework/msfconsole:48:in `<main>'
```

 **ps** : i runned `gem install bundler` & `bundle install` before running `msfconsole`

### Metasploit version
latest one (metasploit v4.14.18-dev-405f2c6ca1)

### I installed Metasploit with:
- [ ] Source install (ruby version : ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32] ) 

### OS

Windows 10 using Pentestbox

**Comment by busterb** [comment]
The issue is with the upstream gem, not Metasploit. Unfortunately, the bcrypt gem maintainer has not fixed the issue yet: https://github.com/codahale/bcrypt-ruby/issues/142

In the mean time, see the workaround we included in the Omnibus metasploit installers for Windows:

https://github.com/rapid7/metasploit-omnibus/blob/e6f35c828b397216637596c62720f71b940799ce/config/software/metasploit-framework.rb#L60

**Comment by busterb** [comment]
Since you encountered this issue using Pentestbox, could you please contact the maintainer there and have them apply the same workaround for now? Thanks.
