### ISSUE TITLE
ssh_login error

### ISSUE THREAD

**Issue by h00die** [rapid7/metasploit-framework#8563]
```
[-] Auxiliary failed: NoMethodError undefined method `split' for nil:NilClass
[-] Call stack:
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:104:in `block in next_message'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:95:in `loop'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:95:in `next_message'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/methods/password.rb:24:in `authenticate'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `each'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
[-]   /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh.rb:237:in `start'
[-]   /git/metasploit-framework/lib/metasploit/framework/login_scanner/ssh.rb:78:in `block in attempt_login'
[-]   /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
[-]   /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
[-]   /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
[-]   /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
[-]   /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
[-]   /git/metasploit-framework/lib/metasploit/framework/login_scanner/ssh.rb:77:in `attempt_login'
[-]   /git/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:231:in `block in scan!'
[-]   /git/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:179:in `block in each_credential'
[-]   /git/metasploit-framework/lib/metasploit/framework/credential_collection.rb:121:in `each'
[-]   /git/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:141:in `each_credential'
[-]   /git/metasploit-framework/lib/metasploit/framework/login_scanner/base.rb:205:in `scan!'
[-]   /git/metasploit-framework/modules/auxiliary/scanner/ssh/ssh_login.rb:127:in `run_host'
[-]   /git/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /git/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
```

**Comment by elenoir** [comment]
Could you post the OPTIONS you set to the module please? And the specified files (user or password)

**Comment by h00die** [comment]
This was too long ago and I never got the time while on site to diagnose.  Going to close for now
