### ISSUE TITLE
Auxiliary failed: NoMethodError undefined method `close' for nil:NilClass in jtr_*

### ISSUE THREAD

**Issue by emanuelb** [rapid7/metasploit-framework#8685]
The error `Auxiliary failed: NoMethodError undefined method close for nil:NilClass` occur in several auxiliary/analyze/jtr* modules when using `run`.

```
msf auxiliary(jtr_mysql_fast) > use auxiliary/analyze/jtr_linux 
msf auxiliary(jtr_linux) > run

[-] Auxiliary failed: NoMethodError undefined method `close' for nil:NilClass
Did you mean?  clone
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/analyze/jtr_linux.rb:49:in `run'
[*] Auxiliary module execution completed
msf auxiliary(jtr_linux) > use auxiliary/analyze/jtr_aix
msf auxiliary(jtr_aix) > run

[-] Auxiliary failed: NoMethodError undefined method `close' for nil:NilClass
Did you mean?  clone
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/analyze/jtr_aix.rb:35:in `run'
[*] Auxiliary module execution completed

msf auxiliary(jtr_oracle_fast) > use auxiliary/analyze/jtr_mssql_fast 
msf auxiliary(jtr_mssql_fast) > run

[-] Auxiliary failed: NoMethodError undefined method `close' for nil:NilClass
Did you mean?  clone
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/analyze/jtr_mssql_fast.rb:36:in `run'
[*] Auxiliary module execution completed
msf auxiliary(jtr_mssql_fast) > use auxiliary/analyze/jtr_crack_fast 
msf auxiliary(jtr_crack_fast) > run

[-] Auxiliary failed: NoMethodError undefined method `close' for nil:NilClass
Did you mean?  clone
[-] Call stack:
[-]   /usr/share/metasploit-framework/modules/auxiliary/analyze/jtr_crack_fast.rb:34:in `run'
[*] Auxiliary module execution completed
```

**Comment by busterb** [comment]
do you actually have john the ripper installed?

**Comment by emanuelb** [comment]
Yes, I am using kali linux, john located at `/usr/sbin/john`,
even setting the path manually via ` set JOHN_PATH /usr/sbin/john` doesn't help

**Comment by wchen-r7** [comment]
It seems ```#close``` on null happens if you don't have an active database connected to framework. Please double check on that. Meanwhile, I will add a check for this condition.

**Comment by wchen-r7** [comment]
A patch is in the queue to improve the user experience. Note that you still need to connect to a database in order to use these modules. Thanks.

**Comment by emanuelb** [comment]
Thanks :+1: it works after setting the database as explained in:
https://www.offensive-security.com/metasploit-unleashed/using-databases/
