### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hktalent** [rapid7/metasploit-framework#8778]
# in meterpreter
`run kiwi
`
# in kiwi.rb i add code
```

  def bin_to_hex(s)
    s.each_byte.map { |b| b.to_s(16) }.join
  end

  def hex_to_bin(s)
    s.scan(/../).map { |x| x.hex.chr }.join ':'
  end

# err message

``````
```

def wifi_list
    response_xml = exec_cmd('misc::wifi')

    results = []
    # TODO: check for XXE?
    doc = REXML::Document.new(response_xml)
    doc.get_elements('wifilist/interface').each do |i|
      interface = {
        :guid     => Rex::Text::to_guid(i.elements['guid'].text),
        :desc     => i.elements['description'].text,
        :state    => i.elements['state'].text,
        :profiles => []
      }

      i.get_elements('profiles/WLANProfile').each do |p|
        interface[:profiles] << {
          :name        => p.elements['name'].text,
          :auth        => p.elements['MSM/security/authEncryption/authentication'].text,
          :key_type    => p.elements['MSM/security/sharedKey/keyType'].text,
          :shared_key  => p.elements['MSM/security/sharedKey/keyMaterial'].text,
          :SSID        => hex_to_bin(p.elements['SSIDConfig/SSID/hex'].text)
        }
      end

      results << interface
    end

    return results
  end
```

#  ==  see

`:SSID        => hex_to_bin(p.elements['SSIDConfig/SSID/hex'].text)`

```
meterpreter > wifi_list                                                                                                                             
[-] Error running command wifi_list: REXML::ParseException #<ArgumentError: invalid byte sequence in UTF-8>
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/source.rb:220:in `match'
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/source.rb:220:in `match'
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/parsers/baseparser.rb:427:in `pull_event'
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/parsers/baseparser.rb:185:in `pull'
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/parsers/treeparser.rb:23:in `parse'
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/document.rb:288:in `build'
/opt/metasploit-framework/embedded/lib/ruby/2.4.0/rexml/document.rb:45:in `initialize'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/post/meterpreter/extensions/kiwi/kiwi.rb:496:in `new'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/post/meterpreter/extensions/kiwi/kiwi.rb:496:in `wifi_list'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb:429:in `cmd_wifi_list'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:105:in `run_command'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:68:in `block in interact'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/shell.rb:195:in `run'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/post/meterpreter/ui/console.rb:66:in `interact'
/Users/xiatian/safe/top20/metasploit-framework/lib/msf/base/sessions/meterpreter.rb:481:in `_interact'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/interactive.rb:49:in `interact'
/Users/xiatian/safe/top20/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1378:in `cmd_sessions'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:430:in `run_command'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:392:in `block in run_single'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `each'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:386:in `run_single'
/Users/xiatian/safe/top20/metasploit-framework/lib/rex/ui/text/shell.rb:205:in `run'
/Users/xiatian/safe/top20/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
/Users/xiatian/safe/top20/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:48:in `<main>'
...
Exception parsing
Line: 30
Position: 5414
Last 80 unconsumed characters:
360

```

**Comment by busterb** [comment]
I cannot tell what you are asking. Did you add some code and are having errors in it? If you need help with development, consider discussing on #metasploit on IRC. Thanks!
