### ISSUE TITLE
Is msfpescan broken on Mac?

### ISSUE THREAD

**Issue by CaledoniaProject** [rapid7/metasploit-framework#8786]
After a successful msfupdate, when I invoke msfpescan, it crashes:

```
/usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/random_identifier_generator.rb:36:in `<class:RandomIdentifierGenerator>': uninitialized constant Rex::Text (NameError)
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/random_identifier_generator.rb:24:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/powershell/payload.rb:2:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/powershell.rb:2:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/text.rb:6:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/assembly/nasm.rb:5:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/pescan/search.rb:6:in `<module:Search>'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/pescan/search.rb:4:in `<module:PeScan>'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/pescan/search.rb:3:in `<module:Rex>'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/pescan/search.rb:2:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-2.0.10/lib/rex/pescan.rb:11:in `<top (required)>'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/Cellar/ruby@2.3/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/homebrew/lib/ruby/gems/2.3.0/gems/rex-bin_tools-0.1.4/bin/msfpescan:6:in `<top (required)>'
	from /usr/local/homebrew/bin/msfpescan:22:in `load'
	from /usr/local/homebrew/bin/msfpescan:22:in `<main>'
```

**Comment by CaledoniaProject** [comment]
It was found on Kali 2017, but in framework2? 

![screen 2017-07-29 at 18 41 27](https://user-images.githubusercontent.com/1357701/28744167-a9e6508e-748d-11e7-90d4-6e5c80fe64f7.jpg)

The same path shipped in vendor was broken as well

**Comment by roya0045** [comment]
I'm going to say the obvious but try (re?)installing the rex/ rex-bin_tools gem. ( if you are unsure here is the guide: http://guides.rubygems.org/rubygems-basics/ )

**Comment by CaledoniaProject** [comment]
Already tried before posting,

```
%> gem install rex rex-bin_tools
Fetching: rex-2.0.11.gem (100%)
Successfully installed rex-2.0.11
Parsing documentation for rex-2.0.11
Installing ri documentation for rex-2.0.11
Done installing documentation for rex after 42 seconds
Successfully installed rex-bin_tools-0.1.4
Parsing documentation for rex-bin_tools-0.1.4
Done installing documentation for rex-bin_tools after 0 seconds
2 gems installed
```

The error is the same

**Comment by busterb** [comment]
Looks like a conflict between the old 'rex' gem and the newer 'rex-text' gem.

**Comment by busterb** [comment]
transitively, this probably happens when the same gemset used for metasploit is used with something that uses rex, like msfrpc-client -> beef or similar.

**Comment by busterb** [comment]
I believe fixed this a year or so ago, by updating rex-text to match the old rex gem again. Sorry for the delay!
