### ISSUE TITLE
update script problem

### ISSUE THREAD

**Issue by darkgirl** [rapid7/metasploit-framework#8794]
when i use msfupdate script to update this project,Bundle install seems to have a problem.

```
Bundler::GemspecError: Could not read gem at /var/lib/gems/2.3.0/cache/ffi-1.9.18.gem.
It may be corrupted.
An error occurred while installing ffi (1.9.18), and Bundler cannot
continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.
```

so, i use gem install ffi -v '1.9.18' to install ffi
then i re-excute bundle install

it seems to have no problem

```
Installing metasploit-credential 2.0.10
Using metasploit-framework 4.15.5 from source at `.`
Bundle complete! 14 Gemfile dependencies, 105 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from dnsruby:
Installing dnsruby...
  For issues and source code: https://github.com/alexdalitz/dnsruby
  For general discussion (please tell us how you use dnsruby): https://groups.google.com/forum/#!forum/dnsruby

but when i wan to excute msfupdate script again,it even can not running, I searched some key words, but no help.

The following is what happened:
 
sudo msfupdate 
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via git
[*] Note: Updating from bleeding edge
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- os (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from /opt/metasploit-framework/msfupdate:153:in `git_globals_okay?'
	from /opt/metasploit-framework/msfupdate:202:in `update_git!'
	from /opt/metasploit-framework/msfupdate:143:in `block in run!'
	from /opt/metasploit-framework/msfupdate:136:in `chdir'
	from /opt/metasploit-framework/msfupdate:136:in `run!'
	from /opt/metasploit-framework/msfupdate:316:in `<main>'
```

It seems to be ruby's problem, but i'm not know ruby.

**Comment by busterb** [comment]
are you using rvm to install ruby? what OS are you using? lots of info left out here.

I'd recommend if you're new to ruby or are not doing development to just use the pre-packaged nightly builds here: https://github.com/rapid7/metasploit-framework/wiki/Nightly-Installers

**Comment by busterb** [comment]
often there are wikis on the internet with outdated installation instructions. please do not use them

**Comment by darkgirl** [comment]
thanks very much!
i reinstalled metasploit, it works well
