### ISSUE TITLE
`db_nmap <tab>` crashes with TypeError in 20170904092357 nightly when `nmap` isn't installed

### ISSUE THREAD

**Issue by relrod** [rapid7/metasploit-framework#8921]
## Steps to reproduce

How'd you do it?

1. Install `metasploit-framework-4.16.5+20170904092357~1rapid7-1.el6.x86_64` on Fedora 26 from metasploit's official yum repo
2. Note that `metasploit-framework` RPM does *not* depend on the `nmap` package.
3. Also note that `nmap` package is *not* installed.
2. From `/opt/metasploit-framework/bin`, run `./msfconsole`, then type `db_nmap ` and press the tab key.

The rpm spec file probably just needs a dependency on `nmap`.

## Expected behavior

The console shouldn't crash, it should print a pretty error message.

## Current behavior

The console crashes:

```
msf > db_nmap /opt/metasploit-framework/embedded/lib/ruby/2.4.0/open3.rb:199:in `spawn': no implicit conversion of nil into String (TypeError)
	from /opt/metasploit-framework/embedded/lib/ruby/2.4.0/open3.rb:199:in `popen_run'
	from /opt/metasploit-framework/embedded/lib/ruby/2.4.0/open3.rb:95:in `popen3'
	from /opt/metasploit-framework/embedded/lib/ruby/2.4.0/open3.rb:258:in `capture3'
	from /opt/metasploit-framework/embedded/framework/lib/msf/ui/console/command_dispatcher/db.rb:1603:in `cmd_db_nmap_tabs'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:360:in `tab_complete_helper'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:320:in `block in tab_complete_stub'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:309:in `each'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:309:in `tab_complete_stub'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/dispatcher_shell.rb:294:in `tab_complete'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:59:in `block in init_tab_complete'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
	from /opt/metasploit-framework/embedded/lib/ruby/gems/2.4.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
	from /opt/metasploit-framework/embedded/framework/lib/rex/ui/text/shell.rb:188:in `run'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /opt/metasploit-framework/embedded/framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /opt/metasploit-framework/bin/../embedded/framework/msfconsole:48:in `<main>'
```

### Metasploit version

```
msf > version
Framework: 4.16.5-dev-
Console  : 4.16.5-dev-
```

```
$ rpm -q metasploit-framework 
metasploit-framework-4.16.5+20170904092357~1rapid7-1.el6.x86_64
```

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)
- [x] Nightly from the official yum repo.

### OS

What OS are you running Metasploit on?

Fedora 26.

**Comment by timwr** [comment]
Thanks for reporting @relrod :)
