### ISSUE TITLE
cerberus_sftp_enumusers - Auxiliary failed: NoMethodError undefined method `start' for nil:NilClass

### ISSUE THREAD

**Issue by necross2** [rapid7/metasploit-framework#8970]
## Steps to reproduce

1. `use auxiliary/scanner/ssh/cerberus_sftp_enumusers`
2. `set USER_FILE /root/usernames.txt`
3. `set RHOSTS x.x.x.x`
4. `run` 

## Expected behavior
What should happen?
Module execution.

## Current behavior
What happens instead?
Crash.
Stack Trace:
```
[*] 205.234.27.226:22 SSH - Checking for vulnerability
[-] Auxiliary failed: NoMethodError undefined method `start' for nil:NilClass
[-] Call stack:
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:65:in `ask_password'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:21:in `authenticate'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/ssh/cerberus_sftp_enumusers.rb:84:in `check_vulnerable'
[-]   /usr/share/metasploit-framework/modules/auxiliary/scanner/ssh/cerberus_sftp_enumusers.rb:207:in `run_host'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /usr/share/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

### Metasploit version
**metasploit v4.16.6-dev**

### I installed Metasploit with:
- [x] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [ ] Source install (please specify ruby version)

### OS
What OS are you running Metasploit on?

Linux version 4.12.0-kali1-amd64 (devel@kali.org) (gcc version 6.4.0 20170820 (Debian 6.4.0-4) ) #1 SMP Debian 4.12.6-1kali6 (2017-08-30)

**Comment by Chiggins** [comment]
I was able to replicate this as well.

msf auxiliary(cerberus_sftp_enumusers) > run

```
[*] 192.168.1.130:22 SSH - Checking for vulnerability
[-] Auxiliary failed: NoMethodError undefined method `start' for nil:NilClass
[-] Call stack:
[-]   /home/chiggins/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:65:in `ask_password'
[-]   /home/chiggins/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:21:in `authenticate'
[-]   /home/chiggins/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
[-]   /home/chiggins/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
[-]   /home/chiggins/.rvm/gems/ruby-2.4.1@metasploit-framework/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
[-]   /home/chiggins/metasploit-framework/modules/auxiliary/scanner/ssh/cerberus_sftp_enumusers.rb:84:in `check_vulnerable'
[-]   /home/chiggins/metasploit-framework/modules/auxiliary/scanner/ssh/cerberus_sftp_enumusers.rb:207:in `run_host'
[-]   /home/chiggins/metasploit-framework/lib/msf/core/auxiliary/scanner.rb:135:in `block (2 levels) in run'
[-]   /home/chiggins/metasploit-framework/lib/msf/core/thread_manager.rb:100:in `block in spawn'
[*] Auxiliary module execution completed
```

**Comment by Chiggins** [comment]
Looks like this could be a problem with the [net-ssh gem](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/methods/password.rb#L65) itself. I wrote this quick little program to mimic what the module does and got the same error with the same gem. If you supply a working password, it works fine and dandy. If not, then it hard-fails.

```
require 'net/ssh'

ip = '192.168.1.181'
opt_hash = {
  port: 22,
  auth_methods: ['password', 'keyboard-interactive'],
  use_agent: false,
  config: false
}

transport = Net::SSH::Transport::Session.new(ip, opt_hash)

auth = Net::SSH::Authentication::Session.new(transport, opt_hash)
auth.authenticate('ssh-connection', 'root', 'passwordthatdoesntexist')

puts "#{ip} connection good -- #{auth.transport.server_version.version}"
```

```
# ruby test_ssh.rb 
/home/chiggins/.rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:65:in `ask_password': undefined method `start' for nil:NilClass (NoMethodError)
	from /home/chiggins/.rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/password.rb:21:in `authenticate'
	from /home/chiggins/.rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
	from /home/chiggins/.rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
	from /home/chiggins/.rvm/gems/ruby-2.3.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
	from test_ssh.rb:14:in `<main>'
```

**Comment by necross2** [comment]
From what I can see, net-ssh-4.2.0 now implements `prompt_info` on line [62](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/methods/password.rb).

```
def ask_password(username)
            host = session.transport.host
            prompt_info = {type: 'password', user: username, host: host}
            if @prompt_info != prompt_info
              @prompt_info = prompt_info
              @prompter = prompt.start(prompt_info)
            end
            echo = false
            @prompter.ask("#{username}@#{host}'s password:", echo)
          end
```

This might actually break all current ssh related modules.
please correct me if I am completely off here...

**Comment by busterb** [comment]
I put up a PR on net-ssh - does that seem to do the trick? 

You can test by pinning the gem to the PR branch, adding this to your 'Gemfile', and running bundler

gem 'net-ssh', git: 'https://github.com/busterb/net-ssh', branch: 'fix-prompt'

**Comment by necross2** [comment]
That seemed to fixed it.

**Comment by busterb** [comment]
Thanks, I let upstream dev know, we'll see what comes down. I had missed an attribute declaration that made my change unnecessary anyway.

**Comment by wchen-r7** [comment]
Please see https://github.com/rapid7/metasploit-framework/pull/9436#issuecomment-359312470 for the correct fix.
