### ISSUE TITLE
msfupdate not working

### ISSUE THREAD

**Issue by InfinitBR** [rapid7/metasploit-framework#8994]
i am in lubuntu 17.04 i installed the msf with the dark operator turorial but when i do the msfupdate command this happens
```
infinit@infinit-T100TAS:/opt/metasploit-framework$ ./msfupdate 
[*]
[*] Attempting to update the Metasploit Framework...
[*]

[*] Checking for updates via git
[*] Note: Updating from bleeding edge
/home/infinit/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- os (LoadError)
	from /home/infinit/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/infinit/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/backports-3.8.0/lib/backports/std_lib.rb:9:in `require_with_backports'
	from ./msfupdate:153:in `git_globals_okay?'
	from ./msfupdate:202:in `update_git!'
	from ./msfupdate:143:in `block in run!'
	from ./msfupdate:136:in `chdir'
	from ./msfupdate:136:in `run!'
	from ./msfupdate:316:in `<main>'
```

**Comment by jdoss** [comment]
https://github.com/rapid7/metasploit-framework/blob/master/msfupdate#L153 is missing the required gem https://rubygems.org/gems/os/versions/1.0.0 in the bundled gems.

**Comment by jmartin-r7** [comment]
This suggests you have not run all commands in the tutorial.

```
gem install bundler
bundle install
```
