### ISSUE TITLE
darn it bundler broke everything again

### ISSUE THREAD

**Issue by busterb** [rapid7/metasploit-framework#9155]
Looks like our tests rely on something from Bundler 1.15 that was removed in Bundler 1.16. We need to fix it, or all of the specs will fail.

It also looks like factory_girl has turned into factory_bot, which will also need adjustment or removal.

```
The command "echo "${CMD}"" exited with 0.
3.43s$ if [[ "${DOCKER}" == "true" ]]; then echo "Starting Docker build job"; travis_wait 40 "${CMD}"; else bash -c "${CMD}"; fi
DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. (called from require at /home/travis/.rvm/gems/ruby-2.2.7/gems/bundler-1.16.0/lib/bundler/runtime.rb:81)
YARD not defined, so yard tasks cannot be setup.
/home/travis/.rvm/rubies/ruby-2.2.7/bin/ruby -I/home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib:/home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-support-3.7.0/lib /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --require rspec-rerun/formatter --format RSpec::Rerun::Formatter --color --format Fivemat --require spec_helper
/home/travis/build/rapid7/metasploit-framework/spec/spec_helper.rb:6:in `<top (required)>': undefined method `without' for #<Bundler::Settings:0x00000000f66238> (NoMethodError)
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `require'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `block in requires='
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `each'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration.rb:1455:in `requires='
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `each'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:99:in `setup'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:86:in `run'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:71:in `run'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/travis/build/rapid7/metasploit-framework/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.7.0/exe/rspec:4:in `<main>'
rake aborted!
```

**Comment by jmartin-r7** [comment]
looks like the culprit is
```
unless Bundler.settings.without.include?(:coverage)
  require 'simplecov'
end
```
running validation test no removal will PR shortly.
