### ISSUE TITLE
PG::ConnectionBad if database is stopped while gather/kerberos_enumusers

### ISSUE THREAD

**Issue by ajaxtpm** [rapid7/metasploit-framework#9393]
I did not start msfdb before I run msfconsole. After a user was found metasploit raises an exception

### Version
Framework Version: 4.16.28-dev

### Steps:

```
msf auxiliary(gather/kerberos_enumusers) > set DOMAIN CONTOSO.LOCAL
DOMAIN => CONTOSO.LOCAL
msf auxiliary(gather/kerberos_enumusers) > set RHOST 10.0.0.10
RHOST => 10.0.0.10
msf auxiliary(gather/kerberos_enumusers) > set USER_FILE rdpusers.txt
USER_FILE => rdpusers.txt
msf auxiliary(gather/kerberos_enumusers) > run

[*] Validating options...
[*] Using domain: CONTOSO.LOCAL...
[*] 10.0.0.10:88 - Testing User: "testuser"...
[*] 10.0.0.10:88 - KDC_ERR_PREAUTH_REQUIRED - Additional pre-authentication required
[+] 10.0.0.10:88 - User: "testuser" is present
[-] Auxiliary failed: PG::ConnectionBad could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

[-] Call stack:
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
[-]   /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
[-]   /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
[-]   /usr/share/metasploit-framework/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
[-]   /usr/share/metasploit-framework/lib/msf/core/db_manager/workspace.rb:18:in `find_workspace'
[-]   /usr/share/metasploit-framework/lib/msf/core/auxiliary/report.rb:67:in `myworkspace'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/kerberos_enumusers.rb:96:in `report_cred'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/kerberos_enumusers.rb:77:in `block in run'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/kerberos_enumusers.rb:65:in `each'
[-]   /usr/share/metasploit-framework/modules/auxiliary/gather/kerberos_enumusers.rb:65:in `run'
```

**Comment by adfoster-r7** [comment]
I believe this is resolved now; closing
