### ISSUE TITLE
python payload seems not compatible with msf modules

### ISSUE THREAD

**Issue by kdlsw** [rapid7/metasploit-framework#9664]
I’m using python/meterpreter/reverse_tcp as the payload, on a win7 target. After establishing a session, all the basic commands (download, upload, ps, etc.) worked just fine, but I cannot get any msf modules scripts to work, I tried with 
`post/windows/gather/checkvm`
`post/windows/manage/migrate`
`post/windows/manage/persistence_exe`

and here are the results

`post/windows/gather/checkvm`
run

[*] Checking if lab1-PC is a Virtual Machine .....
[-] Post failed: RangeError 17217 out of char range
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/checkvm.rb:76:in `<<'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/checkvm.rb:76:in `reduce'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/checkvm.rb:76:in `hypervchk'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/gather/checkvm.rb:347:in `run'
[*] Post module execution completed

============================================================
`post/windows/manage/migrate``post/windows/manage/migrate`
 run

[*] Running module against lab1-PC
[-] Post failed: Rex::Post::Meterpreter::RequestError stdapi_sys_process_attach: Operation failed: Unknown error
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:95:in `_open'
[-]   /opt/metasploit-framework/embedded/framework/lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb:76:in `open'
[-]   /opt/metasploit-framework/embedded/framework/modules/post/windows/manage/migrate.rb:33:in `run'
[*] Post module execution completed

============================================================
`post/windows/manage/persistence_exe`
 run

[*] Running module against lab1-PC
[*] Reading Payload from file /root/AAV/msf.exe

and it stuck

with windows/meterpreter/reverse_tcp and an exe file, all these 3 modules can be executed successfully.
Did I missed something or they are just not compatible with the python payload?
Thank you

**Comment by timwr** [comment]
I suspect some of those modules were written for the native Windows meterpreter, rather than the python meterpreter.
