### ISSUE TITLE
/open3.rb:199 :in 'spawn' path error.

### ISSUE THREAD

**Issue by XTpeeps** [rapid7/metasploit-framework#9707]
## Steps to reproduce

How'd you do it?

1. finished my install.  
2. run ``` msfdb init/start```

## Expected behavior

```
λ msfdb start
D:/HackProgram/MetasploitFramework/metasploit-framework/embedded/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - C:/metasploit-framework/embedded/bin/pg_ctl -o "-p 5433" -D C:\Users\42161/.msf4/db status (Errno::ENOENT)
        from D:/HackProgram/MetasploitFramework/metasploit-framework/embedded/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
        from D:/HackProgram/MetasploitFramework/metasploit-framework/embedded/lib/ruby/2.3.0/open3.rb:95:in `popen3'
        from D:/HackProgram/MetasploitFramework/metasploit-framework/bin/../embedded/framework/msfdb:36:in `run_cmd'
        from D:/HackProgram/MetasploitFramework/metasploit-framework/bin/../embedded/framework/msfdb:84:in `started_db'
        from D:/HackProgram/MetasploitFramework/metasploit-framework/bin/../embedded/framework/msfdb:118:in `start_db'
        from D:/HackProgram/MetasploitFramework/metasploit-framework/bin/../embedded/framework/msfdb:324:in `<main>'
```

## Current behavior

What happens instead?

my `~/.msf4/logs/framework.log` for relevant stack traces is
```
[07/21/2017 09:31:16] [i(0)] core: Trying to continue despite failed database creation: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?

[07/21/2017 09:31:18] [e(0)] core: DB.connect threw an exception: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?

[03/13/2018 15:35:56] [i(0)] core: Trying to continue despite failed database creation: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?

[03/13/2018 15:35:58] [e(0)] core: DB.connect threw an exception: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?

[03/13/2018 16:46:54] [i(0)] core: Trying to continue despite failed database creation: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?

[03/13/2018 16:46:56] [e(0)] core: DB.connect threw an exception: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5433?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5433?
```

### Metasploit version
```
 metasploit-framework-4.16.45+20180312192125
```
### I installed Metasploit with:
- [x] lastest_Metasploit_Framework.msi at windows.metasploit.com.
- [x] admin installed.
- [x] Free MstasploitFramework for windows

### OS

Win10 x64

**Comment by XTpeeps** [comment]
# solved myown issue
Found that metasploit based SQL which i hadn't install ,pgsql or mysql.

#### What did i do
1. so i download [the official exe for postgres](https://www.enterprisedb.com/downloads/postgres-postgresql-downloads).  

2. installed .

3, start service
```
pg_ctl -D "...(which is my install location)...\PostgreSQL\10\data" start
```

4. init msfconf
```
msfdb init
```

5. start main 
```
msfconsole
```


#### What happend
set password and port. then reload ```msfdb.bat init``` drop the old ```/.msf4/db```and rewrite ```..../database.yml```

pgsql start success.

msf init success.

msfconsole db_connect success.

**Comment by asoto-r7** [comment]
Awesome.  Thanks for the explanation of how you solved this issue.  That will help future users!

I'll close this ticket now, but let me know if you need further help.

**Comment by XTpeeps** [comment]
> yeah cool, Glade to afford this little help for this project,  Have to say i realy dont't wanna waste my cpu on VMware, So i have to use ```msf``` on my Windows ~  

 I'll report anytrouble in the further~
####Other Q. for @asoto-r7 
Found that the UPDATA of Metasploit ```msfupdate.bat``` in windows, it default install to ```C:\```,  but the old Metasploit I installed in ```D:\```.   Is there any conf to set this?

**Comment by pharazone** [comment]
the same problem.I installed it on my D: hard drive, but when I typed msfdb init, it showed error:
 No such file or directory - C:/metasploit-framework/embedded/bin/pg_ctl -o "-p 5433" -D

How can I change this script C:/ to D:/.
Thanks.
