### ISSUE TITLE
Failure to install on macOS (database PG error)

### ISSUE THREAD

**Issue by Ekultek** [rapid7/metasploit-framework#9895]
## Steps to reproduce

How'd you do it?

1. Installed via macOS from source (built natively after a `git clone`)
2. Install all dependencies
3. run `msfconsole`

## Expected behavior

It should run the console successfully

## Current behavior

 - Errors out with `No database support: ActiveRecord::StatementInvalid PG::InvalidParameterValue`

Error logs:
```
[04/19/2018 11:42:58] [e(0)] core: DB.connect threw an exception: PG::InvalidParameterValue: ERROR:  invalid value for parameter "TimeZone": "UTC"
: SET time zone 'UTC'
[04/19/2018 11:42:58] [e(0)] core: Failed to connect to the database: PG::InvalidParameterValue: ERROR:  invalid value for parameter "TimeZone": "UTC"
: SET time zone 'UTC'
[04/19/2018 11:42:58] [d(0)] core: Attempting to delegate method: connection_established?
TBG-a0216:met
```

Stack trace:
```
sudo msfconsole
[-] ***rting the Metasploit Framework console...|
[-] * WARNING: No database support: ActiveRecord::StatementInvalid PG::InvalidParameterValue: ERROR:  invalid value for parameter "TimeZone": "UTC"
: SET time zone 'UTC'
[-] ***
/Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec': PG::InvalidParameterValue: ERROR:  invalid value for parameter "TimeZone": "UTC" (ActiveRecord::StatementInvalid)
: SET time zone 'UTC'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:683:in `configure_connection'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:658:in `connect'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	from /Library/Ruby/Gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
	from /usr/local/share/metasploit-framework/lib/msf/core/db_manager/connection.rb:123:in `connection_established?'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/data_service/proxy/core.rb:101:in `method_missing'
	from /usr/local/share/metasploit-framework/lib/msf/ui/console/driver.rb:162:in `initialize'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `new'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/console.rb:62:in `driver'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
	from /usr/local/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
	from /usr/local/bin/msfconsole:49:in `<main>'
```

### Metasploit version
MSF version: `Framework Version: 5.0.0-dev-7b85edfde5`

### I installed Metasploit with:
- [ ] Kali package via apt
- [ ] Omnibus installer (nightly)
- [ ] Commercial/Community installer (from http://www.rapid7.com/products/metasploit/download.jsp)
- [x] Source install (please specify ruby version)

Ruby version: `ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]`

### OS

OS: `macOS High Sierra v.10.13.3 (17D47)`

**Comment by Ekultek** [comment]
Figured I'd tell you what I've tried:

 - All from [here](https://stackoverflow.com/questions/11409075/postgres-error-invalid-value-for-parameter-timezone-utc?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) (SO)
 - All from [here](http://oklasting.xyz/?questions/49320479/failed-to-connect-to-the-database-pginvalidparametervalue-error-invalid-val) (also SO)

**Comment by busterb** [comment]
I'd recommend just using the nightly installer.
