### ISSUE TITLE
invalid arguments should be return error message

### ISSUE THREAD

**Issue by Auxilus** [rapid7/metasploit-framework#9983]
commands like `history` and `info` (maybe others also) don't check for invalid argument. If an invalid argument is passed, it just runs as if no argument is passed.I think in this case it should print error saying `invalid argument #{arg} `

I have fix for history at #9981  but I think code in `rex/parser/arguments.rb` should check for invalid argument while parsing.

**Comment by Auxilus** [comment]
`search -p` returns diff error, changes should fix it too
```
msf5 > search -p
[-] Error while running command search: undefined method `+' for nil:NilClass

Call stack:
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/msf/ui/console/command_dispatcher/modules.rb:464:in `block in cmd_search'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/parser/arguments.rb:70:in `rescue in parse'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/parser/arguments.rb:37:in `parse'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/msf/ui/console/command_dispatcher/modules.rb:454:in `cmd_search'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/ui/text/dispatcher_shell.rb:548:in `run_command'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/ui/text/dispatcher_shell.rb:510:in `block in run_single'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/ui/text/dispatcher_shell.rb:504:in `each'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/ui/text/dispatcher_shell.rb:504:in `run_single'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/rex/ui/text/shell.rb:208:in `run'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/metasploit/framework/command/console.rb:48:in `start'
/data/data/com.termux/files/home/dev/metasploit-framework-psexec_cleanup/lib/metasploit/framework/command/base.rb:82:in `start'
./msfconsole:49:in `<main>'
msf5 >
```

**Comment by kernelsmith** [comment]
It's hard for arguments.rb to check for invalid args as it has no context for what's valid or invalid. It could do basic checks, like for weird characters etc, but I think that's really up to the command_dispatcher to decide. In the case of history, there should probably be an `else` right here: https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/core.rb#L478 which does the same as the -h option.

**Comment by kernelsmith** [comment]
And honestly, cmd_info from https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/modules.rb#L201 is probably complicated enough that it should probably use the same approach as cmd_grep from https://github.com/rapid7/metasploit-framework/blob/master/lib/msf/ui/console/command_dispatcher/core.rb#L79 i.e. the @@info_opts type approach so that an else can be used.

I had this dream once of changing those @@blah_opts to take blocks so there was less redundancy. Tho thos @@blah_opts definitions would start to look pretty ugly
