### ISSUE TITLE
ArgumentError on tab completion

### ISSUE THREAD

**Issue by firefart** [rapid7/metasploit-framework#9985]
Happened on kali
4.16.54-0kali1

msf > version
Framework: 4.16.54-dev
Console  : 4.16.54-dev

When trying a tab completion on a path the following error crashed my msfconsole:

```
msf auxiliary(gather/kerberos_enumusers) > set USER_FILE /usrTraceback (most recent call last):
        29: from /usr/bin/msfconsole:49:in `<main>'
        28: from /usr/share/metasploit-framework/lib/metasploit/framework/command/base.rb:82:in `start'
        27: from /usr/share/metasploit-framework/lib/metasploit/framework/command/console.rb:48:in `start'
        26: from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:191:in `run'
        25: from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:375:in `get_input_line'
        24: from /usr/share/metasploit-framework/lib/rex/ui/text/input/readline.rb:100:in `pgets'
        23: from /usr/share/metasploit-framework/lib/rex/ui/text/input/readline.rb:162:in `readline_with_output'
        22: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4875:in `readline'
        21: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4853:in `readline_internal'
        20: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4779:in `readline_internal_charloop'
        19: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4363:in `_rl_dispatch'
        18: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:4374:in `_rl_dispatch_subseq'
        17: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6903:in `rl_complete'
        16: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6813:in `rl_complete_internal'
        15: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:6329:in `gen_completion_matches'
        14: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:136:in `readline_attempted_completion_function'
        13: from /usr/share/metasploit-framework/lib/rex/ui/text/shell.rb:62:in `block in init_tab_complete'
        12: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:345:in `tab_complete'
        11: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:360:in `tab_complete_stub'
        10: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:360:in `each'
         9: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:371:in `block in tab_complete_stub'
         8: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:411:in `tab_complete_helper'
         7: from /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:1654:in `cmd_set_tabs'
         6: from /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2165:in `tab_complete_option'
         5: from /usr/share/metasploit-framework/lib/msf/ui/console/command_dispatcher/core.rb:2245:in `option_values_dispatch'
         4: from /usr/share/metasploit-framework/lib/rex/ui/text/dispatcher_shell.rb:247:in `tab_complete_filenames'
         3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/readline.rb:476:in `call'
         2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1305:in `rl_completion_matches'
         1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1401:in `compute_lcd_of_matches'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rb-readline-0.5.5/lib/rbreadline.rb:1401:in `sort': comparison of String with nil failed (ArgumentError)
```

**Comment by wvu-r7** [comment]
Did you compare against `master` and Omnibus on Kali?

**Comment by FireFart** [comment]
no not yet.

**Comment by busterb** [comment]
Hmm, haven't tried it on Kali yet, but wasn't able to repro on the 4.x or master branches locally. Out of curiosity, do you have 2 matches for /usr* on your host? Or is it a symlink, different partition, etc?

**Comment by FireFart** [comment]
Nope doesn't seem so:
```
root@kali:~# ls -alh /
total 104K
drwxr-xr-x  23 root root 4.0K May  3 21:10 .
drwxr-xr-x  23 root root 4.0K May  3 21:10 ..
-rw-r--r--   1 root root    0 Apr 12 14:38 0
drwxr-xr-x   2 root root 4.0K May  7 06:45 bin
drwxr-xr-x   3 root root 4.0K May  3 21:10 boot
drwxr-xr-x  17 root root 3.0K May 10 09:12 dev
drwxr-xr-x 178 root root  12K May 10 09:12 etc
drwxr-xr-x   2 root root 4.0K Apr  6 21:19 home
lrwxrwxrwx   1 root root   34 May  3 21:10 initrd.img -> boot/initrd.img-4.15.0-kali3-amd64
lrwxrwxrwx   1 root root   34 May  3 20:57 initrd.img.old -> boot/initrd.img-4.15.0-kali2-amd64
drwxr-xr-x  20 root root 4.0K May  5 22:42 lib
drwxr-xr-x   2 root root 4.0K May  3 21:09 lib32
drwxr-xr-x   2 root root 4.0K May  3 21:00 lib64
drwx------   2 root root  16K May  3 20:57 lost+found
drwxr-xr-x   3 root root 4.0K Apr 12 14:33 media
drwxr-xr-x   3 root root 4.0K May  3 21:14 mnt
drwxr-xr-x   4 root root 4.0K May  5 22:39 opt
dr-xr-xr-x 141 root root    0 May 10 09:12 proc
drwxr-xr-x  33 root root 4.0K May 10 11:00 root
drwxr-xr-x  32 root root  860 May 10 10:59 run
drwxr-xr-x   2 root root  12K May  7 06:45 sbin
drwxr-xr-x   3 root root 4.0K May  3 20:57 srv
dr-xr-xr-x  13 root root    0 May 10 13:14 sys
drwxrwxrwt  15 root root 4.0K May 10 13:14 tmp
drwxr-xr-x  12 root root 4.0K May  3 21:09 usr
drwxr-xr-x  13 root root 4.0K May  3 21:00 var
lrwxrwxrwx   1 root root   31 May  3 21:10 vmlinuz -> boot/vmlinuz-4.15.0-kali3-amd64
lrwxrwxrwx   1 root root   31 May  3 21:00 vmlinuz.old -> boot/vmlinuz-4.15.0-kali2-amd64
````

**Comment by busterb** [comment]
With this debug line added:
```
--- a/lib/rex/ui/text/dispatcher_shell.rb
+++ b/lib/rex/ui/text/dispatcher_shell.rb
@@ -244,6 +244,7 @@ module DispatcherShell
       if matches and matches.length == 1 and File.directory?(matches[0])
         dir = matches[0]
         dir += File::SEPARATOR if dir[-1,1] != File::SEPARATOR
+        File.write("/tmp/hmm", "#{dir} #{dir.length} #{dir.class}\n")
         matches = ::Readline::FILENAME_COMPLETION_PROC.call(dir)
       end
       matches
```
what is the contents of /tmp/hmm when it crashes?

**Comment by FireFart** [comment]
When tab completing /root:
```
root@kali:~# cat /tmp/hmm 
/root/ 6 String
```

**Comment by FireFart** [comment]
I tried to reproduce with master and 4,x on google cloud shell and could not reproduce it. So it looks like some configuration specific to kali

**Comment by FireFart** [comment]
I dumped the contents of `match_list` from here:
https://github.com/ConnorAtherton/rb-readline/blob/78f0f7a9ba3c4ab32d9c95e3897a5b1c8f82d152/lib/rbreadline.rb#L1401

Looks like the `nil` entries are causing problems

```
[nil, "/usr/share", "/usr/sbin", "/usr/var", "/usr/bin", "/usr/games", "/usr/local", "/usr/src", "/usr/lib", "/usr/include", "/usr/lib32", nil]
```

Ruby can't sort the array if there are nil entries:
```
irb(main):016:0> [nil, "a"].sort
Traceback (most recent call last):
        3: from /usr/bin/irb:11:in `<main>'
        2: from (irb):16
        1: from (irb):16:in `sort'
ArgumentError (comparison of NilClass with String failed)
```

**Comment by busterb** [comment]
how does that list compare to the directories that are actually under /usr/  - do 'nil' directories perhaps represent directories without X permissions or something?

This may require a patch to rb-readline to ignore these properly, if we cannot identify what causes `nil` in the first place. Or maybe we need to reimplement ::Readline::FILENAME_COMPLETION_PROC.call locally within metasploit.

**Comment by FireFart** [comment]
https://github.com/ConnorAtherton/rb-readline/blob/78f0f7a9ba3c4ab32d9c95e3897a5b1c8f82d152/lib/rbreadline.rb#L1293

The first element is always nil and the array is also terminated by a nil element (also mentioned in the comment). So the nil elements are there on purpose. So `compute_lcd_of_matches` must have a problem removing them on kali. Need to investigate further.

**Comment by FireFart** [comment]
Oh and /usr/ does not contain anything special:
```
root@kali:~# ls -alh /usr/
total 184K
drwxr-xr-x  12 root root 4.0K May  3 21:09 .
drwxr-xr-x  23 root root 4.0K May  3 21:10 ..
drwxr-xr-x   2 root root 104K May 10 13:17 bin
drwxr-xr-x   2 root root 4.0K Apr  6 21:19 games
drwxr-xr-x  58 root root 4.0K May  7 08:58 include
drwxr-xr-x 130 root root  12K May  5 22:42 lib
drwxr-xr-x   3 root root 4.0K May  3 21:09 lib32
drwxr-xr-x  10 root root 4.0K May  3 20:59 local
drwxr-xr-x   2 root root  20K May 10 13:16 sbin
drwxr-xr-x 403 root root  12K May  7 10:53 share
drwxr-xr-x   6 root root 4.0K May  3 21:13 src
drwxr-xr-x   3 root root 4.0K May  3 21:00 var
```

**Comment by FireFart** [comment]
I have no idea :) I think the bug I hit is definitely a bug in rb readline if all these conditions are met but the open question is, if we set smth. in metasploit framework that should not be set.

**Comment by FireFart** [comment]
I also created an issue on the rb-readline project for this issue

**Comment by adfoster-r7** [comment]
From a quick glance it looks like the original bug still exists in rb-readline, but since it looks like no one else has ran into this since the original error was reported I'll close this for now :+1:
